Repository kyma-incubator/compass, pull requests merged in 2019-07, with the labels that each got.

#86 Use compass chart from Kyma in installation script
  README.md
  chart/compass/Chart.yaml
  chart/compass/charts/gateway/templates/gateway-certs.yaml
  chart/compass/charts/gateway/templates/gateway.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/charts/registry/.helmignore
  chart/compass/charts/registry/Chart.yaml
  chart/compass/charts/registry/templates/deployment.yaml
  chart/compass/charts/registry/templates/service.yaml
  chart/compass/charts/registry/values.yaml
  chart/compass/values.yaml
  installation/cmd/run.sh
  installation/resources/installer-config.yaml
  installation/resources/installer-cr.yaml
  installation/scripts/run.sh
Labels: enhancement

#99 Copy licenses to Docker images
  chart/compass/values.yaml
  components/connector/.gitignore
  components/connector/Dockerfile
  components/connector/Makefile
  components/director/.gitignore
  components/director/Dockerfile
  components/director/Makefile
  components/gateway/.gitignore
  components/gateway/Dockerfile
  components/gateway/Makefile
  components/healthchecker/.gitignore
  components/healthchecker/Dockerfile
  components/healthchecker/Makefile
  components/registry/.gitignore
  components/registry/Dockerfile
  components/registry/Gopkg.lock
  components/registry/Gopkg.toml
  components/registry/Makefile
  components/registry/README.md
  components/registry/before-commit.sh
  components/registry/cmd/main.go
  tests/end-to-end/.gitignore
  tests/end-to-end/Dockerfile
  tests/end-to-end/Makefile
Labels: area/ci, enhancement

#97 Extend graphql model to enable integration tests
  components/director/pkg/graphql/auth.go
  components/director/pkg/graphql/auth_test.go
  components/director/pkg/graphql/timestamp.go
  components/director/pkg/graphql/timestamp_test.go
Labels: enhancement

#100 Support tenancy in Gateway and Director
  README.md
  chart/compass/values.yaml
  components/director/cmd/main.go
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/converter.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/tenant/tenant.go
  components/director/internal/tenant/tenant_test.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/examples/01_get_apps.graphql
  components/director/pkg/graphql/examples/03_get_runtimes.graphql
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/tenant.go
  components/director/pkg/graphql/tenant_test.go
  components/gateway/Dockerfile
  components/gateway/Gopkg.lock
  components/gateway/cmd/main.go
  components/gateway/internal/tenant/tenant.go
  components/gateway/internal/tenant/tenant_test.go
  installation/README.md
Labels: enhancement

#111 Fix handling nil clobs
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/converter_test.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/resolver_test.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/eventapi/converter.go
  components/director/internal/domain/eventapi/converter_test.go
  components/director/internal/domain/eventapi/fixtures_test.go
  components/director/internal/domain/eventapi/resolver_test.go
  components/director/internal/domain/eventapi/service_test.go
  components/director/internal/model/api.go
  components/director/internal/model/api_test.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/eventapi_test.go
Labels: bug

#117 Allow Tenant header in Director VirtualService
  chart/compass/charts/gateway/templates/virtualservice.yaml
Labels: bug

#94 Integration tests for Director
  tests/end-to-end/Dockerfile
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/Gopkg.toml
  tests/end-to-end/README.md
  tests/end-to-end/before-commit.sh
  tests/end-to-end/compass_e2e_test.go
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/assertions.go
  tests/end-to-end/director/common_test.go
  tests/end-to-end/director/ext.go
  tests/end-to-end/director/fields.go
  tests/end-to-end/director/fixtures.go
  tests/end-to-end/director/graphqlizer.go
  tests/end-to-end/director/ptr.go
  tests/end-to-end/director/runtime_api_test.go
Labels: enhancement

#102 Create an overview section about Compass
  CODEOWNERS
  README.md
  installation/README.md
Labels: area/documentation

#118 Release Compass 1.3.0-rc1
  chart/compass/values.yaml
Labels: enhancement

#129 Fix inconsistency in director GraphQL API between input and
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/document/converter.go
  components/director/internal/domain/document/fixtures_test.go
  components/director/internal/domain/eventapi/converter.go
  components/director/internal/domain/eventapi/fixtures_test.go
  components/director/internal/model/api.go
  components/director/internal/model/api_test.go
  components/director/internal/model/document.go
  components/director/internal/model/document_test.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/eventapi_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: enhancement

#112 Modify installation scripts
  installation/cmd/run-from-kyma.sh
  installation/cmd/run.sh
  installation/resources/installer-cr-with-compass.yaml
  installation/resources/installer-cr-without-compass.yaml
  installation/scripts/prow/deploy-and-test.sh
  installation/scripts/testing.sh
Labels: area/ci, enhancement

#130 Add assertions to check required fields in end to end directory Api tests
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/assertions.go
  tests/end-to-end/director/fields.go
Labels: enhancement

#128 Remove annotations from Director
  README.md
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/converter.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
  components/director/pkg/graphql/annotations.go
  components/director/pkg/graphql/annotations_test.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/examples/01_get_apps.graphql
  components/director/pkg/graphql/examples/03_get_runtimes.graphql
  components/director/pkg/graphql/examples/07_create_app.graphql
  components/director/pkg/graphql/examples/08_update_app.graphql
  components/director/pkg/graphql/examples/10_manage_app_labels.graphql
  components/director/pkg/graphql/examples/10_manage_app_labels_and_annotations.graphql
  components/director/pkg/graphql/examples/14_create_runtime.graphql
  components/director/pkg/graphql/examples/15_update_runtime.graphql
  components/director/pkg/graphql/examples/18_manage_runtime_annotation.graphql
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/assertions.go
  tests/end-to-end/director/fields.go
  tests/end-to-end/director/graphqlizer.go
  tests/end-to-end/director/runtime_api_test.go
Labels: enhancement

#131 Add postgres chart
  chart/compass/README.md
  chart/compass/charts/postgresql/.helmignore
  chart/compass/charts/postgresql/Chart.yaml
  chart/compass/charts/postgresql/README.md
  chart/compass/charts/postgresql/files/README.md
  chart/compass/charts/postgresql/files/conf.d/README.md
  chart/compass/charts/postgresql/files/docker-entrypoint-initdb.d/README.md
  chart/compass/charts/postgresql/templates/NOTES.txt
  chart/compass/charts/postgresql/templates/_helpers.tpl
  chart/compass/charts/postgresql/templates/configmap.yaml
  chart/compass/charts/postgresql/templates/extended-config-configmap.yaml
  chart/compass/charts/postgresql/templates/initialization-configmap.yaml
  chart/compass/charts/postgresql/templates/metrics-svc.yaml
  chart/compass/charts/postgresql/templates/networkpolicy.yaml
  chart/compass/charts/postgresql/templates/secrets.yaml
  chart/compass/charts/postgresql/templates/serviceaccount.yaml
  chart/compass/charts/postgresql/templates/servicemonitor.yaml
  chart/compass/charts/postgresql/templates/statefulset-slaves.yaml
  chart/compass/charts/postgresql/templates/statefulset.yaml
  chart/compass/charts/postgresql/templates/svc-headless.yaml
  chart/compass/charts/postgresql/templates/svc-read.yaml
  chart/compass/charts/postgresql/templates/svc.yaml
  chart/compass/charts/postgresql/values-production.yaml
  chart/compass/charts/postgresql/values.yaml
  chart/compass/requirements.yaml
  chart/compass/values.yaml
Labels: enhancement

#127 Create initial project structure
  CODEOWNERS
  components/runtime-agent/.gitignore
  components/runtime-agent/Dockerfile
  components/runtime-agent/Gopkg.lock
  components/runtime-agent/Gopkg.toml
  components/runtime-agent/Makefile
  components/runtime-agent/before-commit.sh
  components/runtime-agent/cmd/main.go
Labels: area/application-connector, enhancement

#138 Add Compass Runtime Agent chart
  chart/compass-runtime-agent/.helmignore
  chart/compass-runtime-agent/Chart.yaml
  chart/compass-runtime-agent/templates/deployment.yaml
  chart/compass-runtime-agent/values.yaml
  installation/cmd/run.sh
  installation/resources/installer-cr-with-compass.yaml
Labels: area/application-connector, enhancement

#141 Move Runtime Agent component to Kyma
  chart/compass-runtime-agent/.helmignore
  chart/compass-runtime-agent/Chart.yaml
  chart/compass-runtime-agent/templates/deployment.yaml
  chart/compass-runtime-agent/values.yaml
  components/runtime-agent/.gitignore
  components/runtime-agent/Dockerfile
  components/runtime-agent/Gopkg.lock
  components/runtime-agent/Gopkg.toml
  components/runtime-agent/Makefile
  components/runtime-agent/before-commit.sh
  components/runtime-agent/cmd/main.go
  installation/cmd/run.sh
  installation/resources/installer-cr-with-compass.yaml
Labels: area/application-connector

#110 Describe runtime agent contract
  docs/README.md
  docs/architecture/establishing-trusted-connection.md
  docs/architecture/runtime-agent-contract.md
Labels: area/application-connector, enhancement

#139 Update end to end test in check application existence
  chart/compass/values.yaml
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/assertions.go
  tests/end-to-end/director/ext.go
  tests/end-to-end/director/graphqlizer.go
Labels: enhancement

#143 Add schema-migrator component and migration hook
  chart/compass/charts/postgresql/templates/secrets.yaml
  chart/compass/charts/postgresql/values.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/values.yaml
  components/schema-migrator/Dockerfile
  components/schema-migrator/Makefile
  components/schema-migrator/README.md
  components/schema-migrator/migrations/1_initialize_schema.down.sql
  components/schema-migrator/migrations/1_initialize_schema.up.sql
  components/schema-migrator/run.sh
Labels: enhancement

#145 Support GCP managed postgresql database
  chart/compass/README.md
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/templates/managed-postgresql-secret.yaml
  chart/compass/values.yaml
  docs/assets/instance-connection-string.png
  docs/assets/sql-instances-list.png
  docs/configure-managed-gcp-postgresql.md
Labels: enhancement

#147 Add validation on Application/Runtime name in graphql mutations
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/runtime_api_test.go
Labels: enhancement

#149 Describe labeling feature
  docs/architecture/labeling.md
  docs/investigations/storage/sql-toolbox/data/01_schema.sql
  docs/investigations/storage/sql-toolbox/run_postgres.sh
Labels: enhancement

#157 Implement json schema validation service
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/pkg/jsonschema/validator.go
  components/director/pkg/jsonschema/validator_test.go
Labels: enhancement

#148 Fix local tests and add a new installation cr
  chart/compass/README.md
  chart/compass/charts/gateway/values.yaml
  chart/compass/charts/postgresql/README.md
  chart/compass/charts/postgresql/files/README.md
  chart/compass/charts/postgresql/files/conf.d/README.md
  chart/compass/charts/postgresql/files/docker-entrypoint-initdb.d/README.md
  chart/compass/templates/test-compass-end-to-end.yaml
  chart/compass/values.yaml
  installation/cmd/run-from-kyma.sh
  installation/cmd/run.sh
  installation/resources/installer-cr-kyma-compass.yaml
  installation/resources/installer-cr-kyma-diet-compass.yaml
  installation/resources/installer-cr-kyma-diet.yaml
  installation/resources/installer-overrides-compass-gateway.yaml
  installation/resources/installer-overrides-minikube.yaml
Labels: area/ci

#167 Update contract regarding the tenancy and runtime configuration
  docs/architecture/runtime-agent-contract.md
Labels: area/application-connector, area/documentation

#158 Add Query to get all applications within tenant
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/service_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  docs/architecture/runtime-agent-contract.md
Labels: enhancement

#174 Merge branch documentation to master
  docs/architecture/app-runtime-flows.md
  docs/architecture/assets/api-credentials-flow.svg
  docs/architecture/assets/mp-components.svg
  docs/architecture/mp-components.md
Labels: area/documentation

#179 Define DB Schema for Labels
  components/schema-migrator/migrations/201907301200_labels.down.sql
  components/schema-migrator/migrations/201907301200_labels.up.sql
Labels: enhancement
