Repository kyma-incubator/compass, pull requests merged in 2019-10, with the labels that each got.

#346 Fix configuration for Cockpit
  chart/compass/charts/cockpit/templates/configmap.yaml
Labels: bug

#329 Rename Runtime Auth to API Runtime Auth in director integration tests
  chart/compass/values.yaml
  components/director/internal/domain/systemauth/service_test.go
  examples/README.md
  examples/query-api-runtime-auths.graphql
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/fields.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/runtime_api_test.go
  tests/end-to-end/director/runtime_auth_test.go
Labels: enhancement

#348 Extend Provisioning API with Provider configuration
  chart/compass/values.yaml
  components/provisioner/Gopkg.lock
  components/provisioner/pkg/gqlschema/additional_properties.go
  components/provisioner/pkg/gqlschema/config.yaml
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/provisioner/pkg/scalar/scalar.go
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/test/apitests/apitests_test.go
  tests/provisioner-tests/test/testkit/client.go
  tests/provisioner-tests/test/testkit/config.go
  tests/provisioner-tests/test/testkit/graphqlizer.go
  tests/provisioner-tests/test/testkit/query.go
Labels: enhancement

#360 Add mutation for deleting SystemAuths
  chart/compass/charts/director/scopes.yaml
  chart/compass/values.yaml
  components/director/Makefile
  components/director/cmd/main.go
  components/director/internal/domain/fetchrequest/repository.go
  components/director/internal/domain/fetchrequest/repository_test.go
  components/director/internal/domain/onetimetoken/config.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/systemauth/automock/repository.go
  components/director/internal/domain/systemauth/automock/system_auth_converter.go
  components/director/internal/domain/systemauth/automock/system_auth_service.go
  components/director/internal/domain/systemauth/fixtures_test.go
  components/director/internal/domain/systemauth/repository.go
  components/director/internal/domain/systemauth/repository_test.go
  components/director/internal/domain/systemauth/resolver.go
  components/director/internal/domain/systemauth/resolver_test.go
  components/director/internal/domain/systemauth/service.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/pkg/graphql/auth_test.go
  components/director/pkg/graphql/json_schema.go
  components/director/pkg/graphql/json_schema_test.go
  components/director/pkg/graphql/labels.go
  components/director/pkg/graphql/labels_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/timestamp.go
  components/director/pkg/pagination/pagination.go
  components/director/pkg/pagination/pagination_test.go
  components/director/pkg/scope/directive.go
  components/director/pkg/scope/directive_test.go
  components/director/pkg/scope/provider.go
  components/director/pkg/strings/strings_test.go
Labels: enhancement

#363 Remove tenant middleware from gateway component
  chart/compass/values.yaml
  components/gateway/Gopkg.lock
  components/gateway/cmd/main.go
  components/gateway/internal/tenant/tenant.go
  components/gateway/internal/tenant/tenant_test.go
Labels: enhancement

#350 Create DB table and sql helpers for Integration Systems
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/apiruntimeauth/repository.go
  components/director/internal/domain/apiruntimeauth/repository_test.go
  components/director/internal/domain/apiruntimeauth/service_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/document/converter_test.go
  components/director/internal/domain/document/repository.go
  components/director/internal/domain/eventapi/converter.go
  components/director/internal/domain/eventapi/converter_test.go
  components/director/internal/domain/eventapi/fixtures_test.go
  components/director/internal/domain/eventapi/repository.go
  components/director/internal/domain/fetchrequest/repository.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/systemauth/repository.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/repo/common.go
  components/director/internal/repo/create.go
  components/director/internal/repo/delete.go
  components/director/internal/repo/delete_test.go
  components/director/internal/repo/exist.go
  components/director/internal/repo/exist_test.go
  components/director/internal/repo/get.go
  components/director/internal/repo/get_test.go
  components/director/internal/repo/list.go
  components/director/internal/repo/list_pageable.go
  components/director/internal/repo/list_pageable_test.go
  components/director/internal/repo/list_test.go
  components/director/internal/repo/update.go
  components/director/internal/repo/update_test.go
  components/director/internal/repo/upsert.go
  components/director/pkg/scope/provider.go
  components/director/pkg/str/strings.go
  components/director/pkg/str/strings_test.go
  components/schema-migrator/migrations/201909241337_add_system_auths.up.sql
  components/schema-migrator/migrations/201910021355_add_integration_systems.down.sql
  components/schema-migrator/migrations/201910021355_add_integration_systems.up.sql
Labels: enhancement

#352 Prepare database schema for Provisioner
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/postgresql/templates/init-db-config-map.yaml
  chart/compass/charts/postgresql/templates/secrets.yaml
  chart/compass/charts/postgresql/values.yaml
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/configure-managed-gcp-postgresql.md
  chart/compass/requirements.yaml
  chart/compass/templates/managed-postgresql-secret.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/values.yaml
  components/provisioner/Dockerfile
  components/provisioner/Gopkg.lock
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/mockresolver.go
  components/provisioner/internal/database/schema_initializer.go
  components/provisioner/pkg/gqlschema/additional_properties.go
  components/provisioner/pkg/gqlschema/cluster_config.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/test/apitests/apitests_test.go
  tests/provisioner-tests/test/testkit/graphqlizer.go
  tests/provisioner-tests/test/testkit/query.go
Labels: WIP, enhancement

#369 Update alpine base image to 3.10
  chart/compass/values.yaml
  components/connector/Dockerfile
  components/director/Dockerfile
  components/gateway/Dockerfile
  components/healthchecker/Dockerfile
  components/provisioner/Dockerfile
  components/schema-migrator/Dockerfile
  tests/connector-tests/Dockerfile
  tests/end-to-end/Dockerfile
  tests/end-to-end/gen-examples.sh
  tests/provisioner-tests/Dockerfile
Labels: enhancement

#365 Add ability to generate OAuth 2.0 client credentials
  chart/compass/charts/director/config.yaml
  chart/compass/charts/director/scopes.yaml
  chart/compass/charts/director/templates/configmap.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/templates/test.yaml
  chart/compass/values.yaml
  components/director/README.md
  components/director/cmd/main.go
  components/director/hack/scopesdecorator/plugin.go
  components/director/hack/scopesdecorator/testdata/expected.graphql
  components/director/internal/domain/labeldef/resolver.go
  components/director/internal/domain/labeldef/resolver_test.go
  components/director/internal/domain/oauth20/automock/application_service.go
  components/director/internal/domain/oauth20/automock/integration_system_service.go
  components/director/internal/domain/oauth20/automock/runtime_service.go
  components/director/internal/domain/oauth20/automock/scope_cfg_provider.go
  components/director/internal/domain/oauth20/automock/service.go
  components/director/internal/domain/oauth20/automock/system_auth_converter.go
  components/director/internal/domain/oauth20/automock/system_auth_service.go
  components/director/internal/domain/oauth20/automock/uid_service.go
  components/director/internal/domain/oauth20/config.go
  components/director/internal/domain/oauth20/resolver.go
  components/director/internal/domain/oauth20/resolver_test.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/domain/oauth20/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/domain/systemauth/automock/o_auth20_service.go
  components/director/internal/domain/systemauth/resolver.go
  components/director/internal/domain/systemauth/resolver_test.go
  components/director/internal/domain/systemauth/service.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/scope/provider.go
  components/director/run.sh
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/testctx.go
  tests/end-to-end/gen-examples.sh
  tests/end-to-end/run.sh
Labels: enhancement

#358 Add Integration System domain and GQL types
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/integrationsystem/automock/converter.go
  components/director/internal/domain/integrationsystem/automock/integration_system_converter.go
  components/director/internal/domain/integrationsystem/automock/integration_system_repository.go
  components/director/internal/domain/integrationsystem/automock/integration_system_service.go
  components/director/internal/domain/integrationsystem/automock/system_auth_converter.go
  components/director/internal/domain/integrationsystem/automock/system_auth_service.go
  components/director/internal/domain/integrationsystem/automock/uid_service.go
  components/director/internal/domain/integrationsystem/converter.go
  components/director/internal/domain/integrationsystem/converter_test.go
  components/director/internal/domain/integrationsystem/entity.go
  components/director/internal/domain/integrationsystem/fixtures_test.go
  components/director/internal/domain/integrationsystem/repository.go
  components/director/internal/domain/integrationsystem/repository_test.go
  components/director/internal/domain/integrationsystem/resolver.go
  components/director/internal/domain/integrationsystem/resolver_test.go
  components/director/internal/domain/integrationsystem/service.go
  components/director/internal/domain/integrationsystem/service_test.go
  components/director/internal/domain/oauth20/automock/integration_system_service.go
  components/director/internal/domain/oauth20/resolver.go
  components/director/internal/domain/oauth20/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/integrationsystem.go
  components/director/internal/model/integrationsystem_test.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/integration_system.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/201910111320_add_description_to_int_sys.down.sql
  components/schema-migrator/migrations/201910111320_add_description_to_int_sys.up.sql
Labels: enhancement

#371 Add retries and timeout to Hydrators
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/values.yaml
Labels: enhancement

#383 Fix getting SystemAuth
  chart/compass/values.yaml
  components/director/internal/domain/oauth20/automock/system_auth_service.go
  components/director/internal/domain/oauth20/resolver.go
  components/director/internal/domain/oauth20/resolver_test.go
  components/director/internal/domain/systemauth/automock/system_auth_service.go
  components/director/internal/domain/systemauth/resolver.go
  components/director/internal/domain/systemauth/resolver_test.go
  components/director/internal/domain/systemauth/service.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/internal/persistence/persistence.go
Labels: bug

#380 Add partial updates investigation
  docs/README.md
  docs/investigations/graphql-complex-updates/graphql-complex-updates.md
Labels: enhancement

#372 Integration system and oauth credentials integration tests
  chart/compass/values.yaml
  components/director/internal/domain/integrationsystem/repository.go
  components/director/internal/domain/integrationsystem/repository_test.go
  examples/README.md
  examples/create-integration-system.graphql
  examples/delete-integration-system.graphql
  examples/query-integration-system.graphql
  examples/query-integration-systems.graphql
  examples/update-integration-system.graphql
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/Gopkg.toml
  tests/end-to-end/director/assertions.go
  tests/end-to-end/director/fields.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/graphqlizer.go
  tests/end-to-end/director/integration_system_api_test.go
  tests/end-to-end/director/oauth20_test.go
  tests/end-to-end/director/token_api_test.go
  tests/end-to-end/gen-examples.sh
Labels: enhancement

#376 Update the docs
  CODEOWNERS
  OWNERS_ALIASES
  README.md
  docs/README.md
  docs/architecture/api-credentials-flows.md
  docs/architecture/app-runtime-flows.md
  docs/architecture/assets/architecture.svg
  docs/architecture/assets/components-high-level.svg
  docs/architecture/assets/components.svg
  docs/architecture/assets/grouping.svg
  docs/architecture/assets/scenarios.svg
  docs/architecture/authentication-and-authorization.md
  docs/architecture/basic-architecture.md
  docs/architecture/components.md
  docs/architecture/director-component.md
  docs/architecture/establishing-trusted-connection.md
  docs/architecture/event-flows-proposal.md
  docs/architecture/high-level-components.md
  docs/architecture/mp-components.md
  docs/architecture/runtime-agent-contract.md
  docs/architecture/support-for-legacy-rest-api.md
  docs/terminology.md
Labels: area/documentation

#381 Allow to update only basic application attributes
  components/director/internal/domain/application/automock/application_converter.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: enhancement

#397 Support not equal operations in sql conditions
  chart/compass/values.yaml
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/apiruntimeauth/repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/document/repository.go
  components/director/internal/domain/eventapi/repository.go
  components/director/internal/domain/fetchrequest/repository.go
  components/director/internal/domain/integrationsystem/repository.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/systemauth/automock/repository.go
  components/director/internal/domain/systemauth/repository.go
  components/director/internal/domain/systemauth/repository_test.go
  components/director/internal/domain/systemauth/service.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/repo/common.go
  components/director/internal/repo/delete_test.go
  components/director/internal/repo/exist_test.go
  components/director/internal/repo/get_test.go
  tests/end-to-end/director/oauth20_test.go
Labels: enhancement

#364 Tenant mapping handler implementation
  chart/compass/charts/director/static-users.yaml
  chart/compass/charts/director/templates/configmap-configuration.yaml
  chart/compass/charts/director/templates/configmap-static-users.yaml
  chart/compass/charts/director/templates/configmap.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/.gitignore
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/README.md
  components/director/cmd/main.go
  components/director/hack/config-local.yaml
  components/director/hack/static-users-local.yaml
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/authenticator/testdata/invalid.json
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/apiruntimeauth/service_test.go
  components/director/internal/domain/eventapi/service_test.go
  components/director/internal/domain/labeldef/resolver_test.go
  components/director/internal/domain/systemauth/automock/repository.go
  components/director/internal/domain/systemauth/automock/system_auth_service.go
  components/director/internal/domain/systemauth/repository.go
  components/director/internal/domain/systemauth/repository_test.go
  components/director/internal/domain/systemauth/resolver.go
  components/director/internal/domain/systemauth/service.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/internal/model/system_auth.go
  components/director/internal/model/system_auth_test.go
  components/director/internal/tenant/tenant.go
  components/director/internal/tenant/tenant_test.go
  components/director/internal/tenantmapping/automock/req_data_parser.go
  components/director/internal/tenantmapping/automock/scopes_getter.go
  components/director/internal/tenantmapping/automock/static_user_repository.go
  components/director/internal/tenantmapping/automock/tenant_and_scopes_for_system_auth_provider.go
  components/director/internal/tenantmapping/automock/tenant_and_scopes_for_user_provider.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/internal/tenantmapping/mapper_for_system_auth.go
  components/director/internal/tenantmapping/mapper_for_system_auth_test.go
  components/director/internal/tenantmapping/mapper_for_user.go
  components/director/internal/tenantmapping/mapper_for_user_test.go
  components/director/internal/tenantmapping/model.go
  components/director/internal/tenantmapping/model_test.go
  components/director/internal/tenantmapping/req_data_parser.go
  components/director/internal/tenantmapping/req_data_parser_test.go
  components/director/internal/tenantmapping/staticuser.go
  components/director/internal/tenantmapping/staticuser_test.go
  components/director/pkg/apperrors/errors.go
  components/director/pkg/apperrors/errors_test.go
  components/director/pkg/str/strings.go
  components/director/pkg/str/strings_test.go
  components/director/run.sh
  tests/end-to-end/director/testctx.go
  tests/end-to-end/gen-examples.sh
Labels: enhancement

#411 Compass Provisioner e2e tests
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/charts/provisioner/templates/tests/role-binding.yaml
  chart/compass/charts/provisioner/templates/tests/service-account.yaml
  chart/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  installation/scripts/testing.sh
  tests/provisioner-tests/Dockerfile
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/Makefile
  tests/provisioner-tests/scripts/entrypoint.sh
  tests/provisioner-tests/scripts/run_localy.sh
  tests/provisioner-tests/test/apitests/apitests_test.go
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/provisioner/main_test.go
  tests/provisioner-tests/test/provisioner/suite.go
  tests/provisioner-tests/test/testkit/assertions/helpers.go
  tests/provisioner-tests/test/testkit/assertions/operation.go
  tests/provisioner-tests/test/testkit/client.go
  tests/provisioner-tests/test/testkit/compass/provisioner/client.go
  tests/provisioner-tests/test/testkit/compass/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/compass/provisioner/query.go
  tests/provisioner-tests/test/testkit/config.go
  tests/provisioner-tests/test/testkit/graphql/client.go
  tests/provisioner-tests/test/testkit/util.go
Labels: enhancement

#391 Secure Connector Service generate token mutations
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/service-role-binding.yaml
  chart/compass/charts/connector/templates/service.yaml
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/charts/connector/values.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/service-account.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/values.yaml
  components/connector/cmd/main.go
  components/connector/gqlgen.sh
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/resolver.go
  components/connector/internal/api/token_resolver.go
  components/connector/internal/certificates/model.go
  components/connector/pkg/graphql/externalschema/config.yaml
  components/connector/pkg/graphql/externalschema/models_gen.go
  components/connector/pkg/graphql/externalschema/schema.graphql
  components/connector/pkg/graphql/externalschema/schema_gen.go
  components/connector/pkg/graphql/internalschema/config.yaml
  components/connector/pkg/graphql/internalschema/schema.graphql
  components/connector/pkg/graphql/internalschema/schema_gen.go
  tests/connector-tests/Gopkg.lock
  tests/connector-tests/Gopkg.toml
  tests/connector-tests/test/apitests/apitests_test.go
  tests/connector-tests/test/apitests/hydrator_api_test.go
  tests/connector-tests/test/testkit/config.go
  tests/connector-tests/test/testkit/connector/cert_secured_client.go
  tests/connector-tests/test/testkit/connector/internal_client.go
  tests/connector-tests/test/testkit/connector/token_secured_client.go
Labels: area/security, enhancement

#421 Delete fork dependency from the Connector Tests
  tests/connector-tests/Gopkg.lock
  tests/connector-tests/Gopkg.toml
Labels: area/security, enhancement
