Repository kyma-incubator/compass, pull requests merged in 2019-08, with the labels that each got.

#182 Fix listing runtimes
  chart/compass/values.yaml
  components/director/internal/domain/runtime/entity.go
  examples/create-runtime.graphql
  examples/query-applications-for-runtime.graphql
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/runtime_api_test.go
Labels: bug

#176 Implement Label logic for Director
  chart/compass/values.yaml
  components/director/README.md
  components/director/internal/appcontext/appcontext.go
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/automock/context_value_setter.go
  components/director/internal/domain/application/automock/label_repository.go
  components/director/internal/domain/application/automock/label_upsert_service.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/label/automock/converter.go
  components/director/internal/domain/label/automock/label_definition_repository.go
  components/director/internal/domain/label/automock/label_repository.go
  components/director/internal/domain/label/automock/uid_service.go
  components/director/internal/domain/label/converter.go
  components/director/internal/domain/label/converter_test.go
  components/director/internal/domain/label/entity.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/label/service.go
  components/director/internal/domain/label/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/label_definition_repository.go
  components/director/internal/domain/runtime/automock/label_repository.go
  components/director/internal/domain/runtime/automock/label_upsert_service.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/converter.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/internal/model/label.go
  components/director/internal/model/label_test.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/runtime.go
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/jsonschema/validator_test.go
  components/director/run.sh
  components/schema-migrator/migrations/201907301200_labels.up.sql
  tests/end-to-end/director/application_api_test.go
Labels: enhancement

#195 Update kyma compass installer CR
  installation/resources/installer-cr-kyma-compass.yaml
Labels: bug

#196 Prepare release 1.4rc2
  chart/compass/values.yaml
Labels: WIP

#190 Create LabelDefinition Scenario with default value
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/internal/domain/application/automock/label_def_repository.go
  components/director/internal/domain/application/automock/scenarios_service.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/label/service.go
  components/director/internal/domain/label/service_test.go
  components/director/internal/domain/labeldef/automock/repository.go
  components/director/internal/domain/labeldef/automock/service.go
  components/director/internal/domain/labeldef/repository.go
  components/director/internal/domain/labeldef/repository_test.go
  components/director/internal/domain/labeldef/resolver.go
  components/director/internal/domain/labeldef/resolver_test.go
  components/director/internal/domain/labeldef/scenarios_service.go
  components/director/internal/domain/labeldef/scenarios_service_test.go
  components/director/internal/domain/labeldef/service.go
  components/director/internal/domain/labeldef/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/label_def_repository.go
  components/director/internal/domain/runtime/automock/scenarios_service.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/labeldef.go
  components/director/internal/model/labeldef_test.go
  components/director/internal/model/scenarios.go
  components/director/internal/model/scenarios_test.go
  components/director/pkg/jsonschema/validator.go
  components/director/pkg/jsonschema/validator_test.go
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/runtime_api_test.go
Labels: enhancement

#205 Fix generating examples from tests
  examples/README.md
  examples/create-application-with-apis.graphql
  examples/create-application-with-documents.graphql
  examples/create-application-with-event-apis.graphql
  examples/create-application-with-webhooks.graphql
  examples/create-application.graphql
  examples/query-applications-for-runtime.graphql
  tests/end-to-end/before-commit.sh
  tests/end-to-end/gen-examples.sh
Labels: enhancement

#175 Add integration tests for labeling
  chart/compass/values.yaml
  components/director/pkg/jsonschema/validator.go
  components/director/pkg/jsonschema/validator_test.go
  examples/README.md
  examples/create-label-definition.graphql
  examples/delete-label-definition.graphql
  examples/query-applications-for-runtime.graphql
  examples/query-label-definition.graphql
  examples/set-application-label.graphql
  examples/update-label-definition.graphql
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/Gopkg.toml
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/common_test.go
  tests/end-to-end/director/ext.go
  tests/end-to-end/director/fields.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/graphqlizer_test.go
  tests/end-to-end/director/labeling_api_test.go
  tests/end-to-end/director/runtime_api_test.go
Labels: enhancement

#206 Rename tests and remove unused CR
  chart/compass/README.md
  chart/compass/templates/test.yaml
  installation/cmd/run-from-kyma.sh
  installation/cmd/run.sh
  installation/resources/installer-cr-kyma-compass.yaml
  installation/scripts/testing.sh
Labels: bug

#212 Add unmarshall method to CSRFToken creditential request auth
  chart/compass/values.yaml
  components/director/pkg/graphql/auth.go
  components/director/pkg/graphql/auth_test.go
Labels: enhancement

#217 Return empty list instead of error
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
Labels: bug

#218 Add the rest of integration tests for labeling
  chart/compass/values.yaml
  examples/README.md
  examples/query-runtimes-with-label-filter.graphql
  tests/end-to-end/director/assertions.go
  tests/end-to-end/director/ext.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/labeling_api_test.go
  tests/end-to-end/director/runtime_api_test.go
Labels: enhancement

#219 Define Database Schema for missing domains
  chart/compass/values.yaml
  components/director/internal/domain/application/repository.go
  components/schema-migrator/migrations/201907181525_initialize_schema.down.sql
  components/schema-migrator/migrations/201907181525_initialize_schema.up.sql
  components/schema-migrator/migrations/201907241200_label_definition.down.sql
  components/schema-migrator/migrations/201907241200_label_definition.up.sql
  components/schema-migrator/migrations/201907301200_labels.down.sql
  components/schema-migrator/migrations/201907301200_labels.up.sql
  components/schema-migrator/migrations/201908141300_initialize_schema.down.sql
  components/schema-migrator/migrations/201908141300_initialize_schema.up.sql
  docs/architecture/assets/entity_diagram.svg
  docs/architecture/db-scheme.md
Labels: enhancement

#229 Update connector API
  components/connector/Dockerfile
  components/connector/cmd/main.go
  components/connector/gqlgen.sh
  components/connector/internal/api/certificateResolver.go
  components/connector/internal/api/resolver.go
  components/connector/internal/api/tokenResolver.go
  components/connector/internal/gqlschema/resolver.go
  components/connector/pkg/gqlschema/config.yaml
  components/connector/pkg/gqlschema/models_gen.go
  components/connector/pkg/gqlschema/schema.graphql
  components/connector/pkg/gqlschema/schema_gen.go
Labels: area/application-connector, enhancement

#220 Implement cascade delete for labeling
  chart/compass/values.yaml
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/labeldef/automock/label_repository.go
  components/director/internal/domain/labeldef/service.go
  components/director/internal/domain/labeldef/service_test.go
Labels: enhancement

#221 Test cascading delete for labeling
  chart/compass/values.yaml
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/labeling_api_test.go
Labels: enhancement

#230 Extend Deleter: DeleteOne and DeleteMany
  chart/compass/values.yaml
  components/director/internal/domain/runtime/repository.go
  components/director/internal/repo/delete.go
  components/director/internal/repo/delete_test.go
Labels: enhancement

#232 Add Authentication Context Middleware to Connector
  components/connector/Gopkg.lock
  components/connector/cmd/main.go
  components/connector/internal/apperrors/apperrors.go
  components/connector/internal/apperrors/apperrors_test.go
  components/connector/internal/authentication/cert_header_parser.go
  components/connector/internal/authentication/cert_header_parser_test.go
  components/connector/internal/authentication/context.go
  components/connector/internal/authentication/context_middleware.go
  components/connector/internal/authentication/context_middleware_test.go
  components/connector/internal/authentication/context_test.go
  components/connector/internal/authentication/mocks/CertificateHeaderParser.go
  components/connector/internal/authentication/subject_extraction.go
  components/connector/internal/authentication/subject_extraction_test.go
  components/connector/internal/tokens/cache.go
  components/connector/internal/tokens/generator.go
  components/connector/internal/tokens/generator_test.go
  components/connector/internal/tokens/mocks/Creator.go
  components/connector/internal/tokens/mocks/Manager.go
  components/connector/internal/tokens/mocks/Service.go
  components/connector/internal/tokens/mocks/TokenCache.go
  components/connector/internal/tokens/model.go
  components/connector/internal/tokens/service.go
  components/connector/internal/tokens/service_test.go
Labels: area/application-connector

#235 Implement additional converter methods for document repository
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/document/automock/document_converter.go
  components/director/internal/domain/document/converter.go
  components/director/internal/domain/document/converter_test.go
  components/director/internal/domain/document/entity.go
  components/director/internal/domain/document/fixtures_test.go
  components/director/internal/domain/document/repository.go
  components/director/internal/domain/document/resolver.go
  components/director/internal/domain/document/service.go
  components/director/internal/domain/document/service_test.go
  components/director/internal/model/document.go
  components/director/internal/model/document_test.go
  components/director/internal/model/fetchrequest.go
  components/director/pkg/strings/strings.go
Labels: enhancement

#231 Add list helper
  chart/compass/values.yaml
  components/director/internal/repo/common.go
  components/director/internal/repo/list.go
  components/director/internal/repo/list_pageable.go
  components/director/internal/repo/list_pageable_test.go
  components/director/internal/repo/list_test.go
  components/director/internal/repo/upsert.go
  components/director/internal/repo/upsert_test.go
  components/schema-migrator/migrations/201908141300_initialize_schema.up.sql
Labels: WIP, enhancement

#243 Implement internal Connector endpoints
  components/connector/cmd/main.go
  components/connector/gqlgen.sh
  components/connector/internal/api/certificateResolver.go
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/api/resolver.go
  components/connector/internal/api/tokenResolver.go
  components/connector/internal/api/token_resolver.go
  components/connector/internal/api/token_resolver_test.go
  components/connector/internal/authentication/authenticator.go
  components/connector/internal/authentication/authenticator_test.go
  components/connector/internal/authentication/cert_header_parser.go
  components/connector/internal/authentication/cert_header_parser_test.go
  components/connector/internal/authentication/context_middleware_test.go
  components/connector/internal/authentication/context_test.go
  components/connector/internal/authentication/mocks/Authenticator.go
  components/connector/internal/authentication/subject_extraction_test.go
  components/connector/internal/tokens/cache.go
  components/connector/internal/tokens/generator.go
  components/connector/internal/tokens/mocks/Creator.go
  components/connector/internal/tokens/mocks/Manager.go
  components/connector/internal/tokens/mocks/TokenCache.go
  components/connector/pkg/graphql/externalschema/config.yaml
  components/connector/pkg/graphql/externalschema/models_gen.go
  components/connector/pkg/graphql/externalschema/schema.graphql
  components/connector/pkg/graphql/externalschema/schema_gen.go
  components/connector/pkg/graphql/internalschema/config.yaml
  components/connector/pkg/graphql/internalschema/schema.graphql
  components/connector/pkg/graphql/internalschema/schema_gen.go
Labels: enhancement

#242 Add signing certificates to Connector
  components/connector/Gopkg.lock
  components/connector/Gopkg.toml
  components/connector/cmd/main.go
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/api/mocks/CertificateResolver.go
  components/connector/internal/api/mocks/TokenResolver.go
  components/connector/internal/apperrors/apperrors.go
  components/connector/internal/apperrors/apperrors_test.go
  components/connector/internal/authentication/cert_header_parser.go
  components/connector/internal/authentication/cert_header_parser_test.go
  components/connector/internal/authentication/mocks/Authenticator.go
  components/connector/internal/authentication/mocks/CertificateHeaderParser.go
  components/connector/internal/certificates/certificates.go
  components/connector/internal/certificates/certificates_test.go
  components/connector/internal/certificates/mocks/CertificateUtility.go
  components/connector/internal/certificates/mocks/Service.go
  components/connector/internal/certificates/model.go
  components/connector/internal/certificates/service.go
  components/connector/internal/certificates/service_test.go
  components/connector/internal/namespacedname/namespacedname.go
  components/connector/internal/namespacedname/namespacedname_test.go
  components/connector/internal/secrets/mocks/Manager.go
  components/connector/internal/secrets/mocks/Repository.go
  components/connector/internal/secrets/repository.go
  components/connector/internal/secrets/repository_test.go
  components/connector/internal/tokens/mocks/Service.go
Labels: enhancement

#248 Implement Configuration mutation
  components/connector/Gopkg.lock
  components/connector/cmd/main.go
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/api/token_resolver.go
  components/connector/internal/certificates/model.go
  components/connector/internal/tokens/cache.go
  components/connector/internal/tokens/model.go
  components/connector/internal/tokens/service_test.go
Labels: enhancement

#249 Change back to single API
  components/connector/cmd/main.go
  components/connector/gqlgen.sh
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/api/mocks/CertificateResolver.go
  components/connector/internal/api/mocks/TokenResolver.go
  components/connector/internal/api/resolver.go
  components/connector/internal/api/token_resolver.go
  components/connector/internal/authentication/context_middleware.go
  components/connector/internal/authentication/context_middleware_test.go
  components/connector/internal/certificates/model.go
  components/connector/pkg/gqlschema/config.yaml
  components/connector/pkg/gqlschema/models_gen.go
  components/connector/pkg/gqlschema/schema.graphql
  components/connector/pkg/gqlschema/schema_gen.go
  components/connector/pkg/graphql/externalschema/config.yaml
  components/connector/pkg/graphql/internalschema/schema.graphql
  components/connector/pkg/graphql/internalschema/schema_gen.go
Labels: enhancement

#250 Adjust internal files to new single Connector API
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/api/token_resolver.go
  components/connector/internal/api/token_resolver_test.go
  components/connector/internal/authentication/authenticator.go
  components/connector/internal/authentication/authenticator_test.go
  components/connector/internal/authentication/cert_header_parser.go
  components/connector/internal/authentication/cert_header_parser_test.go
  components/connector/internal/authentication/context.go
  components/connector/internal/authentication/context_middleware_test.go
  components/connector/internal/authentication/mocks/Authenticator.go
  components/connector/internal/authentication/mocks/CertificateHeaderParser.go
  components/connector/internal/authentication/subject_extraction.go
  components/connector/internal/authentication/subject_extraction_test.go
Labels: enhancement

#245 Implement FetchRequest repository with entity conversion
  chart/compass/values.yaml
  components/director/internal/domain/fetchrequest/automock/converter.go
  components/director/internal/domain/fetchrequest/converter.go
  components/director/internal/domain/fetchrequest/converter_test.go
  components/director/internal/domain/fetchrequest/entity.go
  components/director/internal/domain/fetchrequest/fixtures_test.go
  components/director/internal/domain/fetchrequest/repository.go
  components/director/internal/domain/fetchrequest/repository_test.go
  components/director/internal/model/fetchrequest.go
  components/director/internal/repo/sql_types.go
Labels: enhancement

#251 Adjust Gateway to Connector implementation
  components/gateway/cmd/main.go
Labels: enhancement

#259 Postgres secret should be generated only on install
  chart/compass/charts/postgresql/templates/secrets.yaml
Labels: bug

#254 Compass Connector chart
  chart/compass/charts/connector/templates/certs-setup-job.yaml
  chart/compass/charts/connector/templates/certs-setup-role-binding.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/role-binding.yaml
  chart/compass/charts/connector/templates/service-account.yaml
  chart/compass/charts/connector/values.yaml
  chart/compass/values.yaml
Labels: enhancement

#233 Migrate Webhooks Repository from In-Memory to Postgres
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/webhook_repository.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/webhook/automock/entity_converter.go
  components/director/internal/domain/webhook/automock/webhook_repository.go
  components/director/internal/domain/webhook/converter.go
  components/director/internal/domain/webhook/converter_test.go
  components/director/internal/domain/webhook/entity.go
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/domain/webhook/resolver.go
  components/director/internal/domain/webhook/resolver_test.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/domain/webhook/service_test.go
  components/director/internal/model/webhook.go
  components/director/internal/model/webhook_test.go
  components/director/internal/persistence/txtest/txtest.go
  components/director/internal/tenant/tenant.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/run.sh
  components/schema-migrator/migrations/201908141300_initialize_schema.up.sql
Labels: enhancement

#260 Introduce Event API Definition entity
  chart/compass/values.yaml
  components/director/internal/domain/eventapi/automock/version_converter.go
  components/director/internal/domain/eventapi/converter.go
  components/director/internal/domain/eventapi/converter_test.go
  components/director/internal/domain/eventapi/entity.go
  components/director/internal/domain/eventapi/fixtures_test.go
  components/director/internal/domain/eventapi/resolver_test.go
  components/director/internal/domain/eventapi/service_test.go
  components/director/internal/repo/sql_types.go
Labels: enhancement

#252 Add API definition repository
  chart/compass/values.yaml
  components/director/internal/domain/api/automock/api_definition_converter.go
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/converter_test.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/model/api.go
  components/director/internal/repo/testdb/exist.go
Labels: enhancement

#265 Rework Document repository to use DB
  chart/compass/values.yaml
  components/director/internal/domain/api/resolver_test.go
  components/director/internal/domain/application/automock/document_repository.go
  components/director/internal/domain/application/automock/document_service.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/document/automock/converter.go
  components/director/internal/domain/document/automock/document_repository.go
  components/director/internal/domain/document/converter.go
  components/director/internal/domain/document/converter_test.go
  components/director/internal/domain/document/entity.go
  components/director/internal/domain/document/fixtures_test.go
  components/director/internal/domain/document/repository.go
  components/director/internal/domain/document/repository_test.go
  components/director/internal/domain/document/resolver.go
  components/director/internal/domain/document/resolver_test.go
  components/director/internal/domain/document/service.go
  components/director/internal/domain/document/service_test.go
  components/director/internal/domain/fetchrequest/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/model/document.go
  components/director/internal/model/document_test.go
  components/schema-migrator/migrations/201908141300_initialize_schema.down.sql
  components/schema-migrator/migrations/201908141300_initialize_schema.up.sql
Labels: enhancement

#272 Remove bidirectional references for FetchRequest
  chart/compass/values.yaml
  components/director/internal/domain/api/automock/fetch_request_repository.go
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/converter_test.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/resolver.go
  components/director/internal/domain/api/resolver_test.go
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/eventapi/automock/fetch_request_repository.go
  components/director/internal/domain/eventapi/converter.go
  components/director/internal/domain/eventapi/converter_test.go
  components/director/internal/domain/eventapi/entity.go
  components/director/internal/domain/eventapi/fixtures_test.go
  components/director/internal/domain/eventapi/repository.go
  components/director/internal/domain/eventapi/resolver.go
  components/director/internal/domain/eventapi/resolver_test.go
  components/director/internal/domain/eventapi/service.go
  components/director/internal/domain/eventapi/service_test.go
  components/director/internal/domain/fetchrequest/repository.go
  components/director/internal/domain/fetchrequest/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/api_test.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/eventapi_test.go
Labels: enhancement

#253 Add Runtime Auth domain
  chart/compass/values.yaml
  components/director/internal/domain/api/automock/api_service.go
  components/director/internal/domain/api/automock/runtime_auth_converter.go
  components/director/internal/domain/api/automock/runtime_auth_service.go
  components/director/internal/domain/api/automock/runtime_service.go
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/converter_test.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/resolver.go
  components/director/internal/domain/api/resolver_test.go
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/eventapi/resolver_test.go
  components/director/internal/domain/label/query_test.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/label/service.go
  components/director/internal/domain/label/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/runtime_auth/automock/auth_converter.go
  components/director/internal/domain/runtime_auth/automock/converter.go
  components/director/internal/domain/runtime_auth/automock/repository.go
  components/director/internal/domain/runtime_auth/automock/uid_service.go
  components/director/internal/domain/runtime_auth/converter.go
  components/director/internal/domain/runtime_auth/converter_test.go
  components/director/internal/domain/runtime_auth/entity.go
  components/director/internal/domain/runtime_auth/fixtures_test.go
  components/director/internal/domain/runtime_auth/repository.go
  components/director/internal/domain/runtime_auth/repository_test.go
  components/director/internal/domain/runtime_auth/service.go
  components/director/internal/domain/runtime_auth/service_test.go
  components/director/internal/domain/webhook/resolver_test.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_auth.go
  components/director/internal/persistence/txtest/txtest.go
  components/director/internal/repo/errors.go
  components/director/internal/repo/errors_test.go
  components/director/pkg/graphql/api_definition.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/201908141300_initialize_schema.up.sql
Labels: enhancement

#271 Show API details
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement
