Repository kyma-incubator/compass, pull requests merged in 2019-06, with the labels that each got.

#24 Architecture document about API credentials lifecycle
  docs/README.md
  docs/architecture/api-credentials-flows.md
  docs/architecture/assets/api-credentials-flow.svg
  docs/terminology.md
Labels: area/documentation, enhancement

#23 Add testing framework to compass
  README.md
  chart/compass/templates/test-compass-end-to-end.yaml
  chart/compass/values.yaml
  installation/README.md
  installation/resources/installer-cr.yaml
  installation/scripts/kyma-scripts/testing-common.sh
  installation/scripts/kyma-scripts/utils.sh
  installation/scripts/run.sh
  installation/scripts/testing.sh
Labels: enhancement

#31 Improve description of Management Plane and Compass
  README.md
  docs/architecture/api-credentials-flows.md
  docs/architecture/assets/api-credentials-flow.svg
  docs/terminology.md
Labels: area/documentation, enhancement

#28 Add architecture flow diagrams
  docs/architecture/app-runtime-flows.md
  docs/architecture/assets/api-registration.svg
  docs/architecture/assets/app-configuration-update.svg
  docs/architecture/assets/app-pairing.svg
  docs/architecture/assets/runtime-configuration-update.svg
  docs/architecture/assets/runtime-creation.svg
  docs/architecture/assets/runtime-notification.svg
Labels: area/documentation, enhancement

#30 Add management plane's components diagram
  docs/README.md
  docs/architecture/api-credentials-flows.md
  docs/architecture/assets/api-credentials-flow.svg
  docs/architecture/assets/mp-components.svg
  docs/architecture/mp-components.md
  docs/terminology.md
Labels: area/documentation, enhancement

#25 Investigate Gateway architecture
  docs/investigations/gateway-architecture/gateway-architecture.md
Labels: area/documentation, enhancement

#34 Polish architecture flow diagrams
  docs/README.md
  docs/architecture/app-runtime-flows.md
Labels: area/documentation, enhancement

#32 Initial connector component with GQL schema
  components/connector/.gitignore
  components/connector/Dockerfile
  components/connector/Gopkg.lock
  components/connector/Gopkg.toml
  components/connector/Makefile
  components/connector/README.md
  components/connector/before-commit.sh
  components/connector/cmd/main.go
  components/connector/gqlgen.sh
  components/connector/hack/gqlgen.go
  components/connector/hack/regenerate-mocks.sh
  components/connector/internal/gqlschema/config.yaml
  components/connector/internal/gqlschema/models_gen.go
  components/connector/internal/gqlschema/schema.graphql
  components/connector/internal/gqlschema/schema_gen.go
Labels: enhancement

#39 Create reverse proxy implementation for Gateway
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/service.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/gateway/templates/_helpers.tpl
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/gateway/templates/gateway.yaml
  chart/compass/charts/gateway/templates/service.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/charts/healthchecker/templates/deployment.yaml
  chart/compass/charts/healthchecker/templates/service.yaml
  chart/compass/charts/registry/templates/deployment.yaml
  chart/compass/charts/registry/templates/service.yaml
  chart/compass/templates/test-compass-end-to-end.yaml
  chart/compass/values.yaml
  components/director/.gitignore
  components/director/Dockerfile
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/Makefile
  components/director/README.md
  components/director/before-commit.sh
  components/director/cmd/main.go
  components/director/gqlgen.sh
  components/director/hack/gqlgen.go
  components/director/hack/regenerate-mocks.sh
  components/director/internal/gqlschema/config.yaml
  components/director/internal/gqlschema/examples/01_get_apps.graphql
  components/director/internal/gqlschema/examples/02_get_app.graphql
  components/director/internal/gqlschema/examples/03_get_runtimes.graphql
  components/director/internal/gqlschema/examples/04_get_runtime.graphql
  components/director/internal/gqlschema/examples/05_get_healthchecks.graphql
  components/director/internal/gqlschema/examples/07_create_app.graphql
  components/director/internal/gqlschema/examples/08_update_app.graphql
  components/director/internal/gqlschema/examples/09_delete_app.graphql
  components/director/internal/gqlschema/examples/10_manage_app_labels_and_annotations.graphql
  components/director/internal/gqlschema/examples/11_manage_app_webhooks.graphql
  components/director/internal/gqlschema/examples/12_manage_api.graphql
  components/director/internal/gqlschema/examples/13_mange_event.graphql
  components/director/internal/gqlschema/examples/14_create_runtime.graphql
  components/director/internal/gqlschema/examples/15_update_runtime.graphql
  components/director/internal/gqlschema/examples/16_delete_runtime.graphql
  components/director/internal/gqlschema/examples/17_manage_runtime_label.graphql
  components/director/internal/gqlschema/examples/18_manage_runtime_annotation.graphql
  components/director/internal/gqlschema/examples/19_pagination.graphql
  components/director/internal/gqlschema/models_gen.go
  components/director/internal/gqlschema/resolver.go
  components/director/internal/gqlschema/scalars.go
  components/director/internal/gqlschema/schema.graphql
  components/director/internal/gqlschema/schema_gen.go
  components/gateway/.gitignore
  components/gateway/Dockerfile
  components/gateway/Gopkg.lock
  components/gateway/Gopkg.toml
  components/gateway/Makefile
  components/gateway/README.md
  components/gateway/before-commit.sh
  components/gateway/cmd/main.go
  components/gateway/internal/gqlschema/config.yaml
  installation/scripts/run.sh
Labels: WIP, enhancement

#41 Do not filter headers on Gateway while proxying requests
  chart/compass/charts/director/templates/deployment.yaml
  components/director/Dockerfile
  components/director/cmd/main.go
  components/gateway/Dockerfile
  components/gateway/Gopkg.lock
  components/gateway/cmd/main.go
  components/gateway/pkg/proxy/proxy.go
  components/gateway/pkg/proxy/proxy_test.go
Labels: enhancement

#49 Fix links in the documentation
  docs/README.md
  docs/architecture/api-credentials-flows.md
  docs/architecture/app-runtime-flows.md
  docs/architecture/mp-components.md
Labels: area/application-connector, enhancement

#40 Database investigation
  docs/README.md
  docs/investigations/storage/managed-db/managed-dbs.md
Labels: area/documentation, enhancement

#52 Add client certificate flow documentation
  docs/architecture/app-runtime-flows.md
  docs/architecture/assets/client-certificate-flow.svg
  docs/architecture/establishing-trusted-connection.md
Labels: area/application-connector, enhancement

#45 Detailed postgres investigation with examples
  .gitignore
  docs/README.md
  docs/investigations/storage/postgres/gen.go
  docs/investigations/storage/postgres/postgres.md
  docs/investigations/storage/postgres/run_postgres.sh
  docs/investigations/storage/postgres/select.go
  docs/investigations/storage/postgres/select_json.go
  docs/investigations/storage/postgres/sql/01_schema.sql
  docs/investigations/storage/postgres/sql/02_data.sql
Labels: area/documentation

#42 Describe legacy REST API support
  docs/README.md
  docs/architecture/assets/rest-api-to-to-gql-flow.svg
  docs/architecture/support-for-legacy-rest-api.md
Labels: area/application-connector, enhancement

#64 Describe architecture of Director
  docs/README.md
  docs/architecture/assets/director-architecture.svg
  docs/architecture/director-component.md
Labels: area/documentation, enhancement

#65 Extend API and EventAPI with name and description
  chart/compass/values.yaml
  components/director/internal/graphql/models_gen.go
  components/director/internal/graphql/schema.graphql
  components/director/internal/graphql/schema_gen.go
Labels: area/application-connector, enhancement

#63 Implement scalars
  components/director/Dockerfile
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/internal/domain/application/application_resolver.go
  components/director/internal/domain/healthcheck/healthcheck_resolver.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/graphql/annotations.go
  components/director/internal/graphql/annotations_test.go
  components/director/internal/graphql/clob.go
  components/director/internal/graphql/clob_test.go
  components/director/internal/graphql/config.yaml
  components/director/internal/graphql/httpHeaders.go
  components/director/internal/graphql/httpHeaders_test.go
  components/director/internal/graphql/labels.go
  components/director/internal/graphql/labels_test.go
  components/director/internal/graphql/models_gen.go
  components/director/internal/graphql/pageCursor.go
  components/director/internal/graphql/pageCursor_test.go
  components/director/internal/graphql/queryParams.go
  components/director/internal/graphql/queryParams_test.go
  components/director/internal/graphql/resolver.go
  components/director/internal/graphql/scalars.go
  components/director/internal/graphql/schema.graphql
  components/director/internal/graphql/schema_gen.go
  components/director/internal/graphql/tenant.go
  components/director/internal/graphql/tenant_test.go
  components/director/internal/graphql/timestamp.go
  components/director/internal/graphql/timestamp_test.go
  components/director/pkg/scalar/scalar.go
Labels: enhancement

#33 Support external eventing systems in API
  docs/architecture/assets/external-event-flow.svg
  docs/architecture/assets/internal-event-flow.svg
  docs/architecture/event-flows-proposal.md
Labels: enhancement

#72 Test Auth and Application models in Director
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/internal/model/auth.go
  components/director/internal/model/auth_test.go
Labels: enhancement

#69 Investigate SQL toolbox
  .gitignore
  docs/investigations/storage/sql-toolbox/data/01_schema.sql
  docs/investigations/storage/sql-toolbox/libs/beego/internal/db/id.go
  docs/investigations/storage/sql-toolbox/libs/beego/internal/domain/application/dao.go
  docs/investigations/storage/sql-toolbox/libs/beego/internal/dto/dto.go
  docs/investigations/storage/sql-toolbox/libs/beego/internal/model/model.go
  docs/investigations/storage/sql-toolbox/libs/beego/main.go
  docs/investigations/storage/sql-toolbox/libs/gorm/internal/db/id.go
  docs/investigations/storage/sql-toolbox/libs/gorm/internal/domain/application/dao.go
  docs/investigations/storage/sql-toolbox/libs/gorm/internal/dto/dto.go
  docs/investigations/storage/sql-toolbox/libs/gorm/internal/model/model.go
  docs/investigations/storage/sql-toolbox/libs/gorm/main.go
  docs/investigations/storage/sql-toolbox/libs/sqlx/internal/db/id.go
  docs/investigations/storage/sql-toolbox/libs/sqlx/internal/domain/application/dao.go
  docs/investigations/storage/sql-toolbox/libs/sqlx/internal/domain/application/dao_test.go
  docs/investigations/storage/sql-toolbox/libs/sqlx/internal/dto/dto.go
  docs/investigations/storage/sql-toolbox/libs/sqlx/internal/model/model.go
  docs/investigations/storage/sql-toolbox/libs/sqlx/main.go
  docs/investigations/storage/sql-toolbox/run_postgres.sh
  docs/investigations/storage/sql-toolbox/sql-toolbox.md
Labels: enhancement

#85 Fix webhooks and document repository
  components/director/internal/domain/document/repository.go
  components/director/internal/domain/webhook/repository.go
Labels: bug

#88 Add models for application registry REST API
  components/gateway/internal/application-registry-adapter/model/model.go
Labels: area/application-connector, enhancement

#92 Fill AgentAuth during Runtime creation
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
Labels: enhancement
