Repository kyma-incubator/compass, pull requests merged in 2019-12, with the labels that each got.

#512 GraphQL playground available without auth in director
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/templates/e2e-compass-test.yaml
  chart/compass/values.yaml
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/e2e/fixtures_queries_test.go
  tests/end-to-end/e2e/fixtures_request_test.go
  tests/end-to-end/e2e/playground_test.go
  tests/end-to-end/pkg/connector/certificate.go
  tests/end-to-end/pkg/connector/client.go
  tests/end-to-end/pkg/connector/queries.go
Labels: enhancement

#485 Add input validation to auth & webhook domains
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/examples/add-webhook/add-application-webhook.graphql
  components/director/examples/update-webhook/update-application-webhook.graphql
  components/director/pkg/graphql/auth_test.go
  components/director/pkg/graphql/auth_validation.go
  components/director/pkg/graphql/auth_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/graphql/webhook_validation_test.go
  components/director/pkg/inputvalidation/directive.go
  components/director/pkg/inputvalidation/directive_test.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  components/director/pkg/inputvalidation/validators_pointer.go
  components/director/pkg/inputvalidation/validators_pointer_test.go
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/validation_test.go
Labels: enhancement

#513 Implement integration tests for Application Templates
  chart/compass/charts/director/config.yaml
  chart/compass/charts/director/static-users.yaml
  chart/compass/templates/director-test.yaml
  chart/compass/templates/e2e-compass-test.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/create-application-template/create-application-template.graphql
  components/director/examples/delete-application-template/delete-application-template.graphql
  components/director/examples/query-application-template/query-application-template.graphql
  components/director/examples/query-application-templates/query-application-templates.graphql
  components/director/examples/update-application-template/update-application-template.graphql
  components/director/hack/config-local.yaml
  components/director/hack/static-users-local.yaml
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/graphqlizer.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/application_templates_api_test.go
  tests/end-to-end/director/assertions.go
  tests/end-to-end/director/fixtures.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/gen-examples.sh
  tests/end-to-end/pkg/gql/fields.go
  tests/end-to-end/pkg/gql/graphqlizer.go
  tests/end-to-end/run.sh
Labels: enhancement

#520 Add input validation to runtime, label and label definition domains
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/labeldef/service.go
  components/director/internal/domain/labeldef/service_test.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/labeldef.go
  components/director/internal/model/labeldef_test.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
  components/director/pkg/graphql/labeldef_validation.go
  components/director/pkg/graphql/labeldef_validation_test.go
  components/director/pkg/graphql/labels_test.go
  components/director/pkg/graphql/labels_validation.go
  components/director/pkg/graphql/labels_validation_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/validation.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/labeling_api_test.go
  tests/end-to-end/director/validation_test.go
Labels: enhancement

#455 Add validation to app, integration system, fetch request and document
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/examples/create-application/create-application-with-documents.graphql
  components/director/examples/update-application/update-application.graphql
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/document/service_test.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/internal/model/fetchrequest.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/app_validation_test.go
  components/director/pkg/graphql/document_validation.go
  components/director/pkg/graphql/document_validation_test.go
  components/director/pkg/graphql/fetchrequest_validation.go
  components/director/pkg/graphql/fetchrequest_validation_test.go
  components/director/pkg/graphql/integrationsys_validation.go
  components/director/pkg/graphql/integrationsys_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/inputvalidation/validators_map.go
  components/director/pkg/inputvalidation/validators_map_test.go
  components/director/pkg/inputvalidation/validators_url.go
  components/director/pkg/inputvalidation/validators_url_test.go
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/testctx.go
  tests/end-to-end/director/validation_test.go
Labels: enhancement

#503 Add status message to Clean Up Runtime Data mutation response
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/persistence/dbsession/write.go
  components/provisioner/internal/persistence/service_test.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/08-06-clean-up-runtime-data.md
Labels: enhancement

#530 Expose GraphQL examples for Director playground
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-mtls.yaml
  chart/compass/charts/gateway/templates/virtualservice-secure.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/templates/e2e-compass-test.yaml
  chart/compass/values.yaml
  components/director/Dockerfile
  tests/end-to-end/e2e/playground_suite_test.go
  tests/end-to-end/e2e/playground_test.go
  tests/end-to-end/e2e/testctx.go
Labels: enhancement

#538 Fix waiting for Director before running integration tests
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/configure-managed-gcp-postgresql.md
  chart/compass/templates/director-test.yaml
  chart/compass/templates/e2e-compass-test.yaml
  chart/compass/values.yaml
  tests/end-to-end/gen-examples.sh
  tests/end-to-end/wait-for-director.sh
Labels: bug

#535 Create app from template
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/apptemplate/automock/app_converter.go
  components/director/internal/domain/apptemplate/automock/application_converter.go
  components/director/internal/domain/apptemplate/automock/application_service.go
  components/director/internal/domain/apptemplate/automock/application_template_converter.go
  components/director/internal/domain/apptemplate/automock/application_template_repository.go
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/apptemplate/automock/entity_converter.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/converter_test.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/app_template.go
  components/director/internal/model/app_template_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/auth_validation.go
  components/director/pkg/graphql/document_validation.go
  components/director/pkg/graphql/fetchrequest_validation.go
  components/director/pkg/graphql/integrationsys_validation.go
  components/director/pkg/graphql/labeldef_validation.go
  components/director/pkg/graphql/labels_validation.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/str/strings.go
  docs/architecture/auto-app-management.md
  docs/architecture/input-validation.md
  tests/end-to-end/director/fixtures.go
  tests/end-to-end/director/labeling_api_test.go
  tests/end-to-end/director/validation_test.go
  tests/end-to-end/run.sh
Labels: enhancement

#422 Add api specification support proposal
  docs/README.md
  docs/architecture/api-specs-support.md
Labels: enhancement

#543 Update input validation docs
  docs/architecture/input-validation.md
Labels: enhancement

#547 Return success response for Tenant Mapping Handler all the time
  chart/compass/templates/migrator-job.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/tenantmapping/automock/logger.go
  components/director/internal/tenantmapping/export_test.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/internal/tenantmapping/mapper_for_user.go
  components/director/internal/tenantmapping/mapper_for_user_test.go
  tests/end-to-end/e2e/auth_test.go
  tests/end-to-end/e2e/fixtures_queries.go
  tests/end-to-end/e2e/fixtures_request.go
  tests/end-to-end/e2e/playground_suite.go
  tests/end-to-end/e2e/playground_test.go
  tests/end-to-end/e2e/tenant_mapping_handler_test.go
Labels: enhancement

#563 Add API Consumer ID and Type to ctx
  chart/compass/charts/gateway/values.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/consumer/consumer.go
  components/director/internal/consumer/consumer_test.go
  components/director/internal/consumer/context.go
  components/director/internal/consumer/context_test.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/internal/tenantmapping/mapper_for_system_auth.go
  components/director/internal/tenantmapping/mapper_for_system_auth_test.go
  components/director/internal/tenantmapping/mapper_for_user.go
  components/director/internal/tenantmapping/mapper_for_user_test.go
  components/director/internal/tenantmapping/model.go
  components/director/pkg/scope/context_test.go
Labels: enhancement

#570 Make all nested resolvers optional
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/onetimetoken/resolver.go
  components/director/internal/domain/onetimetoken/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: enhancement

#580 Add TWs as CODEOWNERS of all .md files
  CODEOWNERS
Labels: area/documentation, enhancement

#579 Fix validation for Event Definition spec
  chart/compass/values.yaml
  components/director/pkg/graphql/event_api_validation.go
  components/director/pkg/graphql/event_api_validation_test.go
  docs/architecture/input-validation.md
Labels: bug

#587 Prevent reloading on each navigation change in compass
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#588 Update dependencies in E2E tests
  chart/compass/values.yaml
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/Gopkg.toml
Labels: bug

#551 Investigate simplify usage of Compass api
  docs/investigations/simplify-api-usage/simplify-api-usage.md
Labels: enhancement

#555 Update Hydroform version and Gardener Terraform plugin
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/Dockerfile
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/hydroform/client/client.go
  components/provisioner/internal/hydroform/client/mocks/Client.go
  components/provisioner/internal/hydroform/service.go
  components/provisioner/internal/hydroform/service_test.go
Labels: enhancement

#550 Provide tutorial on how to create certificate application pairing via Compass
  components/connector/docs/08-01-establish-secure-connection-with-compass.md
  components/connector/docs/08-02-maintain-secure-connection-with-compass.md
  docs/connector/02-01-connector-service.md
  docs/connector/08-01-establish-secure-connection-with-compass.md
  docs/connector/08-02-maintain-secure-connection-with-compass.md
  docs/connector/08-03-revoke-client-certificate.md
  docs/connector/assets/001-connection-flow.svg
Labels: area/documentation

#581 Update Compass documentation
  docs/README.md
  docs/architecture/api-credentials-flows.md
  docs/architecture/api-packages.md
  docs/architecture/app-runtime-flows.md
  docs/architecture/assets/architecture.svg
  docs/architecture/assets/components.svg
  docs/architecture/assets/external-event-flow.svg
  docs/architecture/assets/internal-event-flow.svg
  docs/architecture/basic-architecture.md
  docs/architecture/components.md
  docs/architecture/event-flows-proposal.md
  docs/architecture/input-parameters-on-runtime.md
  docs/architecture/provisioning-api.md
  docs/architecture/runtime-agent-contract.md
  docs/archive/establishing-trusted-connection.md
Labels: area/documentation

#592 Update Connector documentation in Architecture docs
  docs/connector/02-01-connector-service.md
  docs/connector/assets/001-connection-flow.svg
Labels: area/documentation
