Repository kyma-incubator/compass, pull requests merged in 2019-11, with the labels that each got.

#427 Add regex pattern for scenario label enum values
  chart/compass/values.yaml
  components/director/internal/model/labeldef_test.go
  components/director/internal/model/scenarios.go
Labels: enhancement

#404 Introduce API Package Proposal
  docs/README.md
  docs/architecture/api-packages.md
  docs/architecture/assets/api-packages.svg
  docs/architecture/input-parameters-on-runtime.md
  docs/architecture/runtime-agent-contract.md
Labels: area/documentation, enhancement

#448 Define GraphQL types, models and DB Schema for Application Types
  chart/compass/values.yaml
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/apptemplate/entity.go
  components/director/internal/model/app_template.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/201911041200_add_app_templates.down.sql
  components/schema-migrator/migrations/201911041200_add_app_templates.up.sql
Labels: enhancement

#435 Compass e2e tests
  chart/compass/templates/director-test.yaml
  chart/compass/templates/e2e-compass-test.yaml
  chart/compass/values.yaml
  installation/scripts/testing.sh
  tests/end-to-end/Dockerfile
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/Makefile
  tests/end-to-end/e2e/README.md
  tests/end-to-end/e2e/e2e_test.go
  tests/end-to-end/e2e/fixtures_queries_test.go
  tests/end-to-end/e2e/fixtures_request_test.go
  tests/end-to-end/e2e/testctx.go
  tests/end-to-end/pkg/gql/fields.go
  tests/end-to-end/pkg/gql/gqlclient.go
  tests/end-to-end/pkg/gql/graphqlizer.go
  tests/end-to-end/pkg/idtokenprovider/auth.go
  tests/end-to-end/pkg/idtokenprovider/config.go
  tests/end-to-end/pkg/idtokenprovider/idtokenprovider.go
Labels: enhancement

#456 Add the terminology doc
  docs/README.md
  docs/architecture/auto-app-management.md
  docs/terminology.md
Labels: area/documentation

#464 Fix creating FetchRequest for API and EventAPI Definition
  chart/compass/values.yaml
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/eventapi/service.go
  components/director/internal/domain/eventapi/service_test.go
  tests/end-to-end/director/application_api_test.go
Labels: bug

#463 Introduce repository and converter for Application Template
  components/director/internal/domain/apptemplate/automock/entity_converter.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/converter_test.go
  components/director/internal/domain/apptemplate/entity.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/app_template.go
Labels: enhancement

#475 Add context object details to Extra map in tenant mapping handler
  chart/compass/values.yaml
  components/director/internal/model/system_auth.go
  components/director/internal/model/system_auth_test.go
  components/director/internal/tenantmapping/automock/object_context_for_system_auth_provider.go
  components/director/internal/tenantmapping/automock/object_context_for_user_provider.go
  components/director/internal/tenantmapping/automock/tenant_and_scopes_for_system_auth_provider.go
  components/director/internal/tenantmapping/automock/tenant_and_scopes_for_user_provider.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/internal/tenantmapping/mapper_for_system_auth.go
  components/director/internal/tenantmapping/mapper_for_system_auth_test.go
  components/director/internal/tenantmapping/mapper_for_user.go
  components/director/internal/tenantmapping/mapper_for_user_test.go
  components/director/internal/tenantmapping/model.go
Labels: enhancement

#482 Cleanup main.go file in director component
  chart/compass/values.yaml
  components/director/cmd/main.go
  components/director/internal/healthz/handler.go
  components/director/internal/healthz/handler_test.go
  components/director/internal/persistence/config.go
  components/director/internal/persistence/config_test.go
Labels: enhancement

#484 Add missing scope for runtime
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
Labels: enhancement

#424 Add possibility to provision Azure and AWS clusters via Gardener
  chart/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  chart/compass/values.yaml
  components/provisioner/Dockerfile
  components/provisioner/Gopkg.lock
  components/provisioner/Gopkg.toml
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/init.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/hydroform/configuration.go
  components/provisioner/internal/hydroform/configuration/builder.go
  components/provisioner/internal/hydroform/configuration/builder_test.go
  components/provisioner/internal/hydroform/configuration/mocks/Builder.go
  components/provisioner/internal/hydroform/configuration/mocks/BuilderFactory.go
  components/provisioner/internal/hydroform/configuration_test.go
  components/provisioner/internal/hydroform/mocks/Service.go
  components/provisioner/internal/hydroform/service.go
  components/provisioner/internal/hydroform/service_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/persistence/dbsession/read.go
  components/provisioner/internal/persistence/dbsession/write.go
  components/provisioner/internal/persistence/service.go
  components/provisioner/internal/persistence/service_test.go
  components/provisioner/internal/provisioning/converters.go
  components/provisioner/internal/provisioning/converters_test.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/json.go
  components/provisioner/internal/util/wait.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/testkit/assertions/operation.go
  tests/provisioner-tests/test/testkit/compass/provisioner/client.go
  tests/provisioner-tests/test/testkit/compass/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/compass/provisioner/query.go
Labels: enhancement

#488 Parametrize connector RBAC rule
  chart/compass/charts/connector/templates/service-role-binding.yaml
  chart/compass/charts/connector/values.yaml
Labels: bug

#487 Add release table to Provisioner
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/main.go
Labels: enhancement

#497 Document Compass Provisioner component
  components/provisioner/README.md
  components/provisioner/pkg/gqlschema/schema.graphql
  docs/architecture/components.md
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/05-01-app-entry-parameters.md
  docs/provisioner/08-01-provisioning-gcp.md
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-03-runtime-operation-status.md
  docs/provisioner/08-04-runtime-status.md
  docs/provisioner/08-05-deprovisioning.md
  docs/provisioner/08-06-clean-up-runtime-data.md
Labels: area/documentation

#468 Implement CRUD operations for Application Templates
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/hack/config-local.yaml
  components/director/internal/domain/apptemplate/automock/application_template_converter.go
  components/director/internal/domain/apptemplate/automock/application_template_repository.go
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/apptemplate/automock/entity_converter.go
  components/director/internal/domain/apptemplate/automock/uid_service.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/converter_test.go
  components/director/internal/domain/apptemplate/entity.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/graphqlizer.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/integrationsystem/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/app_template.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/201911041200_add_app_templates.up.sql
Labels: enhancement

#506 Add input validation docs and tooling
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/cmd/main.go
  components/director/hack/plugins/formatter.go
  components/director/hack/plugins/scopesdecorator/plugin.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/inputvalidation/directive.go
  components/director/pkg/inputvalidation/directive_test.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  components/director/pkg/inputvalidation/validators_iterable.go
  components/director/pkg/inputvalidation/validators_iterable_test.go
  components/director/pkg/inputvalidation/validators_map.go
  components/director/pkg/inputvalidation/validators_map_test.go
  components/director/pkg/inputvalidation/validators_string.go
  components/director/pkg/inputvalidation/validators_string_test.go
  components/director/pkg/scope/directive_test.go
  components/director/pkg/str/strings.go
  docs/README.md
  docs/architecture/input-validation.md
Labels: enhancement

#495 Fix applications/runtimes choosers in create scenario modal
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, bug
