Repository kyma-incubator/compass, pull requests merged in 2019-05, with the labels that each got.

#1 Logo added
  README.md
  logo.png
Labels: enhancement

#10 Add helm charts for compass components
  chart/compass/.helmignore
  chart/compass/Chart.yaml
  chart/compass/charts/director/.helmignore
  chart/compass/charts/director/Chart.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/service.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/gateway/.helmignore
  chart/compass/charts/gateway/Chart.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/gateway/templates/service.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/charts/healthchecker/.helmignore
  chart/compass/charts/healthchecker/Chart.yaml
  chart/compass/charts/healthchecker/templates/deployment.yaml
  chart/compass/charts/healthchecker/templates/service.yaml
  chart/compass/charts/healthchecker/values.yaml
  chart/compass/charts/registry/.helmignore
  chart/compass/charts/registry/Chart.yaml
  chart/compass/charts/registry/templates/deployment.yaml
  chart/compass/charts/registry/templates/service.yaml
  chart/compass/charts/registry/values.yaml
  chart/compass/values.yaml
Labels: enhancement

#11 Add graphql file upload example
  docs/investigations/graphql-file-upload/file-upload-with-graphql.md
Labels: area/documentation

#9 Create first GraphQL API specification
  components/director/before-commit.sh
  components/gateway/.gitignore
  components/gateway/Dockerfile
  components/gateway/Gopkg.lock
  components/gateway/Gopkg.toml
  components/gateway/Makefile
  components/gateway/README.md
  components/gateway/before-commit.sh
  components/gateway/cmd/main.go
  components/gateway/gqlgen.sh
  components/gateway/hack/gqlgen.go
  components/gateway/hack/regenerate-mocks.sh
  components/gateway/internal/gqlschema/config.yaml
  components/gateway/internal/gqlschema/examples/01_get_apps.graphql
  components/gateway/internal/gqlschema/examples/02_get_app.graphql
  components/gateway/internal/gqlschema/examples/03_get_runtimes.graphql
  components/gateway/internal/gqlschema/examples/04_get_runtime.graphql
  components/gateway/internal/gqlschema/examples/05_get_healthchecks.graphql
  components/gateway/internal/gqlschema/examples/06_get_labels.graphql
  components/gateway/internal/gqlschema/examples/07_create_app.graphql
  components/gateway/internal/gqlschema/examples/08_update_app.graphql
  components/gateway/internal/gqlschema/examples/09_delete_app.graphql
  components/gateway/internal/gqlschema/examples/10_manage_app_labels_and_annotations.graphql
  components/gateway/internal/gqlschema/examples/11_manage_app_webhooks.graphql
  components/gateway/internal/gqlschema/examples/12_manage_api.graphql
  components/gateway/internal/gqlschema/examples/13_mange_event.graphql
  components/gateway/internal/gqlschema/examples/14_create_runtime.graphql
  components/gateway/internal/gqlschema/examples/15_update_runtime.graphql
  components/gateway/internal/gqlschema/examples/16_delete_runtime.graphql
  components/gateway/internal/gqlschema/examples/17_manage_runtime_label.graphql
  components/gateway/internal/gqlschema/examples/18_manage_runtime_annotation.graphql
  components/gateway/internal/gqlschema/models_gen.go
  components/gateway/internal/gqlschema/scalars.go
  components/gateway/internal/gqlschema/schema.graphql
  components/gateway/internal/gqlschema/schema_gen.go
  components/healthchecker/before-commit.sh
  components/registry/before-commit.sh
Labels: enhancement

#7 Add S3 storage and Parquet investigation
  docs/storage/requirements.md
  docs/storage/s3/README.md
  docs/storage/s3/assets/bucket-structure.jpg
  docs/storage/s3/parquet.md
Labels: area/documentation, enhancement

#20 Add e2e testing component to compass
  tests/end-to-end/.gitignore
  tests/end-to-end/Dockerfile
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/Gopkg.toml
  tests/end-to-end/Makefile
  tests/end-to-end/README.md
  tests/end-to-end/before-commit.sh
  tests/end-to-end/compass_e2e_test.go
Labels: enhancement
