Repository kyma-incubator/compass, pull requests merged in 2019-09, with the labels that each got.

#276 Add Provisioner boilerplate
  components/provisioner/.gitignore
  components/provisioner/Dockerfile
  components/provisioner/Gopkg.lock
  components/provisioner/Gopkg.toml
  components/provisioner/Makefile
  components/provisioner/README.md
  components/provisioner/before-commit.sh
  components/provisioner/cmd/main.go
  components/provisioner/gqlgen.sh
  components/provisioner/hack/gqlgen.go
  components/provisioner/hack/regenerate-mocks.sh
  components/provisioner/pkg/gqlschema/config.yaml
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: enhancement

#283 Add OWNERS files
  OWNERS
  OWNERS_ALIASES
  chart/compass/charts/cockpit/OWNERS
Labels: area/ci, enhancement

#282 Add XML SpecFormat
  chart/compass/values.yaml
  components/director/internal/model/specformat.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: enhancement

#284 Switch to postgres in apidefinition
  chart/compass/values.yaml
  components/director/internal/domain/api/automock/api_repository.go
  components/director/internal/domain/api/automock/version_converter.go
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/converter_test.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/api/resolver.go
  components/director/internal/domain/api/resolver_test.go
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/application/automock/api_repository.go
  components/director/internal/domain/application/automock/api_service.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/eventapi/automock/version_converter.go
  components/director/internal/domain/eventapi/converter.go
  components/director/internal/domain/eventapi/converter_test.go
  components/director/internal/domain/eventapi/entity.go
  components/director/internal/domain/eventapi/fixtures_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/version/converter.go
  components/director/internal/domain/version/converter_test.go
  components/director/internal/domain/version/embedded_entity.go
  components/director/internal/model/api.go
  components/director/internal/model/api_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: enhancement

#268 Move applications to postgres repository
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/entity_converter.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/fetchrequest/converter.go
  components/director/internal/domain/fetchrequest/converter_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/schema-migrator/migrations/201908141300_initialize_schema.up.sql
  examples/create-application-with-documents.graphql
  examples/create-application-with-event-apis.graphql
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/labeling_api_test.go
Labels: enhancement

#294 Switch EventAPI Definition from in memory database to Postgres
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/event_api_repository.go
  components/director/internal/domain/application/automock/event_api_service.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/eventapi/automock/event_api_repository.go
  components/director/internal/domain/eventapi/converter_test.go
  components/director/internal/domain/eventapi/fixtures_test.go
  components/director/internal/domain/eventapi/repository.go
  components/director/internal/domain/eventapi/repository_test.go
  components/director/internal/domain/eventapi/resolver.go
  components/director/internal/domain/eventapi/resolver_test.go
  components/director/internal/domain/eventapi/service.go
  components/director/internal/domain/eventapi/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/eventapi_test.go
  components/director/internal/persistence/txtest/txtest.go
  components/schema-migrator/migrations/201908141300_initialize_schema.up.sql
  examples/README.md
  examples/query-applications-with-label-filter.graphql
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/labeling_api_test.go
Labels: enhancement

#293 Add runtime auth tests
  chart/compass/values.yaml
  examples/README.md
  examples/query-runtime-auths.graphql
  tests/end-to-end/director/fields.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/runtime_api_test.go
  tests/end-to-end/director/runtime_auth_test.go
Labels: enhancement

#299 Modify extended gql types
  chart/compass/values.yaml
  components/director/pkg/graphql/api.go
  components/director/pkg/graphql/api_definition.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/document.go
  components/director/pkg/graphql/event_api.go
  components/director/pkg/graphql/runtime.go
Labels: bug

#301 Update json schema validator library
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/pkg/jsonschema/validator_test.go
Labels: enhancement

#303 Remove Envoy filter moved to Ory chart, update dependencies to Compass
  chart/compass/templates/rewrite-header-filter.yaml
  chart/compass/values.yaml
  tests/connector-tests/Gopkg.lock
  tests/connector-tests/Gopkg.toml
Labels: enhancement

#308 Create Connector documentation
  components/connector/docs/02-01-connector-service.md
  components/connector/docs/08-01-establish-secure-connection-with-compass.md
  components/connector/docs/08-02-maintain-secure-connection-with-compass.md
  components/connector/docs/api/connectorapi.yaml
  components/connector/docs/assets/001-connection-flow.svg
Labels: area/application-connector, area/documentation

#296 Pass JSON as string in Director
  chart/compass/values.yaml
  components/director/internal/domain/label/translator_test.go
  components/director/internal/domain/labeldef/automock/converter.go
  components/director/internal/domain/labeldef/automock/entity_converter.go
  components/director/internal/domain/labeldef/automock/model_converter.go
  components/director/internal/domain/labeldef/converter.go
  components/director/internal/domain/labeldef/converter_test.go
  components/director/internal/domain/labeldef/repository.go
  components/director/internal/domain/labeldef/repository_test.go
  components/director/internal/domain/labeldef/resolver.go
  components/director/internal/domain/labeldef/resolver_test.go
  components/director/internal/domain/labeldef/service_test.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/json.go
  components/director/pkg/graphql/json_schema.go
  components/director/pkg/graphql/json_schema_test.go
  components/director/pkg/graphql/json_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: bug

#298 Fix schema as string e2e tests
  examples/create-label-definition.graphql
  examples/update-label-definition.graphql
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/graphqlizer_test.go
  tests/end-to-end/director/labeling_api_test.go
Labels: bug

#315 Add mock tenant mapping handler for Director
  components/director/.gitignore
  components/director/cmd/main.go
  components/director/internal/tenantmapping/handler.go
Labels: enhancement

#320 Fix a typo in Connector documentation
  components/connector/docs/08-01-establish-secure-connection-with-compass.md
  components/connector/docs/08-02-maintain-secure-connection-with-compass.md
Labels: area/application-connector, area/documentation, bug

#305 Mock implementation for Compass Provisioner
  chart/compass/charts/provisioner/.helmignore
  chart/compass/charts/provisioner/Chart.yaml
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/templates/service-account.yaml
  chart/compass/charts/provisioner/templates/service.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/Dockerfile
  components/provisioner/Gopkg.lock
  components/provisioner/Gopkg.toml
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/mockresolver.go
  components/provisioner/internal/api/mockresolver_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: area/application-connector, enhancement

#247 Add certificates revocation to Connector
  chart/compass/charts/connector/templates/configmap.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/role-binding.yaml
  chart/compass/charts/connector/templates/tests/role-binding.yaml
  chart/compass/charts/connector/templates/tests/service-account.yaml
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/values.yaml
  components/connector/Gopkg.lock
  components/connector/cmd/main.go
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/authentication/authenticator.go
  components/connector/internal/authentication/authenticator_test.go
  components/connector/internal/authentication/mocks/Authenticator.go
  components/connector/internal/httputils/model.go
  components/connector/internal/httputils/response.go
  components/connector/internal/revocation/mocks/Manager.go
  components/connector/internal/revocation/mocks/RevocationListRepository.go
  components/connector/internal/revocation/repository.go
  components/connector/internal/revocation/repository_test.go
  components/connector/pkg/oathkeeper/validation_hydrator.go
  components/connector/pkg/oathkeeper/validation_hydrator_test.go
  installation/cmd/run-from-kyma.sh
  installation/cmd/run.sh
  tests/connector-tests/Gopkg.lock
  tests/connector-tests/test/apitests/apitests_test.go
  tests/connector-tests/test/apitests/main_test.go
  tests/connector-tests/test/testkit/certificates.go
  tests/connector-tests/test/testkit/config.go
  tests/connector-tests/test/testkit/configmap_cleaner.go
  tests/connector-tests/test/testkit/connector/query.go
Labels: enhancement

#300 Describe Compass security
  docs/README.md
  docs/architecture/assets/certificate-security-diagram-connector.svg
  docs/architecture/assets/certificate-security-diagram-director.svg
  docs/architecture/assets/dex-security-diagram.svg
  docs/architecture/assets/graphql-security.svg
  docs/architecture/assets/oauth2-security-diagram.svg
  docs/architecture/assets/security-architecture.svg
  docs/architecture/authentication-and-authorization.md
  docs/terminology.md
Labels: area/documentation

#334 Mock provisioner tests
  chart/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  chart/compass/values.yaml
  installation/scripts/testing.sh
  tests/provisioner-tests/Dockerfile
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/Makefile
  tests/provisioner-tests/before-commit.sh
  tests/provisioner-tests/scripts/entrypoint.sh
  tests/provisioner-tests/test/apitests/apitests_test.go
  tests/provisioner-tests/test/testkit/client.go
  tests/provisioner-tests/test/testkit/config.go
  tests/provisioner-tests/test/testkit/graphqlizer.go
  tests/provisioner-tests/test/testkit/query.go
Labels: area/application-connector, enhancement

#319 Store Auth in separate DB table
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/system_auth_converter.go
  components/director/internal/domain/runtime/automock/system_auth_service.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/systemauth/automock/auth_converter.go
  components/director/internal/domain/systemauth/automock/converter.go
  components/director/internal/domain/systemauth/automock/repository.go
  components/director/internal/domain/systemauth/automock/uid_service.go
  components/director/internal/domain/systemauth/converter.go
  components/director/internal/domain/systemauth/converter_test.go
  components/director/internal/domain/systemauth/entity.go
  components/director/internal/domain/systemauth/fixtures_test.go
  components/director/internal/domain/systemauth/repository.go
  components/director/internal/domain/systemauth/repository_test.go
  components/director/internal/domain/systemauth/service.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/internal/model/system_auth.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/examples/01_get_apps.graphql
  components/director/pkg/graphql/examples/02_get_app.graphql
  components/director/pkg/graphql/examples/03_get_runtimes.graphql
  components/director/pkg/graphql/examples/04_get_runtime.graphql
  components/director/pkg/graphql/examples/05_get_healthchecks.graphql
  components/director/pkg/graphql/examples/07_create_app.graphql
  components/director/pkg/graphql/examples/08_update_app.graphql
  components/director/pkg/graphql/examples/09_delete_app.graphql
  components/director/pkg/graphql/examples/10_manage_app_labels.graphql
  components/director/pkg/graphql/examples/11_manage_app_webhooks.graphql
  components/director/pkg/graphql/examples/12_manage_api.graphql
  components/director/pkg/graphql/examples/13_mange_event_api.graphql
  components/director/pkg/graphql/examples/14_create_runtime.graphql
  components/director/pkg/graphql/examples/15_update_runtime.graphql
  components/director/pkg/graphql/examples/16_delete_runtime.graphql
  components/director/pkg/graphql/examples/17_manage_runtime_label.graphql
  components/director/pkg/graphql/examples/19_pagination.graphql
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/runtime.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/201909241337_add_system_auths.down.sql
  components/schema-migrator/migrations/201909241337_add_system_auths.up.sql
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/gen-examples.sh
Labels: enhancement

#323 Remove agentAuth field from Runtime and update integration tests
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/converter.go
  components/director/internal/domain/runtime/converter_test.go
  components/director/internal/domain/runtime/entity.go
  components/director/internal/domain/runtime/entity_test.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
  components/director/pkg/graphql/runtime.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/201909251045_remove_agent_auth.down.sql
  components/schema-migrator/migrations/201909251045_remove_agent_auth.up.sql
  examples/create-runtime.graphql
  examples/delete-runtime.graphql
  examples/query-runtime.graphql
  examples/query-runtimes-with-label-filter.graphql
  examples/query-runtimes-with-pagination.graphql
  examples/query-runtimes.graphql
  examples/update-runtime.graphql
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/fields.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/labeling_api_test.go
  tests/end-to-end/director/runtime_api_test.go
  tests/end-to-end/director/runtime_auth_test.go
Labels: enhancement

#335 Certificates in Compass Director
  chart/compass/charts/connector/templates/certs-setup-job.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/oathkeeper-rule.yaml
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/charts/connector/values.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/values.yaml
  tests/connector-tests/test/apitests/apitests_test.go
  tests/connector-tests/test/apitests/oathkeeper_security_test.go
  tests/connector-tests/test/testkit/config.go
Labels: enhancement

#324 Prepare HTTP middleware for Director
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/Gopkg.lock
  components/director/Gopkg.toml
  components/director/cmd/main.go
  components/director/hack/default-jwks.json
  components/director/internal/authenticator/claims.go
  components/director/internal/authenticator/jwks_fetch.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/authenticator/testdata/jwks-private.json
  components/director/internal/authenticator/testdata/jwks-private2.json
  components/director/internal/authenticator/testdata/jwks-public.json
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/pkg/scope/provider.go
  components/director/pkg/scope/provider_test.go
  components/director/pkg/scope/testdata/invalid2.yaml
  components/director/pkg/scope/testdata/invalid3.yaml
  components/director/pkg/scope/testdata/valid2.yaml
  components/director/run.sh
Labels: enhancement

#325 Enable scopes verification for Director
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-secure.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/templates/test.yaml
  chart/compass/values.yaml
  components/director/cmd/main.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/domain/config.go
  components/director/internal/tenantmapping/handler.go
  components/director/run.sh
  installation/cmd/run.sh
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/Gopkg.toml
  tests/end-to-end/README.md
  tests/end-to-end/director/application_api_test.go
  tests/end-to-end/director/common_test.go
  tests/end-to-end/director/examplesaver.go
  tests/end-to-end/director/fixtures.go
  tests/end-to-end/director/fixtures_queries_test.go
  tests/end-to-end/director/fixtures_request_test.go
  tests/end-to-end/director/gqlclient.go
  tests/end-to-end/director/graphqlizer.go
  tests/end-to-end/director/labeling_api_test.go
  tests/end-to-end/director/ptr.go
  tests/end-to-end/director/runtime_api_test.go
  tests/end-to-end/director/runtime_auth_test.go
  tests/end-to-end/director/scopes_test.go
  tests/end-to-end/director/testctx.go
  tests/end-to-end/gen-examples.sh
  tests/end-to-end/pkg/jwtbuilder/jwtbuilder.go
  tests/end-to-end/pkg/ptr/ptr.go
  tests/end-to-end/run.sh
Labels: enhancement

#341 Fix passing scopes in Director
  chart/compass/values.yaml
  components/director/internal/authenticator/claims.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  tests/end-to-end/pkg/jwtbuilder/jwtbuilder.go
Labels: bug

#344 Provisioner mock - error messages fix
  components/provisioner/internal/api/mockresolver.go
Labels: area/application-connector, enhancement

#342 Fix assigning full scopes in Tenant Mapping Handler
  chart/compass/values.yaml
  components/director/internal/tenantmapping/handler.go
  installation/cmd/run.sh
Labels: bug

#345 Fix overwriting tenant in header for Director middleware
  chart/compass/values.yaml
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
Labels: bug
