Repository kyma-incubator/compass, pull requests merged in 2020-01, with the labels that each got.

#602 Restructure Compass docs
  README.md
  components/kyma-environment-broker/README.md
  components/kyma-environment-broker/assets/sm.png
  docs/README.md
  docs/architecture/db-scheme.md
  docs/archive/README.md
  docs/compass/02-01-components.md
  docs/compass/02-02-basic-architecture.md
  docs/compass/02-03-app-runtime-flows.md
  docs/compass/03-01-security.md
  docs/compass/03-02-labeling.md
  docs/compass/03-api-credentials-flows.md
  docs/compass/03-api-packages.md
  docs/compass/03-db-scheme.md
  docs/compass/03-event-flows-proposal.md
  docs/compass/03-input-parameters-on-runtime.md
  docs/compass/03-input-validation.md
  docs/compass/03-provisioning-custom-configuration.md
  docs/compass/03-support-for-legacy-rest-api.md
  docs/compass/03-supported-apis.md
  docs/compass/assets/api-credentials-flow.svg
  docs/compass/assets/api-packages.svg
  docs/compass/assets/api-registration.svg
  docs/compass/assets/app-configuration-update.svg
  docs/compass/assets/app-pairing.svg
  docs/compass/assets/architecture.svg
  docs/compass/assets/certificate-security-diagram-connector.svg
  docs/compass/assets/certificate-security-diagram-director.svg
  docs/compass/assets/client-certificate-flow.svg
  docs/compass/assets/components.svg
  docs/compass/assets/dex-security-diagram.svg
  docs/compass/assets/entity_diagram.svg
  docs/compass/assets/external-event-flow.svg
  docs/compass/assets/graphql-security.svg
  docs/compass/assets/internal-event-flow.svg
  docs/compass/assets/mp-components.svg
  docs/compass/assets/oauth2-security-diagram.svg
  docs/compass/assets/rest-api-to-to-gql-flow.svg
  docs/compass/assets/runtime-configuration-update.svg
  docs/compass/assets/runtime-creation.svg
  docs/compass/assets/runtime-notification.svg
  docs/compass/assets/scenarios.svg
  docs/compass/assets/security-architecture.svg
  docs/connector/oathkeeper-connector-authentication.md
  docs/director/assets/director-architecture.svg
  docs/director/default-eventing-for-application.md
  docs/director/director-component.md
  docs/integration-system/assets/integration-system-registration.svg
  docs/integration-system/auto-app-management.md
  docs/integration-system/integration-systems.md
  docs/investigations/README.md
  docs/kyma-environment-broker/README.md
  docs/provisioner/hyperscaler-account-pool-api-design.md
  docs/provisioner/provisioning-api.md
  docs/runtime-agent/runtime-agent-contract.md
  docs/terminology.md
Labels: area/documentation, enhancement

#606 Fix the linking in Compass docs
  README.md
  docs/archive/assets/client-certificate-flow.svg
  docs/archive/establishing-trusted-connection.md
  docs/compass/02-01-components.md
  docs/compass/02-03-app-runtime-flows.md
  docs/compass/03-support-for-legacy-rest-api.md
  docs/integration-system/auto-app-management.md
  docs/terminology.md
Labels: area/documentation, bug

#593 Add graphql viewer pattern to schema
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/viewer/converter.go
  components/director/internal/domain/viewer/converter_test.go
  components/director/internal/domain/viewer/resolver.go
  components/director/internal/domain/viewer/resolver_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: enhancement

#607 Viewer query integration tests
  chart/compass/values.yaml
  tests/end-to-end/Gopkg.lock
  tests/end-to-end/e2e/README.md
  tests/end-to-end/e2e/auth_test.go
  tests/end-to-end/e2e/fixtures_queries.go
  tests/end-to-end/e2e/fixtures_request.go
  tests/end-to-end/e2e/playground_test.go
  tests/end-to-end/e2e/tenant_mapping_handler_test.go
  tests/end-to-end/e2e/token_utils.go
  tests/end-to-end/e2e/viewer_test.go
  tests/end-to-end/pkg/gql/fields.go
  tests/end-to-end/pkg/idtokenprovider/auth.go
Labels: enhancement

#637 Fix removing examples for Director while generating new ones
  chart/compass/values.yaml
  tests/end-to-end/Makefile
  tests/end-to-end/gen-examples.sh
Labels: enhancement

#636 Return Director authenticator errors in JSON
  chart/compass/values.yaml
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
Labels: enhancement

#450 Pairing Adapters architecture
  docs/integration-system/auto-app-management.md
  docs/investigations/README.md
  docs/investigations/pairing-adapters/external-broker-pairing-adapter.svg
  docs/investigations/pairing-adapters/pairing-application-instance-with-compass.md
  docs/investigations/pairing-adapters/pairing-connector.svg
  docs/investigations/pairing-adapters/pairing-with-use-integration-system.md
  docs/investigations/pairing-adapters/pairing-without-using-integration-system.md
Labels: enhancement

#552 Runtime registers in Compass Director
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/templates/registration-job.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/directorclient_test.go
  components/provisioner/internal/director/graphqlizer.go
  components/provisioner/internal/director/graphqlizer_test.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/director/model.go
  components/provisioner/internal/director/query.go
  components/provisioner/internal/graphql/client.go
  components/provisioner/internal/graphql/gql_client_testkit.go
  components/provisioner/internal/graphql/mocks/Client.go
  components/provisioner/internal/oauth/client.go
  components/provisioner/internal/oauth/client_test.go
  components/provisioner/internal/oauth/mocks/Client.go
  components/provisioner/internal/oauth/types.go
  components/provisioner/internal/oauth/types_test.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/config.yaml
  components/provisioner/pkg/gqlschema/labels.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: enhancement

#651 Pass global account id to provisioner calls
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/broker_test.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/client_v2.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
Labels: area/management-plane

#653 Prepare routes for Connectivity Adapter
  components/connectivity-adapter/cmd/main.go
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/appregistry.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/connector/connector.go
  components/connectivity-adapter/pkg/health/handler.go
Labels: area/management-plane, enhancement

#656 Fix returning GraphQL errors for Director
  chart/compass/values.yaml
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  tests/end-to-end/e2e/tenant_mapping_handler_test.go
Labels: area/management-plane, bug

#671 Align E2E for legacyConnectorURL property in one-time token for the application
  chart/compass/values.yaml
  components/director/run.sh
  tests/director/api/fixtures_queries_test.go
  tests/director/api/fixtures_request_test.go
  tests/director/api/token_api_test.go
  tests/director/gateway-integration/fixtures_queries.go
  tests/director/gateway-integration/fixtures_request.go
  tests/director/gateway-integration/playground_test.go
  tests/director/gen-examples.sh
  tests/director/go.mod
  tests/director/go.sum
  tests/director/pkg/gql/fields.go
Labels: area/management-plane, enhancement

#701 Update charts after kyma migration to k8s 1.16
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/healthchecker/templates/deployment.yaml
  chart/compass/charts/postgresql/templates/statefulset-slaves.yaml
  chart/compass/charts/postgresql/templates/statefulset.yaml
Labels: area/management-plane, enhancement

#705 Change hardcoded component list and seed in keb
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/aws_provider.go
  components/kyma-environment-broker/internal/broker/azure_provider.go
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/broker_test.go
  components/kyma-environment-broker/internal/broker/builder.go
  components/kyma-environment-broker/internal/broker/gcp_provider.go
  components/kyma-environment-broker/internal/provisioner/client_v2.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
Labels: area/management-plane

#680 Assign new runtimes to the default scenario
  chart/compass/values.yaml
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  tests/director/api/assertions.go
  tests/director/api/runtime_api_test.go
  tests/director/go.sum
Labels: area/management-plane, enhancement

#666 Unique cluster name
  chart/compass/values.yaml
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/persistence/service_test.go
  components/provisioner/internal/util/strings.go
  components/provisioner/internal/util/strings_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-04-runtime-status.md
Labels: area/management-plane, enhancement

#717 Handle getting Service via Connectivity Adapter
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/README.md
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/appregistry.go
  components/connectivity-adapter/internal/appregistry/service/automock/gql_fields_provider.go
  components/connectivity-adapter/internal/appregistry/service/automock/graph_q_lizer.go
  components/connectivity-adapter/internal/appregistry/service/automock/graph_ql_request_builder.go
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/fixtures_test.go
  components/connectivity-adapter/internal/appregistry/service/graphql.go
  components/connectivity-adapter/internal/appregistry/service/graphql_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/handler_test.go
Labels: area/management-plane, enhancement

#724 Fix pre-upgrade job in keb chart
  chart/compass/charts/kyma-environment-broker/templates/pre-upgrade-job.yaml
Labels: bug

#729 Save and Load Application Details in context
  components/connectivity-adapter/internal/appregistry/appdetails/app.go
  components/connectivity-adapter/internal/appregistry/appdetails/app_test.go
  components/connectivity-adapter/internal/appregistry/appdetails/middleware.go
Labels: area/management-plane, enhancement

#710 Make API name validation to allow ASCII printable chars
  chart/compass/values.yaml
  components/director/pkg/graphql/api_validation.go
  components/director/pkg/graphql/api_validation_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/event_api_validation.go
  components/director/pkg/graphql/event_api_validation_test.go
  components/director/pkg/graphql/integrationsys_validation.go
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/inputvalidation/validators_map_test.go
  components/director/pkg/inputvalidation/validators_string.go
  components/director/pkg/inputvalidation/validators_string_test.go
  docs/compass/03-input-validation.md
Labels: area/management-plane, enhancement

#726 Support app name param in adapter paths
  chart/compass/charts/connectivity-adapter/templates/oathkeeper-rules.yaml
Labels: area/management-plane, enhancement

#738 Rename tenant to id in tenants query
  chart/compass/values.yaml
  components/director/internal/domain/tenant/resolver.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: area/management-plane, enhancement

#714 Document KEB in Compass
  components/kyma-environment-broker/README.md
  docs/kyma-environment-broker/01-01-overview.md
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/assets/keb-architecture.svg
Labels: area/documentation, enhancement

#693 Provisioner creates ConfigMap with Runtime configuration
  chart/compass/values.yaml
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/middlewares/tenant.go
  components/provisioner/internal/api/mocks/Validator.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/directorclient_test.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/director/model.go
  components/provisioner/internal/director/query.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/Factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/persistence/mocks/Service.go
  components/provisioner/internal/provisioning/persistence/service.go
  components/provisioner/internal/provisioning/runtimes/clientbuilder/clientbuilder.go
  components/provisioner/internal/provisioning/runtimes/clientbuilder/mocks/ConfigMapClientBuilder.go
  components/provisioner/internal/provisioning/runtimes/configuration.go
  components/provisioner/internal/provisioning/runtimes/configuration_test.go
  components/provisioner/internal/provisioning/runtimes/mocks/ConfigProvider.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/errors.go
Labels: area/management-plane, enhancement

#737 Connectivity middleware
  chart/compass/values.yaml
  components/connectivity-adapter/cmd/main.go
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/internal/appregistry/appdetails/automock/graph_ql_request_builder.go
  components/connectivity-adapter/internal/appregistry/appdetails/middleware.go
  components/connectivity-adapter/internal/appregistry/appdetails/middleware_test.go
  components/connectivity-adapter/internal/appregistry/appregistry.go
  components/connectivity-adapter/internal/appregistry/service/automock/gql_fields_provider.go
  components/connectivity-adapter/internal/appregistry/service/graphql.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
Labels: enhancement

#739 Allow empty tenant in claims validation
  chart/compass/values.yaml
  components/director/internal/authenticator/claims.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  tests/director/api/fixtures_queries_test.go
  tests/director/api/integration_system_api_test.go
  tests/director/api/testctx.go
  tests/director/gateway-integration/tenant_mapping_handler_test.go
Labels: area/management-plane, bug

#670 Add support for providing optional components
  chart/compass/charts/kyma-environment-broker/templates/app-config.yaml
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/automock/optional_component_names_provider.go
  components/kyma-environment-broker/internal/broker/automock/optional_component_service.go
  components/kyma-environment-broker/internal/broker/aws_provider.go
  components/kyma-environment-broker/internal/broker/azure_provider.go
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/broker_test.go
  components/kyma-environment-broker/internal/broker/builder.go
  components/kyma-environment-broker/internal/broker/builder_test.go
  components/kyma-environment-broker/internal/broker/dumper.go
  components/kyma-environment-broker/internal/broker/gcp_provider.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/iosafety/iosafety.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/ptr/ptr.go
  components/kyma-environment-broker/internal/runtime/generic_component_disabler.go
  components/kyma-environment-broker/internal/runtime/loki_disabler.go
  components/kyma-environment-broker/internal/runtime/opt_components_service.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/testdata/managed-runtime-components.yaml
Labels: area/management-plane, enhancement

#744 Handle creating Service in Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/appdetails/middleware.go
  components/connectivity-adapter/internal/appregistry/appdetails/middleware_test.go
  components/connectivity-adapter/internal/appregistry/appregistry.go
  components/connectivity-adapter/internal/appregistry/director/cli.go
  components/connectivity-adapter/internal/appregistry/service/automock/converter.go
  components/connectivity-adapter/internal/appregistry/service/automock/gql_fields_provider.go
  components/connectivity-adapter/internal/appregistry/service/automock/graph_q_lizer.go
  components/connectivity-adapter/internal/appregistry/service/automock/graph_ql_requester.go
  components/connectivity-adapter/internal/appregistry/service/automock/service_manager.go
  components/connectivity-adapter/internal/appregistry/service/automock/service_manager_provider.go
  components/connectivity-adapter/internal/appregistry/service/automock/uid_service.go
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connectivity-adapter/internal/appregistry/service/fixtures_test.go
  components/connectivity-adapter/internal/appregistry/service/graphql.go
  components/connectivity-adapter/internal/appregistry/service/graphql_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/handler_test.go
  components/connectivity-adapter/internal/appregistry/service/label.go
  components/connectivity-adapter/internal/appregistry/service/manager.go
  components/connectivity-adapter/internal/appregistry/service/manager_provider.go
  components/connectivity-adapter/internal/appregistry/uid/service.go
  components/connectivity-adapter/pkg/gqlcli/context.go
  components/connectivity-adapter/pkg/gqlcli/context_test.go
Labels: area/management-plane, enhancement

#747 Validation rules fixes
  chart/compass/values.yaml
  components/director/go.sum
  components/director/pkg/graphql/api_validation.go
  components/director/pkg/graphql/api_validation_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/app_validation_test.go
  components/director/pkg/graphql/document_validation.go
  components/director/pkg/graphql/document_validation_test.go
  components/director/pkg/graphql/event_api_validation.go
  components/director/pkg/graphql/event_api_validation_test.go
  components/director/pkg/graphql/integrationsys_validation.go
  components/director/pkg/graphql/integrationsys_validation_test.go
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/graphql/validation.go
  components/director/pkg/graphql/version_validation.go
  components/director/pkg/graphql/version_validation_test.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  docs/compass/03-input-validation.md
  tests/director/api/validation_test.go
  tests/director/gen-examples.sh
  tests/director/go.sum
Labels: area/management-plane, bug, enhancement

#753 Handle deleting Service in Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/director/cli.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/label.go
  components/connectivity-adapter/internal/appregistry/service/manager.go
  components/connectivity-adapter/internal/appregistry/service/manager_factory.go
  components/connectivity-adapter/pkg/apperrors/apperrors.go
Labels: area/management-plane, enhancement

#757 Handle updating service in Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/manager.go
  components/connectivity-adapter/pkg/reqerror/reqerror.go
Labels: area/management-plane, enhancement

#756 add get method
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/model/converted.go
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/label.go
  components/connectivity-adapter/internal/appregistry/service/manager.go
Labels: enhancement

#765 Add LIST method to connectivity adapter
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/label.go
  components/connectivity-adapter/internal/appregistry/service/manager.go
Labels: enhancement

#673 Tenant loader jobs
  chart/compass/charts/director/templates/configmap-default-tenant-config.yaml
  chart/compass/charts/director/templates/tenant-loader-job.yaml
  chart/compass/values.yaml
  components/director/Dockerfile
  components/director/cmd/director/main.go
  components/director/cmd/tenantloader/README.md
  components/director/cmd/tenantloader/main.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/externaltenant/mapping.go
  components/director/internal/externaltenant/mapping_test.go
  components/director/internal/externaltenant/testdata/invalidfiletypes/unsupported.txt
  components/director/internal/externaltenant/testdata/invalidtenants/invalid.json
  components/director/internal/externaltenant/testdata/tenants/valid_tenants.json
  components/director/internal/externaltenant/testdata/tenants/valid_tenants2.json
  components/director/internal/model/businesstenantmapping.go
  docs/compass/03-initial-tenant-loading.md
Labels: area/management-plane, enhancement

#706 Add tenant fetcher
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/templates/tenant-fetcher-secret.yaml
  chart/compass/values.yaml
  components/director/Dockerfile
  components/director/Makefile
  components/director/cmd/tenantfetcher/README.md
  components/director/cmd/tenantfetcher/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/tenant/automock/converter.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/tenantfetcher/automock/converter.go
  components/director/internal/tenantfetcher/automock/event_api_client.go
  components/director/internal/tenantfetcher/automock/tenant_storage_service.go
  components/director/internal/tenantfetcher/client.go
  components/director/internal/tenantfetcher/client_test.go
  components/director/internal/tenantfetcher/converter.go
  components/director/internal/tenantfetcher/converter_test.go
  components/director/internal/tenantfetcher/export_test.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/model.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/run.sh
  components/schema-migrator/migrations/director/202001221149_add_tenant_storage.up.sql
  components/schema-migrator/migrations/director/202001271010_change_unique_on_business_tenants.down.sql
  components/schema-migrator/migrations/director/202001271010_change_unique_on_business_tenants.up.sql
  docs/compass/03-tenant-synchronization.md
Labels: area/management-plane, enhancement

#758 Update compass UI with legacy connector URL
  chart/compass/charts/cockpit/values.yaml
Labels: area/management-plane, enhancement

#770 Fix data in event and api spec marshallin in graphqilzer
  chart/compass/values.yaml
  components/director/examples/register-application/register-application-with-api-definitions.graphql
  components/director/examples/register-application/register-application-with-event-definitions.graphql
  tests/director/api/application_api_test.go
  tests/director/pkg/gql/graphqlizer.go
Labels: bug

#779 Handle cloudsql-proxy on tenant loader and tenant fetcher
  chart/compass/charts/director/templates/tenant-loader-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: area/management-plane

#745 Support for db tenants translation in tenant mapper
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.sum
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/tenantmapping/automock/object_context_for_user_provider.go
  components/director/internal/tenantmapping/automock/tenant_repository.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/internal/tenantmapping/mapper_for_system_auth.go
  components/director/internal/tenantmapping/mapper_for_system_auth_test.go
  components/director/internal/tenantmapping/mapper_for_user.go
  components/director/internal/tenantmapping/mapper_for_user_test.go
  components/director/internal/tenantmapping/model.go
  components/director/internal/tenantmapping/model_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: area/management-plane, enhancement
