Repository kyma-incubator/compass, pull requests merged in 2020-04, with the labels that each got.

#1105 Ensure components order in Provisioner
  chart/compass/values.yaml
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/kyma_config.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/read_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/schema-migrator/migrations/provisioner/202003311308_add_component_order.down.sql
  components/schema-migrator/migrations/provisioner/202003311308_add_component_order.up.sql
Labels: area/management-plane, bug

#1108 Refactor Scenario Assignment service to use Assignment engine
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/automock/assignment_engine.go
  components/director/internal/domain/scenarioassignment/automock/assignment_engine_service.go
  components/director/internal/domain/scenarioassignment/automock/repository.go
  components/director/internal/domain/scenarioassignment/automock/scenarios_def_service.go
  components/director/internal/domain/scenarioassignment/automock/service.go
  components/director/internal/domain/scenarioassignment/engine.go
  components/director/internal/domain/scenarioassignment/mock/mock.go
  components/director/internal/domain/scenarioassignment/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/scenarioassignment/service.go
  components/director/internal/domain/scenarioassignment/service_test.go
Labels: area/management-plane, enhancement

#1088 Kyma version for provisioning on demand from query parameters
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/director/client.go
  components/kyma-environment-broker/internal/director/client_test.go
  components/kyma-environment-broker/internal/director/error.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/error/error.go
  components/kyma-environment-broker/internal/error/error_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/input/automock/component_list_provider.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
Labels: area/management-plane

#1110 Update GraphQL API for Scenario Assignments
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/create-automatic-scenario-assignment/create-automatic-scenario-assignment.graphql
  components/director/examples/delete-automatic-scenario-assignments-for-selector/delete-automatic-scenario-assignments-for-selector.graphql
  components/director/examples/query-automatic-scenario-assignments-for-selector/query-automatic-scenario-assignments-for-selector.graphql
  components/director/hack/config-local.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/api/automatic_scenario_assignment_test.go
  tests/director/api/fixtures_queries_test.go
  tests/director/api/fixtures_request_test.go
Labels: area/management-plane, enhancement

#1115 Retry Connectivity Adapter calls if they failed
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/appdetails/middleware.go
  components/connectivity-adapter/internal/appregistry/appdetails/middleware_test.go
  components/connectivity-adapter/internal/appregistry/director/cli.go
  components/connectivity-adapter/internal/appregistry/director/cli_test.go
  components/connectivity-adapter/internal/connectorservice/connector/client.go
  components/connectivity-adapter/internal/connectorservice/director/client.go
  components/connectivity-adapter/pkg/retry/retry.go
Labels: area/management-plane, enhancement

#1122 Allow disabling default scenario assignment
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/README.md
  components/director/cmd/director/main.go
  components/director/internal/domain/application/automock/scenarios_service.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/labeldef/scenarios_service.go
  components/director/internal/domain/labeldef/scenarios_service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/scenarios_service.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  tests/director/api/labeling_api_test.go
Labels: area/management-plane, enhancement

#1107 Health endpoints for Provisioner and Connector
  chart/compass/charts/connector/templates/virtual-service.yaml
  chart/compass/charts/provisioner/templates/virtual-service.yaml
  chart/compass/values.yaml
  components/connector/config/servers.go
  components/connector/internal/healthz/handler.go
  components/connector/internal/healthz/handler_test.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/middlewares/tenant.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/healthz/handler.go
  components/provisioner/internal/healthz/handler_test.go
Labels: area/management-plane, enhancement

#1120 Change the config brokers field to brokers.hostname and brokers.port
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
Labels: area/eventing

#1144 KEB Image Bump
  chart/compass/values.yaml
Labels: area/eventing

#1142 Make fetcher delete tenants instead of marking them as inactive
  chart/compass/values.yaml
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
Labels: area/management-plane, enhancement

#1126 Tag Azure resource group and namespace with the Kyma runtime properties
  components/kyma-environment-broker/internal/hyperscaler/azure/client.go
  components/kyma-environment-broker/internal/hyperscaler/azure/tags.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
Labels: area/eventing, area/management-plane

#1157 Configure startingDeadlineSeconds in Tenant Fetcher
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: area/management-plane, bug

#1161 Create scenarios Label Definition on get
  chart/compass/values.yaml
  components/director/internal/domain/labeldef/automock/scenarios_service.go
  components/director/internal/domain/labeldef/service.go
  components/director/internal/domain/labeldef/service_test.go
  components/director/internal/domain/root_resolver.go
  tests/director/api/labeling_api_test.go
  tests/director/api/tenant_setup.go
Labels: area/management-plane, enhancement

#1156 Update gopkg.in/yaml.v2 package
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Gopkg.lock
  components/connector/Gopkg.toml
  components/director/go.mod
  components/director/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/provisioner/go.mod
  components/provisioner/go.sum
  tests/connectivity-adapter/go.mod
  tests/connectivity-adapter/go.sum
  tests/connector-tests/Gopkg.lock
  tests/connector-tests/Gopkg.toml
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, bug

#1162 Make Connectors secrets keys configurable
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/values.yaml
  components/connector/config/components.go
  components/connector/config/config.go
  components/connector/internal/certificates/service.go
  components/connector/internal/certificates/service_test.go
Labels: area/management-plane, enhancement

#1134 Add runtime info handler in KEB
  chart/compass/charts/kyma-environment-broker/templates/api-rule.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/appinfo/automock/instance_finder.go
  components/kyma-environment-broker/internal/appinfo/doc.go
  components/kyma-environment-broker/internal/appinfo/dto.go
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_deprovision_operation.golden.json
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_provision_and_deprovision_operations.golden.json
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_provision_operation.golden.json
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_without_operations.golden.json
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_without_service_and_plan_name_should_have_defaults.golden.json
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/no_instances.golden.json
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_validator.go
  components/kyma-environment-broker/internal/broker/plans_validator_test.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/director/oauth/client.go
  components/kyma-environment-broker/internal/httputil/client.go
  components/kyma-environment-broker/internal/httputil/doc.go
  components/kyma-environment-broker/internal/httputil/json.go
  components/kyma-environment-broker/internal/httputil/json_test.go
  components/kyma-environment-broker/internal/httputil/response.go
  components/kyma-environment-broker/internal/httputil/response_dto.go
  components/kyma-environment-broker/internal/httputil/response_test.go
  components/kyma-environment-broker/internal/hyperscaler/azure/env.go
  components/kyma-environment-broker/internal/hyperscaler/azure/env_test.go
  components/kyma-environment-broker/internal/logger/spy_logger.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/ptr/ptr.go
  components/kyma-environment-broker/internal/storage/dbsession/factory.go
  components/kyma-environment-broker/internal/storage/dbsession/read.go
  components/kyma-environment-broker/internal/storage/dbsession/write.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/predicate/predicate.go
  components/kyma-environment-broker/internal/storage/storage.go
  components/kyma-environment-broker/internal/storage/storage_test.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  components/schema-migrator/migrations/kyma-environment-broker/202004032115_add_additonal_runtime_info.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202004032115_add_additonal_runtime_info.up.sql
Labels: area/management-plane, enhancement

#1168 Update Oathkeeper rules to allow port in host header
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
Labels: area/management-plane, bug, priority/critical

#1132 Adjust LMS timeouts
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/internal/httputil/client.go
  components/kyma-environment-broker/internal/lms/client.go
  components/kyma-environment-broker/internal/lms/client_int_test.go
  components/kyma-environment-broker/internal/lms/tenant.go
  components/kyma-environment-broker/internal/lms/tenant_test.go
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step.go
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/lms_tenant_step.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
Labels: area/management-plane

#1135 Add ensure automatic scenario assigment
  chart/compass/values.yaml
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/automock/assignment_engine.go
  components/director/internal/domain/scenarioassignment/automock/assignment_engine_service.go
  components/director/internal/domain/scenarioassignment/automock/label_repository.go
  components/director/internal/domain/scenarioassignment/engine.go
  components/director/internal/domain/scenarioassignment/engine_test.go
  components/director/internal/domain/scenarioassignment/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/scenarioassignment/service.go
  components/director/internal/domain/scenarioassignment/service_test.go
  components/director/pkg/persistence/config.go
  components/director/run.sh
  tests/director/api/automatic_scenario_assignment_test.go
  tests/director/api/fixtures_queries_test.go
  tests/director/api/tenant_setup.go
  tests/director/gen-examples.sh
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#1089 Implement runtime related flows for automatic scenario assignments
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.sum
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/auth_converter.go
  components/director/internal/domain/runtime/automock/eventing_service.go
  components/director/internal/domain/runtime/automock/label_repository.go
  components/director/internal/domain/runtime/automock/label_upsert_service.go
  components/director/internal/domain/runtime/automock/o_auth20_service.go
  components/director/internal/domain/runtime/automock/runtime_converter.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/automock/scenario_assignment_engine.go
  components/director/internal/domain/runtime/automock/scenarios_service.go
  components/director/internal/domain/runtime/automock/system_auth_converter.go
  components/director/internal/domain/runtime/automock/system_auth_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/domain/scenarioassignment/automock/assignment_engine.go
  components/director/internal/domain/scenarioassignment/automock/repository.go
  components/director/internal/domain/scenarioassignment/automock/scenarios_def_service.go
  components/director/internal/domain/scenarioassignment/engine.go
  components/director/internal/domain/scenarioassignment/engine_test.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/scenarioassignment/service_test.go
Labels: area/management-plane, enhancement

#1176 Fix overrides CM in KEB
  chart/compass/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
  docs/kyma-environment-broker/03-06-runtime-overrides.md
Labels: bug, priority/critical

#1175 Document Runtime upgrade and rollback with Runtime Provisioner for devs
  docs/internal/runtime-upgrade.md
Labels: area/documentation, area/management-plane

#1181 Route Director requests from Connectivity Adapter via Gateway
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
Labels: area/management-plane, enhancement

#1185 Remove console overrides towards central MPS
  chart/compass/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
  chart/compass/values.yaml
Labels: area/management-plane

#1195 Update Runtime Agent documentation to be in sync with Kyma docs
  docs/compass/02-01-components.md
  docs/runtime-agent/02-10-runtime-agent-workflow.md
  docs/runtime-agent/03-20-runtime-agent-details.md
  docs/runtime-agent/06-01-runtime-agent-compass-connection.md
  docs/runtime-agent/08-10-runtime-agent-configuration.md
  docs/runtime-agent/08-11-runtime-agent-reconnecting.md
  docs/runtime-agent/assets/runtime-agent-architecture.svg
Labels: area/documentation, area/management-plane

#1204 Remember navigation location after relogin in compass
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#1202 Propagate flag global.enableCompassDefaultScenarioAssignment into UI ConfigMap
  chart/compass/charts/cockpit/templates/configmap.yaml
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, area/management-plane, enhancement

#1198 Proper Runtime labeling in KEB and Provisioner
  chart/compass/values.yaml
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/graphqlizer.go
  components/provisioner/internal/director/graphqlizer_test.go
Labels: area/management-plane, bug

#1184 Tenant Loader as a tool
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher/README.md
  components/director/cmd/tenantloader/README.md
  components/director/cmd/tenantloader/main.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetcher/automock/tenant_storage_service.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  docs/compass/03-initial-tenant-loading.md
  docs/compass/03-tenant-loading.md
Labels: area/management-plane, enhancement

#1200 Provisioner sets subaccountID annotation based on region
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/gardener/testdata/config.json
  components/provisioner/internal/persistence/testutils/database.go
Labels: area/management-plane, enhancement

#1201 Fix delated_at typo
  CODEOWNERS
  chart/compass/values.yaml
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/storage/dbsession/read.go
  components/kyma-environment-broker/internal/storage/dbsession/write.go
  components/kyma-environment-broker/internal/storage/storage_test.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  components/schema-migrator/migrations/kyma-environment-broker/202004201217_fix-delated-typo.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202004201217_fix-delated-typo.up.sql
Labels: bug

#1187 Fix vulnerabilities in repository helpers
  chart/compass/values.yaml
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/document/repository.go
  components/director/internal/domain/document/repository_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/label/query.go
  components/director/internal/domain/label/query_test.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/label/translator.go
  components/director/internal/domain/label/translator_test.go
  components/director/internal/domain/package/automock/api_repository.go
  components/director/internal/domain/package/automock/document_repository.go
  components/director/internal/domain/package/automock/event_api_repository.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/package/service.go
  components/director/internal/domain/packageinstanceauth/repository.go
  components/director/internal/domain/packageinstanceauth/repository_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/scenarioassignment/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/systemauth/repository.go
  components/director/internal/domain/systemauth/repository_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/repo/common.go
  components/director/internal/repo/conditions.go
  components/director/internal/repo/delete.go
  components/director/internal/repo/exist.go
  components/director/internal/repo/get.go
  components/director/internal/repo/get_test.go
  components/director/internal/repo/list.go
  components/director/internal/repo/list_pageable.go
  components/director/internal/repo/list_pageable_test.go
  components/director/internal/repo/list_test.go
  components/director/internal/repo/order_by.go
  components/director/internal/repo/query_builder.go
  components/director/pkg/pagination/pagination.go
  components/director/pkg/pagination/pagination_test.go
Labels: area/management-plane, bug

#1196 Add region to all OSB API requests
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/server.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/httputil/client.go
  components/kyma-environment-broker/internal/middleware/region.go
  components/kyma-environment-broker/internal/middleware/region_test.go
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
  docs/kyma-environment-broker/03-05-authorization.md
Labels: area/documentation, area/management-plane, enhancement

#1230 Autofill FetchRequest URL for OData APIs in Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
Labels: enhancement

#1207 Keb configure provisioning timeout
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/lms/client_int_test.go
  components/kyma-environment-broker/internal/lms/tenant.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step.go
Labels: area/management-plane

#1232 Remove Kyma-specific Runtime Agent documentation
  docs/runtime-agent/02-10-runtime-agent-workflow.md
  docs/runtime-agent/03-20-runtime-agent-details.md
  docs/runtime-agent/06-01-runtime-agent-compass-connection.md
  docs/runtime-agent/08-10-runtime-agent-configuration.md
  docs/runtime-agent/08-11-runtime-agent-reconnecting.md
  docs/runtime-agent/assets/runtime-agent-architecture.svg
Labels: area/documentation, bug

#1231 Adjust APIRule for KEB
  chart/compass/charts/kyma-environment-broker/templates/api-rule.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  docs/kyma-environment-broker/02-02-broker-endpoints.md
Labels: area/management-plane

#1237 Bump k8s to 1.16.9 for SKRs
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
Labels: area/management-plane

#1219 Display runtime labels
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#1193 Add test for upgrade in Provisioner
  chart/compass/values.yaml
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/scripts/entrypoint.sh
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/provisioner/suite.go
  tests/provisioner-tests/test/provisioner/upgrade_test.go
  tests/provisioner-tests/test/testkit/compass/provisioner/client.go
  tests/provisioner-tests/test/testkit/compass/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/compass/provisioner/query.go
  tests/provisioner-tests/test/testkit/config.go
  tests/provisioner-tests/test/testkit/graphql/client.go
  tests/provisioner-tests/test/testkit/inputs.go
  tests/provisioner-tests/test/testkit/util.go
Labels: area/management-plane

#1190 Configures monitoring with OIDC authentication
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/director/client.go
  components/kyma-environment-broker/internal/director/client_test.go
  components/kyma-environment-broker/internal/director/query.go
  components/kyma-environment-broker/internal/ias/assertion_attribute.go
  components/kyma-environment-broker/internal/ias/assertion_attribute_test.go
  components/kyma-environment-broker/internal/ias/automock/bundle.go
  components/kyma-environment-broker/internal/ias/automock/bundle_builder.go
  components/kyma-environment-broker/internal/ias/builder.go
  components/kyma-environment-broker/internal/ias/bundle.go
  components/kyma-environment-broker/internal/ias/bundle_test.go
  components/kyma-environment-broker/internal/ias/client.go
  components/kyma-environment-broker/internal/ias/client_test.go
  components/kyma-environment-broker/internal/ias/fake_client.go
  components/kyma-environment-broker/internal/ias/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/ias_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/ias_deregistration_test.go
  components/kyma-environment-broker/internal/process/provisioning/automock/director_client.go
  components/kyma-environment-broker/internal/process/provisioning/ias_registration.go
  components/kyma-environment-broker/internal/process/provisioning/ias_registration_test.go
  components/kyma-environment-broker/internal/process/provisioning/ias_type.go
  components/kyma-environment-broker/internal/process/provisioning/ias_type_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
Labels: area/management-plane, enhancement

#1212 Connection to EventDataPlatform
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/edp/client.go
  components/kyma-environment-broker/internal/edp/client_test.go
  components/kyma-environment-broker/internal/edp/model.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/automock/edp_client.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/automock/edp_client.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
Labels: area/management-plane, enhancement

#1242 Add scripts for temporary job for Compass with audit log mock enabled
  installation/cmd/run-auditlog-temp.sh
  installation/resources/minikube-values.yaml
  installation/scripts/prow/deploy-and-test-auditlog-temp.sh
  installation/scripts/testing-auditlog-temp.sh
Labels: area/management-plane, enhancement

#1248 Fix selecting EnvironmentKey for EDP
  components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
Labels: area/management-plane

#1217 Add external-services-mock
  chart/compass/values.yaml
  components/external-services-mock/.gitignore
  components/external-services-mock/Dockerfile
  components/external-services-mock/Makefile
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/auditlog/configurationchange/config.go
  components/external-services-mock/internal/auditlog/configurationchange/configuration_test.go
  components/external-services-mock/internal/auditlog/configurationchange/handler.go
  components/external-services-mock/internal/auditlog/configurationchange/service.go
  components/external-services-mock/internal/auditlog/oauth/handler.go
  components/external-services-mock/internal/auditlog/oauth/handler_test.go
  components/external-services-mock/internal/auditlog/oauth/model.go
  components/external-services-mock/internal/httphelpers/common.go
  components/external-services-mock/pkg/health/health.go
  components/gateway/internal/auditlog/automock/auditlog_client.go
  components/gateway/internal/auditlog/automock/auditlog_message_factory.go
  components/gateway/internal/auditlog/client.go
  components/gateway/internal/auditlog/client_test.go
  components/gateway/internal/auditlog/factory.go
  components/gateway/internal/auditlog/factory_test.go
  components/gateway/internal/auditlog/fixtures_test.go
  components/gateway/internal/auditlog/service.go
  components/gateway/internal/auditlog/service_test.go
  components/gateway/pkg/auditlog/model/auditlog.go
  components/gateway/pkg/auditlog/model/graphqlresponse.go
  components/gateway/pkg/auditlog/model/response.go
  components/gateway/pkg/proxy/transport_test.go
Labels: enhancement

#1254 Fix KEB IAS step behavior
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/deprovisioning/ias_deregistration.go
Labels: area/management-plane

#1267 Fix KEB steps behavior
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/edp/client.go
  components/kyma-environment-broker/internal/ias/bundle.go
  components/kyma-environment-broker/internal/ias/client.go
  components/kyma-environment-broker/internal/ias/client_test.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
Labels: area/management-plane
