Repository kyma-incubator/compass, pull requests merged in 2020-02, with the labels that each got.

#784 Update Runtime Provisioner documentation
  components/provisioner/README.md
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/05-01-app-entry-parameters.md
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-03-runtime-operation-status.md
  docs/provisioner/08-04-runtime-status.md
  docs/provisioner/08-05-deprovisioning.md
  docs/provisioner/08-06-clean-up-runtime-data.md
Labels: area/documentation

#790 Fix storing default credentials on API def add
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, area/management-plane, bug

#788 Accept tenants as string for static users
  chart/compass/values.yaml
  components/director/internal/tenantmapping/mapper_for_user.go
  components/director/internal/tenantmapping/mapper_for_user_test.go
  components/director/internal/tenantmapping/staticuser.go
  components/director/internal/tenantmapping/staticuser_test.go
Labels: area/management-plane, enhancement

#741 Setup KEB chart
  chart/compass/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
  chart/compass/charts/kyma-environment-broker/templates/virtualservice.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  installation/cmd/run-from-kyma.sh
  installation/cmd/run.sh
Labels: area/management-plane

#796 Fix broken dropdowns in compass ui
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, bug, priority/critical

#767 V2 separate broker endpoints
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/bind_create.go
  components/kyma-environment-broker/internal/broker/bind_delete.go
  components/kyma-environment-broker/internal/broker/bind_get.go
  components/kyma-environment-broker/internal/broker/bind_last_operation.go
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/broker_test.go
  components/kyma-environment-broker/internal/broker/builder.go
  components/kyma-environment-broker/internal/broker/dumper.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/instance_deprovision.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_last_operation.go
  components/kyma-environment-broker/internal/broker/instance_last_operation_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/director/fake_client.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/common.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  components/kyma-environment-broker/internal/ptr/ptr.go
Labels: area/management-plane, enhancement

#811 Add guards to enable external management of secrets
  chart/compass/charts/gateway/templates/gateway-certs-mtls.yaml
  chart/compass/charts/gateway/templates/gateway-certs.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/charts/provisioner/templates/gardener-creds-secret.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/templates/managed-postgresql-secret.yaml
  chart/compass/templates/tenant-fetcher-secret.yaml
  chart/compass/values.yaml
Labels: area/installation

#761 Add documentation about the optional component functionality
  components/kyma-environment-broker/README.md
  components/kyma-environment-broker/cmd/broker/main.go
  docs/kyma-environment-broker/03-02-runtime-components.md
  docs/kyma-environment-broker/assets/runtime-components.svg
Labels: area/documentation, area/management-plane

#749 Add tests coverage for the opt components functionality
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/internal/broker/builder_test.go
  components/kyma-environment-broker/internal/broker/instance_create_integration_test.go
  components/kyma-environment-broker/internal/broker/testdata/TestBrokerProvisioningScenario.golden.graphql
  components/kyma-environment-broker/internal/broker/testdata/managed-runtime-components.yaml
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  components/kyma-environment-broker/internal/runtime/export_test.go
  components/kyma-environment-broker/internal/runtime/generic_component_disabler_test.go
  components/kyma-environment-broker/internal/runtime/loki_disabler_test.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
  components/kyma-environment-broker/internal/storage/storage_test.go
Labels: area/management-plane, enhancement

#743 Integration tests for Resolver with Gardener
  chart/compass/values.yaml
  components/provisioner/cmd/init.go
  components/provisioner/go.mod
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/api/testdata/shoot.crd.yaml
  components/provisioner/internal/gardener/gardener_main_test.go
  components/provisioner/internal/gardener/shoot_controller.go
  components/provisioner/internal/gardener/step_deprovisioning_in_progress.go
  components/provisioner/internal/gardener/step_installation_in_progress.go
  components/provisioner/internal/installation/installation.go
  components/provisioner/internal/installation/mocks/Service.go
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/internal/runtime/configurator.go
Labels: area/management-plane

#800 Bootstrap Packages GraphQL API mocks
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/domain/api/resolver.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/document/resolver.go
  components/director/internal/domain/eventdef/resolver.go
  components/director/internal/domain/package/mock/api.go
  components/director/internal/domain/package/mock/apiinstanceauth.go
  components/director/internal/domain/package/mock/doc.go
  components/director/internal/domain/package/mock/event.go
  components/director/internal/domain/package/mock/package.go
  components/director/internal/domain/package/resolver.go
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/api.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/document.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/package.go
  components/director/pkg/graphql/package_validation.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: area/management-plane, enhancement

#822 Fix spec format detection and description propagation
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/service/automock/app_labeler.go
  components/connectivity-adapter/internal/appregistry/service/automock/converter.go
  components/connectivity-adapter/internal/appregistry/service/automock/director_client.go
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connectivity-adapter/internal/appregistry/service/fixtures_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/validation/servicedetailsvalidation.go
  components/connectivity-adapter/internal/appregistry/service/validation/servicedetailsvalidation_test.go
Labels: area/management-plane, enhancement

#827 Remove unused packageID from API, Event Definitions and Document
  chart/compass/values.yaml
  components/director/internal/domain/api/resolver.go
  components/director/internal/domain/document/resolver.go
  components/director/internal/domain/eventdef/resolver.go
  components/director/internal/domain/package/mock/api.go
  components/director/internal/domain/package/mock/doc.go
  components/director/internal/domain/package/mock/event.go
  components/director/internal/domain/package/mock/packageinstanceauth.go
  components/director/internal/domain/package/resolver.go
  components/director/pkg/graphql/api.go
  components/director/pkg/graphql/document.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: area/management-plane, enhancement

#812 Add migrations for API Packages
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/202002071200_add_package_definitions.down.sql
  components/schema-migrator/migrations/director/202002071200_add_package_definitions.up.sql
Labels: area/management-plane

#834 Fix Director migrations failing on upgrade
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/202001221149_add_tenant_storage.down.sql
  components/schema-migrator/migrations/director/202001311508_migrate_tenants.up.sql
  components/schema-migrator/migrations/director/202002071200_add_package_definitions.down.sql
  components/schema-migrator/migrations/director/202002071200_add_package_definitions.up.sql
Labels: area/management-plane, bug

#836 Keb operation storage
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/storage/dberr/errors.go
  components/kyma-environment-broker/internal/storage/dbsession/factory.go
  components/kyma-environment-broker/internal/storage/dbsession/read.go
  components/kyma-environment-broker/internal/storage/dbsession/write.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation_test.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/init.go
  components/kyma-environment-broker/internal/storage/storage.go
  components/kyma-environment-broker/internal/storage/storage_test.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  components/schema-migrator/migrations/kyma-environment-broker/202002121000_add_operations.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202002121000_add_operations.up.sql
Labels: area/management-plane

#819 Update documentation for Packages API
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  docs/compass/03-api-credentials-flows.md
  docs/compass/03-api-packages.md
  docs/compass/03-db-scheme.md
  docs/compass/03-input-parameters-on-runtime.md
  docs/compass/03-packages-api.md
  docs/compass/03-packages-credential-requests.md
  docs/compass/assets/api-credentials-flow.svg
  docs/compass/assets/api-packages.svg
  docs/compass/assets/entity_diagram.svg
  docs/compass/assets/packages-api.svg
  docs/runtime-agent/runtime-agent-contract.md
Labels: area/documentation, area/management-plane, enhancement

#837 Store users data in session storage instead of local storage
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#847 Bump base images to alpine-3.11.3
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/gateway/Dockerfile
  components/healthchecker/Dockerfile
  components/kyma-environment-broker/Dockerfile
  components/provisioner/Dockerfile
  components/schema-migrator/Dockerfile
Labels: area/security

#851 Validate Package inputs
  chart/compass/values.yaml
  components/director/pkg/graphql/package_validation.go
  components/director/pkg/graphql/package_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  docs/compass/03-input-validation.md
Labels: area/management-plane, enhancement

#859 Minor provisioning tutorial updates
  docs/provisioner/08-02-provisioning-gardener.md
Labels: area/documentation

#841 Implementation of CRUD operations for Packages
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/package_converter.go
  components/director/internal/domain/application/automock/package_service.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/eventing/service.go
  components/director/internal/domain/package/automock/auth_converter.go
  components/director/internal/domain/package/automock/entity_converter.go
  components/director/internal/domain/package/automock/package_converter.go
  components/director/internal/domain/package/automock/package_repository.go
  components/director/internal/domain/package/automock/package_service.go
  components/director/internal/domain/package/automock/uid_service.go
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/package/converter_test.go
  components/director/internal/domain/package/entity.go
  components/director/internal/domain/package/fixtures_test.go
  components/director/internal/domain/package/mock/package.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/package/resolver.go
  components/director/internal/domain/package/resolver_test.go
  components/director/internal/domain/package/service.go
  components/director/internal/domain/package/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/package.go
  components/director/internal/model/package_test.go
Labels: area/management-plane, enhancement

#855 Implement delete method for PackageInstanceAuth
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/packageinstanceauth/automock/converter.go
  components/director/internal/domain/packageinstanceauth/automock/repository.go
  components/director/internal/domain/packageinstanceauth/automock/service.go
  components/director/internal/domain/packageinstanceauth/automock/uid_service.go
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/packageinstanceauth/resolver_test.go
  components/director/internal/domain/packageinstanceauth/service.go
  components/director/internal/domain/packageinstanceauth/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/package_instance_auth.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  docs/compass/03-packages-credential-requests.md
Labels: area/management-plane, enhancement

#862 Implement repository, converter and models for Package Instance Auth API
  chart/compass/values.yaml
  components/director/internal/domain/packageinstanceauth/automock/auth_converter.go
  components/director/internal/domain/packageinstanceauth/automock/entity_converter.go
  components/director/internal/domain/packageinstanceauth/converter.go
  components/director/internal/domain/packageinstanceauth/converter_test.go
  components/director/internal/domain/packageinstanceauth/entity.go
  components/director/internal/domain/packageinstanceauth/fixtures_test.go
  components/director/internal/domain/packageinstanceauth/repository.go
  components/director/internal/domain/packageinstanceauth/repository_test.go
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/packageinstanceauth/resolver_test.go
  components/director/internal/domain/packageinstanceauth/service_test.go
  components/director/internal/model/package_instance_auth.go
  components/director/internal/model/package_instance_auth_test.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/json.go
  components/director/pkg/graphql/json_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/package_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: area/management-plane, enhancement

#872 Query resolvers for package instance auth
  chart/compass/values.yaml
  components/director/internal/domain/package/automock/package_instance_auth_converter.go
  components/director/internal/domain/package/automock/package_instance_auth_service.go
  components/director/internal/domain/package/fixtures_test.go
  components/director/internal/domain/package/resolver.go
  components/director/internal/domain/package/resolver_test.go
  components/director/internal/domain/packageinstanceauth/automock/repository.go
  components/director/internal/domain/packageinstanceauth/repository.go
  components/director/internal/domain/packageinstanceauth/repository_test.go
  components/director/internal/domain/packageinstanceauth/service.go
  components/director/internal/domain/packageinstanceauth/service_test.go
  components/director/internal/domain/root_resolver.go
Labels: area/management-plane, enhancement

#869 Change logging overrides for disabling loki
  components/kyma-environment-broker/internal/broker/instance_create_integration_test.go
  components/kyma-environment-broker/internal/broker/testdata/TestBrokerProvisioningScenario.golden.graphql
  components/kyma-environment-broker/internal/runtime/loki_disabler.go
  components/kyma-environment-broker/internal/runtime/loki_disabler_test.go
Labels: area/management-plane

#871 Implement requesting deletion of Package Instance Auth
  chart/compass/values.yaml
  components/director/internal/domain/package/automock/package_repository.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/package/resolver.go
  components/director/internal/domain/package/service.go
  components/director/internal/domain/package/service_test.go
  components/director/internal/domain/packageinstanceauth/automock/package_service.go
  components/director/internal/domain/packageinstanceauth/automock/repository.go
  components/director/internal/domain/packageinstanceauth/automock/service.go
  components/director/internal/domain/packageinstanceauth/export_test.go
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/packageinstanceauth/resolver_test.go
  components/director/internal/domain/packageinstanceauth/service.go
  components/director/internal/domain/packageinstanceauth/service_test.go
  components/director/internal/domain/root_resolver.go
Labels: area/management-plane, enhancement

#879 Retry syncing JWKS while token validation error
  chart/compass/values.yaml
  components/director/internal/authenticator/export_test.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/authenticator/testdata/jwks-public2.json
Labels: area/management-plane, bug

#874 Add Package Instance Auth creation request and auth set mutations
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/package/fixtures_test.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/package/service_test.go
  components/director/internal/domain/packageinstanceauth/automock/converter.go
  components/director/internal/domain/packageinstanceauth/automock/package_service.go
  components/director/internal/domain/packageinstanceauth/automock/service.go
  components/director/internal/domain/packageinstanceauth/converter.go
  components/director/internal/domain/packageinstanceauth/converter_test.go
  components/director/internal/domain/packageinstanceauth/fixtures_test.go
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/packageinstanceauth/resolver_test.go
  components/director/internal/domain/packageinstanceauth/service.go
  components/director/internal/domain/packageinstanceauth/service_test.go
  components/director/internal/model/package.go
  components/director/internal/model/package_instance_auth.go
  components/director/internal/model/package_instance_auth_test.go
  components/director/pkg/graphql/json.go
  components/director/pkg/graphql/json_schema.go
  components/director/pkg/graphql/json_schema_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/package_validation.go
  components/director/pkg/graphql/package_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/api/validation_test.go
Labels: area/management-plane, enhancement

#824 Group user login
  chart/compass/charts/director/static-groups.yaml
  chart/compass/charts/director/templates/configmap-static-groups.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/tenantmapping/automock/static_group_repository.go
  components/director/internal/tenantmapping/mapper_for_user.go
  components/director/internal/tenantmapping/mapper_for_user_test.go
  components/director/internal/tenantmapping/model.go
  components/director/internal/tenantmapping/model_test.go
  components/director/internal/tenantmapping/staticgroup.go
  components/director/internal/tenantmapping/staticgroup_test.go
  components/director/internal/tenantmapping/staticuser_test.go
Labels: WIP, area/management-plane, enhancement

#876 Remove go.mod and go.sum from root directory
  go.mod
  go.sum
Labels: area/management-plane

#881 Add static groups file for local run in director
  components/director/hack/static-groups-local.yaml
  components/director/run.sh
  tests/director/gen-examples.sh
Labels: bug

#887 Fix KEB serviceManger charts after #880 typo-fix
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
Labels: bug

#888 Add integration tests for Package API input validation
  chart/compass/values.yaml
  tests/director/api/fixtures_request_test.go
  tests/director/api/validation_test.go
  tests/director/pkg/gql/graphqlizer.go
Labels: area/management-plane, enhancement

#852 Tests for packages API
  chart/compass/values.yaml
  components/connectivity-adapter/go.sum
  components/director/examples/README.md
  components/director/examples/add-package/add-package.graphql
  components/director/examples/delete-package-instance-auth/delete-package-instance-auth.graphql
  components/director/examples/delete-package/delete-package.graphql
  components/director/examples/query-package/query-package.graphql
  components/director/examples/query-packages/query-packages.graphql
  components/director/examples/request-package-instance-auth-creation/request-package-instance-auth-creation.graphql
  components/director/examples/request-package-instance-auth-deletion/request-package-instance-auth-deletion.graphql
  components/director/examples/set-package-instance-auth/set-package-instance-auth.graphql
  components/director/examples/update-package/update-package.graphql
  components/director/internal/domain/package/resolver.go
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/package.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/api/assertions.go
  tests/director/api/fixtures.go
  tests/director/api/fixtures_queries_test.go
  tests/director/api/fixtures_request_test.go
  tests/director/api/labeling_api_test.go
  tests/director/api/package_api_test.go
  tests/director/api/package_instance_auth_test.go
  tests/director/go.mod
  tests/director/go.sum
  tests/director/pkg/gql/fields.go
  tests/director/pkg/gql/graphqlizer.go
Labels: area/management-plane, enhancement

#895 Fix code formatting in provisioning mutation codeblock
  docs/provisioner/08-02-provisioning-gardener.md
Labels: area/documentation

#873 Add documentation on one-time token authentication in Compass security
  docs/compass/03-01-security.md
  docs/compass/assets/security-architecture.svg
  docs/compass/assets/token-security-diagram-connector.svg
  docs/compass/assets/token-security-diagram-director.svg
Labels: area/management-plane
