Repository kyma-incubator/compass, pull requests merged in 2020-07, with the labels that each got.

#1470 Update KEB chart Avs tester tag config parsing
  chart/compass/charts/kyma-environment-broker/templates/_helpers.tpl
  chart/compass/charts/kyma-environment-broker/values.yaml
Labels: area/monitoring

#1474 Fix a broken link
  README.md
Labels: area/documentation, bug

#1471 Bump alpine and luigi in cockpit
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#1479 Update dependencies
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/Gopkg.toml
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
Labels: area/management-plane

#1482 Block merging changes for Kyma Control Plane components
  CODEOWNERS
Labels: area/management-plane, enhancement

#1480 Connectivity adapter use serialized Headers and QueryParams API
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#1481 Update Compass installation document
  README.md
  docs/compass/04-01-installation.md
Labels: area/documentation

#1485 Update installer.yaml
  installation/resources/installer.yaml
Labels: area/management-plane, bug

#1463 Introduce Compass split proposal
  docs/internal/proposals/README.md
  docs/internal/proposals/compass-split/compass-split.md
  docs/internal/proposals/separate-compass/separate-compass.md
Labels: area/documentation, area/management-plane, enhancement

#1486 Remove 2to3 from installer
  installation/resources/installer.yaml
Labels: area/management-plane, bug

#1489 Fix missing values in Compass chart
  chart/compass/configure-managed-gcp-postgresql.md
  chart/compass/templates/managed-postgresql-secret.yaml
Labels: area/management-plane, bug

#1488 Remove dependency on local postgresql installation in compass run script
  components/director/run.sh
Labels: area/management-plane, enhancement

#1493 Split Compass/KCP docs
  docs/README.md
  docs/compass/02-01-components.md
  docs/connector/02-01-connector-service.md
  docs/internal/investigations/provisioning-custom-configuration.md
  docs/internal/runtime-upgrade.md
  docs/kyma-environment-broker/01-01-overview.md
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/03-02-runtime-components.md
  docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
  docs/kyma-environment-broker/03-04-hyperscaler-account-pool.md
  docs/kyma-environment-broker/03-05-authorization.md
  docs/kyma-environment-broker/03-06-runtime-overrides.md
  docs/kyma-environment-broker/03-07-environments-cleanup.md
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
  docs/kyma-environment-broker/08-02-deprovisioning-kyma-environment.md
  docs/kyma-environment-broker/08-03-operation-status.md
  docs/kyma-environment-broker/08-04-instance-details.md
  docs/kyma-environment-broker/assets/hap-flow.svg
  docs/kyma-environment-broker/assets/keb-architecture.svg
  docs/kyma-environment-broker/assets/runtime-components.svg
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/05-01-app-entry-parameters.md
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-03-runtime-operation-status.md
  docs/provisioner/08-04-runtime-status.md
  docs/provisioner/08-05-deprovisioning.md
  docs/provisioner/hyperscaler-account-pool-api-design.md
  docs/provisioner/provisioning-api.md
  docs/runtime-agent/runtime-agent-contract.md
  docs/terminology.md
Labels: area/documentation

#1494 Fix the Runtime Agent contract
  docs/runtime-agent/runtime-agent-contract.md
Labels: area/documentation, area/management-plane

#1492 Bump auths texts
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, area/management-plane

#1496 Update outdated Compass readmes
  README.md
  components/connectivity-adapter/README.md
Labels: area/documentation, area/management-plane, enhancement

#1491 Add doc about tenancy in Compass Director.
  docs/director/03-tenancy.md
  docs/director/assets/tenant-mapping.svg
Labels: area/documentation, area/management-plane

#1498 Bump "Get Kubeconfig"
  chart/compass/charts/cockpit/values.yaml
Labels: area/management-plane

#1502 Describe Compass dependencies
  README.md
Labels: area/documentation, area/management-plane, enhancement

#1503 Bump UI fixes - small texts and notification toast
  chart/compass/charts/cockpit/values.yaml
Labels: area/management-plane

#1505 Describe multiple modes of Compass installation
  README.md
  chart/compass/charts/gateway/templates/gateway-certs-mtls-cacert.yaml
  chart/compass/charts/gateway/templates/gateway-certs-mtls.yaml
  chart/compass/charts/gateway/templates/gateway-certs.yaml
  chart/compass/values.yaml
  docs/compass/04-01-installation.md
  docs/compass/08-01-basic-flow-tutorial.md
  docs/compass/assets/lambda.yaml
  docs/compass/assets/order-service.yaml
  installation/cmd/run.sh
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-overrides-compass-gateway.yaml
  installation/scripts/install-minimal-kyma.sh
Labels: area/documentation, area/management-plane, enhancement
