Repository kyma-incubator/compass, pull requests merged in 2020-06, with the labels that each got.

#1399 Initial Metrics for Provisioner
  chart/compass/charts/provisioner/files/dashboard.json
  chart/compass/charts/provisioner/templates/dashboard.yaml
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/templates/metrics-policy.yaml
  chart/compass/charts/provisioner/templates/service-monitor.yaml
  chart/compass/charts/provisioner/templates/service.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/requirements.yaml
  chart/compass/values.yaml
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/metrics/in_progress_operations.go
  components/provisioner/internal/metrics/in_progress_operations_test.go
  components/provisioner/internal/metrics/metrics.go
  components/provisioner/internal/metrics/mocks/OperationsStatsGetter.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
Labels: area/management-plane

#1404 Add "initialized" metadata field for Tenants query in Director
  chart/compass/values.yaml
  components/director/examples/query-integration-systems/query-integration-systems.graphql
  components/director/examples/query-tenants/query-tenants.graphql
  components/director/internal/domain/labeldef/repository.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/entity.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/str/strings.go
  components/director/pkg/str/strings_test.go
  tests/director/api/application_api_test.go
  tests/director/api/assertions.go
  tests/director/api/tenant_setup.go
  tests/director/api/tenants_api_test.go
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#1411 Update dependency to Director in Director API test
  chart/compass/values.yaml
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#1397 Refactor Runtime Provisioner and Connector charts
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/charts/connectivity-adapter/templates/oathkeeper-rules.yaml
  chart/compass/charts/connectivity-adapter/templates/service.yaml
  chart/compass/charts/connectivity-adapter/templates/tests/service-account.yaml
  chart/compass/charts/connectivity-adapter/templates/tests/tests.yaml
  chart/compass/charts/connectivity-adapter/templates/virtualservice-mtls.yaml
  chart/compass/charts/connectivity-adapter/templates/virtualservice.yaml
  chart/compass/charts/connector/templates/certs-setup-job.yaml
  chart/compass/charts/connector/templates/certs-setup-role-binding.yaml
  chart/compass/charts/connector/templates/configmap.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/role-binding.yaml
  chart/compass/charts/connector/templates/service-account.yaml
  chart/compass/charts/connector/templates/service-role-binding.yaml
  chart/compass/charts/connector/templates/service.yaml
  chart/compass/charts/connector/templates/tests/role-binding.yaml
  chart/compass/charts/connector/templates/tests/service-account.yaml
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/charts/connector/templates/virtual-service.yaml
  chart/compass/charts/connector/values.yaml
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/templates/gardener-creds-secret.yaml
  chart/compass/charts/provisioner/templates/role-binding.yaml
  chart/compass/charts/provisioner/templates/service-account.yaml
  chart/compass/charts/provisioner/templates/service.yaml
  chart/compass/charts/provisioner/templates/tests/role-binding.yaml
  chart/compass/charts/provisioner/templates/tests/service-account.yaml
  chart/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  chart/compass/charts/provisioner/templates/virtual-service.yaml
  chart/compass/charts/provisioner/values.yaml
Labels: area/management-plane, enhancement

#1413 Unify Connector charts
  chart/compass/charts/connector/templates/certs-setup-job.yaml
  chart/compass/charts/connector/templates/configmap.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/role-binding.yaml
  chart/compass/charts/connector/templates/tests/role-binding.yaml
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/values.yaml
Labels: area/management-plane, enhancement

#1414 Introduce separate Compass proposal
  docs/internal/proposals/README.md
  docs/internal/proposals/separate-compass/separate-compass.md
Labels: area/documentation, area/management-plane, enhancement

#1406 Allow Tiller artifacts to not to exist
  chart/compass/values.yaml
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/installation/installation.go
  components/provisioner/internal/installation/release/downloader.go
  components/provisioner/internal/installation/release/downloader_test.go
  components/provisioner/internal/installation/release/file_downloader.go
  components/provisioner/internal/installation/release/on_demand.go
  components/provisioner/internal/installation/release/on_demand_test.go
Labels: area/management-plane

#1405 Install Compass as a separate component
  OWNERS_ALIASES
  chart/compass/charts/cockpit/OWNERS
  chart/compass/charts/cockpit/templates/configmap.yaml
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/cockpit/values.yaml
  chart/compass/charts/gateway/templates/gateway-certs-mtls-cacert.yaml
  chart/compass/charts/gateway/templates/gateway-certs-mtls.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/charts/kyma-environment-broker/files/dashboard.json
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/templates/tests/rbac.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/charts/metris/values.yaml
  chart/compass/requirements.yaml
  chart/compass/templates/agent-configuration-job.yaml
  chart/compass/templates/compass-apps-microfrontend.yaml
  chart/compass/templates/registration-job.yaml
  chart/compass/values.yaml
  installation/cmd/run-from-kyma.sh
  installation/cmd/run.sh
  installation/resources/KYMA_VERSION
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-cr-kyma-diet-compass.yaml
  installation/resources/installer-cr-kyma-diet.yaml
  installation/resources/installer-cr.yaml.tpl
  installation/resources/installer-local.yaml
  installation/resources/installer-overrides-api-gateway.yaml
  installation/resources/installer-overrides-minikube.yaml
  installation/resources/installer.yaml
  installation/resources/minikube-values.yaml
  installation/scripts/build-compass-installer.sh
  installation/scripts/concat-yamls.sh
  installation/scripts/configure-components.sh
  installation/scripts/create-cr.sh
  installation/scripts/extract-compass-installer-image.sh
  installation/scripts/generate-compass-installer-artifacts.sh
  installation/scripts/install-tiller.sh
  installation/scripts/installer.sh
  installation/scripts/is-installed.sh
  installation/scripts/is-ready.sh
  installation/scripts/run-compass-installer.sh
  installation/scripts/testing.sh
  installation/scripts/tiller-tls.sh
  installation/scripts/utils.sh
  tools/compass-installer/Makefile
  tools/compass-installer/compass.Dockerfile
Labels: area/ci, area/management-plane, enhancement

#1418 Extend KEB internal Avs to support custom overrides
  components/kyma-environment-broker/internal/avs/config.go
  components/kyma-environment-broker/internal/avs/external_eval_assistant.go
  components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
  components/kyma-environment-broker/internal/avs/model.go
  components/kyma-environment-broker/internal/avs/model_configurator.go
  components/kyma-environment-broker/internal/avs/model_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations_test.go
  components/kyma-environment-broker/internal/process/provisioning/internal_eval_test.go
Labels: area/monitoring

#1427 Add missing tiller resource
  installation/resources/tiller.yaml
Labels: area/ci, area/management-plane, enhancement

#1433 Adjust KEB usage example tutorials after removing Basic authentication
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
  docs/kyma-environment-broker/08-02-deprovisioning-kyma-environment.md
  docs/kyma-environment-broker/08-03-operation-status.md
  docs/kyma-environment-broker/08-04-instance-details.md
Labels: area/documentation, bug

#1421 Add KEB provisioner client test
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/internal/provisioner/automock/client.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/client_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
Labels: area/management-plane

#1426 Add KymaInstaller artifacts to Compass Artifacts
  installation/cmd/run.sh
  installation/resources/installer-cr-kyma-dependencies.yaml
  installation/resources/installer-overrides-api-gateway.yaml
  installation/scripts/generate-compass-installer-artifacts.sh
  installation/scripts/installer.sh
  installation/scripts/is-kyma-installed.sh
Labels: area/ci, area/management-plane, enhancement

#1437 Disable autoupdate for Gardener clusters
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
Labels: area/management-plane, enhancement

#1435 Update KEB to support extended Avs configuration
  chart/compass/charts/kyma-environment-broker/templates/_helpers.tpl
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/values.yaml
Labels: area/installation

#1431 Show only initialized tenants in compass cockpit
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, enhancement

#1415 [Director Error handling]Use repo.helpers in Label Definition repository
  chart/compass/values.yaml
  components/director/internal/domain/labeldef/entity.go
  components/director/internal/domain/labeldef/repository.go
  components/director/internal/domain/labeldef/repository_test.go
Labels: enhancement

#1423 Bump KYMA_VERISON
  installation/resources/KYMA_VERSION
Labels: area/management-plane, enhancement

#1420 Kubeconfig service
  CODEOWNERS
  chart/oidc-kubeconfig-service/.helmignore
  chart/oidc-kubeconfig-service/Chart.yaml
  chart/oidc-kubeconfig-service/templates/_helpers.tpl
  chart/oidc-kubeconfig-service/templates/deployment.yaml
  chart/oidc-kubeconfig-service/templates/service.yaml
  chart/oidc-kubeconfig-service/templates/serviceaccount.yaml
  chart/oidc-kubeconfig-service/values.yaml
  components/kubeconfig-service/Dockerfile
  components/kubeconfig-service/Makefile
  components/kubeconfig-service/README.md
  components/kubeconfig-service/cmd/generator/main.go
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  components/kubeconfig-service/pkg/authn/middleware.go
  components/kubeconfig-service/pkg/authn/middleware_test.go
  components/kubeconfig-service/pkg/authn/oidc.go
  components/kubeconfig-service/pkg/caller/caller.go
  components/kubeconfig-service/pkg/caller/caller_test.go
  components/kubeconfig-service/pkg/caller/queryProvider.go
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/env/env.go
  components/kubeconfig-service/pkg/reload/doc.go
  components/kubeconfig-service/pkg/reload/reload.go
  components/kubeconfig-service/pkg/reload/watch.go
  components/kubeconfig-service/pkg/reload/watch_test.go
  components/kubeconfig-service/pkg/transformer/kubeconfig.go
  components/kubeconfig-service/pkg/transformer/transformer.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
  components/kubeconfig-service/run.sh
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-cr.yaml.tpl
Labels: area/management-plane, area/security, enhancement

#1425 Add a purpose for the SKRs
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202006161055_add_purpose_for_gardener_config.down.sql
  components/schema-migrator/migrations/provisioner/202006161055_add_purpose_for_gardener_config.up.sql
Labels: area/management-plane, enhancement

#1446 Update Provisioner and KEB documentation after changes to GraphQL schema
  components/kyma-environment-broker/README.md
  docs/kyma-environment-broker/03-01-service-description.md
  docs/provisioner/08-02-provisioning-gardener.md
Labels: area/documentation, area/management-plane

#1449 Delete fork from KEB dependencies
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
Labels: area/management-plane

#1448 Bump Kyma Operator to use Helm3
  .dockerignore
  installation/cmd/run.sh
  installation/resources/installer-local.yaml
  installation/resources/installer.yaml
  installation/resources/tiller.yaml
  installation/scripts/installer.sh
  tools/compass-installer/compass.Dockerfile
Labels: area/management-plane, enhancement

#1451 Update KEB documentation after Provisioner's GraphQL schema changed
  docs/kyma-environment-broker/03-01-service-description.md
Labels: area/documentation, area/management-plane

#1454 Fix Runtime Provisioner naming in KEB docs
  components/kyma-environment-broker/README.md
  docs/kyma-environment-broker/01-01-overview.md
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
  docs/kyma-environment-broker/08-04-instance-details.md
Labels: area/documentation, area/management-plane, bug

#1441 Remove bottleneck in Connector
  chart/compass/values.yaml
  components/connector/cmd/main.go
  components/connector/config/components.go
  components/connector/internal/certificates/cache.go
  components/connector/internal/certificates/loader.go
  components/connector/internal/certificates/service.go
  components/connector/internal/certificates/service_test.go
  components/connector/pkg/graphql/clientset/clientset_main_test.go
Labels: area/application-connector, enhancement

#1462 Fix reading Shoot purpose
  chart/compass/values.yaml
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
Labels: area/management-plane, bug

#1465 Add LicenceType field to GardenerConfig
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202006261510_add_type_for_gardener_config.down.sql
  components/schema-migrator/migrations/provisioner/202006261510_add_type_for_gardener_config.up.sql
Labels: area/management-plane
