Repository kyma-incubator/compass, pull requests merged in 2020-05, with the labels that each got.

#1241 Add new component for usage consumption metering
  CODEOWNERS
  chart/compass/charts/metris/.helmignore
  chart/compass/charts/metris/Chart.yaml
  chart/compass/charts/metris/templates/_helpers.tpl
  chart/compass/charts/metris/templates/deployment.yaml
  chart/compass/charts/metris/templates/secrets.yaml
  chart/compass/charts/metris/templates/service-account.yaml
  chart/compass/charts/metris/templates/service.yaml
  chart/compass/charts/metris/templates/servicemonitor.yaml
  chart/compass/charts/metris/values.yaml
  chart/compass/requirements.yaml
  chart/compass/values.yaml
  components/metris/.dockerignore
  components/metris/.gitignore
  components/metris/Dockerfile
  components/metris/Makefile
  components/metris/README.md
  components/metris/cmd/metris/main.go
  components/metris/go.mod
  components/metris/go.sum
  components/metris/internal/edp/client.go
  components/metris/internal/edp/client_test.go
  components/metris/internal/gardener/client.go
  components/metris/internal/gardener/client_test.go
  components/metris/internal/gardener/controller.go
  components/metris/internal/gardener/controller_test.go
  components/metris/internal/gardener/handlers.go
  components/metris/internal/metrics/metrics.go
  components/metris/internal/provider/azure/azure.go
  components/metris/internal/provider/azure/clients.go
  components/metris/internal/provider/azure/metrics.go
  components/metris/internal/provider/azure/model.go
  components/metris/internal/provider/azure/resources.go
  components/metris/internal/provider/azure/utils.go
  components/metris/internal/provider/provider.go
  components/metris/internal/server/server.go
  components/metris/internal/server/server_test.go
  components/metris/internal/utils/utils.go
Labels: area/management-plane

#1282 Define Azure allowed regions
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
Labels: area/management-plane

#1276 Annotations based on seeds instead of regions
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/gardener/shoot_controller.go
  components/provisioner/internal/gardener/shoot_reconciler.go
Labels: area/management-plane, enhancement

#1284 Bump Provisioner image version
  chart/compass/values.yaml
Labels: area/management-plane

#1250 Auditlog integration tests
  chart/compass/templates/gateway-auditlog-integration-test.yaml
  chart/compass/values.yaml
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/auditlog/configurationchange/handler.go
  installation/resources/minikube-values.yaml
  installation/scripts/testing-auditlog-temp.sh
  tests/director/Dockerfile
  tests/director/external-services-mock-integration/README.md
  tests/director/external-services-mock-integration/auditlog_integration_test.go
  tests/director/external-services-mock-integration/fixtures_queries.go
  tests/director/external-services-mock-integration/fixtures_request.go
  tests/director/external-services-mock-integration/test_main_test.go
  tests/director/external-services-mock-integration/testctx.go
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane

#1222 Update Director with provisioning Runtime information
  chart/compass/values.yaml
  components/director/internal/domain/runtime/converter.go
  components/director/internal/domain/runtime/converter_test.go
  components/director/internal/model/runtime.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/directorclient_test.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/director/model.go
  components/provisioner/internal/director/query.go
  components/provisioner/internal/gardener/annotations.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/shoot_reconciler.go
  components/provisioner/internal/gardener/step_provisioning_failed_step.go
  components/provisioner/internal/gardener/step_provisioning_in_progress.go
  components/provisioner/internal/gardener/step_provisioning_initial.go
  components/provisioner/internal/graphql/gql_client_testkit.go
  components/provisioner/internal/operations/executor.go
  components/provisioner/internal/operations/executor_test.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/wait_for_agent_to_connect.go
  components/provisioner/internal/operations/stages/wait_for_agent_to_connect_test.go
  components/schema-migrator/migrations/director/202004220821_alter_runtimes_status_condition.down.sql
  components/schema-migrator/migrations/director/202004220821_alter_runtimes_status_condition.up.sql
Labels: area/management-plane, enhancement

#1283 Add troubleshooting for Application default eventing
  docs/director/10-01-troubleshooting.md
  docs/director/default-eventing-for-application.md
Labels: area/documentation, area/management-plane

#1252 Add Runtime labeling acceptance test
  chart/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/Makefile
  tests/provisioner-tests/scripts/run_localy.sh
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/provisioner/main_test.go
  tests/provisioner-tests/test/provisioner/suite.go
  tests/provisioner-tests/test/testkit/compass/director/client.go
  tests/provisioner-tests/test/testkit/compass/director/oauth/client.go
  tests/provisioner-tests/test/testkit/compass/director/oauth/client_test.go
  tests/provisioner-tests/test/testkit/compass/director/oauth/types.go
  tests/provisioner-tests/test/testkit/compass/director/oauth/types_test.go
  tests/provisioner-tests/test/testkit/compass/director/query.go
  tests/provisioner-tests/test/testkit/config.go
Labels: area/management-plane, enhancement

#1285 Remove fork from Provisioner dependencies
  components/provisioner/go.mod
  components/provisioner/go.sum
Labels: area/management-plane

#1294 Add doc how to register package without creds
  docs/compass/03-packages-credential-requests.md
Labels: area/documentation, area/management-plane, enhancement

#1277 Add availability zones to the provisioning mutation
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/infrastructure.go
  components/provisioner/internal/model/infrastructure/azure/control_plane.go
  components/provisioner/internal/model/infrastructure/gcp/control_plane.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/pkg/gqlschema/cluster_config.go
  components/provisioner/pkg/gqlschema/cluster_config_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: area/management-plane

#1296 Add zones handling to the Runtime Provisioner in KEB
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/common.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
Labels: area/management-plane

#1259 Create Secrets as configuration of Runtime Agent
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/runtime/clientbuilder/clientbuilder.go
  components/provisioner/internal/runtime/clientbuilder/mocks/ConfigMapClientBuilder.go
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/internal/runtime/configurator.go
  components/provisioner/internal/util/k8s/client_provider.go
  components/provisioner/internal/util/k8s/mocks/K8sClientProvider.go
Labels: area/management-plane

#1300 Increase Tiller wait time
  chart/compass/values.yaml
  components/provisioner/internal/installation/installation.go
Labels: area/management-plane

#1265 Add maintenance window to Provisioner
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/maintwindow.json
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/gardener/testdata/maintwindow.json
  components/provisioner/internal/operations/executor.go
Labels: area/management-plane, enhancement

#1297 metris locking issues fix and some improvments
  chart/compass/charts/metris/templates/_helpers.tpl
  chart/compass/charts/metris/templates/deployment.yaml
  chart/compass/charts/metris/templates/secrets.yaml
  chart/compass/charts/metris/templates/service-account.yaml
  chart/compass/charts/metris/templates/service.yaml
  chart/compass/charts/metris/templates/servicemonitor.yaml
  chart/compass/charts/metris/values.yaml
  components/metris/go.mod
  components/metris/go.sum
  components/metris/internal/gardener/controller_test.go
  components/metris/internal/gardener/handlers.go
  components/metris/internal/metrics/metrics.go
  components/metris/internal/provider/azure/azure.go
  components/metris/internal/provider/azure/metrics.go
  components/metris/internal/provider/azure/model.go
  components/metris/internal/provider/azure/resources.go
  components/metris/internal/provider/provider.go
Labels: area/management-plane

#1308 Fix migrations order
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/202005071312_alter_runtimes_status_condition.down.sql
  components/schema-migrator/migrations/director/202005071312_alter_runtimes_status_condition.up.sql
Labels: area/management-plane, bug

#1307 Update codeowners
  CODEOWNERS
  OWNERS
Labels: enhancement

#1256 Filter out applications in the runtime based on application type
  chart/compass/charts/director/config.yaml
  chart/compass/charts/director/templates/configmap-configuration.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/values.yaml
  components/director/README.md
  components/director/cmd/director/main.go
  components/director/hack/config-local.yaml
  components/director/internal/domain/application/automock/application_hide_cfg_provider.go
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/webhook_repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/label/query.go
  components/director/internal/domain/label/query_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/apperrors/errors.go
  components/director/pkg/apperrors/errors_test.go
  components/director/pkg/config/hiddenapps.go
  components/director/pkg/config/hiddenapps_test.go
  components/director/pkg/config/provider.go
  components/director/pkg/config/provider_test.go
  components/director/pkg/config/scopes.go
  components/director/pkg/config/scopes_test.go
  components/director/pkg/config/testdata/invalid-hide-selectors-invalid-format.yaml
  components/director/pkg/config/testdata/invalid.yaml
  components/director/pkg/config/testdata/valid-hide-selectors-empty.yaml
  components/director/pkg/config/testdata/valid.yaml
  components/director/pkg/scope/context.go
  components/director/pkg/scope/context_test.go
  components/director/pkg/scope/directive.go
  components/director/pkg/scope/directive_test.go
  components/director/pkg/scope/errors.go
  components/director/pkg/scope/provider.go
  components/director/pkg/scope/provider_test.go
  components/director/pkg/scope/testdata/invalid2.yaml
  components/director/pkg/scope/testdata/invalid3.yaml
  components/director/pkg/scope/testdata/valid.yaml
  components/director/pkg/scope/testdata/valid2.yaml
  components/director/run.sh
  docs/director/03-01-hide-applications-from-runtimes.md
  tests/director/api/runtime_api_test.go
  tests/director/api/tenant_setup.go
  tests/director/gen-examples.sh
Labels: area/management-plane, enhancement

#1298 Cleanup temporary auditlog testing job
  installation/cmd/run-auditlog-temp.sh
  installation/cmd/run.sh
  installation/scripts/prow/deploy-and-test-auditlog-temp.sh
  installation/scripts/testing-auditlog-temp.sh
  installation/scripts/testing.sh
Labels: area/management-plane

#1312 Update the Runtime Provisioner documentation after zone changed to a list of zones
  docs/internal/runtime-upgrade.md
  docs/provisioner/08-02-provisioning-gardener.md
Labels: area/management-plane

#1306 Update the Runtime Provisioner e2e test
  chart/compass/values.yaml
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/testkit/compass/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/compass/provisioner/query.go
  tests/provisioner-tests/test/testkit/inputs.go
Labels: area/management-plane

#1295 Add tests for EH Namespace in e2e provisioning test suite
  chart/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
  chart/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
  chart/compass/values.yaml
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/README.md
  tests/e2e/provisioning/internal/gardener/client.go
  tests/e2e/provisioning/internal/gardener/config.go
  tests/e2e/provisioning/internal/hyperscaler/account_pool.go
  tests/e2e/provisioning/internal/hyperscaler/account_provider.go
  tests/e2e/provisioning/internal/hyperscaler/azure/client.go
  tests/e2e/provisioning/internal/hyperscaler/azure/config.go
  tests/e2e/provisioning/internal/hyperscaler/azure/env.go
  tests/e2e/provisioning/internal/hyperscaler/azure/provider.go
  tests/e2e/provisioning/internal/hyperscaler/azure/tags.go
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
  tests/e2e/provisioning/test/e2e_provisioning_test.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/eventing

#1320 Fix Azure zones input in Runtime Provisioner e2e test
  tests/provisioner-tests/test/testkit/inputs.go
Labels: area/management-plane, bug

#1310 Replace basic authentication to oAuth2 in KEB e2e tests
  chart/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
  chart/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
  chart/compass/charts/kyma-environment-broker/templates/tests/rbac.yaml
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/management-plane

#1309 Remove basic authentication from KEB
  chart/compass/charts/kyma-environment-broker/templates/api-rule.yaml
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/server.go
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-05-authorization.md
Labels: area/management-plane

#1321 Handle empty credentials in Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/appdetails/middleware.go
  components/connectivity-adapter/internal/appregistry/appdetails/middleware_test.go
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/pkg/res/error.go
  components/connectivity-adapter/pkg/res/success.go
Labels: area/management-plane, bug

#1329 Update ServiceManagerProxy chart ref
  chart/compass/charts/kyma-environment-broker/values.yaml
Labels: area/management-plane, area/service-catalog

#1255 Add maxConneciton live parameter to director
  chart/compass/values.yaml
  components/director/README.md
  components/director/pkg/persistence/config.go
  components/director/pkg/persistence/persistence.go
Labels: enhancement

#1327 Read component order as *int
  chart/compass/values.yaml
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/read_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/util/pointers.go
Labels: area/management-plane

#1334 Add info about performing migration steps in the Upgrade doc
  docs/internal/runtime-upgrade.md
Labels: area/documentation, area/management-plane

#1330 Fix double marshalling in audit log service
  chart/compass/values.yaml
  components/gateway/internal/auditlog/fixtures_test.go
  components/gateway/internal/auditlog/service.go
  components/gateway/internal/auditlog/service_test.go
  components/gateway/pkg/auditlog/model/auditlog.go
Labels: area/management-plane

#1336 Removing secrets before create new one for IAS
  components/kyma-environment-broker/internal/ias/bundle.go
  components/kyma-environment-broker/internal/ias/bundle_test.go
  components/kyma-environment-broker/internal/ias/client.go
  components/kyma-environment-broker/internal/ias/client_test.go
  components/kyma-environment-broker/internal/ias/fake_client.go
  components/kyma-environment-broker/internal/ias/model.go
Labels: area/management-plane

#1304 Use the InstanceID as a unique name for the EventHubs Resource Group and Namespace
  components/kyma-environment-broker/.gitignore
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
Labels: area/eventing

#1339 Add KEB Technical metrics
  chart/compass/charts/kyma-environment-broker/templates/dashboard.yaml
  chart/compass/charts/kyma-environment-broker/templates/policy.yaml
  chart/compass/charts/kyma-environment-broker/templates/service-monitor.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
Labels: area/management-plane, area/monitoring, enhancement

#1352 Fix operation succeeded description
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
Labels: area/management-plane

#1360 Extend documentation about statuses in the Director
  docs/director/02-01-director-component.md
  docs/director/03-default-eventing-for-application.md
  docs/director/03-fetch-requests.md
  docs/director/03-statuses.md
  docs/director/automatic-status-update.md
Labels: area/documentation

#1338 Collect metrics from Director
  chart/compass/values.yaml
  components/director/README.md
  components/director/cmd/director/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/oauth20/config.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/domain/oauth20/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/metrics/collector.go
  components/director/pkg/persistence/automock/transactioner.go
  components/director/pkg/persistence/persistence.go
Labels: area/management-plane, area/monitoring, enhancement

#1367 Update the Runtime Provisioner documentation
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-04-runtime-status.md
Labels: area/documentation, area/management-plane

#1363 Add a prefix for the created Azure resources
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
Labels: area/eventing, bug

#1344 Add identifier field support to Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/appregistry.go
  components/connectivity-adapter/internal/appregistry/director/cli.go
  components/connectivity-adapter/internal/appregistry/director/cli_test.go
  components/connectivity-adapter/internal/appregistry/service/automock/app_labeler.go
  components/connectivity-adapter/internal/appregistry/service/automock/converter.go
  components/connectivity-adapter/internal/appregistry/service/automock/director_client.go
  components/connectivity-adapter/internal/appregistry/service/automock/request_context_provider.go
  components/connectivity-adapter/internal/appregistry/service/automock/validator.go
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connectivity-adapter/internal/appregistry/service/fixtures_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/handler_test.go
  components/connectivity-adapter/internal/appregistry/service/label.go
  components/connectivity-adapter/internal/appregistry/service/label_test.go
  components/connectivity-adapter/internal/appregistry/service/req_context_provider.go
  components/connectivity-adapter/internal/appregistry/service/validation/servicedetailsvalidation.go
Labels: area/management-plane, bug

#1364 Fix bug in setting audit logs
  components/provisioner/internal/gardener/shoot_reconciler.go
Labels: area/management-plane

#1372 Make sure Azure resource names are in lower case
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
Labels: WIP, area/eventing, bug

#1335 Provisioner gardener steps refactor
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/cmd/migrate_provisioning_operations.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/director/model.go
  components/provisioner/internal/gardener/annotations.go
  components/provisioner/internal/gardener/kubeconfig_provider.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/gardener/shoot.go
  components/provisioner/internal/gardener/shoot_controller.go
  components/provisioner/internal/gardener/shoot_reconciler.go
  components/provisioner/internal/gardener/step_deprovisioning_in_progress.go
  components/provisioner/internal/gardener/step_provisioning_failed_step.go
  components/provisioner/internal/gardener/step_provisioning_in_progress.go
  components/provisioner/internal/gardener/step_provisioning_initial.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/executor_test.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/deprovisioning/delete_cluster.go
  components/provisioner/internal/operations/stages/deprovisioning/delete_cluster_test.go
  components/provisioner/internal/operations/stages/deprovisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/deprovisioning/trigger_kyma_uninstall.go
  components/provisioner/internal/operations/stages/deprovisioning/trigger_kyma_uninstall_test.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion_test.go
  components/provisioner/internal/operations/stages/provisioning/connect_agent.go
  components/provisioner/internal/operations/stages/provisioning/connect_agent_test.go
  components/provisioner/internal/operations/stages/provisioning/install_kyma.go
  components/provisioner/internal/operations/stages/provisioning/install_kyma_test.go
  components/provisioner/internal/operations/stages/provisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/provisioning/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation_test.go
  components/provisioner/internal/operations/stages/upgrade/update_upgrade_state.go
  components/provisioner/internal/operations/stages/upgrade/update_upgrade_step_test.go
  components/provisioner/internal/operations/stages/upgrade/upgrade_kyma.go
  components/provisioner/internal/operations/stages/upgrade/upgrade_kyma_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
Labels: area/management-plane, enhancement

#1368 Push metrics from Tenant Fetcher
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher/README.md
  components/director/cmd/tenantfetcher/main.go
  components/director/internal/metrics/collector.go
  components/director/internal/metrics/const.go
  components/director/internal/metrics/pusher.go
  components/director/internal/tenantfetcher/automock/metrics_pusher.go
  components/director/internal/tenantfetcher/client.go
  components/director/internal/tenantfetcher/client_test.go
Labels: area/management-plane, area/monitoring, enhancement

#1380 Fix shortening response status for metrics in Tenant Fetcher
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/client.go
Labels: area/management-plane, bug

#1378 Fix transtaction rollback log
  chart/compass/values.yaml
  components/director/cmd/tenantloader/main.go
  components/director/internal/domain/api/resolver.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/document/resolver.go
  components/director/internal/domain/document/resolver_test.go
  components/director/internal/domain/eventdef/resolver.go
  components/director/internal/domain/eventdef/resolver_test.go
  components/director/internal/domain/eventing/resolver.go
  components/director/internal/domain/integrationsystem/resolver.go
  components/director/internal/domain/integrationsystem/resolver_test.go
  components/director/internal/domain/labeldef/resolver.go
  components/director/internal/domain/labeldef/resolver_test.go
  components/director/internal/domain/oauth20/resolver.go
  components/director/internal/domain/onetimetoken/resolver.go
  components/director/internal/domain/package/resolver.go
  components/director/internal/domain/package/resolver_test.go
  components/director/internal/domain/packageinstanceauth/resolver.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/systemauth/resolver.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/webhook/resolver.go
  components/director/internal/runtimemapping/handler.go
  components/director/internal/statusupdate/handler.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/pkg/persistence/automock/transactioner.go
  components/director/pkg/persistence/persistence.go
  components/director/pkg/persistence/txtest/txtest.go
Labels: enhancement

#1398 Fix total count in the Director domains
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/integrationsystem/resolver.go
  components/director/internal/domain/package/resolver.go
  components/director/internal/model/businesstenantmapping.go
Labels: area/management-plane, bug

#1400 Remove cbs dependency
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/pkg/executor/executor.go
  components/director/pkg/executor/executor_test.go
  components/director/pkg/signal/signal.go
Labels: area/management-plane

#1401 Fix director tests
  chart/compass/values.yaml
  tests/director/api/assertions.go
  tests/director/api/integration_system_api_test.go
  tests/director/gateway-integration/tenants_test.go
  tests/director/gen-examples.sh
Labels: bug

#1407 Update Runtime Upgrade Readme
  docs/internal/runtime-upgrade.md
Labels: area/management-plane
