Repository kyma-incubator/compass, pull requests merged in 2020-03, with the labels that each got.

#896 [KEB] Remove monitoring from optional components
  chart/compass/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  docs/kyma-environment-broker/03-02-runtime-components.md
Labels: area/service-catalog

#897 Fix nginx vulnerabilities in cockpit
  chart/compass/charts/cockpit/values.yaml
Labels: area/console

#890 Add provisioning operation documentation and bump KEB image
  docs/kyma-environment-broker/03-03-add-provisioning-step.md
Labels: area/management-plane

#909 Modify input validation rule for Application Template
  chart/compass/values.yaml
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  docs/compass/03-input-validation.md
  tests/director/api/validation_test.go
Labels: area/management-plane, enhancement

#907 Generate Junit report from tests
  installation/scripts/prow/deploy-and-test.sh
  installation/scripts/testing.sh
Labels: area/management-plane

#893 Update docker images
  components/director/Dockerfile
  components/schema-migrator/Dockerfile
  tests/connectivity-adapter/Dockerfile
  tests/connector-tests/Dockerfile
  tests/director/Dockerfile
  tests/e2e/provisioning/Dockerfile
  tests/provisioner-tests/Dockerfile
Labels: area/security

#922 Make Loki as required component
  chart/compass/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_validator_test.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/runtime/custom_disabler_example.go
  components/kyma-environment-broker/internal/runtime/custom_disabler_example_test.go
  components/kyma-environment-broker/internal/runtime/loki_disabler.go
  docs/kyma-environment-broker/03-02-runtime-components.md
Labels: area/service-catalog

#911 Add migration with default commerce Application Template
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/graphqlizer/graphqlizer_test.go
  components/schema-migrator/migrations/director/202003041400_add_commerce_template.down.sql
  components/schema-migrator/migrations/director/202003041400_add_commerce_template.up.sql
Labels: area/management-plane, enhancement

#921 Add Support for Service Manager Credentials Override Modes
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/assets/sm.png
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provision_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides_config.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides_test.go
Labels: area/service-catalog

#935 Move graphqlizer to director
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/appdetails/middleware.go
  components/connectivity-adapter/internal/appregistry/appdetails/middleware_test.go
  components/connectivity-adapter/internal/appregistry/director/cli.go
  components/connectivity-adapter/internal/appregistry/service/manager_factory.go
  components/director/examples/query-application-templates/query-application-templates.graphql
  tests/connectivity-adapter/go.mod
  tests/connectivity-adapter/go.sum
  tests/connectivity-adapter/test/testkit/director/client.go
  tests/director/api/application_templates_api_test.go
  tests/director/api/fixtures_request_test.go
  tests/director/api/testctx.go
  tests/director/gateway-integration/testctx.go
  tests/director/go.mod
  tests/director/go.sum
  tests/director/pkg/gql/fields.go
  tests/director/pkg/gql/graphqlizer.go
Labels: area/management-plane, enhancement

#613 Provisioner end-to-end test on Gardener
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/templates/tests/test-provisioner.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/scripts/entrypoint.sh
  tests/provisioner-tests/scripts/run_localy.sh
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/provisioner/main_test.go
  tests/provisioner-tests/test/provisioner/suite.go
  tests/provisioner-tests/test/testkit/assertions/helpers.go
  tests/provisioner-tests/test/testkit/assertions/operation.go
  tests/provisioner-tests/test/testkit/compass/provisioner/client.go
  tests/provisioner-tests/test/testkit/compass/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/compass/provisioner/query.go
  tests/provisioner-tests/test/testkit/config.go
  tests/provisioner-tests/test/testkit/graphql/client.go
  tests/provisioner-tests/test/testkit/util.go
Labels: area/management-plane, area/quality, enhancement

#565 Hyperscaler credential pool proposal
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/secrets.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/gardener/client.go
  components/kyma-environment-broker/internal/gardener/config.go
  components/kyma-environment-broker/internal/hyperscaler/account_pool.go
  components/kyma-environment-broker/internal/hyperscaler/account_pool_test.go
  components/kyma-environment-broker/internal/hyperscaler/account_provider.go
  components/kyma-environment-broker/internal/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/internal/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
Labels: area/documentation, area/management-plane, enhancement

#944 Handle empty credentials for Packages
  chart/compass/values.yaml
  components/director/pkg/graphql/api_validation_test.go
  components/director/pkg/graphql/auth_validation.go
  components/director/pkg/graphql/auth_validation_test.go
  components/director/pkg/graphql/fetchrequest_validation_test.go
  components/director/pkg/graphql/package_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/webhook_validation_test.go
Labels: area/management-plane, enhancement

#948 Fix GraphQLizer after making credentials optional
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  docs/compass/03-input-validation.md
Labels: area/management-plane, bug

#870 Add a document describing Hyperscaler Account Pool
  docs/kyma-environment-broker/03-03-hyperscaler-account-pool.md
  docs/kyma-environment-broker/assets/hap-flow.svg
Labels: area/documentation, area/management-plane

#913 Configure Audit logs for Gardener
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/provisioner/automock/client.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  components/provisioner/Dockerfile
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/middlewares/tenant.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/gardener/annotations.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/schema-migrator/migrations/provisioner/202003050749_add_sub_account_id.down.sql
  components/schema-migrator/migrations/provisioner/202003050749_add_sub_account_id.up.sql
Labels: area/management-plane

#954 Bump cockpit-ui image with whitesource changes
  chart/compass/charts/cockpit/values.yaml
Labels: area/security

#963 Remove istio-init from components list
  installation/resources/installer-cr-kyma-diet-compass.yaml
  installation/resources/installer-cr-kyma-diet.yaml
Labels: area/management-plane, bug

#937 Align KEB chart with the one from Kyma repo
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/pre-upgrade-job.yaml
  chart/compass/charts/kyma-environment-broker/templates/tests/e2e-provisioning.yaml
  chart/compass/charts/kyma-environment-broker/values.yaml
Labels: area/management-plane

#961 Remove possibility to update application name
  chart/compass/values.yaml
  components/director/examples/update-application/update-application.graphql
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/app_validation_test.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/api/application_api_test.go
  tests/director/api/validation_test.go
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#966 Update Director pkg ref in director tests
  chart/compass/values.yaml
  tests/director/go.mod
Labels: area/management-plane, enhancement

#835 Update Compass documentation
  docs/README.md
  docs/archive/README.md
  docs/archive/assets/client-certificate-flow.svg
  docs/archive/establishing-trusted-connection.md
  docs/compass/02-03-app-runtime-flow.md
  docs/compass/02-03-app-runtime-flows.md
  docs/compass/03-02-labeling.md
  docs/compass/03-02-labels.md
  docs/compass/03-supported-apis.md
  docs/compass/assets/api-registration.svg
  docs/compass/assets/app-configuration-update.svg
  docs/compass/assets/app-pairing.svg
  docs/compass/assets/runtime-configuration-update.svg
  docs/compass/assets/runtime-creation.svg
  docs/compass/assets/runtime-notification.svg
  docs/investigations/provisioning-custom-configuration.md
Labels: area/documentation, area/management-plane, enhancement

#927 Improve logging in KEB, sync deprovisioning
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/bind_create.go
  components/kyma-environment-broker/internal/broker/bind_delete.go
  components/kyma-environment-broker/internal/broker/bind_get.go
  components/kyma-environment-broker/internal/broker/bind_last_operation.go
  components/kyma-environment-broker/internal/broker/dumper.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/instance_deprovision.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_last_operation.go
  components/kyma-environment-broker/internal/broker/instance_last_operation_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
Labels: area/management-plane, enhancement

#971 Fix Package description conversion
  chart/compass/values.yaml
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/package/converter_test.go
Labels: area/management-plane, bug

#978 Fix broken links
  docs/provisioner/08-02-provisioning-gardener.md
Labels: area/documentation, bug

#972 Move default auth management to packages
  chart/compass/charts/cockpit/values.yaml
Labels: area/console

#986 Make tenant fetcher discriminator field env optional
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/converter.go
Labels: area/management-plane, bug

#916 Add support for on demand revision parameter while installing Kyma
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/installation/release/mocks/Provider.go
  components/provisioner/internal/installation/release/on_demand.go
  components/provisioner/internal/installation/release/on_demand_test.go
  components/provisioner/internal/installation/release/repository.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
Labels: area/management-plane

#987 Don't fetch both API & Event on details view
  chart/compass/charts/cockpit/values.yaml
Labels: area/console

#892 Switch to Packages API in Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/appregistry.go
  components/connectivity-adapter/internal/appregistry/director/automock/gql_fields_provider.go
  components/connectivity-adapter/internal/appregistry/director/automock/graph_q_lizer.go
  components/connectivity-adapter/internal/appregistry/director/cli.go
  components/connectivity-adapter/internal/appregistry/director/cli_test.go
  components/connectivity-adapter/internal/appregistry/model/converted.go
  components/connectivity-adapter/internal/appregistry/service/automock/app_labeler.go
  components/connectivity-adapter/internal/appregistry/service/automock/converter.go
  components/connectivity-adapter/internal/appregistry/service/automock/director_client.go
  components/connectivity-adapter/internal/appregistry/service/automock/graph_ql_request_builder.go
  components/connectivity-adapter/internal/appregistry/service/automock/graph_ql_requester.go
  components/connectivity-adapter/internal/appregistry/service/automock/request_context_provider.go
  components/connectivity-adapter/internal/appregistry/service/automock/service_manager.go
  components/connectivity-adapter/internal/appregistry/service/automock/service_manager_provider.go
  components/connectivity-adapter/internal/appregistry/service/automock/uid_service.go
  components/connectivity-adapter/internal/appregistry/service/automock/validator.go
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connectivity-adapter/internal/appregistry/service/fixtures_test.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/handler_test.go
  components/connectivity-adapter/internal/appregistry/service/label.go
  components/connectivity-adapter/internal/appregistry/service/manager.go
  components/connectivity-adapter/internal/appregistry/service/manager_factory.go
  components/connectivity-adapter/internal/appregistry/service/req_context_provider.go
  components/connectivity-adapter/internal/appregistry/service/req_context_provider_test.go
  components/connectivity-adapter/internal/appregistry/service/validation/servicedetailsvalidation.go
  components/connectivity-adapter/internal/appregistry/uid/service.go
  components/connectivity-adapter/internal/connectorservice/connector/automock/client.go
Labels: area/management-plane, enhancement

#996 Fix Application update in UI
  chart/compass/charts/cockpit/values.yaml
Labels: area/console, area/management-plane, bug

#957 Enhance KubeAPIServer field of the shoot
  chart/compass/values.yaml
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/persistence/database/schema_initializer_test.go
Labels: area/management-plane, enhancement

#994 Label def scopes for integration systems
  chart/compass/charts/director/config.yaml
  components/director/hack/config-local.yaml
Labels: area/management-plane, enhancement

#905 Install knative-kafka in Kyma Runtime
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/hyperscaler/azure/client.go
  components/kyma-environment-broker/internal/hyperscaler/azure/config.go
  components/kyma-environment-broker/internal/hyperscaler/azure/env.go
  components/kyma-environment-broker/internal/hyperscaler/azure/provider.go
  components/kyma-environment-broker/internal/process/operation.go
  components/kyma-environment-broker/internal/process/operation_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
Labels: area/eventing

#991 [KEB] Add packages support override for SKR
  chart/compass/values.yaml
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provision_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
Labels: area/management-plane

#929 Separate user DB per component
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/tenant-loader-job.yaml
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/pre-upgrade-job.yaml
  chart/compass/charts/postgresql/templates/init-db-config-map.yaml
  chart/compass/charts/postgresql/templates/secrets.yaml
  chart/compass/charts/postgresql/templates/statefulset-slaves.yaml
  chart/compass/charts/postgresql/templates/statefulset.yaml
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/configure-managed-gcp-postgresql.md
  chart/compass/templates/director-api-test.yaml
  chart/compass/templates/managed-postgresql-secret.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
Labels: area/management-plane, area/security

#984 Add validation to label keys
  chart/compass/values.yaml
  components/director/examples/delete-application-label/delete-application-label.graphql
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/eventing/service.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/app_validation_test.go
  components/director/pkg/graphql/labeldef_validation.go
  components/director/pkg/graphql/labeldef_validation_test.go
  components/director/pkg/graphql/labels_validation.go
  components/director/pkg/graphql/labels_validation_test.go
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/graphql/validation.go
  components/kyma-environment-broker/internal/director/query.go
  docs/compass/03-input-validation.md
  docs/director/default-eventing-for-application.md
  docs/integration-system/auto-app-management.md
  tests/connectivity-adapter/test/testkit/director/query.go
  tests/director/api/application_api_test.go
  tests/director/api/assertions.go
  tests/director/api/eventing_test.go
  tests/director/api/runtime_api_test.go
  tests/director/api/validation_test.go
  tests/director/go.sum
Labels: area/management-plane, bug

#1014 Update Director pkg ref in director tests
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#1004 Remove Node Count from Provisioners API
  chart/compass/values.yaml
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/query.go
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/cluster_config_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202003190820_remove_node_count.down.sql
  components/schema-migrator/migrations/provisioner/202003190820_remove_node_count.up.sql
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/testkit/compass/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/compass/provisioner/query.go
  tests/provisioner-tests/test/testkit/util.go
Labels: area/management-plane

#1000 Add overrides from resource step
  chart/compass/charts/kyma-environment-broker/templates/deployment.yaml
  chart/compass/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
  chart/compass/charts/kyma-environment-broker/templates/rbac.yaml
  chart/compass/values.yaml
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
  docs/kyma-environment-broker/03-06-runtime-overrides.md
Labels: area/management-plane, enhancement

#1020 Add GQL types and operations for automatic scenarios assignment
  chart/compass/charts/director/config.yaml
  chart/compass/charts/director/static-groups.yaml
  chart/compass/charts/director/static-users.yaml
  chart/compass/templates/director-api-test.yaml
  chart/compass/templates/director-gateway-integration-test.yaml
  chart/compass/values.yaml
  components/director/go.sum
  components/director/hack/config-local.yaml
  components/director/hack/static-users-local.yaml
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/api/testctx.go
  tests/director/common.sh
  tests/director/gen-examples.sh
  tests/director/go.sum
  tests/director/run.sh
  tests/director/tools/prettier/Dockerfile
Labels: area/management-plane, enhancement

#1030 Revert commercial application template migration
  components/schema-migrator/migrations/director/202003041400_add_commerce_template.down.sql
  components/schema-migrator/migrations/director/202003041400_add_commerce_template.up.sql
  components/schema-migrator/migrations/director/202003121300_alter_app_runtime_status.down.sql
  components/schema-migrator/migrations/director/202003121300_alter_app_runtime_status.up.sql
  components/schema-migrator/migrations/provisioner/202003190820_remove_node_count.down.sql
  components/schema-migrator/migrations/provisioner/202003190820_remove_node_count.up.sql
Labels: area/management-plane, bug

#1033 Fix Runtime Agent naming across docs
  docs/compass/02-01-components.md
  docs/runtime-agent/runtime-agent-contract.md
Labels: area/documentation, area/management-plane

#1037 Add reverted provisioner mutations
  chart/compass/values.yaml
  components/schema-migrator/migrations/provisioner/202003190820_remove_node_count.down.sql
  components/schema-migrator/migrations/provisioner/202003190820_remove_node_count.up.sql
Labels: area/management-plane, bug

#1038 Fix director tests after persistence refactoring
  chart/compass/values.yaml
  tests/director/api/main_test.go
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, bug

#1039 Refactor director tests
  chart/compass/values.yaml
  components/director/examples/eventing/set-default-eventing-for-application.graphql
  components/director/examples/unregister-application/unregister-application.graphql
  components/director/pkg/graphql/graphqlizer/fields.go
  tests/director/api/application_api_test.go
  tests/director/api/eventing_test.go
  tests/director/api/fixtures_request_test.go
  tests/director/api/labeling_api_test.go
  tests/director/api/runtime_api_test.go
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#1044 Update Director pkg ref in director tests
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement

#1047 introduce account label in shoot specs
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/hydroform/service_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/gcp_config.go
  components/provisioner/internal/model/provider.go
Labels: area/management-plane, enhancement

#1051 bump provisioner
  chart/compass/values.yaml
Labels: area/management-plane, enhancement

#1057 Fix app and runtime status update with initial value
  chart/compass/values.yaml
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/runtime/converter.go
  components/director/internal/domain/runtime/converter_test.go
Labels: area/management-plane, bug

#1060 remove provider prefix in cluster names
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
Labels: area/management-plane

#1061 bump provisioner
  chart/compass/values.yaml
Labels: area/management-plane

#1062 Provisioner downloads pre releases
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/templates/gardener-creds-secret.yaml
  chart/compass/charts/provisioner/values.yaml
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
Labels: area/management-plane

#1078 Add mocked queries and mutations for AutomaticScenarioAssignment area
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/mock/mock.go
  components/director/internal/domain/scenarioassignment/resolver.go
Labels: area/management-plane, enhancement

#1067 Fix overrides CM in KEB
  chart/compass/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
Labels: bug

#1069 Implement scenario assignment query for given scenario name
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/automock/converter.go
  components/director/internal/domain/scenarioassignment/automock/entity_converter.go
  components/director/internal/domain/scenarioassignment/automock/repository.go
  components/director/internal/domain/scenarioassignment/automock/service.go
  components/director/internal/domain/scenarioassignment/converter.go
  components/director/internal/domain/scenarioassignment/converter_test.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/internal/domain/scenarioassignment/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/scenarioassignment/service.go
  components/director/internal/domain/scenarioassignment/service_test.go
Labels: area/management-plane, enhancement

#1016 Add knative-eventing-kafka component
  chart/compass/charts/kyma-environment-broker/values.yaml
Labels: area/eventing

#1077 Implement mutation for deleting AutomaticScenarioAssignment type for given selector
  chart/compass/values.yaml
  components/director/internal/domain/scenarioassignment/automock/converter.go
  components/director/internal/domain/scenarioassignment/automock/entity_converter.go
  components/director/internal/domain/scenarioassignment/automock/repository.go
  components/director/internal/domain/scenarioassignment/automock/service.go
  components/director/internal/domain/scenarioassignment/converter_test.go
  components/director/internal/domain/scenarioassignment/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/scenarioassignment/service.go
  components/director/internal/domain/scenarioassignment/service_test.go
Labels: area/management-plane, enhancement

#1084 Implement listing AutomaticScenarioAssignments in Director API
  chart/compass/values.yaml
  components/director/README.md
  components/director/internal/domain/scenarioassignment/automock/repository.go
  components/director/internal/domain/scenarioassignment/automock/service.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/internal/domain/scenarioassignment/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/scenarioassignment/service.go
  components/director/internal/domain/scenarioassignment/service_test.go
  components/director/internal/model/scenarioassignment.go
Labels: area/management-plane, enhancement

#1046 Enable component custom sources in Provisioner schema
  chart/compass/values.yaml
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_with_hydroform_test.go
  components/provisioner/internal/installation/installation.go
  components/provisioner/internal/installation/installation_test.go
  components/provisioner/internal/model/kyma_config.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202003241337_add_source_url.down.sql
  components/schema-migrator/migrations/provisioner/202003241337_add_source_url.up.sql
Labels: area/management-plane, enhancement

#1070 Mutation for deleting AutomaticScenarioAssignment type for a given scenario
  chart/compass/values.yaml
  components/director/internal/domain/scenarioassignment/automock/repository.go
  components/director/internal/domain/scenarioassignment/automock/service.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/internal/domain/scenarioassignment/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/scenarioassignment/service.go
  components/director/internal/domain/scenarioassignment/service_test.go
Labels: area/management-plane, enhancement

#1090 Adjust gqlizer to changes in Automatic Scenario Assignment
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/graphqlizer/graphqlizer_test.go
Labels: area/management-plane, enhancement

#1095 Fix content type for success response from Connectivity Adapter
  chart/compass/values.yaml
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/appdetails/middleware.go
  components/connectivity-adapter/internal/appregistry/service/handler.go
  components/connectivity-adapter/internal/appregistry/service/handler_test.go
  components/connectivity-adapter/internal/connectorservice/api/certificates.go
  components/connectivity-adapter/internal/connectorservice/api/info.go
  components/connectivity-adapter/internal/connectorservice/api/middlewares/authorization.go
  components/connectivity-adapter/internal/connectorservice/api/revocations.go
  components/connectivity-adapter/pkg/res/error.go
  components/connectivity-adapter/pkg/res/header.go
  components/connectivity-adapter/pkg/res/success.go
Labels: area/management-plane, bug

#1081 Provisioner operates only on Shoots in the database
  chart/compass/charts/provisioner/templates/deployment.yaml
  chart/compass/charts/provisioner/values.yaml
  chart/compass/values.yaml
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/annotations.go
  components/provisioner/internal/gardener/shoot_reconciler.go
Labels: area/management-plane, bug

#1097 Update provisioning documentation with custom component sourceURL info
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-04-runtime-status.md
Labels: area/documentation, area/management-plane

#1094 Add Automatic Scenario Assignment query int tests
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/query-automatic-scenario-assignment-for-scenario/query-automatic-scenario-assignment-for-scenario.graphql
  components/director/examples/query-automatic-scenario-assignment-for-selector/query-automatic-scenario-assignment-for-selector.graphql
  components/director/examples/query-automatic-scenario-assignments/query-automatic-scenario-assignments.graphql
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/api/assertions.go
  tests/director/api/automatic_scenario_assignment_test.go
  tests/director/api/fixtures_queries_test.go
  tests/director/api/fixtures_request_test.go
  tests/director/api/tenant_setup.go
  tests/director/go.mod
  tests/director/go.sum
Labels: area/management-plane, enhancement
