Repository kyma-incubator/compass, pull requests merged in 2020-12, with the labels that each got.

#1647 Remove Kyma TWs from owners of MD files
  CODEOWNERS
Labels: area/documentation

#1542 Groups configuration change
  chart/compass/charts/director/static-groups.yaml
  chart/compass/charts/director/values.yaml
Labels: area/management-plane

#1652 Introduce Tenant Fetcher standalone component
  chart/compass/charts/cockpit/templates/configmap.yaml
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-mtls.yaml
  chart/compass/charts/gateway/templates/virtualservice-secure.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/charts/tenant-fetcher/.helmignore
  chart/compass/charts/tenant-fetcher/Chart.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/service.yaml
  chart/compass/charts/tenant-fetcher/templates/tests/tenant-fetcher-test.yaml
  chart/compass/charts/tenant-fetcher/values.yaml
  chart/compass/templates/agent-configuration-job.yaml
  chart/compass/templates/director-gateway-integration-test.yaml
  chart/compass/templates/gateway-external-services-integration.yaml
  chart/compass/values.yaml
  components/tenant-fetcher/Dockerfile
  components/tenant-fetcher/Makefile
  components/tenant-fetcher/cmd/main.go
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  tests/tenant-fetcher/Dockerfile
  tests/tenant-fetcher/Makefile
  tests/tenant-fetcher/go.mod
  tests/tenant-fetcher/go.sum
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/wait-for-tenant-fetcher.sh
Labels: :wave: request review

#1653 Optimize catalog query
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/system-broker/internal/director/client.go
  components/system-broker/internal/director/client_test.go
  components/system-broker/internal/director/directorfakes/fake_client.go
  components/system-broker/internal/director/mocks/GqlFieldsProvider.go
  components/system-broker/internal/director/mocks/GraphQLizer.go
  components/system-broker/internal/osb/bind_create_test.go
  components/system-broker/internal/osb/bind_delete_test.go
  components/system-broker/internal/osb/bind_get_test.go
  components/system-broker/internal/osb/bind_last_op_test.go
  components/system-broker/internal/osb/catalog_converter_test.go
  components/system-broker/internal/osb/catalog_test.go
  components/system-broker/internal/osb/osbfakes/fake_package_credentials_create_requester.go
  components/system-broker/internal/osb/osbfakes/fake_package_credentials_delete_requester.go
  components/system-broker/internal/osb/osbfakes/fake_package_credentials_fetcher.go
  components/system-broker/internal/osb/osbfakes/fake_package_credentials_fetcher_for_instance.go
  components/system-broker/internal/osb/types.go
  components/system-broker/pkg/env/envfakes/fake_environment.go
Labels: :wave: request review

#1657 Connector to go modules
  chart/compass/values.yaml
  components/connector/Dockerfile
  components/connector/Gopkg.lock
  components/connector/Gopkg.toml
  components/connector/Makefile
  components/connector/go.mod
  components/connector/go.sum
  components/connector/pkg/graphql/externalschema/schema_gen.go
  components/connector/pkg/graphql/internalschema/schema_gen.go
  scripts/generic_make_go.mk
  tests/connector-tests/Gopkg.lock
  tests/connector-tests/Gopkg.toml
  tests/connector-tests/Makefile
  tests/connector-tests/go.mod
  tests/connector-tests/go.sum
Labels: :wave: request review
