Repository kyma-incubator/compass, pull requests merged in 2020-11, with the labels that each got.

#1588 E2E tests codebase tweaks
  chart/compass/values.yaml
  tests/connectivity-adapter/test/api/connector_test.go
  tests/connectivity-adapter/test/testkit/connector/certs.go
  tests/connectivity-adapter/test/testkit/connector/securedclient.go
  tests/director/api/testctx.go
  tests/director/external-services-mock-integration/main_test.go
  tests/director/gateway-integration/compass_auth_test.go
  tests/director/gateway-integration/main_test.go
  tests/director/pkg/connector/certificate.go
  tests/director/pkg/connector/client.go
  tests/director/pkg/idtokenprovider/auth.go
  tests/director/pkg/idtokenprovider/idtokenprovider.go
  tests/director/pkg/jwtbuilder/jwtbuilder.go
Labels: :wave: request review

#1591 Use form3tech-oss/jwt-go instead of dgrijalva/jwt-go
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/authenticator/claims.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/oathkeeper/model.go
  components/director/internal/runtimemapping/automock/token_verifier.go
  components/director/internal/runtimemapping/handler.go
  components/director/internal/runtimemapping/handler_test.go
  components/director/internal/runtimemapping/keys_cache.go
  components/director/internal/runtimemapping/keys_cache_test.go
  components/director/internal/runtimemapping/token_verifier.go
  components/director/internal/runtimemapping/token_verifier_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/auditlog/oauth/handler.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/gateway/pkg/proxy/transport.go
  tests/director/go.mod
  tests/director/go.sum
  tests/director/pkg/jwtbuilder/jwtbuilder.go
Labels: :wave: request review

#1595 Fix director dependency as part of timeout handler fix
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Gopkg.lock
  components/gateway/go.mod
  components/gateway/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
Labels: :wave: request review

#1592 Fix CloudSQL Proxy throttling issue with Tenant Fetcher
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: :wave: request review

#1593 Add E2E tests for HasScenario directive
  chart/compass/values.yaml
  components/director/pkg/scenario/directive.go
  tests/director/api/application_api_test.go
  tests/director/api/fixtures_queries_test.go
  tests/director/api/package_instance_auth_test.go
  tests/director/api/runtime_api_test.go
Labels: :wave: request review

#1579 Refactor correlation ID handling in director
  chart/compass/templates/rewrite-correlation-headers-filter.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/graphql_client/client.go
  components/director/pkg/correlation/context.go
  components/director/pkg/correlation/context_test.go
  components/director/pkg/correlation/middleware.go
  components/director/pkg/correlation/middleware_test.go
  components/director/pkg/http/automock/http_round_tripper.go
  components/director/pkg/http/correlation_id_transport.go
  components/director/pkg/http/correlation_id_transport_test.go
  components/director/pkg/http/request/request.go
  components/director/pkg/http/request/request_test.go
  components/director/pkg/http/types.go
  components/director/pkg/request/request.go
  components/director/pkg/request/request_test.go
Labels: :wave: request review

#1600 Use newer EnvoyFilter declaration
  chart/compass/templates/rewrite-correlation-headers-filter.yaml
Labels: :wave: request review, bug

#1606 Ensure empty services are not present in System Broker Catalog
  components/system-broker/internal/osb/catalog.go
  components/system-broker/internal/osb/catalog_converter.go
  components/system-broker/tests/catalog_test/catalog_test.go
Labels: :wave: request review

#1605 Set CloudSQL Proxy Termination timeout
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: :wave: request review

#1574 Catalog sys broker
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/system-broker/internal/director/client.go
  components/system-broker/internal/director/query_provider.go
  components/system-broker/internal/osb/catalog.go
  components/system-broker/internal/osb/catalog_converter.go
  components/system-broker/internal/osb/catalog_test.go
  components/system-broker/internal/osb/osbfakes/fake_applications_lister.go
  components/system-broker/internal/osb/osbfakes/fake_converter.go
  components/system-broker/internal/osb/types.go
  components/system-broker/pkg/env/env.go
  components/system-broker/pkg/graphql/client.go
  components/system-broker/pkg/http/secured_transport.go
  components/system-broker/pkg/http/types.go
  components/system-broker/pkg/server/config.go
  components/system-broker/pkg/server/server.go
  components/system-broker/run.sh
  components/system-broker/tests/catalog_test/catalog_test.go
  components/system-broker/tests/common/common.go
  components/system-broker/tests/common/fake_router.go
  components/system-broker/tests/common/gql_fake_server.go
  components/system-broker/tests/common/test_context.go
  components/system-broker/tools/tools.go
Labels: :wave: request review

#1602 Use new correlation middleware and transport
  chart/compass/values.yaml
  components/connectivity-adapter/cmd/main.go
  components/connectivity-adapter/internal/appregistry/service/req_context_provider.go
  components/connectivity-adapter/pkg/gqlcli/gqlcli.go
  components/connector/Gopkg.lock
  components/connector/cmd/main.go
  components/connector/config/servers.go
  components/connector/pkg/graphql/clientset/cert_secured_client.go
  components/connector/pkg/graphql/clientset/token_secured_client.go
  components/gateway/cmd/main.go
  components/gateway/internal/auditlog/automock/auditlog_client.go
  components/gateway/internal/auditlog/basic_client.go
  components/gateway/internal/auditlog/client.go
  components/gateway/internal/auditlog/client_test.go
  components/gateway/internal/auditlog/service.go
  components/gateway/internal/auditlog/service_test.go
  components/gateway/internal/auditlog/worker.go
  components/gateway/pkg/proxy/automock/auditlog_service.go
  components/gateway/pkg/proxy/proxy.go
  components/gateway/pkg/proxy/transport.go
  components/gateway/pkg/proxy/transport_test.go
  components/pairing-adapter/cmd/main.go
  tests/director/external-services-mock-integration/fixtures_request.go
Labels: :wave: request review

#1597 Unify Logging in Connector
  chart/compass/values.yaml
  components/connector/Gopkg.lock
  components/connector/cmd/main.go
  components/connector/config/config.go
  components/connector/config/servers.go
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/api/token_resolver.go
  components/connector/internal/api/token_resolver_test.go
  components/connector/internal/authentication/authenticator.go
  components/connector/internal/certificates/loader.go
  components/connector/internal/certificates/mocks/Service.go
  components/connector/internal/certificates/service.go
  components/connector/internal/certificates/service_test.go
  components/connector/internal/healthz/handler.go
  components/connector/internal/healthz/handler_test.go
  components/connector/internal/httputils/response.go
  components/connector/internal/httputils/util.go
  components/connector/internal/revocation/cache.go
  components/connector/internal/revocation/loader.go
  components/connector/internal/tokens/cache.go
  components/connector/internal/tokens/mocks/Service.go
  components/connector/internal/tokens/service.go
  components/connector/internal/tokens/service_test.go
  components/connector/pkg/graphql/clientset/clientset_main_test.go
  components/connector/pkg/graphql/clientset/clientset_test.go
  components/connector/pkg/oathkeeper/validation_hydrator.go
  tests/connector-tests/scripts/run_localy.sh
Labels: :wave: request review

#1603 Runtime Contexts Initial data model and CRUD operations
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/domain/label/converter.go
  components/director/internal/domain/label/entity.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime_context/automock/label_repository.go
  components/director/internal/domain/runtime_context/automock/label_upsert_service.go
  components/director/internal/domain/runtime_context/automock/runtime_context_converter.go
  components/director/internal/domain/runtime_context/automock/runtime_context_repository.go
  components/director/internal/domain/runtime_context/automock/runtime_context_service.go
  components/director/internal/domain/runtime_context/automock/uid_service.go
  components/director/internal/domain/runtime_context/converter.go
  components/director/internal/domain/runtime_context/converter_test.go
  components/director/internal/domain/runtime_context/entity.go
  components/director/internal/domain/runtime_context/entity_test.go
  components/director/internal/domain/runtime_context/repository.go
  components/director/internal/domain/runtime_context/repository_test.go
  components/director/internal/domain/runtime_context/resolver.go
  components/director/internal/domain/runtime_context/resolver_test.go
  components/director/internal/domain/runtime_context/service.go
  components/director/internal/domain/runtime_context/service_test.go
  components/director/internal/model/label.go
  components/director/internal/model/runtime_context.go
  components/director/internal/model/runtime_context_test.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/runtime_context.go
  components/director/pkg/graphql/runtime_context_validation.go
  components/director/pkg/graphql/runtime_context_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/validation.go
  components/director/pkg/resource/resource.go
  components/schema-migrator/migrations/director/202011031147_add_runtime_contexts.down.sql
  components/schema-migrator/migrations/director/202011031147_add_runtime_contexts.up.sql
Labels: :wave: request review

#1611 Fix timeout handler ambiguous logs
  chart/compass/values.yaml
  components/director/pkg/handler/timeout_handler.go
Labels: :wave: request review

#1612 Fix dependencies as part of Timeout Handler fix
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Gopkg.lock
  components/gateway/go.mod
  components/gateway/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
Labels: :wave: request review

#1613 Fix pairing-adapter handler
  chart/compass/values.yaml
  components/pairing-adapter/cmd/main.go
Labels: :wave: request review

#1604 Update connector documentation
  docs/connector/08-01-establish-secure-connection-with-compass.md
Labels: :wave: request review, area/documentation

#1615 Use CMP org team in CODEOWNERS
  CODEOWNERS
Labels: :wave: request review

#1596 Adjust Policy and IstioOperator resources
  chart/compass/charts/connectivity-adapter/templates/virtualservice.yaml
  chart/compass/charts/director/templates/policy.yaml
  chart/compass/charts/gateway/templates/virtualservice-mtls.yaml
  chart/compass/charts/gateway/templates/virtualservice-secure.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/policy.yaml
  chart/compass/templates/rewrite-client-cert-filter.yaml
  chart/compass/templates/rewrite-token-filter.yaml
  installation/resources/KYMA_VERSION
  installation/resources/kyma/installer-cr-kyma-dependencies.yaml
  installation/resources/kyma/installer-cr-kyma.yaml
  installation/resources/kyma/installer-overrides-istio.yaml
  installation/resources/kyma/installer-overrides-kyma-config-local.yaml
  installation/scripts/generate-compass-installer-artifacts.sh
Labels: area/installation, area/service-mesh

#1608 Add timeout environment variables to the README.md
  components/connectivity-adapter/README.md
  components/director/README.md
  components/gateway/README.md
  components/pairing-adapter/README.md
Labels: :wave: request review, area/documentation

#1618 Propagate client_user to Token Service
  chart/compass/charts/gateway/templates/virtualservice-secure.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/domain/client/client.go
  components/director/internal/domain/client/client_test.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/onetimetoken/service_test.go
  components/director/pkg/apperrors/consts.go
  components/director/pkg/apperrors/errors.go
  components/director/pkg/pairing/model.go
  components/pairing-adapter/internal/adapter/handler_test.go
  components/pairing-adapter/internal/adapter/model.go
Labels: :wave: request review

#1624 Fix istio installation on minikube
  installation/resources/kyma/installer-overrides-istio.yaml
Labels: :wave: request review

#1620 Fix tenant-fetcher crash loop
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: :wave: request review

#1619 Fix resources limits of director and gateway deployments
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/healthchecker/templates/deployment.yaml
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
Labels: :wave: request review

#1625 Use minikube docker driver to run a cluster alongside VPN
  installation/cmd/run.sh
Labels: :wave: request review

#1627 Fix compass console charts
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/cockpit/values.yaml
  chart/compass/values.yaml
Labels: :wave: request review

#1628 Fix other jobs with CloudSQL proxy potential crash loops
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/templates/migrator-job.yaml
Labels: :wave: request review

#1623 Use kyma-gateway instead of compass-gateway during kyma installation
  chart/compass/charts/connectivity-adapter/templates/virtualservice-mtls.yaml
  chart/compass/charts/gateway/templates/cmp-root-ca.yaml
  chart/compass/charts/gateway/templates/gateway-certs-mtls.yaml
  chart/compass/charts/gateway/templates/gateway.yaml
  chart/compass/charts/gateway/templates/virtualservice-mtls.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/values.yaml
  installation/resources/installer-config-local-compass-with-full-kyma.yaml
  installation/resources/kyma/installer-cr-kyma-dependencies.yaml
  installation/resources/kyma/installer-overrides-api-gateway.yaml
  installation/resources/kyma/installer-overrides-core-tests.yaml
  installation/resources/kyma/installer-overrides-tracing.yaml
  installation/scripts/install-kyma.sh
Labels: :wave: request review

#1631 Replace latest-published source flag with master source flag
  installation/scripts/install-kyma.sh
Labels: area/cli
