Repository kyma-incubator/compass, pull requests merged in 2021-02, with the labels that each got.

#1715 Enable holdApplicationUntilProxyStarts Istio flag
  chart/compass/charts/connectivity-adapter/templates/tests/tests.yaml
  chart/compass/charts/connector/templates/tests/test-connector.yaml
  chart/compass/charts/ord-service/templates/tests/ord-service-test.yaml
  chart/compass/charts/system-broker/templates/tests/system-broker-test.yaml
  chart/compass/charts/tenant-fetcher/templates/tests/tenant-fetcher-test.yaml
  chart/compass/templates/director-api-test.yaml
  chart/compass/templates/director-gateway-integration-test.yaml
  chart/compass/templates/gateway-external-services-integration.yaml
  chart/compass/values.yaml
  installation/resources/kyma/installer-overrides-istio.yaml
  installation/resources/kyma/installer-overrides-kyma-config-local.yaml
  scripts/README.md
  tests/connector-tests/before-commit.sh
  tests/connector-tests/test/apitests/main_test.go
  tests/connector-tests/test/testkit/wait.go
  tests/director/Dockerfile
  tests/director/gen-examples.sh
  tests/director/go.sum
  tests/director/wait-for-director.sh
  tests/ord-service/Dockerfile
  tests/ord-service/go.sum
  tests/ord-service/wait-for-components.sh
  tests/system-broker/Dockerfile
  tests/system-broker/go.mod
  tests/system-broker/wait-for-components.sh
  tests/tenant-fetcher/Dockerfile
  tests/tenant-fetcher/wait-for-tenant-fetcher.sh
Labels: :wave: request review

#1720 [CMP-426] Update dependencies versions
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/healthchecker/Gopkg.lock
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/system-broker/tests/common/test_context.go
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
Labels: :wave: request review

#1721 Downgrade kube builder's dependencies in the system broker
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/tenantfetcher/kubernetes.go
  components/director/pkg/inputvalidation/validators_string_test.go
  components/system-broker/go.mod
  components/system-broker/go.sum
Labels: :heavy_check_mark: Approved

#1726 Add RW mutex in mocked services
  chart/compass/values.yaml
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/auditlog/configurationchange/configuration_test.go
  components/external-services-mock/internal/auditlog/configurationchange/service.go
Labels: :wave: request review

#1717 Add async-operations component and corresponding charts
  chart/compass/charts/operations-controller/.helmignore
  chart/compass/charts/operations-controller/Chart.yaml
  chart/compass/charts/operations-controller/templates/crds.yaml
  chart/compass/charts/operations-controller/templates/manager.yaml
  chart/compass/charts/operations-controller/templates/prometheus.yaml
  chart/compass/charts/operations-controller/templates/rbac.yaml
  chart/compass/charts/operations-controller/templates/tests/async-operations-tests.yaml
  chart/compass/charts/operations-controller/values.yaml
  chart/compass/requirements.yaml
  chart/compass/values.yaml
  components/operations-controller/.gitignore
  components/operations-controller/Dockerfile
  components/operations-controller/Makefile
  components/operations-controller/PROJECT
  components/operations-controller/README.md
  components/operations-controller/api/v1alpha1/groupversion_info.go
  components/operations-controller/api/v1alpha1/operation_types.go
  components/operations-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/operations-controller/config/certmanager/certificate.yaml
  components/operations-controller/config/certmanager/kustomization.yaml
  components/operations-controller/config/certmanager/kustomizeconfig.yaml
  components/operations-controller/config/crd/bases/operations.compass_operations.yaml
  components/operations-controller/config/crd/kustomization.yaml
  components/operations-controller/config/crd/kustomizeconfig.yaml
  components/operations-controller/config/crd/patches/cainjection_in_operations.yaml
  components/operations-controller/config/crd/patches/webhook_in_operations.yaml
  components/operations-controller/config/default/kustomization.yaml
  components/operations-controller/config/default/manager_auth_proxy_patch.yaml
  components/operations-controller/config/default/manager_webhook_patch.yaml
  components/operations-controller/config/default/webhookcainjection_patch.yaml
  components/operations-controller/config/manager/kustomization.yaml
  components/operations-controller/config/manager/manager.yaml
  components/operations-controller/config/prometheus/kustomization.yaml
  components/operations-controller/config/prometheus/monitor.yaml
  components/operations-controller/config/rbac/auth_proxy_client_clusterrole.yaml
  components/operations-controller/config/rbac/auth_proxy_role.yaml
  components/operations-controller/config/rbac/auth_proxy_role_binding.yaml
  components/operations-controller/config/rbac/auth_proxy_service.yaml
  components/operations-controller/config/rbac/kustomization.yaml
  components/operations-controller/config/rbac/leader_election_role.yaml
  components/operations-controller/config/rbac/leader_election_role_binding.yaml
  components/operations-controller/config/rbac/operation_editor_role.yaml
  components/operations-controller/config/rbac/operation_viewer_role.yaml
  components/operations-controller/config/rbac/role.yaml
  components/operations-controller/config/rbac/role_binding.yaml
  components/operations-controller/config/samples/operations_v1alpha1_operation.yaml
  components/operations-controller/config/webhook/kustomization.yaml
  components/operations-controller/config/webhook/kustomizeconfig.yaml
  components/operations-controller/config/webhook/service.yaml
  components/operations-controller/controllers/operation_controller.go
  components/operations-controller/controllers/suite_test.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/operations-controller/hack/boilerplate.go.txt
  components/operations-controller/main.go
  tests/operations-controller/Dockerfile
  tests/operations-controller/Makefile
  tests/operations-controller/go.mod
  tests/operations-controller/go.sum
  tests/operations-controller/tests/main_test.go
Labels: :wave: request review

#1728 Remove Healthchecker component
  CODEOWNERS
  chart/compass/README.md
  chart/compass/charts/healthchecker/.helmignore
  chart/compass/charts/healthchecker/Chart.yaml
  chart/compass/charts/healthchecker/templates/deployment.yaml
  chart/compass/charts/healthchecker/templates/service.yaml
  chart/compass/charts/healthchecker/values.yaml
  chart/compass/values.yaml
  components/healthchecker/.gitignore
  components/healthchecker/Dockerfile
  components/healthchecker/Gopkg.lock
  components/healthchecker/Gopkg.toml
  components/healthchecker/Makefile
  components/healthchecker/README.md
  components/healthchecker/cmd/main.go
Labels: :wave: request review

#1729 Add APP_URL to README.md
  components/director/README.md
Labels: :wave: request review

#1732 Use bundles without query param
  chart/compass/values.yaml
  components/connectivity-adapter/cmd/main.go
  components/director/internal/packagetobundles/handler.go
  components/system-broker/cmd/main.go
  components/system-broker/go.sum
  tests/director/api/application_api_test.go
  tests/director/pkg/gql/gqlclient.go
Labels: :wave: request review

#1735 Drop redundant logic for fallback header
  chart/compass/values.yaml
  components/director/internal/tenantmapping/authenticator_context_provider.go
  components/director/internal/tenantmapping/authenticator_context_provider_test.go
Labels: :heavy_check_mark: Approved

#1738 Unify System Broker and ORD specification APIs
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-mtls.yaml
  chart/compass/charts/system-broker/templates/deployment.yaml
  chart/compass/charts/system-broker/templates/tests/system-broker-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/spec/converter.go
  components/director/internal/domain/spec/fixtures_test.go
  components/director/pkg/graphql/api.go
  components/director/pkg/graphql/event_api.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/fields_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/system-broker/README.md
  components/system-broker/cmd/main.go
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/system-broker/internal/config/config.go
  components/system-broker/internal/osb/broker.go
  components/system-broker/internal/osb/catalog_converter.go
  components/system-broker/internal/osb/catalog_converter_test.go
  components/system-broker/internal/specs/api.go
  components/system-broker/pkg/ord/config.go
  components/system-broker/pkg/ord/config_test.go
  components/system-broker/tests/catalog_test/catalog_test.go
  components/system-broker/tests/common/test_context.go
  tests/director/api/application_api_test.go
  tests/director/api/assertions.go
  tests/director/api/fixtures.go
  tests/director/gateway-integration/automatic_status_update_test.go
  tests/director/gateway-integration/compass_auth_test.go
  tests/director/gateway-integration/fixtures_queries.go
  tests/director/gateway-integration/integration_system_scope_test.go
  tests/director/gateway-integration/playground_test.go
  tests/director/gateway-integration/tenants_test.go
  tests/director/gateway-integration/viewer_test.go
  tests/director/go.mod
  tests/director/go.sum
  tests/system-broker/go.mod
  tests/system-broker/go.sum
  tests/system-broker/pkg/config.go
  tests/system-broker/pkg/testctx.go
  tests/system-broker/tests/auth_test.go
  tests/system-broker/tests/main_test.go
Labels: :wave: request review

#1740 Bump ord version
  chart/compass/values.yaml
Labels: do not merge
