Repository kyma-incubator/compass, pull requests merged in 2021-10, with the labels that each got.

#2048 Fix for system certificates
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
Labels: :wave: request review, size/S, lgtm

#2049 Fix for system certificates
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
Labels: :wave: request review, size/S, lgtm

#2052 Handle same customer and account external tenants ID
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: size/M, lgtm

#2053 Hotfix v1.17.4 2052
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: size/M, lgtm

#2054 Fix metrics hash field
  chart/compass/values.yaml
  components/director/internal/metrics/collector.go
Labels: size/XS, lgtm

#2066 Fix director benchmark test chart
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/values.yaml
  tests/director/bench/main_test.go
  tests/pkg/config/director.go
  tests/pkg/tenant/tenant_setup.go
Labels: bug, :wave: request review, size/M, lgtm

#2070 Use authenticator name from resource name
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-authenticator-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-authenticators.yaml
  chart/compass/values.yaml
  installation/resources/installer-config-local.yaml.tpl
Labels: :wave: request review, size/S, lgtm

#2079 Make subscription test skippable in E2E tests
  chart/compass/values.yaml
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, size/L, lgtm

#2081 Hotfix 1.18.2
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-authenticator-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-authenticators.yaml
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20211014114000_update_views.down.sql
  components/schema-migrator/migrations/director/20211014114000_update_views.up.sql
  installation/resources/installer-config-local.yaml.tpl
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: :hammer: hotfix, size/XL
