Repository kyma-incubator/compass, pull requests merged in 2021-07, with the labels that each got.

#1923 Enable periodic full resync on tenant-fetcher jobs
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher/main.go
  components/director/internal/tenantfetcher/automock/kube_client.go
  components/director/internal/tenantfetcher/kubernetes.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
Labels: :wave: request review, lgtm, size/L

#1888 Tenant fetcher deployment customer tenant storage and tenant table remodelling
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/pkg/tenant/entity.go
  components/schema-migrator/migrations/director/20210628113500_adopt_new_customer_tenant.down.sql
  components/schema-migrator/migrations/director/20210628113500_adopt_new_customer_tenant.up.sql
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  components/tenant-fetcher/internal/model/model.go
  components/tenant-fetcher/internal/model/tenant.go
  components/tenant-fetcher/internal/tenant/automock/converter.go
  components/tenant-fetcher/internal/tenant/automock/tenant_repository.go
  components/tenant-fetcher/internal/tenant/converter.go
  components/tenant-fetcher/internal/tenant/fixtures_test.go
  components/tenant-fetcher/internal/tenant/handler.go
  components/tenant-fetcher/internal/tenant/repository.go
  components/tenant-fetcher/internal/tenant/repository_test.go
  components/tenant-fetcher/internal/tenant/service.go
  components/tenant-fetcher/internal/tenant/service_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, lgtm, size/XXL

#1911 Use suggested token when pairing applications
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/virtualservice-authenticators.yaml
  chart/compass/charts/gateway/templates/virtualservice-secure.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/onetimetoken/automock/application_service.go
  components/director/internal/domain/onetimetoken/config.go
  components/director/internal/domain/onetimetoken/converter.go
  components/director/internal/domain/onetimetoken/resolver.go
  components/director/internal/domain/onetimetoken/resolver_test.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/onetimetoken/service_test.go
  components/director/internal/domain/onetimetoken/token.go
  components/director/internal/domain/root_resolver.go
  tests/connector/tests/apitests_test.go
  tests/pkg/fixtures/application_queries.go
Labels: :wave: request review, lgtm, size/XL

#1928 Fix helm formatting
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: lgtm, size/S

#1925 Better errors on webhook validation
  chart/compass/values.yaml
  components/director/internal/authnmappinghandler/handler.go
  components/director/pkg/graphql/webhook_validation.go
  components/system-broker/pkg/http/error_transport.go
Labels: :wave: request review, lgtm, size/M

#1932 Bump Console version
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1930 Enhance aggregator e2e test
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: lgtm, size/S

#1934 Fix local director run
  chart/compass/values.yaml
  components/director/run.sh
  components/schema-migrator/seeds/director/add_tenants.sql
Labels: :wave: request review, lgtm, size/S

#1898 Validation rule for resource def
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/eventdef/service.go
  components/director/internal/domain/eventdef/service_test.go
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/package/entity.go
  components/director/internal/domain/package/fixtures_test.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/package/service.go
  components/director/internal/domain/package/service_test.go
  components/director/internal/model/api.go
  components/director/internal/model/api_test.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/eventapi_test.go
  components/director/internal/model/package.go
  components/director/internal/model/package_test.go
  components/director/internal/open_resource_discovery/automock/api_service.go
  components/director/internal/open_resource_discovery/automock/event_service.go
  components/director/internal/open_resource_discovery/automock/package_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/schema-migrator/migrations/director/20210628173500_add_hash_field.down.sql
  components/schema-migrator/migrations/director/20210628173500_add_hash_field.up.sql
Labels: :wave: request review, lgtm, size/XXL

#1926 Expose healthz API
  chart/compass/charts/director/templates/virtual-service.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/values.yaml
  components/director/internal/healthz/indicator.go
  components/director/internal/healthz/indicator_test.go
  installation/cmd/run.sh
  tests/director/tests/health_test.go
  tests/go.mod
  tests/pkg/config/director.go
Labels: :wave: request review, lgtm, size/L

#1927 Refetch failed specs in ORD Aggregator
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/open_resource_discovery/automock/spec_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/apispec/handler.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/tenant-fetcher/go.sum
  tests/ord-aggregator/tests/handler_test.go
Labels: :wave: request review, lgtm, size/XXL

#1935 Fix tenant type in tenant-fetcher job
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/event_page.go
  components/director/internal/tenantfetcher/event_page_test.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/service_test.go
Labels: :wave: request review, bug, lgtm, size/S

#1938 Fix aggregator tests timeout
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: lgtm, size/XS

#1937 Use newer envoy filter config
  chart/compass/templates/filters/disable-istio-retries-filter.yaml
Labels: :wave: request review, lgtm, size/XS

#1940 Tenant fetcher server no-op delete
  chart/compass/values.yaml
  components/tenant-fetcher/internal/tenant/automock/tenant_repository.go
  components/tenant-fetcher/internal/tenant/repository.go
  components/tenant-fetcher/internal/tenant/repository_test.go
  components/tenant-fetcher/internal/tenant/service.go
  components/tenant-fetcher/internal/tenant/service_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, lgtm, size/L

#1941 Tenant fetcher server no-op delete (#1940)
  chart/compass/values.yaml
  components/tenant-fetcher/internal/tenant/automock/tenant_repository.go
  components/tenant-fetcher/internal/tenant/repository.go
  components/tenant-fetcher/internal/tenant/repository_test.go
  components/tenant-fetcher/internal/tenant/service.go
  components/tenant-fetcher/internal/tenant/service_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: lgtm, size/L

#1942 Remove crabtree from CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/M

#1945 Upgrade kyma to version 1.20.0
  installation/resources/KYMA_VERSION
Labels: :wave: request review, lgtm, size/XS

#1929 [CMP-688] Store CRM ID in tenant fetcher job
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher/README.md
  components/director/go.sum
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetcher/README.md
  components/director/internal/tenantfetcher/event_page.go
  components/director/internal/tenantfetcher/event_page_test.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/pkg/str/strings.go
  components/director/pkg/tenant/entity.go
  components/schema-migrator/Makefile
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  components/tenant-fetcher/internal/tenant/converter.go
  components/tenant-fetcher/internal/tenant/fixtures_test.go
Labels: :wave: request review, lgtm, size/L

#1933 Add temporary managed label
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, lgtm, size/M

#1943 Bump ord-service version
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1944 Allow longer runtime names
  chart/compass/values.yaml
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  tests/director/tests/validation_test.go
Labels: :wave: request review, lgtm, size/S

#1949 Add managed label migration
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20210713103000_add_managed_label.down.sql
  components/schema-migrator/migrations/director/20210713103000_add_managed_label.up.sql
Labels: :wave: request review, lgtm, size/S

#1951 Adopt new ORD regexes
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
Labels: :wave: request review, lgtm, size/XS

#1947 Remove inactive contributor from owners and codeowners
  CODEOWNERS
  chart/compass/OWNERS
Labels: lgtm, size/M

#1952 Fix CRM filtering when graphQL variables are used
  chart/compass/values.yaml
  components/director/internal/ownertenant/middleware.go
  components/director/internal/ownertenant/middleware_test.go
Labels: :wave: request review, bug, lgtm, size/L

#1953 Fix CRM filtering when graphQL variables are used (#1952)
  chart/compass/values.yaml
  components/director/internal/ownertenant/middleware.go
  components/director/internal/ownertenant/middleware_test.go
Labels: size/L

#1939 Use kibana formatter
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
  chart/compass/charts/system-broker/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/cmd/main.go
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.sum
  components/director/pkg/log/configure.go
  components/director/pkg/log/formatter.go
  components/director/pkg/log/formatter_test.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/cmd/main.go
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/pairing-adapter/internal/adapter/client.go
  components/pairing-adapter/internal/adapter/client_test.go
  components/pairing-adapter/internal/adapter/handler.go
  components/pairing-adapter/internal/adapter/model.go
  components/system-broker/cmd/main.go
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  tests/go.mod
  tests/go.sum
Labels: lgtm, size/L

#1955 Fix logging setting
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: lgtm, size/XS

#1957 Configure logging in tenant-fetcher job
  chart/compass/templates/tenant-fetcher-job.yaml
Labels: lgtm, size/XS

#1958 Replace label repo deleteOne with deleteMany
  chart/compass/values.yaml
  components/director/internal/domain/label/repository.go
Labels: lgtm, size/XS

#1960 Delete eventing label
  chart/compass/values.yaml
  components/director/internal/domain/eventing/service.go
  components/director/internal/domain/eventing/service_test.go
Labels: lgtm, size/L

#1956 Bump go builder image version
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/system-broker/Dockerfile
  components/tenant-fetcher/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, lgtm, size/M

#1959 bump kyma version to 1.21.2
  installation/resources/KYMA_VERSION
Labels: :wave: request review, lgtm, size/XS

#1963 Configure logging in operation controller
  chart/compass/values.yaml
  components/operations-controller/cmd/main.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
Labels: lgtm, size/M

#1905 Fetch known systems from Systems service
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/system-fetcher/role-binding.yaml
  chart/compass/templates/tests/system-fetcher/service-account.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/Dockerfile
  components/director/cmd/systemfetcher/README.md
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/eventing/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/application.go
  components/director/internal/systemfetcher/auth.go
  components/director/internal/systemfetcher/automock/systems_api_client.go
  components/director/internal/systemfetcher/automock/systems_service.go
  components/director/internal/systemfetcher/automock/tenant_service.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/auditlog/oauth/handler.go
  components/external-services-mock/internal/systemfetcher/handler.go
  components/schema-migrator/migrations/director/20210716403210_system_number.down.sql
  components/schema-migrator/migrations/director/20210716403210_system_number.up.sql
  installation/resources/installer-config-local.yaml.tpl
  tests/Dockerfile
  tests/go.mod
  tests/go.sum
  tests/system-fetcher/Makefile
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
Labels: lgtm, size/XXL

#1965 Fix tenant fetcher full resync
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
Labels: :wave: request review, lgtm, size/M

#1968 Add logging env property to jobs
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
Labels: lgtm, size/XS

#1969 Use the correct unix timestamp format in requests
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
Labels: :heavy_check_mark: Approved, lgtm, size/S
