Repository kyma-incubator/compass, pull requests merged in 2021-09, with the labels that each got.

#1996 Upgrade go to version 1.17
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connectivity-adapter/Makefile
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Dockerfile
  components/connector/Makefile
  components/connector/go.mod
  components/connector/go.sum
  components/connector/hack/gqlgen.go
  components/director/Dockerfile
  components/director/Makefile
  components/director/go.mod
  components/director/go.sum
  components/director/hack/gqlgen_internal.go
  components/director/tools/tools.go
  components/external-services-mock/Dockerfile
  components/external-services-mock/Makefile
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/Dockerfile
  components/gateway/Makefile
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/Dockerfile
  components/operations-controller/Makefile
  components/operations-controller/api/v1alpha1/zz_generated.deepcopy.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/Dockerfile
  components/pairing-adapter/Makefile
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/Makefile
  components/system-broker/Dockerfile
  components/system-broker/Makefile
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/system-broker/tools/tools.go
  tests/Dockerfile
  tests/Makefile
  tests/connectivity-adapter/Makefile
  tests/connector/Makefile
  tests/director/Makefile
  tests/director/tests/oauth20_test.go
  tests/director/tests/token_api_test.go
  tests/external-services-mock/Makefile
  tests/gateway/Makefile
  tests/go.mod
  tests/go.sum
  tests/istio/Makefile
  tests/ord-aggregator/Makefile
  tests/ord-service/Makefile
  tests/system-broker/Makefile
  tests/system-fetcher/Makefile
  tests/tenant-fetcher/Makefile
Labels: size/XXL, lgtm

#1999 Handle absolute config url in ORD Aggregator
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/external-services-mock/cmd/main.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
Labels: :wave: request review, size/L, lgtm

#2003 Security tools regular monitoring
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, size/M, lgtm

#2006 Fix pull licenses local
  scripts/generic_make_go.mk
Labels: :wave: request review, size/XS, lgtm

#2005 Infer API Protocol for non-ORD compliant systems
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20210902160202_infer_api_protocol.down.sql
  components/schema-migrator/migrations/director/20210902160202_infer_api_protocol.up.sql
  tests/ord-service/tests/api_test.go
Labels: :wave: request review, size/M, lgtm

#2004 Expose additional System Instance metadata
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20210902175141_extend_system_instaces.down.sql
  components/schema-migrator/migrations/director/20210902175141_extend_system_instaces.up.sql
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
  tests/director/tests/application_templates_api_test.go
  tests/ord-service/tests/api_test.go
Labels: :wave: request review, size/L, lgtm

#1995 Rename master branch to main
  .github/pull-request-template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  chart/compass/README.md
  components/connectivity-adapter/README.md
  components/connectivity-adapter/internal/appregistry/service/validation/servicedetailsvalidation.go
  components/connectivity-adapter/internal/appregistry/service/validation/servicedetailsvalidation_test.go
  components/connectivity-adapter/pkg/apperrors/apperrors.go
  components/connectivity-adapter/pkg/res/error.go
  components/director/cmd/tenantfetcher-job/README.md
  docs/README.md
  docs/compass/02-01-components.md
  docs/compass/03-01-security.md
  docs/compass/03-02-labels.md
  docs/compass/03-tenant-loading.md
  docs/compass/04-01-installation.md
  docs/director/03-01-hide-applications-from-runtimes.md
  docs/director/03-tenancy.md
  docs/internal/proposals/separate-compass/separate-compass.md
  docs/terminology.md
  installation/resources/readme.md
  installation/scripts/generate-compass-installer-artifacts.sh
  installation/scripts/install-kyma.sh
  scripts/README.md
  tests/gateway/tests/README.md
Labels: :wave: request review, size/L, lgtm

#2011 Rename master to main in compass installer makefile
  tools/compass-installer/Makefile
Labels: size/XS, lgtm

#2012 Bump compass console version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm

#2010 Allow extensive ord querying
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/bundlereferences/automock/uid_service.go
  components/director/internal/domain/bundlereferences/converter.go
  components/director/internal/domain/bundlereferences/entity.go
  components/director/internal/domain/bundlereferences/fixtures_test.go
  components/director/internal/domain/bundlereferences/repository.go
  components/director/internal/domain/bundlereferences/service.go
  components/director/internal/domain/bundlereferences/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/bundle_references.go
  components/director/internal/model/bundle_references_test.go
  components/schema-migrator/migrations/director/20210907181222_ord_extensive_querying.down.sql
  components/schema-migrator/migrations/director/20210907181222_ord_extensive_querying.up.sql
  tests/ord-service/tests/api_test.go
  tests/pkg/fixtures/bundle_requests.go
Labels: size/L, lgtm

#1998 Introduce regional subaccount tenants
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/values.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-job/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/domain/tenant/tenant.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/automock/tenant_provisioner.go
  components/director/internal/tenantfetchersvc/automock/tenant_service.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/director/pkg/tenant/entity.go
  components/schema-migrator/migrations/director/20210910112500_subaccount_tenants.down.sql
  components/schema-migrator/migrations/director/20210910112500_subaccount_tenants.up.sql
  scripts/generic_make_go.mk
  tests/go.mod
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, lgtm

#2014 Update internal-communication-policies.yaml
  chart/compass/templates/internal-communication-policies.yaml
Labels: bug, size/XS, lgtm

#2007 Whitelist ott for graphql schema
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/api/automock/token_service.go
  components/director/internal/api/token_resolver.go
  components/director/internal/domain/application/automock/one_time_token_service.go
  components/director/internal/domain/application/automock/system_auth_service.go
  components/director/internal/domain/application/automock/time_service.go
  components/director/internal/domain/application/automock/token_converter.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/onetimetoken/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/systemauth/service.go
  components/director/internal/oathkeeper/automock/one_time_token_service.go
  components/director/internal/oathkeeper/automock/system_auth_service.go
  components/director/internal/oathkeeper/validation_hydrator.go
  components/director/internal/oathkeeper/validation_hydrator_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/one_time_token.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/connector/tests/hydrator_api_test.go
Labels: :wave: request review, size/XL, lgtm

#2015 Fix authenticator rule path
  chart/compass/charts/gateway/templates/oathkeeper-authenticator-rules.yaml
  chart/compass/values.yaml
Labels: bug, :wave: request review, size/XS, lgtm

#1993 Add request monitoring per client identificator for all authentication flows
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/service-monitor.yaml
  chart/compass/templates/general-dashboard-configmap.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/onetimetoken/service_test.go
  components/director/internal/domain/onetimetoken/token.go
  components/director/internal/domain/systemauth/service_test.go
  components/director/internal/metrics/collector.go
  components/director/internal/oathkeeper/validation_hydrator_test.go
  components/director/internal/tenantmapping/automock/client_instrumenter.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
Labels: :wave: request review, size/L, lgtm

#2017 [hotfix]Fix authenticator rule path
  chart/compass/charts/gateway/templates/oathkeeper-authenticator-rules.yaml
  chart/compass/templates/internal-communication-policies.yaml
  chart/compass/values.yaml
Labels: :hammer: hotfix, size/XS, lgtm

#2018 Allow access to ORD docs endpoint
  chart/compass/templates/internal-communication-policies.yaml
Labels: :wave: request review, size/XS, lgtm

#2019 Support account creation with matching child ID
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: bug, :wave: request review, size/L, lgtm

#2020 [hotfix]Fix account creation
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :hammer: hotfix, size/L, lgtm

#2021 Increase director TestDefinition memory
  chart/compass/templates/tests/director/director-test.yaml
Labels: :wave: request review, size/XS, lgtm

#2013 Tenant Fetcher job improvements
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
Labels: :wave: request review, size/L, lgtm

#2022 Add benchmark test for ord-service
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/values.yaml
  tests/Dockerfile
  tests/ord-service/bench/main_test.go
  tests/ord-service/bench/system_bundles_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/clients/int_system_client.go
Labels: size/L, lgtm

#2023 Subscription flow labelling
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/label/query.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/tenantfetchersvc/automock/runtime_service.go
  components/director/internal/tenantfetchersvc/automock/tenant_provisioner.go
  components/director/internal/tenantfetchersvc/automock/tenant_subscriber.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/director/internal/tenantfetchersvc/subscriber.go
  components/director/internal/tenantfetchersvc/subscriber_test.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, lgtm

#2026 Add Upsert logic for Tenants
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/repo/unsafe_create.go
  components/director/internal/repo/unsafe_create_test.go
  components/director/internal/tenantfetcher/automock/tenant_service.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/tenant.go
  components/director/run.sh
Labels: :wave: request review, size/XL, lgtm

#2028 Improve application cleanup in benchmark tests
  chart/compass/values.yaml
  tests/director/bench/application_api_test.go
  tests/ord-service/bench/system_bundles_test.go
Labels: size/S, lgtm

#2029 Obfuscate personal data in Prometheus
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/metrics/collector.go
Labels: size/S, lgtm

#2027 Increase dependencies
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/internal/appregistry/service/converter.go
  components/connectivity-adapter/internal/appregistry/service/converter_test.go
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/bundlereferences/automock/uid_service.go
  components/director/internal/domain/oauth20/automock/ory_hydra_service.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/tenantfetchersvc/automock/runtime_service.go
  components/director/internal/tenantfetchersvc/automock/tenant_provisioner.go
  components/director/internal/tenantfetchersvc/automock/tenant_service.go
  components/director/internal/tenantfetchersvc/automock/tenant_subscriber.go
  components/director/internal/tenantmapping/automock/client_instrumenter.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/api_requests.go
  tests/pkg/fixtures/auth_requests.go
  tests/pkg/idtokenprovider/idtokenprovider.go
Labels: size/XXL, lgtm

#2024 Add documentation for Tenant Fetcher deployment
  components/director/README.md
  components/director/cmd/tenantfetcher-svc/README.md
Labels: :wave: request review, size/M, lgtm

#2033 Fix local installation with hyperkit failing
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
Labels: bug, :wave: request review, size/S, lgtm

#2036 Make CensoredFlows environment variable optional
  components/director/internal/metrics/collector.go
Labels: size/XS, lgtm

#2037 Bump Chart versions
  chart/compass/values.yaml
Labels: size/XS, lgtm

#2035 Bump console version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm

#2040 Handle NPE
  chart/compass/values.yaml
  components/director/internal/domain/systemauth/service.go
Labels: size/XS, lgtm

#2038 Handle NPE
  chart/compass/values.yaml
  components/director/internal/domain/systemauth/service.go
Labels: size/XS, lgtm

#2034 Retry AuditLog operation if fails
  chart/compass/values.yaml
  components/gateway/go.mod
  components/gateway/go.sum
  components/gateway/internal/auditlog/client.go
  components/gateway/internal/auditlog/client_test.go
Labels: size/M, lgtm

#2042 Adopt ORD changes after v1
  chart/compass/values.yaml
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/access_strategy.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
Labels: :wave: request review, size/L, lgtm

#2043 Adapt and extract ORD hardcoded regexes
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
Labels: :wave: request review, size/S, lgtm

#2046 Fix all system auths are assumed to be OneTimeTokens
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/systemauth/service.go
  components/director/pkg/graphql/one_time_token.go
  components/director/pkg/graphql/schema_gen.go
Labels: size/M, lgtm

#2045 Fix all system auths are assumed to be OneTimeTokens
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/systemauth/service.go
  components/director/pkg/graphql/one_time_token.go
  components/director/pkg/graphql/schema_gen.go
Labels: bug, :wave: request review, size/M, lgtm
