Repository kyma-incubator/compass, pull requests merged in 2021-04, with the labels that each got.

#1810 Bump compass-console version
  chart/compass/values.yaml
Labels: :wave: request review

#1783 Fix logging
  chart/compass/values.yaml
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/certificates/service.go
  components/connector/internal/revocation/loader.go
  components/connector/pkg/oathkeeper/validation_hydrator.go
  components/director/cmd/director/main.go
  components/director/internal/api/token_resolver.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/error_presenter/presenter.go
  components/director/internal/error_presenter/presenter_test.go
  components/director/internal/healthz/handler.go
  components/director/internal/oathkeeper/req_data_parser.go
  components/director/internal/oathkeeper/validation_hydrator.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/packagetobundles/handler.go
  components/director/internal/runtimemapping/token_verifier.go
  components/director/internal/statusupdate/handler.go
  components/director/internal/statusupdate/handler_test.go
  components/director/internal/tenantmapping/handler.go
  components/director/pkg/apperrors/http_errors.go
  components/director/pkg/authenticator/jwks_fetch.go
  components/director/pkg/httputils/response.go
  components/director/pkg/kubernetes/client.go
  components/director/pkg/operation/api.go
  components/director/pkg/operation/directive.go
  components/director/pkg/operation/update_operation_handler.go
  components/director/pkg/persistence/sql_error_mapper.go
  components/director/pkg/scenario/directive.go
  components/gateway/internal/auditlog/worker.go
  components/gateway/pkg/httpcommon/http.go
  components/gateway/pkg/proxy/transport.go
  components/system-broker/internal/osb/catalog.go
  components/system-broker/pkg/env/env.go
  components/tenant-fetcher/internal/authenticator/middleware.go
  components/tenant-fetcher/internal/tenant/handler.go
  components/tenant-fetcher/internal/tenant/service.go
Labels: :wave: request review

#1812 Add Aggregator README.md
  components/director/cmd/ordaggregator/README.md
Labels: :wave: request review

#1815 Docker build optimisations
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review

#1813 Wait for auditlogs to be available before testing
  chart/compass/values.yaml
  tests/external-services-mock/tests/auditlog_integration_test.go
Labels: :wave: request review

#1768 Strip sensitive data
  chart/compass/charts/director/config.yaml
  chart/compass/charts/director/static-groups.yaml
  chart/compass/charts/director/static-users.yaml
  chart/compass/charts/director/templates/configmap-configuration.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/values.yaml
  components/director/Dockerfile
  components/director/Makefile
  components/director/README.md
  components/director/cmd/director/main.go
  components/director/cmd/scopessynchronizer/main.go
  components/director/excluded.txt
  components/director/go.mod
  components/director/go.sum
  components/director/hack/config-local.yaml
  components/director/hack/plugins/descriptionsdecorator/plugin.go
  components/director/internal/domain/oauth20/automock/ory_hydra_service.go
  components/director/internal/domain/oauth20/config.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/domain/oauth20/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/systemauth/repository.go
  components/director/internal/scopes_sync/automock/o_auth_service.go
  components/director/internal/scopes_sync/automock/system_auth_repo.go
  components/director/internal/scopes_sync/service.go
  components/director/internal/scopes_sync/service_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/operation/middleware.go
  components/director/pkg/scope/directive.go
  components/director/pkg/scope/directive_test.go
  components/director/pkg/scope/error_provider.go
  components/director/pkg/str/strings.go
  components/director/run.sh
  components/operations-controller/internal/auth/unsigned_token_provider.go
  components/operations-controller/internal/auth/unsigned_token_provider_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/fetch_request_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/compass_auth_test.go
  tests/gateway/tests/integration_system_scope_test.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/application_template_queries.go
  tests/pkg/fixtures/application_template_requests.go
  tests/pkg/fixtures/integration_system_queries.go
  tests/pkg/fixtures/runtime_queries.go
  tests/pkg/token/token_utils.go
Labels: :wave: request review

#1816 Update values.yaml
  chart/compass/values.yaml
Labels: :heavy_check_mark: Approved

#1819 Fix scopes synchronizer job template
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
Labels: :wave: request review

#1811 Fix last operation handling
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/application/automock/application_hide_cfg_provider.go
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/integration_system_repository.go
  components/director/internal/domain/application/automock/label_repository.go
  components/director/internal/domain/application/automock/label_upsert_service.go
  components/director/internal/domain/application/automock/runtime_repository.go
  components/director/internal/domain/application/automock/scenarios_service.go
  components/director/internal/domain/application/automock/uid_service.go
  components/director/internal/domain/application/automock/webhook_repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/service.go
  components/director/internal/repo/update.go
  components/director/pkg/operation/operation.go
  tests/director/tests/application_api_test.go
  tests/director/tests/main_test.go
  tests/go.sum
  tests/pkg/fixtures/application_requests.go
  tests/pkg/gql/gqlclient.go
Labels: :wave: request review

#1814 Fix asynchronous system deletion failure
  chart/compass/values.yaml
  components/operations-controller/internal/webhook/client.go
  components/operations-controller/internal/webhook/client_test.go
Labels: :wave: request review

#1821 Extend current oauth-clients-scopes-sync job
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
  chart/compass/values.yaml
  components/director/internal/scopes_sync/service.go
  components/director/internal/scopes_sync/service_test.go
Labels: :construction: WIP :construction:

#1818 Deleting app with no labels no longer errors
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/error_presenter/presenter.go
  tests/director/tests/application_api_test.go
  tests/pkg/fixtures/runtime_requests.go
Labels: :wave: request review

#1820 Fix jwt signing keys
  chart/compass/values.yaml
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/authenticator/testdata/jwks-private3.json
  components/director/internal/authenticator/testdata/jwks-public3.json
  components/tenant-fetcher/internal/authenticator/middleware.go
  components/tenant-fetcher/internal/authenticator/middleware_test.go
Labels: :heavy_check_mark: Approved

#1823 Fix client update in scopes synchronizer
  chart/compass/values.yaml
  components/director/internal/domain/oauth20/service.go
  components/director/internal/scopes_sync/service.go
  components/director/internal/scopes_sync/service_test.go
Labels: :wave: request review, bug

#1824 Use correct sql condition when listing clients for update
  chart/compass/values.yaml
  components/director/internal/scopes_sync/service.go
  components/director/internal/scopes_sync/service_test.go
Labels: :wave: request review, bug

#1825 Pass grant type and client id in update body
  chart/compass/charts/director/config.yaml
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
  chart/compass/values.yaml
  components/director/internal/domain/oauth20/automock/client_details_config_provider.go
  components/director/internal/domain/oauth20/automock/scope_cfg_provider.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/domain/oauth20/service_test.go
  components/director/internal/scopes_sync/automock/o_auth_service.go
  components/director/internal/scopes_sync/service.go
  components/director/internal/scopes_sync/service_test.go
  components/director/pkg/config/scopes.go
  components/director/pkg/config/scopes_test.go
  components/director/pkg/config/testdata/valid.yaml
  tests/director/tests/sensitive_data_strip_test.go
  tests/pkg/token/token_utils.go
Labels: bug

#1829 Update console version
  chart/compass/values.yaml
Labels: :wave: request review, bug

#1827 Sanitize directive
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_hide_cfg_provider.go
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/integration_system_repository.go
  components/director/internal/domain/application/automock/label_repository.go
  components/director/internal/domain/application/automock/label_upsert_service.go
  components/director/internal/domain/application/automock/runtime_repository.go
  components/director/internal/domain/application/automock/scenarios_service.go
  components/director/internal/domain/application/automock/system_auth_converter.go
  components/director/internal/domain/application/automock/uid_service.go
  components/director/internal/domain/application/automock/webhook_repository.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/integrationsystem/automock/system_auth_converter.go
  components/director/internal/domain/integrationsystem/fixtures_test.go
  components/director/internal/domain/integrationsystem/resolver.go
  components/director/internal/domain/integrationsystem/resolver_test.go
  components/director/internal/domain/oauth20/automock/ory_hydra_service.go
  components/director/internal/domain/oauth20/automock/system_auth_converter.go
  components/director/internal/domain/oauth20/resolver.go
  components/director/internal/domain/oauth20/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/system_auth_converter.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/systemauth/automock/system_auth_converter.go
  components/director/internal/domain/systemauth/converter.go
  components/director/internal/domain/systemauth/converter_test.go
  components/director/internal/domain/systemauth/fixtures_test.go
  components/director/internal/domain/systemauth/resolver.go
  components/director/internal/domain/systemauth/resolver_test.go
  components/director/internal/scopes_sync/automock/o_auth_service.go
  components/director/internal/scopes_sync/automock/system_auth_repo.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/pkg/token/token_utils.go
Labels: :wave: request review

#1833 Introduce Autoscaling configuration
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/charts/connectivity-adapter/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/connectivity-adapter/values.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/connector/values.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/gateway/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/charts/ord-service/templates/deployment.yaml
  chart/compass/charts/ord-service/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/ord-service/values.yaml
  chart/compass/charts/system-broker/templates/deployment.yaml
  chart/compass/charts/system-broker/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/system-broker/values.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/tenant-fetcher/values.yaml
Labels: :wave: request review

#1830 Check if TestDefinition exists before patching it
  installation/cmd/run.sh
Labels: :wave: request review

#1834 Enable System Broker deployment resource configuration
  chart/compass/charts/system-broker/templates/deployment.yaml
Labels: :wave: request review

#1837 Verify ORD Service
  chart/compass/values.yaml
Labels: :wave: request review

#1838 Update values.yaml
  chart/compass/values.yaml
Labels: :wave: request review

#1828 Update deps
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Dockerfile
  components/connector/go.mod
  components/connector/go.sum
  components/director/Dockerfile
  components/director/go.mod
  components/director/go.sum
  components/director/pkg/graphql/application.go
  components/external-services-mock/Dockerfile
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/Dockerfile
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/Dockerfile
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/Dockerfile
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/tenant-fetcher/Dockerfile
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  tests/Dockerfile
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review

#1831 Handle Moved Runtime events
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/tenantfetcher/main.go
  components/director/go.mod
  components/director/internal/domain/labeldef/automock/repository.go
  components/director/internal/domain/labeldef/repository.go
  components/director/internal/domain/labeldef/repository_test.go
  components/director/internal/domain/labeldef/service.go
  components/director/internal/domain/labeldef/service_test.go
  components/director/internal/domain/oauth20/automock/client_details_config_provider.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetcher/automock/label_definition_service.go
  components/director/internal/tenantfetcher/automock/runtime_service.go
  components/director/internal/tenantfetcher/automock/tenant_service.go
  components/director/internal/tenantfetcher/client.go
  components/director/internal/tenantfetcher/client_test.go
  components/director/internal/tenantfetcher/event_page.go
  components/director/internal/tenantfetcher/event_page_test.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/model.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/schema-migrator/migrations/director/20210413140518_update-runtime-tenantId-update-cascade.down.sql
  components/schema-migrator/migrations/director/20210413140518_update-runtime-tenantId-update-cascade.up.sql
Labels: :wave: request review

#1832 Add runtime id to bundle instance auths
  chart/compass/values.yaml
  components/director/go.sum
  components/director/internal/domain/bundleinstanceauth/automock/repository.go
  components/director/internal/domain/bundleinstanceauth/automock/service.go
  components/director/internal/domain/bundleinstanceauth/automock/uid_service.go
  components/director/internal/domain/bundleinstanceauth/converter.go
  components/director/internal/domain/bundleinstanceauth/converter_test.go
  components/director/internal/domain/bundleinstanceauth/entity.go
  components/director/internal/domain/bundleinstanceauth/fixtures_test.go
  components/director/internal/domain/bundleinstanceauth/repository.go
  components/director/internal/domain/bundleinstanceauth/repository_test.go
  components/director/internal/domain/bundleinstanceauth/resolver_test.go
  components/director/internal/domain/bundleinstanceauth/service.go
  components/director/internal/domain/bundleinstanceauth/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/bundle_instance_auth_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/model/bundle_instance_auth.go
  components/director/internal/model/bundle_instance_auth_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/integration_system.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/runtime.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20210413143811_extend_bundle_instance_auth_entity.down.sql
  components/schema-migrator/migrations/director/20210413143811_extend_bundle_instance_auth_entity.up.sql
  tests/connector/tests/hydrator_api_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/oauth20_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/gateway/tests/tenants_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/integration_system_queries.go
  tests/pkg/fixtures/runtime_queries.go
Labels: :heavy_check_mark: Approved

#1839 Grafana dashboard for system broker
  chart/compass/charts/system-broker/templates/dashboard-configmap.yaml
  chart/compass/charts/system-broker/templates/deployment.yaml
  chart/compass/charts/system-broker/templates/policy.yaml
  chart/compass/charts/system-broker/templates/service-monitor.yaml
  chart/compass/values.yaml
  components/system-broker/cmd/main.go
  components/system-broker/go.sum
  components/system-broker/internal/config/config.go
  components/system-broker/internal/metrics/collector.go
  components/system-broker/internal/metrics/config.go
  components/system-broker/internal/metrics/path_to_instrumentation.go
  components/system-broker/internal/osb/api.go
  components/system-broker/pkg/server/server.go
  components/system-broker/pkg/server/server_test.go
  components/system-broker/tests/common/test_context.go
Labels: :wave: request review

#1842 Update compass console version
  chart/compass/values.yaml
Labels: lgtm

#1844 Skip tenant events that contain invalid data
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/event_page.go
  components/director/internal/tenantfetcher/event_page_test.go
  components/director/internal/tenantfetcher/service_test.go
Labels: lgtm, size/L

#1846 Verify Adopt jpa-processor 0.3.9
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS
