Repository kyma-incubator/compass, pull requests merged in 2021-08, with the labels that each got.

#1948 Down migrations
  chart/compass/templates/migrator-down-job.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/migrator-pvc.yaml
  chart/compass/values.yaml
  components/schema-migrator/Dockerfile
  components/schema-migrator/README.md
  components/schema-migrator/run.sh
  components/schema-migrator/validate.sh
Labels: :wave: request review, lgtm, size/L

#1973 Fix migrator job identation
  chart/compass/templates/migrator-down-job.yaml
Labels: lgtm, size/XS

#1977 Refactor system fetcher mapping
  chart/compass/values.yaml
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
Labels: :wave: request review, size/M, lgtm

#1976 Bump kyma version
  installation/resources/KYMA_VERSION
  installation/resources/kyma/installer-overrides-kyma-full-config-local.yaml
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
Labels: :wave: request review, size/XS, lgtm

#1975 Rework test resources cleanup
  chart/compass/values.yaml
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connectivity-adapter/tests/connector_test.go
  tests/connector/tests/apitests_test.go
  tests/connector/tests/hydrator_api_test.go
  tests/connector/tests/oathkeeper_security_test.go
  tests/director/bench/application_api_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/bundle_api_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/eventing_test.go
  tests/director/tests/fetch_request_test.go
  tests/director/tests/integration_system_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/oauth20_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/scopes_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/director/tests/token_api_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/external-services-mock/tests/fetch_request_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/compass_auth_test.go
  tests/gateway/tests/integration_system_scope_test.go
  tests/gateway/tests/tenants_test.go
  tests/gateway/tests/viewer_test.go
  tests/go.sum
  tests/istio/tests/request_payload_limit_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/clients/director_client.go
  tests/pkg/clients/secured_client.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/application_template_queries.go
  tests/pkg/fixtures/integration_system_queries.go
  tests/pkg/fixtures/runtime_queries.go
  tests/system-broker/tests/auth_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, lgtm

#1967 Enable formation filtering in ORD service
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/tenantmapping/system_auth_context_provider.go
  components/schema-migrator/migrations/director/20210730100823_add_tenant_mapping_views.down.sql
  components/schema-migrator/migrations/director/20210730100823_add_tenant_mapping_views.up.sql
  tests/director/tests/main_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
Labels: :wave: request review, size/L, lgtm

#1966 Readiness probes
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/ord-service/templates/deployment.yaml
  chart/compass/charts/ord-service/values.yaml
  chart/compass/templates/expected-schema-version-configmap.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/update-expected-schema-version-job.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/schema/repository.go
  components/director/internal/healthz/automock/repository.go
  components/director/internal/healthz/handler.go
  components/director/internal/healthz/handler_test.go
  components/director/internal/healthz/ready.go
  components/director/internal/healthz/ready_test.go
  components/director/pkg/resource/resource.go
  components/director/run.sh
  components/schema-migrator/Dockerfile
  components/schema-migrator/update-expected-schema-version.sh
Labels: :wave: request review, size/XL, lgtm

#1980 Remove regional config for migration persistence volume
  chart/compass/templates/migrator-pvc.yaml
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm

#1983 Fix ORD service test
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
Labels: bug, :wave: request review, size/M, lgtm

#1984 Fix ORD service test 2
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
Labels: bug, :wave: request review, size/XS, lgtm

#1981 Secure ORD Service with external certificate issuer
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/connector/values.yaml
  chart/compass/charts/gateway/templates/cmp-root-ca.yaml
  chart/compass/charts/gateway/templates/gateway.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-external-mtls.yaml
  chart/compass/templates/filters/preserve-external-host.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/ord-service/role-binding.yaml
  chart/compass/templates/tests/ord-service/service-account.yaml
  chart/compass/values.yaml
  components/connector/cmd/main.go
  components/connector/config/components.go
  components/connector/config/config.go
  components/connector/config/servers.go
  components/connector/go.mod
  components/connector/internal/certificates/model.go
  components/connector/pkg/oathkeeper/cert_header_parser.go
  components/connector/pkg/oathkeeper/cert_header_parser_test.go
  components/connector/pkg/oathkeeper/contract.go
  components/connector/pkg/oathkeeper/mocks/CertificateHeaderParser.go
  components/connector/pkg/oathkeeper/subject_extraction.go
  components/connector/pkg/oathkeeper/subject_extraction_test.go
  components/connector/pkg/oathkeeper/validation_hydrator.go
  components/connector/pkg/oathkeeper/validation_hydrator_test.go
  components/director/cmd/director/main.go
  components/director/internal/oathkeeper/model.go
  components/director/internal/tenantmapping/cert_service_context_provider.go
  components/director/internal/tenantmapping/cert_service_context_provider_test.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  installation/cmd/run.sh
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/pkg/clients/k8s_clientset.go
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, lgtm

#1987 fix gqlgen script
  components/director/go.sum
  components/director/hack/gqlgen_internal.go
Labels: size/XS, lgtm

#1986 Update label query filtering
  docs/compass/03-02-labels.md
Labels: size/M, lgtm

#1988 Use authenticator for tenant-fetcher deployment instead of manually authenticate requests
  chart/compass/charts/gateway/templates/oathkeeper-authenticator-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/internal/authnmappinghandler/handler.go
  components/director/internal/authnmappinghandler/handler_test.go
  components/director/internal/oathkeeper/model.go
  components/director/pkg/authenticator/types.go
  components/tenant-fetcher/Makefile
  components/tenant-fetcher/cmd/main.go
  components/tenant-fetcher/internal/authenticator/claims.go
  components/tenant-fetcher/internal/authenticator/middleware.go
  components/tenant-fetcher/internal/authenticator/middleware_test.go
  components/tenant-fetcher/internal/authenticator/testdata/invalid.json
  components/tenant-fetcher/internal/authenticator/testdata/jwks-private.json
  components/tenant-fetcher/internal/authenticator/testdata/jwks-private2.json
  components/tenant-fetcher/internal/authenticator/testdata/jwks-private3.json
  components/tenant-fetcher/internal/authenticator/testdata/jwks-public.json
  components/tenant-fetcher/internal/authenticator/testdata/jwks-public2.json
  components/tenant-fetcher/internal/authenticator/testdata/jwks-public3.json
  components/tenant-fetcher/internal/tenant/handler.go
  tests/pkg/authentication/token.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, size/XL, lgtm

#1989 Bump console and ord-service versions
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm

#1985 Add paging to system fetcher
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/pkg/paging/page_iterator.go
  components/director/pkg/paging/page_iterator_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.sum
  components/external-services-mock/internal/systemfetcher/handler.go
  tests/go.sum
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
Labels: enhancement, :wave: request review, size/XL, lgtm

#1979 Update dependencies
  chart/compass/values.yaml
  components/connectivity-adapter/Makefile
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Makefile
  components/connector/go.mod
  components/connector/go.sum
  components/director/Makefile
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/Makefile
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/Makefile
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/Makefile
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/Makefile
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/pairing-adapter/internal/adapter/client_test.go
  components/schema-migrator/Makefile
  components/system-broker/Makefile
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/tenant-fetcher/Makefile
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  tests/Makefile
  tests/connectivity-adapter/Makefile
  tests/connector/Makefile
  tests/director/Makefile
  tests/external-services-mock/Makefile
  tests/gateway/Makefile
  tests/go.mod
  tests/go.sum
  tests/istio/Makefile
  tests/operations-controller/Makefile
  tests/ord-aggregator/Makefile
  tests/ord-service/Makefile
  tests/system-broker/Makefile
  tests/system-fetcher/Makefile
  tests/tenant-fetcher/Makefile
Labels: :wave: request review, size/XL, lgtm

#1994 Bump spring boot
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm

#2000 Increase memory limits for connectivity-adapter and tenant-fetcher components
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
Labels: :heavy_check_mark: Approved, size/XS, lgtm

#1997 Conditionally skip tests by name
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/go.sum
  tests/ord-service/tests/api_test.go
  tests/pkg/certs/certs.go
  tests/pkg/request/make_request.go
  tests/pkg/testing/testing.go
Labels: :wave: request review, size/L, lgtm

#2001 Update dependencies
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/cmd/main.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/XXL, lgtm

#2002 Bump ORD Service Version
  chart/compass/values.yaml
Labels: size/XS, lgtm
