Repository kyma-incubator/compass, pull requests merged in 2021-05, with the labels that each got.

#1847 Verify PR-23 of ord-service
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1848 Bump console version
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1853 Clean unneded files
  chart/compass/values.yaml
  components/schema-migrator/Gopkg.lock
  components/schema-migrator/Gopkg.toml
  components/schema-migrator/Makefile
  components/schema-migrator/doc.go
Labels: :wave: request review, lgtm, size/S

#1849 Label filtering for apps and runtimes
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime_context/resolver_test.go
Labels: :wave: request review, approved, lgtm, size/L

#1851 Adjust livenessProbe settings
  chart/compass/charts/ord-service/templates/deployment.yaml
  chart/compass/charts/ord-service/values.yaml
Labels: :wave: request review, lgtm, size/S

#1850 NoOpService now implements PreLog
  chart/compass/values.yaml
  components/gateway/cmd/main.go
  components/gateway/internal/auditlog/service.go
  components/gateway/pkg/proxy/transport.go
Labels: :wave: request review, lgtm, size/S

#1855 Update codeowners
  CODEOWNERS
Labels: area/community, lgtm, size/M

#1858 Ord rc3 adaptation
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/ordvendor/converter.go
  components/director/internal/domain/ordvendor/entity.go
  components/director/internal/domain/ordvendor/fixtures_test.go
  components/director/internal/domain/ordvendor/repository.go
  components/director/internal/domain/ordvendor/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/vendor.go
  components/director/internal/model/vendor_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20210512130350_adapt_ord_rc3.down.sql
  components/schema-migrator/migrations/director/20210512130350_adapt_ord_rc3.up.sql
Labels: :wave: request review, lgtm, size/XXL

#1859 Prometheus alerts
  chart/compass/charts/operations-controller/templates/crds.yaml
  chart/compass/values.yaml
  components/operations-controller/api/v1alpha1/operation_types.go
  components/operations-controller/cmd/main.go
  components/operations-controller/config/crd/bases/operations.compass_operations.yaml
  components/operations-controller/controllers/controllersfakes/fake_director_client.go
  components/operations-controller/controllers/controllersfakes/fake_kubernetes_client.go
  components/operations-controller/controllers/controllersfakes/fake_status_manager.go
  components/operations-controller/controllers/controllersfakes/fake_webhook_client.go
  components/operations-controller/controllers/operation_controller.go
  components/operations-controller/controllers/operation_controller_integration_test.go
  components/operations-controller/controllers/operation_controller_test.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/operations-controller/internal/k8s/status/manager.go
  components/operations-controller/internal/metrics/collector.go
Labels: :wave: request review, lgtm, size/L

#1861 Additional test cases for ord rc3
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: lgtm, size/L

#1864 Add migration for delete cascade on api and event ready_fk
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20210525102013_add_api_and_event_ready_fk_delete_cascade.down.sql
  components/schema-migrator/migrations/director/20210525102013_add_api_and_event_ready_fk_delete_cascade.up.sql
  installation/cmd/run.sh
  installation/scripts/is-kyma-installed.sh
Labels: :wave: request review, lgtm, size/M

#1867 Hotfix migration for delete cascade on api and event ready_fk
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20210525102013_add_api_and_event_ready_fk_delete_cascade.down.sql
  components/schema-migrator/migrations/director/20210525102013_add_api_and_event_ready_fk_delete_cascade.up.sql
  installation/cmd/run.sh
  installation/scripts/is-kyma-installed.sh
Labels: lgtm, size/M

#1863 Add additional label to operations_near_reconciliation_timeout_count
  chart/compass/values.yaml
  components/operations-controller/controllers/operation_controller.go
  components/operations-controller/internal/metrics/collector.go
Labels: lgtm, size/S

#1870 Change alpine-kubectl image to k8s-tools
  chart/compass/templates/agent-configuration-job.yaml
  chart/compass/templates/registration-job.yaml
Labels: lgtm, size/XS

#1871 Improve unit test
  chart/compass/values.yaml
  components/director/internal/domain/api/service_test.go
Labels: lgtm, size/XS

#1856 Introduce Performance Tests
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/values.yaml
  installation/scripts/testing.sh
  tests/Dockerfile
  tests/director/bench/application_api_test.go
  tests/director/bench/main_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/fixtures/api_definition_requests.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/application_requests.go
  tests/pkg/fixtures/application_template_queries.go
  tests/pkg/fixtures/auth_requests.go
  tests/pkg/fixtures/bundle_requests.go
  tests/pkg/fixtures/bundles_queries.go
  tests/pkg/fixtures/fixtures.go
  tests/pkg/fixtures/integration_system_queries.go
  tests/pkg/fixtures/label_definitions_queries.go
  tests/pkg/fixtures/runtime_queries.go
  tests/pkg/fixtures/scenario_assignment_requests.go
  tests/pkg/fixtures/scenarios_queries.go
  tests/pkg/json/utils_json.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, lgtm, size/XL

#1860 Allow Director to use DB dump
  .gitignore
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/hack/jwt_generator.sh
  components/director/run.sh
  components/schema-migrator/Dockerfile
  components/schema-migrator/Makefile
  components/schema-migrator/dump_db.sh
  components/schema-migrator/run.sh
  components/schema-migrator/validate.sh
  installation/cmd/run.sh
  installation/scripts/prow/deploy-and-test.sh
  scripts/generic_make_go.mk
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/external-services-mock/tests/fetch_request_test.go
  tests/external-services-mock/tests/main_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/compass_auth_test.go
  tests/gateway/tests/integration_system_scope_test.go
  tests/gateway/tests/main_test.go
  tests/gateway/tests/playground_suite.go
  tests/gateway/tests/playground_test.go
  tests/gateway/tests/tenants_test.go
  tests/gateway/tests/viewer_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, lgtm, size/XL

#1873 Bump ord service
  chart/compass/values.yaml
Labels: lgtm, size/XS

#1874 Improve benchmark test
  chart/compass/values.yaml
  tests/director/bench/application_api_test.go
Labels: :wave: request review, lgtm, size/S

#1877 Execute benchmarks on a specific node
  chart/compass/templates/bench/director/director-bench.yaml
  installation/cmd/run.sh
Labels: :wave: request review, lgtm, size/XS

#1872 Increace hydrator retry interval
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/S

#1876 Bump ORD Service version
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1868 Update dependencies
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/authnmappinghandler/handler.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/pkg/graphql/api_validation.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/auth_validation.go
  components/director/pkg/graphql/bundle_validation.go
  components/director/pkg/graphql/document_validation.go
  components/director/pkg/graphql/event_api_validation.go
  components/director/pkg/graphql/fetchrequest_validation.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/integrationsys_validation.go
  components/director/pkg/graphql/labeldef_validation.go
  components/director/pkg/graphql/labels_validation.go
  components/director/pkg/graphql/runtime_context_validation.go
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/version_validation.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/inputvalidation/directive_test.go
  components/director/pkg/inputvalidation/helpers.go
  components/director/pkg/inputvalidation/validators_iterable.go
  components/director/pkg/inputvalidation/validators_iterable_test.go
  components/director/pkg/inputvalidation/validators_map.go
  components/director/pkg/inputvalidation/validators_map_test.go
  components/director/pkg/inputvalidation/validators_url.go
  components/director/pkg/inputvalidation/validators_url_test.go
  components/director/pkg/operation/operation.go
  components/director/pkg/operation/update_operation_handler.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/system-broker/pkg/director/client_test.go
  components/system-broker/pkg/log/lager_adapter.go
  components/system-broker/pkg/panic_recovery/recovery.go
  components/system-broker/tests/common/fake_router.go
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, lgtm, size/XL

#1879 Ensure Schema Migrator cleans up dump before release
  chart/compass/values.yaml
  components/director/run.sh
  components/schema-migrator/Makefile
  components/schema-migrator/run.sh
Labels: :wave: request review, lgtm, size/S
