Repository kyma-incubator/compass, pull requests merged in 2021-11, with the labels that each got.

#2095 Remove implicit label def creation
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/cmd/tenantfetcher-job/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/application/automock/scenarios_service.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/label/service.go
  components/director/internal/domain/label/service_test.go
  components/director/internal/domain/labeldef/automock/tenant_repository.go
  components/director/internal/domain/labeldef/service.go
  components/director/internal/domain/labeldef/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/scenarios_service.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/runtime_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, size/XXL, lgtm

#2086 Match cert and token pair in consumer-provider flow.
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/authenticator/automock/claims_validator.go
  components/director/internal/authenticator/claims/automock/runtime_service.go
  components/director/internal/authenticator/claims/claims.go
  components/director/internal/authenticator/claims/scopes_validator.go
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/authenticator/claims/validators_test.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/authnmappinghandler/handler_test.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  components/director/internal/oathkeeper/model.go
  components/director/internal/tenantmapping/authenticator_context_provider.go
  components/director/internal/tenantmapping/authenticator_context_provider_test.go
  components/director/internal/tenantmapping/cert_service_context_provider.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
  components/director/internal/tenantmapping/model.go
  components/director/internal/tenantmapping/system_auth_context_provider.go
  components/director/internal/tenantmapping/user_context_provider.go
  components/director/pkg/apperrors/consts.go
  components/director/pkg/apperrors/errors.go
  components/director/pkg/authenticator/types.go
Labels: :wave: request review, size/XL, lgtm

#2093 Adjust Usage of ORD baseURL
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/accessstrategy/access_strategy.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/cmd/main.go
  tests/ord-aggregator/tests/handler_test.go
Labels: :wave: request review, size/L, lgtm

#2097 Fix tenant fetcher not updating configmap if no events are present
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
Labels: size/XS, lgtm

#2098 Hotfix - 1.19.2
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/tenants_api_test.go
  tests/pkg/fixtures/label_definitions_queries.go
Labels: :wave: request review, size/S, lgtm

#2099 Hotfix -1.19.2 to master
  chart/compass/values.yaml
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/tenants_api_test.go
  tests/pkg/fixtures/label_definitions_queries.go
Labels: :wave: request review, size/S, lgtm

#2096 Runtime self-registration preaparation and cleanup
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/application/automock/scenarios_service.go
  components/director/internal/domain/document/resolver_test.go
  components/director/internal/domain/labeldef/automock/tenant_repository.go
  components/director/internal/domain/labeldef/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/external_svc_caller.go
  components/director/internal/domain/runtime/automock/self_register_manager.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/rtmtest/caller.go
  components/director/internal/domain/runtime/rtmtest/selfreg_manager.go
  components/director/internal/domain/runtime/selfreg_manager.go
  components/director/internal/domain/runtime/selfreg_manager_test.go
  components/director/internal/domain/runtime_context/resolver_test.go
  components/director/internal/healthz/ready_test.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/securehttp/caller.go
  components/director/internal/securehttp/caller_test.go
  components/director/internal/systemfetcher/service_test.go
  components/director/internal/tenantfetcher/automock/tenant_sync_service.go
  components/director/pkg/persistence/automock/transactioner.go
  components/director/pkg/persistence/persistence.go
  components/director/pkg/persistence/txtest/txtest.go
  components/director/pkg/str/strings.go
  components/director/run.sh
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/oauth/token_handler.go
  components/external-services-mock/internal/selfreg/handler.go
  tests/director/tests/self_reg_test.go
  tests/pkg/config/director.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, size/XXL, lgtm

#2100 update ord service version
  chart/compass/values.yaml
Labels: size/XS, lgtm

#2101 Align self register e2e tests
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/director/tests/self_reg_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/config/director.go
Labels: size/M, lgtm

#2108 Increase test timeouts
  chart/compass/values.yaml
  installation/scripts/testing.sh
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/clients/int_system_client.go
Labels: :wave: request review, size/S, lgtm

#2106 Externalize Operations controller resources
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/charts/operations-controller/values.yaml
Labels: :wave: request review, size/S, lgtm

#2109 Remove leftover test tenant
  chart/compass/values.yaml
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, size/S, lgtm

#2107 Allow softer OU validation for external cert header parser
  chart/compass/charts/connector/values.yaml
  chart/compass/values.yaml
  components/connector/config/servers.go
  components/connector/go.mod
  components/connector/go.sum
  components/connector/pkg/oathkeeper/subject_extraction.go
  components/director/pkg/cert/certutils.go
  components/director/pkg/cert/certutils_test.go
Labels: :wave: request review, size/L, lgtm, to be released :rocket:

#2105 Add CorrelationID to Bundles
  chart/compass/values.yaml
  components/director/internal/domain/bundle/converter.go
  components/director/internal/domain/bundle/entity.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/model/bundle.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20211111122118_bundles_correlation_id.down.sql
  components/schema-migrator/migrations/director/20211111122118_bundles_correlation_id.up.sql
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/assertions/assertions.go
Labels: :wave: request review, size/L, lgtm, to be released :rocket:

#2111 Update vulnerable dependencies
  chart/compass/values.yaml
  components/connector/go.mod
  components/connector/go.sum
  components/connector/internal/authentication/context_middleware.go
Labels: :wave: request review, size/L, lgtm

#2067 Upgrade Kyma version
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  installation/resources/KYMA_VERSION
  installation/resources/kyma/installer-overrides-kyma-full-config-local.yaml
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
Labels: :wave: request review, size/S, lgtm, to be released :rocket:

#2084 Fix operation processing for already deleted application
  chart/compass/values.yaml
  components/operations-controller/controllers/operation_controller.go
  components/operations-controller/controllers/operation_controller_test.go
  components/operations-controller/controllers/types.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/operations-controller/internal/k8s/status/manager.go
  components/system-broker/pkg/director/client.go
  components/system-broker/pkg/director/client_test.go
Labels: :wave: request review, size/L, lgtm, to be released :rocket:

#2114 Move gke overrides to compass
  installation/resources/installer-config-gke-integration.yaml.tpl
Labels: size/M, lgtm

#2102 Audit log operations in tenant-fetcher job
  chart/compass/charts/director/config.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/templates/tests/tenant-fetcher-job/role-binding.yaml
  chart/compass/templates/tests/tenant-fetcher-job/service-account.yaml
  chart/compass/templates/tests/tenant-fetcher-job/tenant-fetcher-job-test.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-job/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/hack/config-local.yaml
  components/director/internal/authenticator/claims/automock/runtime_service.go
  components/director/internal/domain/labeldef/converter.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_converter.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetcher/automock/director_graph_ql_client.go
  components/director/internal/tenantfetcher/automock/label_def_converter.go
  components/director/internal/tenantfetcher/automock/label_definition_service.go
  components/director/internal/tenantfetcher/automock/runtime_service.go
  components/director/internal/tenantfetcher/automock/tenant_converter.go
  components/director/internal/tenantfetcher/automock/tenant_service.go
  components/director/internal/tenantfetcher/automock/tenant_storage_service.go
  components/director/internal/tenantfetcher/event_page.go
  components/director/internal/tenantfetcher/event_page_test.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql_client/automock/graph_ql_client.go
  components/director/pkg/graphql_client/director_client.go
  components/director/pkg/graphql_client/director_client_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/tenantfetcher/handler.go
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  tests/Dockerfile
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/fixtures.go
  tests/pkg/fixtures/tenant_requests.go
  tests/pkg/k8s/jobs.go
  tests/system-fetcher/tests/handler_test.go
  tests/tenant-fetcher-job/Makefile
  tests/tenant-fetcher-job/tests/handler_test.go
  tests/tenant-fetcher-job/tests/main_test.go
Labels: :wave: request review, size/XXL, lgtm

#2112 Add external certificate rotation cronjob
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/charts/director/templates/rbac.yaml
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/open_resource_discovery/accessstrategy/access_strategy.go
  components/director/internal/open_resource_discovery/accessstrategy/automock/executor.go
  components/director/internal/open_resource_discovery/accessstrategy/cmp_mtls_access_strategy.go
  components/director/internal/open_resource_discovery/accessstrategy/executor_provider.go
  components/director/internal/open_resource_discovery/accessstrategy/open_access_strategy.go
  components/director/internal/open_resource_discovery/accessstrategy/open_access_strategy_test.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/pkg/cert/certsvc_client.go
  components/director/pkg/cert/certsvc_client_test.go
  components/director/pkg/certloader/automock/manager.go
  components/director/pkg/certloader/cache.go
  components/director/pkg/certloader/loader.go
  components/director/pkg/certloader/loader_test.go
  components/director/pkg/namespacedname/namespacedname.go
  components/director/pkg/namespacedname/namespacedname_test.go
  components/external-services-mock/internal/cert/handler.go
  components/external-services-mock/internal/cert/handler_test.go
  components/operations-controller/go.mod
  tests/go.sum
Labels: :heavy_check_mark: Approved, size/XXL, lgtm
