Repository kyma-incubator/compass, pull requests merged in 2021-06, with the labels that each got.

#1869 Ord rc4 adaptation
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/pkg/graphql/event_api.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20210528113600_adapt_ord_rc4.down.sql
  components/schema-migrator/migrations/director/20210528113600_adapt_ord_rc4.up.sql
Labels: lgtm, size/XXL

#1880 Upgrade Kyma to v1.19.2
  chart/compass/templates/rewrite-client-cert-filter.yaml
  chart/compass/templates/rewrite-correlation-headers-filter.yaml
  chart/compass/templates/rewrite-token-filter.yaml
  installation/resources/KYMA_VERSION
  installation/resources/kyma/installer-overrides-kyma-config-local.yaml
Labels: :wave: request review, lgtm, size/M

#1878 Adapt ORD v1
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20210528122934_adapt_ord_v1.down.sql
  components/schema-migrator/migrations/director/20210528122934_adapt_ord_v1.up.sql
  tests/ord-service/tests/api_test.go
Labels: :wave: request review, lgtm, size/L

#1882 Fix logging response writer
  chart/compass/values.yaml
  components/director/pkg/log/logging_response_writer.go
Labels: :wave: request review, lgtm, size/S

#1884 Adopt Fix logging response writer
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
Labels: :wave: request review, lgtm, size/L

#1887 Inconsistent operation controller namings cause deploy-on-minikube to fail
  chart/compass/charts/operations-controller/templates/deployment.yaml
Labels: lgtm

#1883 Fix DB Leaks
  chart/compass/values.yaml
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/document/repository_test.go
  components/director/internal/domain/integrationsystem/repository_test.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/scenarioassignment/repository_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/repo/create.go
  components/director/internal/repo/create_test.go
  components/director/internal/repo/delete.go
  components/director/internal/repo/delete_test.go
  components/director/internal/repo/exist.go
  components/director/internal/repo/exist_test.go
  components/director/internal/repo/get.go
  components/director/internal/repo/get_test.go
  components/director/internal/repo/list.go
  components/director/internal/repo/list_pageable.go
  components/director/internal/repo/list_pageable_test.go
  components/director/internal/repo/list_test.go
  components/director/internal/repo/update.go
  components/director/internal/repo/update_test.go
  components/director/internal/repo/upsert.go
  components/director/internal/repo/upsert_test.go
  components/director/internal/statusupdate/repo.go
  components/director/pkg/persistence/automock/persistence_op.go
  components/director/pkg/persistence/automock/persistence_tx.go
  components/director/pkg/persistence/persistence.go
  components/director/pkg/persistence/sql_error_mapper.go
  components/director/pkg/persistence/sql_error_mapper_test.go
Labels: :wave: request review, lgtm, size/L

#1890 Fix liveliness probe
  chart/compass/charts/director/templates/deployment.yaml
Labels: lgtm, size/XS

#1896 [v1.7] Fix Runtime Name Validation
  chart/compass/values.yaml
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  tests/director/tests/validation_test.go
Labels: :hammer: hotfix, :wave: request review, bug, lgtm, size/L

#1893 Remove runtime name restriction
  chart/compass/values.yaml
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  tests/director/tests/validation_test.go
Labels: :wave: request review, bug, lgtm, size/L

#1897 [v1.8] Fix Runtime Name Validation
  chart/compass/values.yaml
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
  tests/director/tests/validation_test.go
Labels: :hammer: hotfix, :wave: request review, bug, lgtm, size/L

#1894 Introduce automatic vendor assignment
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
Labels: lgtm, size/L

#1899 Bump console version
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1891 Make WebhookInput's outputTemplate field mandatory for certain webhook types
  chart/compass/values.yaml
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/graphql/webhook_validation_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/sensitive_data_strip_test.go
Labels: :wave: request review, lgtm, size/M

#1900 Use XDS v3 API in EnvoyFilters
  chart/compass/templates/oathkeeper-timeout-filter.yaml
  chart/compass/templates/rewrite-client-cert-filter.yaml
  chart/compass/templates/rewrite-correlation-headers-filter.yaml
  chart/compass/templates/rewrite-token-filter.yaml
Labels: :wave: request review, lgtm, size/XS

#1881 E2E tests execution on real environment
  chart/compass/charts/external-services-mock/templates/auditlog-configmap.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/templates/managed-postgresql-secret.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/connector/service.yaml
  chart/compass/templates/tests/connector/virtualservice.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/director/service.yaml
  chart/compass/templates/tests/director/virtualservice.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/external-services-mock/service.yaml
  chart/compass/templates/tests/external-services-mock/virtualservice.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/gateway/service.yaml
  chart/compass/templates/tests/gateway/virtualservice.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/istio/service.yaml
  chart/compass/templates/tests/istio/virtualservice.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-aggregator/service.yaml
  chart/compass/templates/tests/ord-aggregator/virtualservice.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/ord-service/service.yaml
  chart/compass/templates/tests/ord-service/virtualservice.yaml
  chart/compass/templates/tests/system-broker/service.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-broker/virtualservice.yaml
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  docs/compass/09-01-e2e-test-design.md
  installation/resources/installer-config-local.yaml.tpl
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connectivity-adapter/tests/connector_test.go
  tests/connector/tests/main_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/eventing_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
  tests/external-services-mock/tests/main_test.go
  tests/gateway/tests/main_test.go
  tests/istio/tests/request_payload_limit_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/certs/certs.go
  tests/pkg/clients/secured_client.go
  tests/pkg/clients/static_user_client.go
  tests/pkg/config/director.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/server/helpers.go
  tests/pkg/server/server.go
  tests/pkg/testctx/broker/system_broker_testctx.go
  tests/pkg/testctx/testctx.go
  tests/system-broker/tests/main_test.go
Labels: :wave: request review, lgtm, size/XXL

#1902 Adapt system instance validation
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: lgtm, size/L

#1903 Add release name in TestDefinitions
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
Labels: :wave: request review, lgtm, size/XS

#1889 Url template validation
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/director/pkg/graphql/webhook_validation_test.go
  components/director/pkg/webhook/types.go
Labels: :wave: request review, lgtm, size/L

#1904 Use minikube context for local installation
  installation/cmd/run.sh
  installation/scripts/install-kyma.sh
  installation/scripts/run-compass-installer.sh
  installation/scripts/utils.sh
Labels: :wave: request review, lgtm, size/S

#1907 Fix empty JWKS cache
  chart/compass/values.yaml
  components/director/internal/authenticator/middleware.go
  components/tenant-fetcher/internal/authenticator/middleware.go
Labels: :wave: request review, bug, lgtm, size/M

#1909 [CMP-710] Update dependencies
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1910 Update dependencies
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/tenant-fetcher/go.mod
  components/tenant-fetcher/go.sum
  components/tenant-fetcher/internal/tenant/repository.go
  tests/go.mod
  tests/go.sum
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, lgtm, size/XL

#1908 Introduce panic handler
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/pkg/panic_recovery/handler.go
  components/director/pkg/panic_recovery/handler_test.go
Labels: :wave: request review, lgtm, size/M

#1916 Update gce-proxy
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/charts/ord-service/templates/deployment.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
Labels: lgtm, size/S

#1918 Update compass-console version
  chart/compass/values.yaml
Labels: :wave: request review, lgtm, size/XS

#1920 Disable Istio retries
  chart/compass/templates/filters/disable-istio-retries-filter.yaml
  chart/compass/templates/filters/oathkeeper-timeout-filter.yaml
  chart/compass/templates/filters/rewrite-client-cert-filter.yaml
  chart/compass/templates/filters/rewrite-correlation-headers-filter.yaml
  chart/compass/templates/filters/rewrite-token-filter.yaml
Labels: lgtm, size/S

#1919 Fix db-dump on PR jobs
  chart/compass/values.yaml
  components/director/pkg/executor/executor.go
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/tenants_api_test.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, lgtm, size/M

#1921 Attach retry envoy filter on GW
  chart/compass/templates/filters/disable-istio-retries-filter.yaml
Labels: lgtm, size/XS

#1914 Async health checks
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/healthz/automock/indicator.go
  components/director/internal/healthz/automock/status.go
  components/director/internal/healthz/config.go
  components/director/internal/healthz/db_indicator.go
  components/director/internal/healthz/db_indicator_test.go
  components/director/internal/healthz/handler.go
  components/director/internal/healthz/handler_test.go
  components/director/internal/healthz/health.go
  components/director/internal/healthz/health_test.go
  components/director/internal/healthz/indicator.go
  components/director/internal/healthz/indicator_test.go
  components/director/run.sh
Labels: :wave: request review, lgtm, size/XL

#1922 Do not Update App/Runtime status on one time token requests
  chart/compass/values.yaml
  components/director/internal/authenticator/claims.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/consumer/consumer.go
  components/director/internal/statusupdate/handler.go
  components/director/internal/statusupdate/handler_test.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
Labels: :wave: request review, lgtm, size/M

#1924 Fix operations controller tests
  chart/compass/values.yaml
  components/operations-controller/controllers/assertions_test.go
  components/operations-controller/controllers/operation_controller_integration_test.go
Labels: :wave: request review, lgtm, size/S
