Repository kyma-incubator/compass, pull requests merged in 2021-12, with the labels that each got.

#2118 Enable mtls in operations controller and pairing-adapter
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/charts/operations-controller/templates/rbac.yaml
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
  chart/compass/charts/pairing-adapter/templates/rbac.yaml
  chart/compass/charts/pairing-adapter/values.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/pairing-adapter/service.yaml
  chart/compass/templates/tests/pairing-adapter/virtualservice.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/go.mod
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/pkg/accessstrategy/access_strategy.go
  components/director/pkg/accessstrategy/automock/executor.go
  components/director/pkg/accessstrategy/automock/executor_provider.go
  components/director/pkg/accessstrategy/cmp_mtls_access_strategy.go
  components/director/pkg/accessstrategy/executor_provider.go
  components/director/pkg/accessstrategy/fixtures_test.go
  components/director/pkg/accessstrategy/open_access_strategy.go
  components/director/pkg/accessstrategy/open_access_strategy_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/external-services-mock/cmd/main.go
  components/operations-controller/cmd/main.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/operations-controller/internal/config/config.go
  components/operations-controller/internal/utils/automock/certificate_cache.go
  components/operations-controller/internal/utils/clients.go
  components/operations-controller/internal/utils/clients_test.go
  components/operations-controller/internal/webhook/client.go
  components/operations-controller/internal/webhook/client_test.go
  components/pairing-adapter/cmd/main.go
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/pairing-adapter/internal/adapter/model.go
  tests/Dockerfile
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/external-services-mock/tests/main_test.go
  tests/go.mod
  tests/go.sum
  tests/pairing-adapter/Makefile
  tests/pairing-adapter/tests/main_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/config/pairing-adapter.go
  tests/pkg/webhook/webhook.go
Labels: :wave: request review, size/XXL, lgtm, to be released :rocket:

#2120 Secure graphql with external certificate for configured consumers
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/director/config.yaml
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/director/role-binding.yaml
  chart/compass/values.yaml
  components/connector/config/config.go
  components/connector/config/servers.go
  components/connector/go.mod
  components/connector/go.sum
  components/connector/internal/subject/subject.go
  components/connector/internal/subject/subject_test.go
  components/connector/pkg/oathkeeper/automock/certificate_header_parser.go
  components/connector/pkg/oathkeeper/cert_header_parser.go
  components/connector/pkg/oathkeeper/cert_header_parser_test.go
  components/connector/pkg/oathkeeper/mocks/CertificateHeaderParser.go
  components/connector/pkg/oathkeeper/validation_hydrator.go
  components/connector/pkg/oathkeeper/validation_hydrator_test.go
  components/director/cmd/director/main.go
  components/director/internal/domain/labeldef/automock/tenant_repository.go
  components/director/internal/domain/oauth20/service.go
  components/director/internal/domain/oauth20/service_test.go
  components/director/internal/oathkeeper/model.go
  components/director/internal/tenantmapping/automock/scopes_getter.go
  components/director/internal/tenantmapping/cert_service_context_provider.go
  components/director/internal/tenantmapping/cert_service_context_provider_test.go
  components/director/internal/tenantmapping/model.go
  components/director/internal/tenantmapping/system_auth_context_provider.go
  components/director/internal/tenantmapping/system_auth_context_provider_test.go
  components/director/pkg/cert/certutils.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/main_test.go
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/main_test.go
  tests/pkg/certs/certs.go
  tests/pkg/certs/config.go
  tests/pkg/config/director.go
  tests/pkg/tenant/tenant_setup.go
Labels: size/XXL, lgtm, to be released :rocket:

#2124 Lazily store missing subaccounts
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/formation/automock/tenant_service.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/runtime/automock/tenant_service.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/domain/scenarioassignment/automock/tenant_service.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  tests/director/tests/automatic_scenario_assignment_test.go
Labels: size/L, lgtm

#2125 Add missing intermediate certificate in cert loader cache
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/values.yaml
  components/connector/go.mod
  components/connector/go.sum
  components/connector/pkg/graphql/clientset/clientset.go
  components/director/pkg/cert/certutils.go
  components/director/pkg/certloader/loader.go
  tests/go.mod
  tests/go.sum
  tests/pkg/certs/certs.go
Labels: :heavy_check_mark: Approved, size/L, lgtm

#2117 Improve System Processing in System Fetcher
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/bundle/automock/spec_service.go
  components/director/internal/domain/labeldef/repository.go
  components/director/internal/domain/labeldef/repository_test.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/repo/tenant_access_m2m.go
  components/director/internal/repo/testdb/generic_repo_upsert_tests.go
  components/director/internal/repo/upsert.go
  components/director/internal/repo/upsert_test.go
  components/director/internal/systemfetcher/automock/systems_service.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/internal/tenantfetcher/automock/label_repo.go
  components/director/pkg/apperrors/consts.go
  components/schema-migrator/migrations/director/20211204173222_unique_system_number.down.sql
  components/schema-migrator/migrations/director/20211204173222_unique_system_number.up.sql
Labels: :wave: request review, size/XXL, lgtm

#2119 Adapt cert loader for local director installation
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/charts/director/templates/rbac.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/README.md
  components/director/cmd/director/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/pkg/certloader/cache.go
  components/director/pkg/certloader/config.go
  components/director/pkg/certloader/loader.go
  components/director/pkg/certloader/loader_test.go
  components/director/run.sh
Labels: :heavy_check_mark: Approved, size/L, lgtm

#2129 Fix storage-redesign migration
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20211122114401_storage-redesign.up.sql
Labels: bug, :wave: request review, size/S, lgtm

#2131 [HOTFIX] Fix storage-redesign migration
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20211122114401_storage-redesign.up.sql
Labels: bug, :wave: request review, size/S, lgtm

#2126 Deps update
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/operations-controller/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, size/M, lgtm

#2128 Introduce ORD defaultBundle for APIs/Events
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/resolver.go
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/bundlereferences/converter.go
  components/director/internal/domain/bundlereferences/entity.go
  components/director/internal/domain/bundlereferences/fixtures_test.go
  components/director/internal/domain/bundlereferences/repository.go
  components/director/internal/domain/bundlereferences/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/resolver.go
  components/director/internal/domain/eventdef/service.go
  components/director/internal/domain/eventdef/service_test.go
  components/director/internal/model/api.go
  components/director/internal/model/bundle_references.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/automock/api_service.go
  components/director/internal/open_resource_discovery/automock/event_service.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20211206143039_ord_default_bundle.down.sql
  components/schema-migrator/migrations/director/20211206143039_ord_default_bundle.up.sql
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/assertions/assertions.go
Labels: :wave: request review, size/XL, lgtm

#2127 Update director's readme file
  components/director/README.md
Labels: :heavy_check_mark: Approved, size/M, lgtm

#2133 Allow retrying existing timedout operations
  chart/compass/values.yaml
  components/operations-controller/api/v1alpha1/operation_types.go
  components/operations-controller/config/crd/bases/operations.compass_operations.yaml
  components/operations-controller/controllers/assertions_test.go
  components/operations-controller/controllers/controllersfakes/fake_status_manager.go
  components/operations-controller/controllers/operation_controller.go
  components/operations-controller/controllers/operation_controller_integration_test.go
  components/operations-controller/controllers/operation_controller_test.go
  components/operations-controller/controllers/types.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/operations-controller/internal/k8s/status/manager.go
  components/operations-controller/internal/k8s/status/manager_test.go
  components/operations-controller/tools/tools.go
Labels: bug, :wave: request review, size/XL, lgtm

#2132 System Fetcher dual oauth mode
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/virtual-service.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/root_resolver.go
  components/director/internal/securehttp/caller.go
  components/director/internal/securehttp/caller_test.go
  components/director/internal/systemfetcher/automock/api_client.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/oauth_client.go
  components/director/pkg/auth/automock/certificate_cache.go
  components/director/pkg/auth/basic_provider_test.go
  components/director/pkg/auth/mtls_token_provider.go
  components/director/pkg/auth/mtls_token_provider_test.go
  components/director/pkg/auth/service_account_token_provider_test.go
  components/director/pkg/auth/token_provider.go
  components/director/pkg/auth/token_provider_test.go
  components/director/pkg/auth/types.go
  components/director/pkg/oauth/config.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/oauth/model.go
  components/external-services-mock/internal/oauth/token_handler.go
  components/external-services-mock/internal/oauth/token_handler_test.go
  components/external-services-mock/internal/systemfetcher/handler.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/operations-controller/internal/utils/clients_test.go
  components/operations-controller/internal/webhook/client.go
  components/system-broker/pkg/oauth/token_provider_from_secret.go
  components/system-broker/pkg/oauth/token_provider_from_secret_test.go
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
Labels: :wave: request review, size/XXL, lgtm

#2137 Fix generate-examples.sh
  components/director/examples/add-api-definition-to-bundle/add-api-definition-to-bundle.graphql
  components/director/examples/add-bundle/add-bundle.graphql
  components/director/examples/add-document-to-bundle/add-document-to-bundle.graphql
  components/director/examples/add-event-definition-to-bundle/add-event-definition-to-bundle.graphql
  components/director/examples/add-webhook/add-application-template-webhook.graphql
  components/director/examples/add-webhook/add-application-webhook.graphql
  components/director/examples/create-application-template/create-application-template.graphql
  components/director/examples/delete-application-template/delete-application-template.graphql
  components/director/examples/delete-bundle-instance-auth/delete-bundle-instance-auth.graphql
  components/director/examples/delete-bundle/delete-bundle.graphql
  components/director/examples/delete-webhook/delete-application-webhook.graphql
  components/director/examples/query-api-definition/query-api-definition.graphql
  components/director/examples/query-api-definitions/query-api-definitions.graphql
  components/director/examples/query-application-template/query-application-template.graphql
  components/director/examples/query-application-templates/query-application-templates.graphql
  components/director/examples/query-application/query-application.graphql
  components/director/examples/query-applications-for-runtime/query-applications-for-runtime.graphql
  components/director/examples/query-applications/query-applications-with-label-filter.graphql
  components/director/examples/query-applications/query-applications.graphql
  components/director/examples/query-bundle/query-bundle.graphql
  components/director/examples/query-bundles/query-bundles.graphql
  components/director/examples/query-document/query-document.graphql
  components/director/examples/query-documents/query-documents.graphql
  components/director/examples/query-event-definition/query-event-definition.graphql
  components/director/examples/query-event-definitions/query-event-definitions.graphql
  components/director/examples/query-integration-system/query-integration-system.graphql
  components/director/examples/query-integration-systems/query-integration-systems.graphql
  components/director/examples/query-runtime/query-runtime.graphql
  components/director/examples/query-runtimes/query-runtimes-with-label-filter.graphql
  components/director/examples/query-runtimes/query-runtimes-with-pagination.graphql
  components/director/examples/query-runtimes/query-runtimes.graphql
  components/director/examples/query-tenants/query-tenants.graphql
  components/director/examples/refetch-api-spec/refetch-api-spec.graphql
  components/director/examples/register-application-from-template/register-application-from-template.graphql
  components/director/examples/register-application/register-application-with-bundles.graphql
  components/director/examples/register-application/register-application-with-status.graphql
  components/director/examples/register-application/register-application-with-webhooks.graphql
  components/director/examples/register-application/register-application.graphql
  components/director/examples/register-integration-system/register-integration-system.graphql
  components/director/examples/register-runtime/register-runtime.graphql
  components/director/examples/request-bundle-instance-auth-creation/request-bundle-instance-auth-creation.graphql
  components/director/examples/request-bundle-instance-auth-deletion/request-bundle-instance-auth-deletion.graphql
  components/director/examples/set-bundle-instance-auth/set-bundle-instance-auth.graphql
  components/director/examples/unpair-application/unpair-application.graphql
  components/director/examples/unregister-application/unregister-application.graphql
  components/director/examples/unregister-integration-system/unregister-integration-system.graphql
  components/director/examples/unregister-runtime/unregister-runtime.graphql
  components/director/examples/update-api-definition/update-api-definition.graphql
  components/director/examples/update-application-template/update-application-template.graphql
  components/director/examples/update-application/update-application.graphql
  components/director/examples/update-bundle/update-bundle.graphql
  components/director/examples/update-event-definition/update-event-definition.graphql
  components/director/examples/update-integration-system/update-integration-system.graphql
  components/director/examples/update-runtime/update-runtime.graphql
  components/director/examples/update-webhook/update-application-webhook.graphql
  tests/director/generate_examples.sh
Labels: size/L, lgtm

#2123 Introduce Write-only Protected Labels on Runtimes
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/tenantfetcher-job/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/automock/self_register_manager.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/rtmtest/selfreg_manager.go
  components/director/internal/domain/runtime/selfreg_manager.go
  components/director/internal/domain/runtime/selfreg_manager_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  tests/director/tests/runtime_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: size/L, lgtm

#2138 Return unauthorized for deleted systems in connectivity-adapter
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/appdetails/middleware_test.go
  components/connectivity-adapter/pkg/res/error.go
Labels: bug, :wave: request review, size/M, lgtm

#2141 Restart critical deployments on a new installation
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
Labels: :wave: request review, size/XS, lgtm

#2140 Bump console version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm

#2146 [HOTFIX] Escape special characters in graphQL requests from tenant-fetcher job
  chart/compass/values.yaml
  components/director/hack/jwt_generator.sh
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: bug, :wave: request review, size/M, lgtm

#2145 Escape special characters in graphQL requests from tenant-fetcher job
  chart/compass/values.yaml
  components/director/hack/jwt_generator.sh
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: :wave: request review, size/M, lgtm

#2147 Respect dirty flag on schema version in readiness probe
  chart/compass/values.yaml
  components/director/internal/domain/schema/repository.go
  components/director/internal/healthz/automock/repository.go
  components/director/internal/healthz/ready.go
  components/director/internal/healthz/ready_test.go
Labels: bug, :wave: request review, size/M, lgtm

#2148 [HOTFIX] Respect dirty flag on schema version in readiness probe
  chart/compass/values.yaml
  components/director/internal/domain/schema/repository.go
  components/director/internal/healthz/automock/repository.go
  components/director/internal/healthz/ready.go
  components/director/internal/healthz/ready_test.go
Labels: bug, :wave: request review, size/M, lgtm

#2151 [HOTFIX] Fix resources are not deleted when tenant is deleted
  chart/compass/values.yaml
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/pkg/resource/resource.go
  components/schema-migrator/migrations/director/20211201114401_delete-orphaned-data.down.sql
  components/schema-migrator/migrations/director/20211201114401_delete-orphaned-data.up.sql
Labels: bug, :wave: request review, size/L, lgtm

#2150 Fix resources are not deleted when tenant is deleted
  chart/compass/values.yaml
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/pkg/resource/resource.go
  components/schema-migrator/migrations/director/20211201114401_delete-orphaned-data.down.sql
  components/schema-migrator/migrations/director/20211201114401_delete-orphaned-data.up.sql
Labels: bug, :wave: request review, size/L, lgtm

#2149 Update compass console
  chart/compass/values.yaml
Labels: size/XS, lgtm

#2142 Expose external certs' rootCA on info endpoint
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/root-ca.yaml
  chart/compass/charts/gateway/templates/cmp-root-ca.yaml
  chart/compass/charts/gateway/templates/gateway-certs-mtls.yaml
  chart/compass/charts/gateway/templates/gateway-certs.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/values.yaml
  components/director/internal/info/handler.go
Labels: :wave: request review, size/S, lgtm

#2104 Enable mTLS Prometheus Scraping
  chart/compass/charts/director/templates/policy.yaml
  chart/compass/charts/director/templates/service-monitor.yaml
  chart/compass/charts/gateway/templates/policy.yaml
  chart/compass/charts/gateway/templates/service-monitor.yaml
  chart/compass/charts/operations-controller/templates/policy.yaml
  chart/compass/charts/operations-controller/templates/service-monitor.yaml
  chart/compass/charts/postgresql/templates/servicemonitor.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/policy.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/servicemonitor.yaml
  chart/compass/charts/system-broker/templates/policy.yaml
  chart/compass/charts/system-broker/templates/service-monitor.yaml
  chart/compass/templates/internal-communication-policies.yaml
  installation/cmd/run.sh
  installation/scripts/prom-mtls-patch.sh
Labels: size/XL, lgtm

#2155 Self registration with cert
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.sum
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/selfreg_manager.go
  components/director/internal/securehttp/caller.go
  components/director/internal/securehttp/caller_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/oauth/model.go
  components/external-services-mock/internal/oauth/token_handler.go
  components/external-services-mock/internal/oauth/token_handler_test.go
Labels: :wave: request review, size/XL, lgtm

#2159 Fix director's run.sh.
  components/director/run.sh
Labels: bug, :wave: request review, size/XS, lgtm
