Repository kyma-incubator/compass, pull requests merged in 2022-07, with the labels that each got.

#2453 Add retry mechanism for ORD Aggregator fetch requests
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/retry/retry.go
  components/director/pkg/retry/retry_test.go
  components/director/run.sh
  tests/external-services-mock/tests/fetch_request_test.go
  tests/external-services-mock/tests/main_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2454 Remove unneded tenant check
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/automock/label_repository.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/label/repository.go
  tests/director/tests/application_templates_api_test.go
  tests/pkg/testctx/testctx.go
Labels: :wave: request review, size/M, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#2464 Runtime contexts improvements
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220701113309_runtime_contexts_improvements.down.sql
  components/schema-migrator/migrations/director/20220701113309_runtime_contexts_improvements.up.sql
Labels: size/M, approved, lgtm, to be released :rocket:

#2459 Bump ORD Service version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, to be released :rocket:

#2466 Remove unneeded multi-team owners files
  CODEOWNERS
  components/director/cmd/director/OWNERS
  components/director/cmd/tenantloader/OWNERS
  components/external-services-mock/OWNERS
  components/schema-migrator/OWNERS
Labels: size/M, approved, lgtm

#2467 Use upsert instead of create for tenant access
  chart/compass/values.yaml
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
Labels: size/S, approved, lgtm

#2468 Use upsert instead of create for tenant access
  chart/compass/values.yaml
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
Labels: size/S, approved, lgtm

#2465 Check for provider runtime existence before creating a new one
  chart/compass/values.yaml
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/rtmtest/selfreg_manager.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/domain/subscription/automock/runtime_service.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  tests/director/tests/runtime_api_test.go
  tests/go.sum
Labels: approved, size/XL, lgtm

#2471 [HOTFIX] Fix runtime contexts tests' external cert configuration
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
Labels: :wave: request review, size/S, approved, lgtm

#2470 Fix runtime contexts tests' external cert configuration
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
Labels: size/S, approved, lgtm

#2477 [HOTFIX] Fix subscription tests configuration
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
Labels: :hammer: hotfix, size/M, approved, lgtm

#2480 Rename the application template registered by NS Adapter
  chart/compass/values.yaml
  components/director/cmd/ns-adapter/main.go
  components/director/run.sh
  tests/ns-adapter/tests/delta_report_test.go
  tests/ns-adapter/tests/full_report_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2481 Fix test secret reference
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/certificates_access_test.go
  tests/director/tests/main_test.go
Labels: size/M, approved, lgtm

#2482 [HOTFIX] Fix test secret reference
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/certificates_access_test.go
  tests/director/tests/main_test.go
Labels: size/M, approved, lgtm

#2425 Add additional Application Provider onboarding validation
  chart/compass/charts/external-services-mock/templates/region-instances-credentials.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/apptemplate/automock/application_template_repository.go
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/apptemplate/automock/label_repository.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/nsadapter/handler/exposed_systems_handler.go
  components/director/internal/nsadapter/handler/exposed_systems_handler_test.go
  components/director/run.sh
  components/schema-migrator/migrations/director/20220617104418_remove-app-template-name-constraint.down.sql
  components/schema-migrator/migrations/director/20220617104418_remove-app-template-name-constraint.up.sql
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/certificates_access_test.go
  tests/ns-adapter/tests/delta_report_test.go
  tests/ns-adapter/tests/full_report_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/certs/certprovider/ext_cert_provider.go
  tests/pkg/subscription/config.go
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon, :dragon: team-dragon

#2469 Patch TestDefinitions for autoscaler eviction
  chart/compass/charts/testing/charts/octopus/templates/manager.yaml
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#2474 Allow one self registration for app templates
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/apptmpltest/selfreg_manager.go
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/formation/automock/formation_repository.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/gateway/tests/integration_system_scope_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2485 Fix e2e apptemplate tests which use different region
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
Labels: :wave: request review, size/M, approved, lgtm

#2486 Revert "Fix e2e apptemplate tests which use different region"
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
Labels: size/M, approved, lgtm

#2487 Branch enablement of internal communication policies
  chart/compass/templates/internal-communication-policies.yaml
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#2479 Ensure ORD Aggregator ignores unknown ORD entities and properties
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/service.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/ord-aggregator/handler.go
  components/external-services-mock/internal/ord-aggregator/template.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2428 Add Formation Template documentation
  docs/compass/03-formation-templates.md
Labels: :wave: request review, size/M, approved, lgtm

#2490 Restart TF on each installation
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
Labels: :wave: request review, size/XS, approved, lgtm, to be released :rocket:, :dragon: team-dragon

#2488 Fix app template subscriptions with second region
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/main_test.go
  tests/pkg/certs/certprovider/ext_cert_provider.go
  tests/pkg/tenant/tenant_setup.go
Labels: size/M, approved, lgtm

#2492 Fix director cert client for region 2 configuration
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
Labels: size/S, approved, lgtm

#2493 Fix consumer account ID
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
Labels: size/XS

#2494 Bump timestamp for app template name constraint migration
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220719132455_remove-app-template-name-constraint.down.sql
  components/schema-migrator/migrations/director/20220719132455_remove-app-template-name-constraint.up.sql
Labels: size/XS, approved, lgtm

#2497 Fix create application template e2e tests
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
Labels: approved, size/L, lgtm

#2498 Fix e2e test assertions
  chart/compass/values.yaml
  tests/director/tests/runtime_contexts_api_test.go
Labels: size/M, approved, lgtm

#2495 Fix consumer provider ID in RuntimeContextSubscriptionFlows e2e test
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
Labels: size/XS, approved, lgtm

#2499 Fix TestRuntimeContextSubscriptionFlows e2e test assertions
  chart/compass/values.yaml
  tests/director/tests/runtime_contexts_api_test.go
Labels: size/M, approved, lgtm, to be released :rocket:

#2489 Update Compass installation docs
  chart/compass/templates/agent-configuration-job.yaml
  chart/compass/templates/internal-communication-policies.yaml
  chart/compass/templates/migrator-pvc.yaml
  chart/compass/values.yaml
  docs/compass/04-01-installation.md
  installation/resources/kyma/kyma-overrides-full.yaml
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/install-compass.sh
  installation/scripts/install-kyma.sh
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2502 Fix deploy-on-k3d make target
  components/director/Makefile
  components/external-services-mock/Makefile
  scripts/generic_make_go.mk
Labels: size/XS, approved, lgtm

#2503 Adapt ext-svc-mock self-reg cleanup
  chart/compass/values.yaml
  components/external-services-mock/internal/selfreg/handler.go
  components/external-services-mock/internal/subscription/handler.go
  tests/director/tests/runtime_contexts_api_test.go
Labels: size/M, approved, lgtm

#2478 Respect runtime types in ASAs
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/document/repository_test.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/formation/automock/formation_template_repository.go
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/repository_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/internal/domain/ordvendor/repository_test.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/product/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/runtime_context/automock/runtime_repository.go
  components/director/internal/domain/runtime_context/repository.go
  components/director/internal/domain/runtime_context/repository_test.go
  components/director/internal/domain/runtime_context/service.go
  components/director/internal/domain/runtime_context/service_test.go
  components/director/internal/domain/spec/repository_test.go
  components/director/internal/domain/tombstone/repository_test.go
  components/director/internal/model/formation.go
  components/director/internal/repo/testdb/generic_repo_exist_tests.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/fomation_requests.go
  tests/pkg/fixtures/formation_queries.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2456 Make DB dumps environment/DB specific
  chart/compass/values.yaml
  components/schema-migrator/run.sh
  components/schema-migrator/update-expected-schema-version.sh
  installation/cmd/run.sh
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2500 Support ORD Aggregation with Tenant Header
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/service.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/webhook/automock/webhook_repository.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/open_resource_discovery/automock/tenant_service.go
  components/director/internal/open_resource_discovery/automock/webhook_service.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/pkg/accessstrategy/access_strategy.go
  components/director/pkg/accessstrategy/automock/executor.go
  components/director/pkg/accessstrategy/cmp_mtls_access_strategy.go
  components/director/pkg/accessstrategy/executor_provider.go
  components/director/pkg/accessstrategy/open_access_strategy.go
  components/director/pkg/accessstrategy/open_access_strategy_test.go
  components/director/pkg/http/request.go
  components/director/pkg/http/request_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/ord-aggregator/globalregistry/template.go
  components/external-services-mock/internal/ord-aggregator/handler.go
  components/external-services-mock/internal/subscription/handler.go
  tests/go.mod
  tests/go.sum
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-aggregator/tests/registry_client.go
  tests/pkg/fixtures/application_template_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#2508 Fix tenants resync: add tenant listing in chunks
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
Labels: :wave: request review, :hammer: hotfix, approved, size/L, lgtm

#2509 [v1.37.0] Fix tenants resync: add tenant listing in chunks
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
Labels: :wave: request review, :hammer: hotfix, approved, size/L, lgtm

#2505 Fix runtime/runtime contexts ASA processing
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/runtime_context/service.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  tests/director/tests/formation_api_test.go
  tests/go.sum
Labels: approved, size/XL, lgtm, to be released :rocket:, :t-rex: team-raptor

#2511 Fix TestORDAggregator e2e test
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#2512 Fix runtime context's parent owner check
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/runtime_context/service.go
  components/director/internal/domain/runtime_context/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor
