Repository kyma-incubator/compass, pull requests merged in 2022-10, with the labels that each got.

#2659 Formation assignments entity
  CODEOWNERS
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/dataloaders/formationAssignmentLoaders.go
  components/director/internal/dataloaders/formationassignmentloader_gen.go
  components/director/internal/domain/formation/automock/formation_assignment_converter.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formationassignment/OWNERS
  components/director/internal/domain/formationassignment/automock/entity_converter.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_converter.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_repository.go
  components/director/internal/domain/formationassignment/automock/uid_service.go
  components/director/internal/domain/formationassignment/converter.go
  components/director/internal/domain/formationassignment/converter_test.go
  components/director/internal/domain/formationassignment/entity.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/model/formation_assignment.go
  components/director/internal/model/formation_assignment_test.go
  components/director/internal/repo/testdb/generic_repo_create_tests.go
  components/director/internal/repo/testdb/generic_repo_delete_tests.go
  components/director/internal/repo/testdb/generic_repo_list_tests.go
  components/director/internal/repo/testdb/generic_repo_update_tests.go
  components/director/pkg/graphql/formation.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/resource/resource.go
  components/schema-migrator/migrations/director/20221003120132_introduce-formation-assignments-entity.down.sql
  components/schema-migrator/migrations/director/20221003120132_introduce-formation-assignments-entity.up.sql
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#2660 Proper ORD Aggregator validation errors list logging
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/validation.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2663 Fix long-living DB transactions in ORD Aggregator
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/automock/application_service.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#2667 Adjust the certificate used for communication with Ext service
  chart/compass/charts/director/templates/ext-svc-certificate-rotation-job.yaml
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2668 Adjust the certificate used for communication with Ext service
  chart/compass/charts/director/templates/ext-svc-certificate-rotation-job.yaml
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2653 Set timeout for tenant destination sync
  chart/compass/charts/destination-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/destinationfetcher-svc/main.go
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/client_test.go
  components/director/internal/destinationfetchersvc/handler.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/service_test.go
  components/director/internal/destinationfetchersvc/syncjob.go
  components/director/internal/domain/tenant/repository.go
  components/director/pkg/cronjob/cronjob.go
Labels: approved, size/L, lgtm, :eagle: team-falcon

#2669 Set timeout for tenant destination sync (#2653)
  chart/compass/charts/destination-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/destinationfetcher-svc/main.go
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/client_test.go
  components/director/internal/destinationfetchersvc/handler.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/service_test.go
  components/director/internal/destinationfetchersvc/syncjob.go
  components/director/internal/domain/tenant/repository.go
  components/director/pkg/cronjob/cronjob.go
Labels: approved, size/L, lgtm, :eagle: team-falcon

#2670 Update ord-service
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#2671 API validation rules adjusted
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2672 Extend label filter query
  chart/compass/values.yaml
  components/director/internal/domain/label/query.go
  components/director/internal/domain/label/query_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2644 Allow Technical Client authentication
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/charts/hydrator/values.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims/validator.go
  components/director/pkg/cert/certutils.go
  components/director/pkg/cert/certutils_test.go
  components/director/pkg/consumer/consumer.go
  components/director/pkg/model/system_auth.go
  components/hydrator/cmd/main.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/subject/cert_subject.go
  components/hydrator/internal/subject/cert_subject_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/technical_client_test.go
  tests/go.mod
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/certs/certprovider/ext_cert_provider.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2673 Validate ORD service and Compass Console
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2674 Change webhook in ext-svc-mock docs
  tests/external-services-mock/tests/README.md
Labels: size/XS, lgtm

#2676 Disable Technical Client test
  chart/compass/values.yaml
  tests/director/tests/technical_client_test.go
Labels: size/S, approved, lgtm

#2679 Make tech client e2e test skippable
  chart/compass/values.yaml
  tests/director/tests/technical_client_test.go
Labels: :wave: request review, size/M, approved, lgtm

#2677 Rename internal Tenant Fecher subscription function to a more general name
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/subscriber.go
Labels: :wave: request review, size/S, approved, lgtm, :dragon: team-dragon

#2678 Add correlation ID for ORD Aggregation
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2682 Add schema to table in custom query
  chart/compass/values.yaml
  components/director/internal/domain/label/query.go
  components/director/internal/domain/label/query_test.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2684 Fix query for manual applications
  chart/compass/values.yaml
  components/director/internal/domain/label/query.go
  components/director/internal/domain/label/query_test.go
Labels: size/XS, approved, lgtm

#2685 [HOTFIX] Fix query for filtration
  chart/compass/values.yaml
  components/director/internal/domain/label/query.go
  components/director/internal/domain/label/query_test.go
Labels: size/XS, approved, lgtm

#2686 Fix ORD e2e test
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/k8s/jobs.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2687 [Hotfix] Fix ORD e2e test
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/k8s/jobs.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2613 Refactor installation scripts
  installation/cmd/run.sh
  installation/scripts/install-compass.sh
  installation/scripts/prow/execute-tests.sh
  installation/scripts/prow/provision.sh
  installation/scripts/prow/uninstall-compass.sh
  installation/scripts/prow/update-compass.sh
  installation/scripts/uninstall-compass.sh
  installation/scripts/utils.sh
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2692 Refactor metrics pusher
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/metrics/pusher.go
  components/director/internal/tenantfetchersvc/resync/automock/aggregation_failure_pusher.go
  components/director/internal/tenantfetchersvc/resync/automock/event_api_client.go
  components/director/internal/tenantfetchersvc/resync/automock/metrics_pusher.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/internal/tenantfetchersvc/resync/client.go
  components/director/internal/tenantfetchersvc/resync/client_test.go
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/director/internal/tenantfetchersvc/resync/event_page_test.go
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/synchronizer_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_mover.go
  components/director/internal/tenantfetchersvc/resync/tenant_mover_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :dragon: team-dragon

#2693 Disable System Broker component
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm

#2689 Rework System Fetcher to use application templates labels
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/nsadapter/handler/exposed_systems_handler_test.go
  components/director/internal/nsadapter/nsmodel/model.go
  components/director/internal/nsadapter/nsmodel/model_test.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2697 Trim leading and trailing whitespace from ORD Validation errors
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2696 Temporary remove TA HPA
  chart/compass/charts/tenant-fetcher/templates/horizontal-pod-autoscaler.yaml
Labels: :wave: request review, size/M, approved, lgtm, :dragon: team-dragon

#2699 Adjsut TestFormationAssignments test to be skippable
  chart/compass/values.yaml
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2694 Make db transactions in ORD Aggregator more granularly
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  tests/go.mod
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#2698 Support atom tenant types
  chart/compass/values.yaml
  components/director/internal/domain/tenant/service_test.go
  components/director/pkg/tenant/entity.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/subject/cert_subject.go
  components/schema-migrator/migrations/director/20221017150000_introduce_atom_tenant_types.down.sql
  components/schema-migrator/migrations/director/20221017150000_introduce_atom_tenant_types.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2695 Placeholders for apps in subscription
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/subscription/automock/label_service.go
  components/director/internal/domain/subscription/fixtures_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/internal/domain/tenant/service.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/pkg/subscription/config.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2701 Introduce mutation for single tenant upsertion
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_converter.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#2703 Fix app template unit tests
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver_test.go
Labels: size/XS, approved, lgtm

#2700 Generate formation notification about Runtime/RuntimeCtx for Application
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/open_resource_discovery/service_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2704 [HOTFIX] Fix app subscription for templates with optional placeholders
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/application_templates_subscription_test.go
Labels: :wave: request review, size/XS, approved, lgtm

#2707 Fix long running ord aggregator e2e tests
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/k8s/jobs.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2708 [HOTFIX] Fix long running ord aggregator e2e tests
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/k8s/jobs.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2705 Fix app subscription for templates with optional placeholders
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/application_templates_subscription_test.go
Labels: :wave: request review, size/XS, approved, lgtm

#2710 Add a check in the cert-rotation job if the TOKEN is "null"
  chart/compass/charts/director/templates/ext-svc-certificate-rotation-job.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
Labels: size/XS, approved, lgtm, :t-rex: team-raptor
