Repository kyma-incubator/compass, pull requests merged in 2022-12, with the labels that each got.

#2768 Soften app template name and displayName requirements
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/ord-service/tests/api_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/fixtures/application_template_requests.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2764 Introduce discovery domain
  chart/compass/charts/gateway/templates/cmp-root-CAs.yaml
  chart/compass/charts/gateway/templates/cmp-root-ca.yaml
  chart/compass/charts/gateway/templates/gateway-certs-mtls.yaml
  chart/compass/charts/gateway/templates/gateway.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-discovery-mtls.yaml
  chart/compass/values.yaml
  installation/cmd/run.sh
  installation/resources/compass-overrides-local.yaml
Labels: approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor

#2776 [HOTFIX]Fix assign to formation from ASA
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_repository.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_service.go
  components/director/internal/domain/formation/automock/formation_repository.go
  components/director/internal/domain/formation/automock/formation_template_repository.go
  components/director/internal/domain/formation/automock/label_def_repository.go
  components/director/internal/domain/formation/automock/label_def_service.go
  components/director/internal/domain/formation/automock/label_repository.go
  components/director/internal/domain/formation/automock/label_service.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/automock/tenant_service.go
  components/director/internal/domain/formation/automock/uuid_service.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
Labels: kind/bug, :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2771 Upgrade Kyma version to 2.2.0
  README.md
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/scripts/install-kyma.sh
Labels: :wave: request review, size/S, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#2773 Retrieve all fetch requests for object with one query
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/automock/spec_service.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2779 Add missing benchmark override
  installation/resources/compass-overrides-gke-benchmark.yaml
Labels: size/XS, approved, lgtm

#2785 Fix benchmark local overrides
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
Labels: size/XS, approved, lgtm

#2794 Add log for existing app template subscription
  chart/compass/values.yaml
  components/director/internal/domain/subscription/service.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2795 Fix local overrides
  chart/compass/values.yaml
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
Labels: size/S, approved, lgtm

#2797 Transfer local overrides to values.yaml
  chart/compass/values.yaml
  installation/resources/compass-overrides-local.yaml
Labels: size/XS, approved, lgtm

#2792 Use LocalTenantId during ORD Aggregation
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/cmd/ordaggregator/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/tenant/tenant.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/service.go
  components/director/pkg/accessstrategy/cmp_mtls_access_strategy.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2799 Fix benchmark overrides
  chart/compass/values.yaml
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
Labels: :wave: request review, size/S, approved, lgtm

#2796 Introduce tenant scoped formation templates
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/formation_template_repository.go
  components/director/internal/domain/formation/repository_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationtemplate/automock/formation_template_converter.go
  components/director/internal/domain/formationtemplate/automock/formation_template_repository.go
  components/director/internal/domain/formationtemplate/automock/tenant_service.go
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/converter_test.go
  components/director/internal/domain/formationtemplate/entity.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/internal/domain/formationtemplate/resolver.go
  components/director/internal/domain/formationtemplate/service.go
  components/director/internal/domain/formationtemplate/service_test.go
  components/director/internal/domain/labeldef/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/tenant.go
  components/director/internal/domain/tenant/tenant_test.go
  components/director/internal/model/formation_template.go
  components/director/internal/repo/delete.go
  components/director/internal/repo/testdb/generic_repo_get_tests.go
  components/schema-migrator/migrations/director/20221206114754_add-tenant-to-formation-templates.down.sql
  components/schema-migrator/migrations/director/20221206114754_add-tenant-to-formation-templates.up.sql
  components/schema-migrator/seeds/director/add_tenants.sql
  tests/director/tests/formation_templates_test.go
  tests/pkg/fixtures/formation_template_queries.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#2804 Adjust app name and rune limits
  chart/compass/values.yaml
  components/director/pkg/graphql/api_validation.go
  components/director/pkg/graphql/api_validation_test.go
  components/director/pkg/graphql/app_validation_test.go
  components/director/pkg/graphql/event_api_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/validation.go
  components/director/pkg/inputvalidation/inputvalidationtest/validator_fixtures.go
Labels: :wave: request review, :hammer: hotfix, size/S, approved, lgtm

#2806 Remove a negative test
  chart/compass/values.yaml
  tests/director/tests/application_templates_subscription_test.go
Labels: :wave: request review, size/M, approved, lgtm

#2800 Add some logs and skip processing of systems with unsupported type
  chart/compass/values.yaml
  components/director/cmd/ns-adapter/main.go
  components/director/internal/nsadapter/handler/exposed_systems_handler.go
  components/director/internal/nsadapter/handler/exposed_systems_handler_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2798 Fix UnassignFormation in Async API
  chart/compass/values.yaml
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/converter.go
  components/director/internal/domain/formationassignment/converter_test.go
  components/director/internal/domain/formationassignment/entity.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/internal/model/formation_assignment.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/persistence/txtest/txtest.go
  components/director/pkg/webhook/application_tenant_mapping.go
  components/schema-migrator/migrations/director/20221219120419_add-self-fa-and-drop-last-operation.down.sql
  components/schema-migrator/migrations/director/20221219120419_add-self-fa-and-drop-last-operation.up.sql
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#2778 Add applicationBySystemNumber endpoint
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/systemfetcher/automock/systems_service.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/pkg/fixtures/application_requests.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2809 Fix Formation Assignment creation
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/automock/formation_assignment_repository.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2810 Handle null error value in Formation Status API
  chart/compass/values.yaml
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#2812 Replace communication scenarios
  chart/compass/values.yaml
  components/pairing-adapter/internal/adapter/client.go
  components/pairing-adapter/internal/adapter/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2814 Hotfix temporary fix scenario groups
  chart/compass/values.yaml
  components/pairing-adapter/internal/adapter/client.go
  components/pairing-adapter/internal/adapter/handler.go
Labels: size/S, :eagle: team-falcon
