Repository kyma-incubator/compass, pull requests merged in 2022-06, with the labels that each got.

#2389 Override oathkeeper proxy timeout
  installation/resources/kyma/installer-overrides-kyma-full-config-local.yaml
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
Labels: size/XS, approved, lgtm

#2392 Adapt Runtime label APIs to use new Formation APIs underneath
  chart/compass/values.yaml
  components/director/go.mod
  components/director/internal/domain/runtime/automock/formation_service.go
  components/director/internal/domain/runtime/automock/scenario_assignment_engine.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/model/scenarios.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2395 bump ord-service version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2396 Fix self reg flow for app templates
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/model/app_template.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/main_test.go
Labels: :wave: request review, size/M, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#2399 Fix tests and add logic in self reg mgr
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/tenant-fetcher-job/tenant-fetcher-job-test.yaml
  chart/compass/values.yaml
  components/director/internal/selfregmanager/selfreg_manager.go
  components/director/internal/selfregmanager/selfreg_manager_test.go
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connectivity-adapter/tests/main_test.go
  tests/connector/tests/apitests_test.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/connector/tests/hydrator_api_test.go
  tests/director/bench/application_api_test.go
  tests/director/bench/main_test.go
  tests/director/tests/runtime_api_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/viewer_test.go
  tests/istio/tests/request_payload_limit_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/config/connector.go
  tests/pkg/config/istio.go
  tests/pkg/config/system_broker.go
  tests/system-broker/tests/auth_test.go
  tests/tenant-fetcher-job/tests/handler_test.go
  tests/tenant-fetcher-job/tests/main_test.go
Labels: approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2386 Adapt Application Label API to use Formations API
  chart/compass/values.yaml
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/application/automock/formation_service.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2405 Check for certificate consumer before delete xsuaa clone
  chart/compass/values.yaml
  components/director/internal/selfregmanager/selfreg_manager.go
  components/director/internal/selfregmanager/selfreg_manager_test.go
  tests/director/tests/application_api_test.go
Labels: size/M, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2385 Secure Application Provider Onboarding & Offboarding APIs with BTP Certificates
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/domain/bundleinstanceauth/service.go
  components/director/internal/packagetobundles/handler.go
  components/director/pkg/consumer/consumer.go
  components/director/pkg/model/system_auth.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/director/query_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider.go
  components/hydrator/pkg/oathkeeper/model.go
  tests/director/tests/application_templates_external_cert_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2409 Add verbose output on app delete
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/values.yaml
  tests/pkg/fixtures/application_queries.go
Labels: size/XS, approved, lgtm

#2407 Replace all director images on deploy-on-minikube
  components/director/Makefile
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2413 TestApplicationDeletionInScenario adjustments
  chart/compass/charts/postgresql/values-production.yaml
  chart/compass/charts/postgresql/values.yaml
  chart/compass/values.yaml
  installation/scripts/prow/deploy-and-test.sh
  tests/director/tests/application_api_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2414 Fix long lock in application list
  chart/compass/values.yaml
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
Labels: size/XS, approved, lgtm, to be released :rocket:

#2406 Delete app from tmpl on unsubscription callback
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/scenarioassignment/automock/runtime_repository.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/internal/domain/subscription/automock/application_service.go
  components/director/internal/domain/subscription/automock/subscription_service.go
  components/director/internal/domain/subscription/fixtures_test.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/resolver_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/pkg/graphql_client/director_client.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, do-not-merge/hold, size/XL, lgtm, :eagle: team-falcon, :dragon: team-dragon

#2412 Introduce Formation Templates
  CODEOWNERS
  chart/compass/charts/director/config.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/create-formation-template/create-formation-template.graphql
  components/director/examples/delete-formation-template/delete-formation-template.graphql
  components/director/examples/query-formation-template/query-formation-template.graphql
  components/director/examples/query-formation-templates/query-formation-templates.graphql
  components/director/examples/update-formation-template/update-formation-template.graphql
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/formationtemplate/OWNERS
  components/director/internal/domain/formationtemplate/automock/entity_converter.go
  components/director/internal/domain/formationtemplate/automock/formation_template_converter.go
  components/director/internal/domain/formationtemplate/automock/formation_template_repository.go
  components/director/internal/domain/formationtemplate/automock/formation_template_service.go
  components/director/internal/domain/formationtemplate/automock/uid_service.go
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/converter_test.go
  components/director/internal/domain/formationtemplate/entity.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/internal/domain/formationtemplate/resolver.go
  components/director/internal/domain/formationtemplate/resolver_test.go
  components/director/internal/domain/formationtemplate/service.go
  components/director/internal/domain/formationtemplate/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/formation_template.go
  components/director/internal/repo/testdb/generic_repo_exist_tests.go
  components/director/pkg/graphql/formation_template_validation.go
  components/director/pkg/graphql/formation_template_validation_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/resource/resource.go
  components/schema-migrator/migrations/director/20220606171814_introduce_formation_templates.down.sql
  components/schema-migrator/migrations/director/20220606171814_introduce_formation_templates.up.sql
  tests/director/tests/formation_templates_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/formation_template_fixtures.go
  tests/pkg/fixtures/formation_template_queries.go
  tests/pkg/fixtures/formation_template_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#2393 Allow generating OTT for applications registered on subaccount level from Pairing Adapter
  chart/compass/values.yaml
  components/director/internal/domain/onetimetoken/automock/external_tenants_service.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/onetimetoken/service_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2420 Introduce application namespace to AppTemplate
  chart/compass/values.yaml
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/entity.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/model/app_template.go
  components/director/internal/model/app_template_test.go
  components/director/internal/model/application.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/director/pkg/graphql/applicaiton_template.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20220615095050_introduce-application-namespace.down.sql
  components/schema-migrator/migrations/director/20220615095050_introduce-application-namespace.up.sql
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :eagle: team-falcon

#2424 Fix pairing-adapter e2e-test
  chart/compass/values.yaml
  tests/pairing-adapter/tests/mtls_flow_test.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#2404 App from tmpl on subscription callback
  chart/compass/charts/director/config.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/hack/config-local.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/apptemplate/automock/application_template_repository.go
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/subscription_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/subscription/automock/application_converter.go
  components/director/internal/domain/subscription/automock/application_service.go
  components/director/internal/domain/subscription/automock/application_template_service.go
  components/director/internal/domain/subscription/automock/label_service.go
  components/director/internal/domain/subscription/automock/runtime_service.go
  components/director/internal/domain/subscription/automock/subscription_service.go
  components/director/internal/domain/subscription/automock/tenant_service.go
  components/director/internal/domain/subscription/automock/uid_service.go
  components/director/internal/domain/subscription/fixtures_test.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/resolver_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/internal/subscription/service.go
  components/director/internal/subscription/service_test.go
  components/director/internal/tenantfetchersvc/automock/director_graph_ql_client.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/subscriber.go
  components/director/internal/tenantfetchersvc/subscriber_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql_client/director_client.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  tests/pkg/tenantfetcher/tenant_helper.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :eagle: team-falcon, :dragon: team-dragon

#2422 Introduce local tenand ID for applications
  chart/compass/charts/director/config.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/model/application.go
  components/director/internal/model/application_test.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20220616094814_application-local-tenant.down.sql
  components/schema-migrator/migrations/director/20220616094814_application-local-tenant.up.sql
  installation/cmd/run.sh
  tests/director/tests/application_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/token/token_utils.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2415 Forbid merging of systems which represent SaaS Application subscriptions-2
  chart/compass/charts/ns-adapter/templates/deployment.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/nsadapter/adapter/configuration.go
  components/director/internal/open_resource_discovery/automock/application_template_service.go
  tests/director/tests/application_api_test.go
  tests/pkg/token/token_utils.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :eagle: team-falcon

#2426 Remove debugging logs from flapping e2e tests
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
  tests/pkg/fixtures/application_queries.go
Labels: size/S, approved, lgtm

#2397 Add autoscaling annotation to cronjob & jobs
  chart/compass/charts/connector/templates/certs-setup-job.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/templates/agent-configuration-job.yaml
  chart/compass/templates/migrator-down-job.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/registration-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/templates/update-expected-schema-version-job.yaml
Labels: :wave: request review, size/S, lgtm, :t-rex: team-raptor

#2429 Fix local env on M1 macs
  installation/cmd/run.sh
  installation/scripts/install-kyma.sh
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2430 Revert SaaS callback incompatible change
  chart/compass/values.yaml
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/external-services-mock/internal/subscription/config.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: approved, size/XL, lgtm, :dragon: team-dragon

#2322 Replace K8s jobs with Go routines
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/rbac.yaml
  chart/compass/templates/additional-prometheus-rules.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/tenantfetcher/automock/tenant_storage_service.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/kubernetes.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_job_config.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_job_config_test.go
  components/director/pkg/kubernetes/client.go
  components/external-services-mock/internal/tenantfetcher/handler.go
  installation/resources/compass-overrides-local.yaml
  tests/tenant-fetcher-job/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2431 Add unique constraint to Formation Template name
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220621145611_make-formation-template-name-unique.down.sql
  components/schema-migrator/migrations/director/20220621145611_make-formation-template-name-unique.up.sql
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#2435 Register application with external certificate
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2437 Adjust deploy on k3d for SF and Director
  components/director/Makefile
  components/external-services-mock/Makefile
  scripts/generic_make_go.mk
Labels: :wave: request review, size/M, approved, lgtm

#2432 Increase size of a status_message column
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220621163400_increase_status_message_length.down.sql
  components/schema-migrator/migrations/director/20220621163400_increase_status_message_length.up.sql
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2440 Adjust UnsubscribeTenant flow
  chart/compass/values.yaml
  components/director/internal/domain/subscription/resolver.go
Labels: :wave: request review, size/XS, approved, lgtm

#2441 Adjust UnsubscribeTenant flow
  chart/compass/values.yaml
  components/director/internal/domain/subscription/resolver.go
Labels: :wave: request review, size/XS, approved, lgtm

#2433 Remove optional parameter from createFormation mutation and introduce unique constraint
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/labeldef/automock/formation_service.go
  components/director/internal/domain/labeldef/resolver.go
  components/director/internal/domain/labeldef/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/formation.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20220622090911_add-formation-name-tenant-unique-constraint.down.sql
  components/schema-migrator/migrations/director/20220622090911_add-formation-name-tenant-unique-constraint.up.sql
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2439 Reuse system number as local tenant ID in System Fetcher
  chart/compass/values.yaml
  components/director/internal/systemfetcher/service.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2434 Add runtime type label to kyma runtimes
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/tenantfetcher-job/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  components/schema-migrator/migrations/director/20220622093251_add-runtime-type-labels.down.sql
  components/schema-migrator/migrations/director/20220622093251_add-runtime-type-labels.up.sql
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
Labels: approved, size/L, lgtm, :dragon: team-dragon

#2436 Adapt docs and files from minikube to k3d
  README.md
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
  chart/compass/values.yaml
  components/director/Makefile
  components/director/cmd/scopessynchronizer/README.md
  components/schema-migrator/Makefile
  components/schema-migrator/README.md
  components/system-broker/README.md
  docs/compass/03-01-security.md
  docs/compass/04-01-installation.md
  docs/compass/08-01-basic-flow-tutorial.md
  installation/scripts/prow/deploy-and-test.sh
  scripts/generic_make_go.mk
  tests/README.md
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2447 Add director tests skip pattern functionality
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm

#2408 Secure app provider metadata api
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/appmetadatavalidation/automock/label_service.go
  components/director/internal/appmetadatavalidation/automock/tenant_service.go
  components/director/internal/appmetadatavalidation/directive.go
  components/director/internal/appmetadatavalidation/directive_test.go
  components/director/internal/appmetadatavalidation/fixtures_test.go
  components/director/internal/appmetadatavalidation/handler.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  tests/director/tests/application_templates_external_cert_api_test.go
  tests/director/tests/certificates_access_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2448 Add missing env in director tests
  chart/compass/templates/tests/director/director-test.yaml
Labels: size/XS, approved, lgtm

#2419 Runtime contexts documentation adaptation
  docs/compass/03-01-security.md
Labels: size/XS, approved, lgtm

#2445 SubscribeTenantToApplication should be Idempotent
  chart/compass/values.yaml
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2446 Use better config variable name for ORD Aggregator parallelism
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2452 Update Team Dragon Members
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2451 Subscription fixes
  chart/compass/values.yaml
  components/director/internal/domain/subscription/automock/subscription_service.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/resolver_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/pkg/graphql_client/director_client.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/subscription/utils.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2458 Revert logic for tenant swap
  chart/compass/values.yaml
  components/director/internal/appmetadatavalidation/directive.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  tests/director/tests/certificates_access_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2461 Fix subscription test
  chart/compass/values.yaml
  tests/director/tests/application_templates_subscription_test.go
Labels: approved, size/L, lgtm

#2460 Kill the build after 15 minutes
  chart/compass/values.yaml
  scripts/generic_make_go.mk
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2457 Switch liter config to Go 1.17
  chart/compass/values.yaml
  components/director/.golangci.yml
  components/director/hack/plugins/descriptionsdecorator/plugin.go
  components/director/hack/plugins/formatter.go
  components/director/internal/appmetadatavalidation/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2463 Store local tenant id for SaaS applications
  chart/compass/values.yaml
  components/director/internal/domain/subscription/automock/subscription_service.go
  components/director/internal/domain/subscription/fixtures_test.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/resolver_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/internal/tenantfetchersvc/automock/director_graph_ql_client.go
Labels: :wave: request review, size/M, lgtm, :dragon: team-dragon
