Repository kyma-incubator/compass, pull requests merged in 2022-08, with the labels that each got.

#2514 Fix TestORDAggregator e2e test
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2506 Patch mtls configuration of ServiceMonitors
  installation/scripts/prom-mtls-patch.sh
Labels: approved, lgtm, :t-rex: team-raptor

#2504 Cleanup & adaptations regarding kyma2.0
  .dockerignore
  README.md
  chart/compass/README.md
  docs/compass/09-01-e2e-test-design.md
  installation/cmd/run.sh
  installation/resources/readme.md
  installation/scripts/install-kyma.sh
  tools/compass-installer/Makefile
  tools/compass-installer/compass.Dockerfile
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2519 Fix ord aggregator e2e test
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2518 Fix ord aggregator e2e test.
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2475 Respect subscriptions in Application Provider Metadata Push APIs
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/appmetadatavalidation/automock/label_service.go
  components/director/internal/appmetadatavalidation/automock/tenant_service.go
  components/director/internal/appmetadatavalidation/directive.go
  components/director/internal/appmetadatavalidation/directive_test.go
  components/director/internal/appmetadatavalidation/fixtures_test.go
  components/director/internal/appmetadatavalidation/handler.go
  components/director/internal/authenticator/claims/automock/application_service.go
  components/director/internal/authenticator/claims/automock/application_template_service.go
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/authenticator/claims/validators_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/internal/features/features.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_job_config.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/persistence/txtest/txtest.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/main_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :eagle: team-falcon, :dragon: team-dragon

#2520 Specify GOARCH when building sandbox test Go binaries
  tests/connectivity-adapter/Makefile
  tests/connector/Makefile
  tests/director/Makefile
  tests/external-services-mock/Makefile
  tests/gateway/Makefile
  tests/istio/Makefile
  tests/ns-adapter/Makefile
  tests/ord-aggregator/Makefile
  tests/ord-service/Makefile
  tests/pairing-adapter/Makefile
  tests/system-broker/Makefile
  tests/system-fetcher/Makefile
  tests/tenant-fetcher/Makefile
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2524 Ensure App Provider subscriptions tests use dedicated provider cert client during double auth
  chart/compass/values.yaml
  tests/director/tests/application_templates_subscription_test.go
Labels: :wave: request review, size/M, approved, lgtm

#2523 Make template region in system-fetcher optional
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#2517 Fix runtimeType label immutability
  chart/compass/values.yaml
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  tests/director/tests/runtime_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2450 Allow Application Providers to query individual SaaS consumer systems
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims/claims.go
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/automock/application_template_service.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/consumer/consumer.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/main_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#2528 Fix runtimeType immutability e2e test.
  chart/compass/values.yaml
  tests/director/tests/runtime_api_test.go
Labels: size/XS, approved, lgtm

#2529 Make template region in system-fetcher optional
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#2532 add runtime type label where missing
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220805123243_add-runtime-type-label.down.sql
  components/schema-migrator/migrations/director/20220805123243_add-runtime-type-label.up.sql
Labels: size/S, approved, lgtm

#2531 Fix runtime type imutability
  chart/compass/values.yaml
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/schema-migrator/migrations/director/20220805123243_add-runtime-type-label.down.sql
  components/schema-migrator/migrations/director/20220805123243_add-runtime-type-label.up.sql
  tests/director/tests/runtime_api_test.go
Labels: approved, size/L, lgtm

#2522 Dynamically expose issuer and subject of Compass cert on the info endpoint
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/info/handler.go
  components/director/internal/info/handler_test.go
  components/director/run.sh
  tests/director/tests/info_api_test.go
  tests/director/tests/main_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2530 Bump ORD Service Version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2525 Support more than one locality in cert-rotation job
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/values.yaml
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#2536 Fix flapping ord test
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
Labels: size/XS, approved, lgtm

#2538 Fix generate examples script
  tests/director/generate_examples.sh
Labels: size/XS, approved, lgtm

#2539 Fix create application log message
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
Labels: size/S, approved, lgtm

#2534 Proper cleanup in subscription e2e tests
  chart/compass/values.yaml
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2542 Fix possible nil error on ns-adapter/system-fetcher start
  chart/compass/values.yaml
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/systemfetcher/main.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2541 Enrich application template already exists error message with region
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  tests/director/tests/application_templates_api_test.go
Labels: size/S, approved, lgtm

#2526 Add update application base url logic on AddBundle request
  chart/compass/values.yaml
  components/director/internal/domain/bundle/automock/application_service.go
  components/director/internal/domain/bundle/resolver.go
  components/director/internal/domain/bundle/resolver_test.go
  components/director/internal/domain/root_resolver.go
  tests/director/tests/bundle_api_test.go
Labels: approved, size/L, lgtm

#2540 Make get dependencies callback region aware
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/Makefile
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/run.sh
  tests/director/tests/application_templates_api_test.go
  tests/pkg/tenantfetcher/tenant_helper.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: approved, size/L, lgtm, :dragon: team-dragon

#2533 Update installation docs
  docs/compass/04-01-installation.md
Labels: :wave: request review, size/L, lgtm, :t-rex: team-raptor

#2521 Consumer context provider
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/tenant.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/subscription/config.go
  components/hydrator/cmd/main.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/config/consumer_claims.go
  components/hydrator/internal/director/automock/client.go
  components/hydrator/internal/director/client.go
  components/hydrator/internal/tenantmapping/automock/director_client.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  components/hydrator/internal/tenantmapping/handler.go
  components/hydrator/internal/tenantmapping/model.go
  components/hydrator/pkg/oathkeeper/model.go
  components/hydrator/pkg/tenantmapping/const.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/certificates_access_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/certs/certprovider/ext_cert_provider.go
  tests/pkg/subscription/utils.go
  tests/pkg/token/token_utils.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#2547 Increase unsubscribe client timeout in e2e tests
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#2548 Remove region from applicationType label
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  tests/director/tests/application_templates_api_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2549 Less wait for build to complete
  components/connectivity-adapter/Makefile
  components/connector/Makefile
  components/director/Makefile
  components/gateway/Makefile
  components/hydrator/Makefile
  components/operations-controller/Makefile
  components/pairing-adapter/Makefile
  components/system-broker/Makefile
  scripts/generic_make_go.mk
  tests/Makefile
Labels: :wave: request review, size/S, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2507 Allow mtls credential push
  chart/compass/values.yaml
  components/director/internal/domain/auth/converter.go
  components/director/internal/domain/auth/converter_test.go
  components/director/internal/domain/auth/fixtures_test.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/systemauth/fixtures_test.go
  components/director/internal/model/auth.go
  components/director/pkg/graphql/auth.go
  components/director/pkg/graphql/auth_test.go
  components/director/pkg/graphql/auth_validation.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/auth_requests.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#2484 Ensure region label is derived during onboarding flow
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantloader/main.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/domain/apptemplate/apptmpltest/selfreg_manager.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/rtmtest/selfreg_manager.go
  components/director/internal/externaltenant/mapping.go
  components/director/internal/externaltenant/mapping_test.go
  components/director/internal/externaltenant/testdata/tenants/valid_tenants.json
  components/director/internal/externaltenant/testdata/tenants/valid_tenants2.json
  components/director/internal/selfregmanager/selfreg_manager.go
  components/director/internal/selfregmanager/selfreg_manager_test.go
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/access_level_context_provider_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/handler.go
  components/hydrator/internal/tenantmapping/handler_test.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider_test.go
  components/hydrator/internal/tenantmapping/user_context_provider.go
  components/hydrator/internal/tenantmapping/user_context_provider_test.go
  installation/scripts/install-compass.sh
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2551 Remove subdomain label update in hydrator
  chart/compass/values.yaml
  components/hydrator/internal/director/automock/client.go
  components/hydrator/internal/director/client.go
  components/hydrator/internal/tenantmapping/automock/director_client.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  components/hydrator/internal/tenantmapping/handler.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2554 Increase external services mock client timeout
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
Labels: size/XS, approved, lgtm

#2527 Check runtime type when assigning to formation
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/nsadapter/adapter/configuration.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/eventing_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/go.sum
  tests/pkg/config/connector.go
  tests/pkg/fixtures/fomation_requests.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/formation_template_fixtures.go
  tests/pkg/fixtures/runtime_queries.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2555 Ensure region is matching only for Consumer-provider flow
  chart/compass/values.yaml
  components/director/internal/externaltenant/mapping.go
  components/director/internal/externaltenant/mapping_test.go
  components/director/internal/externaltenant/testdata/tenants/valid_tenants.json
  components/director/internal/externaltenant/testdata/tenants/valid_tenants2.json
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/access_level_context_provider_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  components/hydrator/internal/tenantmapping/handler.go
  components/hydrator/internal/tenantmapping/handler_test.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider_test.go
  components/hydrator/internal/tenantmapping/user_context_provider.go
  components/hydrator/internal/tenantmapping/user_context_provider_test.go
Labels: size/L, :t-rex: team-raptor

#2556 Tweak Director e2e test when registering app template
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
Labels: size/XS

#2558 Update docs
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/values.yaml
  components/hydrator/internal/config/consumer_claims.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  docs/compass/03-01-security.md
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2561 [HOTFIX] Extend subscription tests job timeout
  chart/compass/values.yaml
  tests/pkg/subscription/utils.go
Labels: size/XS

#2566 Add user to team falcon
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#2564 Extend subscription job timeout
  chart/compass/values.yaml
  tests/pkg/subscription/utils.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2562 Optimize cache usage in token validation
  chart/compass/values.yaml
  components/hydrator/internal/authnmappinghandler/handler.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2563 Break down ORD views for embedded entities
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220815173614_ord_breakdown_embedded_entities_views.down.sql
  components/schema-migrator/migrations/director/20220815173614_ord_breakdown_embedded_entities_views.up.sql
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#2565 Remove specifications join in tenants apis view
  chart/compass/values.yaml
  components/director/internal/domain/api/service.go
  components/schema-migrator/migrations/director/20220816113345_remove-left-join-in-tenant-apis-view.down.sql
  components/schema-migrator/migrations/director/20220816113345_remove-left-join-in-tenant-apis-view.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2550 Add destinations to saas dependency callback
  chart/compass/charts/external-services-mock/templates/tenant-dependencies-secret.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/README.md
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/pkg/config/common.go
  components/director/run.sh
  installation/resources/compass-overrides-local.yaml
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: approved, size/L, lgtm, :dragon: team-dragon

#2573 Mock external call in authenticator unit test
  chart/compass/values.yaml
  components/director/internal/authenticator/middleware_test.go
Labels: :wave: request review, size/S, approved, lgtm

#2576 Optimise extensible view for APIs and Events
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220822112548_optimise_extensible_views.down.sql
  components/schema-migrator/migrations/director/20220822112548_optimise_extensible_views.up.sql
Labels: size/M, approved, do-not-merge/hold, lgtm

#2575 Bump alpine and go minor versions
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2579 Bump dependencies
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
Labels: approved, size/L, lgtm

#2578 Merge the two application inputs
  chart/compass/values.yaml
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: approved, size/L, lgtm, :eagle: team-falcon

#2462 Adjust testing.sh for benchmark usage
  chart/compass/values.yaml
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/scripts/testing.sh
  tests/director/bench/application_api_test.go
  tests/director/bench/main_test.go
  tests/go.mod
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2572 Unify the names of the docker images
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/pairing-adapter/Makefile
  installation/scripts/patch-test-definitions.sh
  tests/Makefile
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2574 Fix global registry & FR client
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/external-services-mock/cmd/main.go
  tests/ord-aggregator/tests/handler_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2559 Check application type when assigning to formation
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/features/features.go
  components/director/internal/nsadapter/adapter/configuration.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/config/connector.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/formation_template_fixtures.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2581 Fix sf integration systems new
  chart/compass/values.yaml
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: approved, size/L, lgtm, :eagle: team-falcon

#2560 Request http ORD documents in parallel
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2570 Application templates are managed by the System Fetcher
  chart/compass/templates/system-fetcher-configmap.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
  components/director/internal/systemfetcher/automock/app_tmpl_service.go
  components/director/internal/systemfetcher/automock/int_sys_svc.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/systemfetcher/loader_test.go
  components/director/internal/systemfetcher/model.go
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
  tests/system-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#2582 ORD db optimisations
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220823141813_ord_performance_optimisations.down.sql
  components/schema-migrator/migrations/director/20220823141813_ord_performance_optimisations.up.sql
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#2577 Trigger ORD Aggregator job manually in ORD Aggregator e2e tests
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2584 Fix ord aggregator template
  chart/compass/values.yaml
  components/external-services-mock/internal/apispec/handler.go
  components/external-services-mock/internal/apispec/template.go
  components/external-services-mock/internal/ord-aggregator/template.go
  tests/external-services-mock/tests/fetch_request_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2568 Extract postgresql chart
  chart/compass/charts/ns-adapter/templates/deployment.yaml
  chart/compass/requirements.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  chart/localdb/.helmignore
  chart/localdb/Chart.yaml
  chart/localdb/README.md
  chart/localdb/charts/dbdump/.helmignore
  chart/localdb/charts/dbdump/Chart.yaml
  chart/localdb/charts/dbdump/templates/dbdump-job.yaml
  chart/localdb/charts/dbdump/templates/dbdump-pv.yaml
  chart/localdb/charts/dbdump/values.yaml
  chart/localdb/charts/postgresql/.helmignore
  chart/localdb/charts/postgresql/Chart.yaml
  chart/localdb/charts/postgresql/README.md
  chart/localdb/charts/postgresql/templates/NOTES.txt
  chart/localdb/charts/postgresql/templates/_helpers.tpl
  chart/localdb/charts/postgresql/templates/configmap.yaml
  chart/localdb/charts/postgresql/templates/extended-config-configmap.yaml
  chart/localdb/charts/postgresql/templates/init-db-config-map.yaml
  chart/localdb/charts/postgresql/templates/initialization-configmap.yaml
  chart/localdb/charts/postgresql/templates/metrics-svc.yaml
  chart/localdb/charts/postgresql/templates/networkpolicy.yaml
  chart/localdb/charts/postgresql/templates/secrets.yaml
  chart/localdb/charts/postgresql/templates/serviceaccount.yaml
  chart/localdb/charts/postgresql/templates/servicemonitor.yaml
  chart/localdb/charts/postgresql/templates/statefulset-slaves.yaml
  chart/localdb/charts/postgresql/templates/statefulset.yaml
  chart/localdb/charts/postgresql/templates/svc-headless.yaml
  chart/localdb/charts/postgresql/templates/svc-read.yaml
  chart/localdb/charts/postgresql/templates/svc.yaml
  chart/localdb/charts/postgresql/values-production.yaml
  chart/localdb/charts/postgresql/values.yaml
  chart/localdb/values.yaml
  components/schema-migrator/run.sh
  docs/compass/04-01-installation.md
  installation/cmd/run.sh
  installation/scripts/install-compass.sh
  installation/scripts/install-db.sh
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2545 Migrate to kyma 2.1.3
  README.md
  chart/compass/templates/filters/request-limit-filter-2mb.yaml
  chart/compass/templates/filters/request-limit-filter-5mb.yaml
  chart/compass/templates/internal-communication-policies.yaml
  chart/compass/values.yaml
  components/schema-migrator/Dockerfile
  docs/compass/04-01-installation.md
  installation/cmd/run.sh
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-components-full.yaml
  installation/resources/kyma/kyma-components-minimal.yaml
  installation/resources/kyma/kyma-overrides-full.yaml
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/install-kyma.sh
  installation/scripts/prom-mtls-patch.sh
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2588 App to app formation notifications
  chart/compass/values.yaml
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/application_repository.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/model/webhook.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/application_tenant_mapping.go
  components/schema-migrator/migrations/director/20220825092104_app-to-app-formation-notifications.down.sql
  components/schema-migrator/migrations/director/20220825092104_app-to-app-formation-notifications.up.sql
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/gateway/tests/integration_system_scope_test.go
  tests/go.mod
  tests/go.sum
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/api_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/fixtures/application_template_queries.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2591 Fix app to app notifications e2e test when DEFAULT scenario is disabled
  chart/compass/values.yaml
  tests/director/tests/formation_api_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2593 Empty DB on local installation with DB Dump
  chart/localdb/charts/dbdump/templates/dbdump-job.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2589 Add imagePullSecret to Deployments when Portieris is enabled
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/charts/ns-adapter/templates/deployment.yaml
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/charts/ord-service/templates/deployment.yaml
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/deployment.yaml
  chart/compass/charts/system-broker/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/migrator-down-job.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/templates/update-expected-schema-version-job.yaml
  chart/compass/values.yaml
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2597 Fix name of imagePullSecrets.
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/connectivity-adapter/templates/deployment.yaml
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/oauth-clients-scopes-sync-job.yaml
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/charts/ns-adapter/templates/deployment.yaml
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/charts/ord-service/templates/deployment.yaml
  chart/compass/charts/pairing-adapter/templates/deployment.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/deployment.yaml
  chart/compass/charts/system-broker/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/migrator-down-job.yaml
  chart/compass/templates/migrator-job.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/templates/update-expected-schema-version-job.yaml
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon
