Repository kyma-incubator/compass, pull requests merged in 2022-01, with the labels that each got.

#2143 Improve external certs authentication handling for integration systems
  chart/compass/values.yaml
  components/connector/config/servers.go
  components/connector/go.mod
  components/connector/go.sum
  components/connector/internal/subject/subject.go
  components/connector/internal/subject/subject_test.go
  components/connector/pkg/oathkeeper/cert_header_parser.go
  components/connector/pkg/oathkeeper/cert_header_parser_test.go
  components/connector/pkg/oathkeeper/validation_hydrator_test.go
  components/director/cmd/director/main.go
  components/director/internal/authenticator/claims/automock/integration_system_service.go
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/authenticator/claims/validators_test.go
  components/director/internal/oathkeeper/model.go
  components/director/internal/tenantmapping/access_level_context_provider.go
  components/director/internal/tenantmapping/access_level_context_provider_test.go
  components/director/internal/tenantmapping/authenticator_context_provider.go
  components/director/internal/tenantmapping/cert_service_context_provider.go
  components/director/internal/tenantmapping/cert_service_context_provider_test.go
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/model.go
  components/director/internal/tenantmapping/system_auth_context_provider.go
  components/director/internal/tenantmapping/user_context_provider.go
  components/director/pkg/cert/certutils.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/runtime_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/tenant/tenant_setup.go
  tests/pkg/testctx/testctx.go
Labels: :wave: request review, size/XXL, lgtm

#2157 Adopt ORD changes
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/bundle/converter.go
  components/director/internal/domain/bundle/entity.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/ordvendor/converter.go
  components/director/internal/domain/ordvendor/entity.go
  components/director/internal/domain/ordvendor/fixtures_test.go
  components/director/internal/domain/ordvendor/repository.go
  components/director/internal/domain/ordvendor/repository_test.go
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/package/entity.go
  components/director/internal/domain/package/fixtures_test.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/product/converter.go
  components/director/internal/domain/product/entity.go
  components/director/internal/domain/product/fixtures_test.go
  components/director/internal/domain/product/repository.go
  components/director/internal/domain/product/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/application.go
  components/director/internal/model/bundle.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/package.go
  components/director/internal/model/product.go
  components/director/internal/model/vendor.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20211221215747_ord_documentation_labels.down.sql
  components/schema-migrator/migrations/director/20211221215747_ord_documentation_labels.up.sql
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/assertions/assertions.go
Labels: :wave: request review, size/XXL, lgtm

#2158 Rework tenant search
  chart/compass/values.yaml
  components/director/examples/query-tenants/query-tenants.graphql
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/runtime_context/repository_test.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/repo/conditions.go
  components/director/internal/repo/list_pageable.go
  components/director/internal/repo/list_pageable_test.go
  components/director/internal/repo/query_builder.go
  components/director/pkg/auth/automock/certificate_cache.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/tenants_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/fixtures.go
  tests/pkg/fixtures/tenant_queries.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, lgtm

#2160 Change label value used during self-registration
  chart/compass/values.yaml
  components/director/internal/domain/formation/frmtest/uuid.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/label/lbltest/uuid.go
  components/director/internal/domain/label/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/bundle_instance_auth_service.go
  components/director/internal/domain/runtime/automock/eventing_service.go
  components/director/internal/domain/runtime/automock/o_auth20_service.go
  components/director/internal/domain/runtime/automock/runtime_converter.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/automock/scenario_assignment_service.go
  components/director/internal/domain/runtime/automock/self_register_manager.go
  components/director/internal/domain/runtime/automock/system_auth_converter.go
  components/director/internal/domain/runtime/automock/system_auth_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/rtmtest/selfreg_manager.go
  components/director/internal/domain/runtime/rtmtest/uuid.go
  components/director/internal/domain/runtime/selfreg_manager.go
  components/director/internal/domain/runtime/selfreg_manager_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: bug, :wave: request review, size/L, lgtm

#2156 Enable e2e test on real environment - part 1
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/ord-service/role-binding.yaml
  chart/compass/values.yaml
  components/external-services-mock/internal/selfreg/handler.go
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connectivity-adapter/tests/connector_test.go
  tests/connectivity-adapter/tests/main_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
  tests/go.sum
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/config/director.go
  tests/pkg/gql/gqlclient.go
Labels: :wave: request review, :heavy_check_mark: Approved, size/L, lgtm

#2165 Add retry logic on label creation
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/subscriber.go
  components/director/internal/tenantfetchersvc/subscriber_test.go
Labels: :wave: request review, size/M, lgtm

#2167 Aggregate errors in ORD aggregator
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: :wave: request review, size/L, lgtm

#2168 Horizontal scalling in charts
  chart/compass/charts/connectivity-adapter/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/connectivity-adapter/values.yaml
  chart/compass/charts/connector/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/connector/values.yaml
  chart/compass/charts/director/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/gateway/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/gateway/values.yaml
  chart/compass/charts/ord-service/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/ord-service/values.yaml
  chart/compass/charts/system-broker/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/system-broker/values.yaml
  chart/compass/charts/tenant-fetcher/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/tenant-fetcher/values.yaml
Labels: :wave: request review, size/L, lgtm

#2170 Fix tenant fetcher to read different field from the event
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/event_page.go
  components/director/internal/tenantfetcher/event_page_test.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  tests/tenant-fetcher-job/tests/handler_test.go
Labels: :wave: request review, size/L, lgtm

#2164 [CMP-1303] Improve logging for GraphQL requests
  chart/compass/values.yaml
  components/connector/config/servers.go
  components/connector/go.mod
  components/connector/go.sum
  components/connector/internal/authentication/context_middleware.go
  components/director/cmd/director/main.go
  components/director/internal/authenticator/middleware.go
  components/director/pkg/log/gql_ops_logger.go
  components/director/pkg/log/gql_ops_logger_test.go
  components/director/pkg/log/mdc.go
  components/director/pkg/log/mdc_test.go
  components/director/pkg/log/request.go
  components/director/pkg/log/request_test.go
Labels: size/L, lgtm

#2172 [Hotfix]Fix tenant fetcher to read different field from the event
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/event_page.go
  components/director/internal/tenantfetcher/event_page_test.go
  components/director/internal/tenantfetcher/fixtures_test.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  tests/tenant-fetcher-job/tests/handler_test.go
Labels: :hammer: hotfix, size/L, lgtm

#2169 ORD Global Registry for global products / vendors
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/service.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/ordvendor/automock/vendor_repository.go
  components/director/internal/domain/ordvendor/converter.go
  components/director/internal/domain/ordvendor/entity.go
  components/director/internal/domain/ordvendor/fixtures_test.go
  components/director/internal/domain/ordvendor/repository.go
  components/director/internal/domain/ordvendor/repository_test.go
  components/director/internal/domain/ordvendor/service.go
  components/director/internal/domain/ordvendor/service_test.go
  components/director/internal/domain/product/automock/product_repository.go
  components/director/internal/domain/product/converter.go
  components/director/internal/domain/product/entity.go
  components/director/internal/domain/product/fixtures_test.go
  components/director/internal/domain/product/repository.go
  components/director/internal/domain/product/repository_test.go
  components/director/internal/domain/product/service.go
  components/director/internal/domain/product/service_test.go
  components/director/internal/model/product.go
  components/director/internal/model/product_test.go
  components/director/internal/model/vendor.go
  components/director/internal/model/vendor_test.go
  components/director/internal/open_resource_discovery/automock/api_service.go
  components/director/internal/open_resource_discovery/automock/event_service.go
  components/director/internal/open_resource_discovery/automock/global_product_service.go
  components/director/internal/open_resource_discovery/automock/global_registry_service.go
  components/director/internal/open_resource_discovery/automock/global_vendor_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/global_registry.go
  components/director/internal/open_resource_discovery/global_registry_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/repo/testdb/generic_repo_create_tests.go
  components/director/internal/repo/testdb/generic_repo_delete_tests.go
  components/director/internal/repo/testdb/generic_repo_get_tests.go
  components/director/internal/repo/testdb/generic_repo_list_tests.go
  components/director/internal/repo/testdb/generic_repo_update_tests.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/ord-aggregator/globalregistry/handler.go
  components/external-services-mock/internal/ord-aggregator/globalregistry/template.go
  components/external-services-mock/internal/ord-aggregator/handler.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20211221215747_ord_documentation_labels.down.sql
  components/schema-migrator/migrations/director/20220106093539_ord-global-registry.down.sql
  components/schema-migrator/migrations/director/20220106093539_ord-global-registry.up.sql
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/assertions/assertions.go
Labels: :wave: request review, size/XXL, lgtm

#2166 Vulnerabilities fix
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, size/M, lgtm

#2178 Update documentation for GCP PostgresSQL
  chart/compass/configure-managed-gcp-postgresql.md
Labels: size/S, lgtm

#2179 register/unregister runtime without tenant header
  chart/compass/values.yaml
  tests/director/tests/runtime_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/runtime_queries.go
Labels: :wave: request review, size/M, lgtm

#2181 Adapt local dev to work on M1 macs
  chart/compass/charts/operations-controller/values.yaml
  installation/cmd/run.sh
  installation/resources/kyma/installer-cr-kyma-minimal.yaml
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
Labels: :wave: request review, size/L, lgtm

#2182 [Hotfix] Fix ord tests
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
Labels: :heavy_check_mark: Approved, :hammer: hotfix, size/S, lgtm

#2183 Fix ord tests
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
Labels: :wave: request review, size/S, lgtm

#2185 Logout from IDP on compass console logout
  chart/compass/charts/cockpit/templates/configmap.yaml
  chart/compass/charts/cockpit/values.yaml
  chart/compass/values.yaml
Labels: size/XS, lgtm

#2188 [Hotfix] adapt ord views not to rely on global_subaccount_id label
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220119113231_ord_views_tenant_from_table_not_label.down.sql
  components/schema-migrator/migrations/director/20220119113231_ord_views_tenant_from_table_not_label.up.sql
  tests/ord-service/tests/subscription_flow_test.go
Labels: :heavy_check_mark: Approved, :hammer: hotfix, size/XL, lgtm

#2187 Adapt ord views not to rely on global_subaccount_id label
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220119113231_ord_views_tenant_from_table_not_label.down.sql
  components/schema-migrator/migrations/director/20220119113231_ord_views_tenant_from_table_not_label.up.sql
  tests/ord-service/tests/subscription_flow_test.go
Labels: :heavy_check_mark: Approved, size/XL, lgtm

#2162 OWNERS & CODEOWNERS cleanup
  CODEOWNERS
  chart/compass/OWNERS
Labels: size/M, lgtm

#2189 add helm post hook for ord-aggregator job
  chart/compass/templates/ord-aggregator-job.yaml
Labels: :heavy_check_mark: Approved, size/XS, lgtm

#2180 Improve CORS handling for compass-console
  chart/compass/charts/connectivity-adapter/templates/virtualservice.yaml
  chart/compass/charts/gateway/templates/virtualservice-authenticators.yaml
  chart/compass/charts/gateway/templates/virtualservice-external-mtls.yaml
  chart/compass/charts/gateway/templates/virtualservice-internal.yaml
  chart/compass/charts/gateway/templates/virtualservice-mtls.yaml
  chart/compass/charts/gateway/templates/virtualservice-secure.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/templates/tests/connector/virtualservice.yaml
  chart/compass/templates/tests/director/virtualservice.yaml
  chart/compass/templates/tests/external-services-mock/virtualservice.yaml
  chart/compass/templates/tests/gateway/virtualservice.yaml
  chart/compass/templates/tests/istio/virtualservice.yaml
  chart/compass/templates/tests/ord-aggregator/virtualservice.yaml
  chart/compass/templates/tests/ord-service/virtualservice.yaml
  chart/compass/templates/tests/pairing-adapter/virtualservice.yaml
  chart/compass/templates/tests/system-broker/virtualservice.yaml
Labels: :wave: request review, size/L, lgtm

#2174 Enable Auditlog tests on real env
  chart/compass/charts/external-services-mock/templates/auditlog-configmap.yaml
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/templates/tests/external-services-mock/auditlog-secret.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/values.yaml
  components/external-services-mock/go.sum
  components/external-services-mock/internal/auditlog/configurationchange/config.go
  components/external-services-mock/internal/auditlog/configurationchange/configuration_test.go
  components/external-services-mock/internal/auditlog/configurationchange/handler.go
  components/external-services-mock/internal/auditlog/configurationchange/service.go
  docs/compass/09-01-e2e-test-design.md
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/external-services-mock/tests/async_api_unpair_test.go
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/external-services-mock/tests/fetch_request_test.go
  tests/external-services-mock/tests/main_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/config/auditlog.go
  tests/pkg/fixtures/fixtures.go
Labels: :wave: request review, size/XL, lgtm

#2190 Bump compass console version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm
