Repository kyma-incubator/compass, pull requests merged in 2022-03, with the labels that each got.

#2212 Build docker images for multiple architectures
  chart/compass/values.yaml
  scripts/generic_make_go.mk
Labels: size/M, lgtm

#2225 Supportability tools on local installation
  installation/resources/kyma/installer-overrides-kyma-full-config-local.yaml
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
  installation/scripts/prom-mtls-patch.sh
Labels: :wave: request review, size/M, lgtm

#2227 Update cert-rotation-job environment in consumer-provider test
  chart/compass/templates/internal-communication-policies.yaml
  chart/compass/values.yaml
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/k8s/jobs.go
Labels: :wave: request review, size/M, lgtm

#2232 fix product and vendor assertions
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/assertions/assertions.go
Labels: size/M, lgtm

#2229 [HOTFIX] Update cert-rotation-job environment in consumer-provider test
  chart/compass/templates/internal-communication-policies.yaml
  chart/compass/values.yaml
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/k8s/jobs.go
Labels: :wave: request review, :hammer: hotfix, size/M, lgtm

#2233 [v1.27] Fix product and vendor assertions
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/assertions/assertions.go
Labels: :hammer: hotfix, size/M, lgtm

#2234 Use GetForUpdate for applications in ORD Aggregator
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/open_resource_discovery/automock/application_service.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/repo/get.go
  components/director/internal/repo/get_test.go
Labels: :wave: request review, size/L, lgtm

#2237 [v1.27] Use GetForUpdate for applications in ORD Aggregator
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/open_resource_discovery/automock/application_service.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/repo/get.go
  components/director/internal/repo/get_test.go
Labels: :hammer: hotfix, size/L, lgtm

#2198 Add support for x509 certificates when requesting an access token for communication with the audit log service
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/templates/tests/external-services-mock/auditlog-secret.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/values.yaml
  components/gateway/cmd/main.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/gateway/internal/auditlog/config.go
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/config/auditlog.go
  tests/pkg/token/token_utils.go
Labels: :wave: request review, size/L, lgtm

#2224 Change connector CA certificate
  chart/compass/values.yaml
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
Labels: :heavy_check_mark: Approved, size/S, lgtm

#2241 fix cloud sql proxy for ns-adapter e2e test
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
Labels: size/S, lgtm

#2244 fix indentation
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
Labels: size/XS, lgtm

#2231 Address ORD validation feedback
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/pkg/accessstrategy/access_strategy.go
  components/schema-migrator/migrations/director/20220301143225_ord_increase_short_description_length.down.sql
  components/schema-migrator/migrations/director/20220301143225_ord_increase_short_description_length.up.sql
Labels: :wave: request review, size/XXL, lgtm

#2242 Bump alpine images
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, size/M, lgtm

#2214 Support IDPs other that Dex
  README.md
  chart/compass/charts/cockpit/templates/configmap.yaml
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/cockpit/templates/jwks-job.yaml
  chart/compass/charts/cockpit/templates/secret.yaml
  chart/compass/charts/cockpit/values.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice.yaml
  chart/compass/values.yaml
  components/director/internal/oathkeeper/model.go
  docs/compass/03-01-security.md
  docs/compass/04-01-installation.md
  docs/connector/08-01-establish-secure-connection-with-compass.md
  installation/cmd/run.sh
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/kyma/installer-cr-kyma-minimal.yaml
  installation/resources/kyma/installer-cr-kyma.yaml
  installation/resources/kyma/installer-overrides-kyma-minimal-config-local.yaml
  installation/scripts/install-kyma.sh
  installation/scripts/is-kyma-installed.sh
  installation/scripts/prom-mtls-patch.sh
  tests/external-services-mock/tests/README.md
  tests/gateway/tests/README.md
Labels: :wave: request review, size/L, lgtm

#2248 Remove wrong check in jwks job
  chart/compass/templates/jwks-job.yaml
Labels: :wave: request review, size/XS, lgtm

#2209 Improve documentation for GCP PostgresSQL
  chart/compass/configure-managed-gcp-postgresql.md
Labels: size/XS, lgtm

#2240 Add certs in director run.sh
  components/director/run.sh
Labels: size/XS, lgtm

#2235 clean dirty flag before retrying migrations
  chart/compass/values.yaml
  components/schema-migrator/run.sh
Labels: :wave: request review, size/S, lgtm

#2249 Fix auditlog and ns-adapter e2e-tests
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/values.yaml
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/go.mod
  tests/pkg/config/auditlog.go
Labels: size/M, lgtm

#2251 Fix e2e tests
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/values.yaml
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/go.mod
  tests/pkg/config/auditlog.go
  tests/pkg/token/token_utils.go
Labels: size/M, lgtm

#2261 Fix external-svc-mock e2e tests
  chart/compass/values.yaml
  tests/pkg/token/token_utils.go
Labels: size/S, lgtm

#2262 Code Owners update respecting each team
  CODEOWNERS
  OWNERS_ALIASES
  chart/compass/.helmignore
  chart/compass/OWNERS
  chart/compass/charts/connectivity-adapter/OWNERS
  chart/compass/charts/connector/OWNERS
  chart/compass/charts/gateway/OWNERS
  chart/compass/charts/ns-adapter/OWNERS
  chart/compass/charts/operations-controller/OWNERS
  chart/compass/charts/ord-service/OWNERS
  chart/compass/charts/pairing-adapter/OWNERS
  chart/compass/charts/tenant-fetcher/OWNERS
  chart/compass/templates/filters/OWNERS
  components/connectivity-adapter/OWNERS
  components/connector/OWNERS
  components/director/cmd/director/OWNERS
  components/director/cmd/ns-adapter/OWNERS
  components/director/cmd/ordaggregator/OWNERS
  components/director/cmd/scopessynchronizer/OWNERS
  components/director/cmd/systemfetcher/OWNERS
  components/director/cmd/tenantfetcher-job/OWNERS
  components/director/cmd/tenantfetcher-svc/OWNERS
  components/director/cmd/tenantloader/OWNERS
  components/director/internal/authnmappinghandler/OWNERS
  components/director/internal/info/OWNERS
  components/director/internal/nsadapter/OWNERS
  components/director/internal/oathkeeper/OWNERS
  components/director/internal/open_resource_discovery/OWNERS
  components/director/internal/runtimemapping/OWNERS
  components/director/internal/scopes_sync/OWNERS
  components/director/internal/systemfetcher/OWNERS
  components/director/internal/tenantfetcher/OWNERS
  components/director/internal/tenantfetchersvc/OWNERS
  components/director/internal/tenantmapping/OWNERS
  components/director/pkg/accessstrategy/OWNERS
  components/director/pkg/authenticator/OWNERS
  components/director/pkg/operation/OWNERS
  components/director/pkg/scenario/OWNERS
  components/external-services-mock/OWNERS
  components/gateway/OWNERS
  components/operations-controller/OWNERS
  components/pairing-adapter/OWNERS
  components/schema-migrator/OWNERS
  installation/cmd/OWNERS
  installation/scripts/OWNERS
  tests/connectivity-adapter/OWNERS
  tests/connector/OWNERS
  tests/gateway/OWNERS
  tests/istio/OWNERS
  tests/ns-adapter/OWNERS
  tests/ord-aggregator/OWNERS
  tests/ord-service/OWNERS
  tests/pairing-adapter/OWNERS
  tests/system-fetcher/OWNERS
  tests/tenant-fetcher-job/OWNERS
  tests/tenant-fetcher/OWNERS
Labels: size/L, lgtm

#2271 Update OWNERS
  OWNERS
  OWNERS_ALIASES
  chart/compass/charts/cockpit/OWNERS
  chart/compass/charts/connectivity-adapter/OWNERS
  chart/compass/charts/connector/OWNERS
  chart/compass/charts/gateway/OWNERS
  chart/compass/charts/ns-adapter/OWNERS
  chart/compass/charts/operations-controller/OWNERS
  chart/compass/charts/ord-service/OWNERS
  chart/compass/charts/pairing-adapter/OWNERS
  chart/compass/charts/tenant-fetcher/OWNERS
  chart/compass/templates/filters/OWNERS
  components/connectivity-adapter/OWNERS
  components/connector/OWNERS
  components/director/cmd/director/OWNERS
  components/director/cmd/ns-adapter/OWNERS
  components/director/cmd/ordaggregator/OWNERS
  components/director/cmd/scopessynchronizer/OWNERS
  components/director/cmd/systemfetcher/OWNERS
  components/director/cmd/tenantfetcher-job/OWNERS
  components/director/cmd/tenantfetcher-svc/OWNERS
  components/director/cmd/tenantloader/OWNERS
  components/director/internal/authnmappinghandler/OWNERS
  components/director/internal/info/OWNERS
  components/director/internal/nsadapter/OWNERS
  components/director/internal/oathkeeper/OWNERS
  components/director/internal/open_resource_discovery/OWNERS
  components/director/internal/runtimemapping/OWNERS
  components/director/internal/scopes_sync/OWNERS
  components/director/internal/systemfetcher/OWNERS
  components/director/internal/tenantfetcher/OWNERS
  components/director/internal/tenantfetchersvc/OWNERS
  components/director/internal/tenantmapping/OWNERS
  components/director/pkg/accessstrategy/OWNERS
  components/director/pkg/authenticator/OWNERS
  components/director/pkg/operation/OWNERS
  components/director/pkg/scenario/OWNERS
  components/external-services-mock/OWNERS
  components/gateway/OWNERS
  components/operations-controller/OWNERS
  components/pairing-adapter/OWNERS
  components/schema-migrator/OWNERS
  installation/cmd/OWNERS
  installation/scripts/OWNERS
  tests/connectivity-adapter/OWNERS
  tests/connector/OWNERS
  tests/gateway/OWNERS
  tests/istio/OWNERS
  tests/ns-adapter/OWNERS
  tests/ord-aggregator/OWNERS
  tests/ord-service/OWNERS
  tests/pairing-adapter/OWNERS
  tests/system-fetcher/OWNERS
  tests/tenant-fetcher-job/OWNERS
  tests/tenant-fetcher/OWNERS
Labels: size/L

#2273 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/S, approved, lgtm

#2277 Fix OWNERS label
  chart/compass/charts/connectivity-adapter/OWNERS
  chart/compass/charts/connector/OWNERS
  chart/compass/charts/gateway/OWNERS
  chart/compass/charts/ns-adapter/OWNERS
  chart/compass/charts/operations-controller/OWNERS
  chart/compass/charts/ord-service/OWNERS
  chart/compass/charts/pairing-adapter/OWNERS
  chart/compass/charts/tenant-fetcher/OWNERS
  chart/compass/templates/filters/OWNERS
  components/connectivity-adapter/OWNERS
  components/connector/OWNERS
  components/director/cmd/ns-adapter/OWNERS
  components/director/cmd/ordaggregator/OWNERS
  components/director/cmd/scopessynchronizer/OWNERS
  components/director/cmd/systemfetcher/OWNERS
  components/director/cmd/tenantfetcher-job/OWNERS
  components/director/cmd/tenantfetcher-svc/OWNERS
  components/director/internal/authnmappinghandler/OWNERS
  components/director/internal/info/OWNERS
  components/director/internal/nsadapter/OWNERS
  components/director/internal/oathkeeper/OWNERS
  components/director/internal/open_resource_discovery/OWNERS
  components/director/internal/runtimemapping/OWNERS
  components/director/internal/scopes_sync/OWNERS
  components/director/internal/systemfetcher/OWNERS
  components/director/internal/tenantfetcher/OWNERS
  components/director/internal/tenantfetchersvc/OWNERS
  components/director/internal/tenantmapping/OWNERS
  components/director/pkg/accessstrategy/OWNERS
  components/director/pkg/authenticator/OWNERS
  components/director/pkg/operation/OWNERS
  components/director/pkg/scenario/OWNERS
  components/gateway/OWNERS
  components/operations-controller/OWNERS
  components/pairing-adapter/OWNERS
  installation/cmd/OWNERS
  installation/scripts/OWNERS
  tests/connectivity-adapter/OWNERS
  tests/connector/OWNERS
  tests/gateway/OWNERS
  tests/istio/OWNERS
  tests/ns-adapter/OWNERS
  tests/ord-aggregator/OWNERS
  tests/ord-service/OWNERS
  tests/pairing-adapter/OWNERS
  tests/system-fetcher/OWNERS
  tests/tenant-fetcher-job/OWNERS
  tests/tenant-fetcher/OWNERS
Labels: size/M, approved

#2259 Audit log operations in tenant fetcher deployment
  chart/compass/charts/director/config.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/rbac.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/tenantfetcher-svc/README.md
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/subscription_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/subscription/automock/label_service.go
  components/director/internal/subscription/automock/runtime_service.go
  components/director/internal/subscription/automock/tenant_service.go
  components/director/internal/subscription/automock/uid_service.go
  components/director/internal/subscription/service.go
  components/director/internal/subscription/service_test.go
  components/director/internal/tenantfetchersvc/automock/director_graph_ql_client.go
  components/director/internal/tenantfetchersvc/automock/tenant_converter.go
  components/director/internal/tenantfetchersvc/automock/tenant_provisioner.go
  components/director/internal/tenantfetchersvc/automock/tenant_service.go
  components/director/internal/tenantfetchersvc/automock/tenant_subscriber.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/director/internal/tenantfetchersvc/subscriber.go
  components/director/internal/tenantfetchersvc/subscriber_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql_client/director_client.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :dragon: team-dragon

#2267 Expose ORD Version Through Well-Known Endpoint
  chart/compass/values.yaml
  components/director/internal/info/handler.go
  components/director/internal/open_resource_discovery/version.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2258 ORD Aggregator Parallel Fetching
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2263 Allow self-registration from different regions
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/charts/external-services-mock/templates/region-instances-credentials.yaml
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/bundle_instance_auth_service.go
  components/director/internal/domain/runtime/automock/entity_converter.go
  components/director/internal/domain/runtime/automock/eventing_service.go
  components/director/internal/domain/runtime/automock/external_svc_caller.go
  components/director/internal/domain/runtime/automock/external_svc_caller_provider.go
  components/director/internal/domain/runtime/automock/o_auth20_service.go
  components/director/internal/domain/runtime/automock/runtime_converter.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/automock/scenario_assignment_service.go
  components/director/internal/domain/runtime/automock/self_register_manager.go
  components/director/internal/domain/runtime/automock/system_auth_converter.go
  components/director/internal/domain/runtime/automock/system_auth_service.go
  components/director/internal/domain/runtime/caller_provider.go
  components/director/internal/domain/runtime/caller_provider_test.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/rtmtest/caller.go
  components/director/internal/domain/runtime/rtmtest/selfreg_manager.go
  components/director/internal/domain/runtime/selfreg_config.go
  components/director/internal/domain/runtime/selfreg_config_test.go
  components/director/internal/domain/runtime/selfreg_manager.go
  components/director/internal/domain/runtime/selfreg_manager_test.go
  components/director/internal/securehttp/caller.go
  components/director/pkg/auth/types.go
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#2283 Get region label value from environment
  chart/compass/charts/external-services-mock/templates/region-instances-credentials.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
Labels: :wave: request review, size/S, approved, lgtm

#2284 Make region label value conigurable
  chart/compass/charts/external-services-mock/templates/region-instances-credentials.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
Labels: size/S, approved, lgtm

#2289 fix region Label
  chart/compass/values.yaml
  tests/director/tests/runtime_api_test.go
Labels: size/XS, approved, lgtm

#2290 fix region Label
  chart/compass/values.yaml
  tests/director/tests/runtime_api_test.go
Labels: size/XS, approved, lgtm

#2281 process scopes in deterministic way
  chart/compass/values.yaml
  components/director/internal/tenantmapping/handler.go
  components/director/internal/tenantmapping/handler_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#2285 Use latest console version.
  chart/compass/values.yaml
Labels: kind/bug, :wave: request review, size/XS, approved, lgtm

#2278 Update template for example system
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/service.yaml
  chart/compass/charts/external-services-mock/templates/virtual-service.yaml
  chart/compass/charts/gateway/templates/deployment.yaml
  chart/compass/charts/gateway/templates/gateway.yaml
  chart/compass/templates/internal-communication-policies.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/ord-aggregator/globalregistry/handler.go
  components/external-services-mock/internal/ord-aggregator/globalregistry/template.go
  installation/cmd/run.sh
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2247 add ns-adapter documentation
  components/director/cmd/ns-adapter/README.md
  components/director/run.sh
Labels: area/documentation, :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2282 Add logs from jobs started from e2e tests
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher-job/tenant-fetcher-job-test.yaml
  chart/compass/values.yaml
  tests/pkg/certs/certprovider/ext_cert_provider.go
  tests/pkg/k8s/jobs.go
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
  tests/tenant-fetcher-job/tests/handler_test.go
  tests/tenant-fetcher-job/tests/main_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, :dragon: team-dragon

#2292 Install ns adapter as helm post hook
  chart/compass/charts/ns-adapter/templates/deployment.yaml
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#2295 fixed path for importing db schema
  components/director/README.md
Labels: area/documentation, size/XS, approved, lgtm
