Repository kyma-incubator/compass, pull requests merged in 2022-02, with the labels that each got.

#2191 Add support for x509 certificates when requesting an access token
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-job/main.go
  components/director/internal/model/vendor_test.go
  components/director/internal/tenantfetcher/client.go
  components/director/internal/tenantfetcher/client_test.go
  components/director/internal/tenantfetcher/export_test.go
  components/director/internal/util/base64.go
  components/director/internal/util/base64_test.go
  components/director/pkg/cert/certutils.go
  components/director/pkg/cert/certutils_test.go
  components/director/pkg/certloader/loader.go
  components/director/pkg/oauth/config.go
Labels: size/L, lgtm

#2195 [Hotfix] fix tenant conversions
  chart/compass/values.yaml
  components/director/internal/tenantmapping/system_auth_context_provider.go
Labels: :heavy_check_mark: Approved, size/XS, lgtm

#2194 Fix tenant conversions
  chart/compass/values.yaml
  components/director/internal/tenantmapping/system_auth_context_provider.go
Labels: :heavy_check_mark: Approved, size/XS, lgtm

#2196 Enhance error messages
  chart/compass/values.yaml
  components/director/internal/domain/runtime/selfreg_manager.go
  components/director/internal/error_presenter/presenter.go
  components/director/internal/error_presenter/presenter_test.go
  components/director/internal/tenantfetcher/event_page.go
  components/director/pkg/apperrors/consts.go
  components/director/pkg/apperrors/errors.go
  components/director/pkg/apperrors/errortype_string.go
Labels: :heavy_check_mark: Approved, size/M, lgtm

#2192 Prevent One-Time Token fetching from being audit logged
  chart/compass/charts/connector/templates/deployment.yaml
  chart/compass/charts/director/templates/virtual-service-internal.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/values.yaml
  components/connector/go.mod
  components/connector/go.sum
  components/connector/internal/api/certificate_resolver.go
  components/connector/internal/api/certificate_resolver_test.go
  components/connector/internal/authentication/context.go
  components/connector/internal/tokens/automock/service.go
Labels: :wave: request review, size/M, lgtm

#2203 Allow null for isDefaultBundle value
  chart/compass/values.yaml
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/bundlereferences/converter.go
  components/director/internal/domain/bundlereferences/entity.go
  components/director/internal/domain/bundlereferences/fixtures_test.go
  components/director/internal/domain/eventdef/service.go
  components/director/internal/domain/eventdef/service_test.go
  components/director/internal/model/bundle_references.go
Labels: :wave: request review, size/M, lgtm

#2200 Call global registry in ORD aggregator tests
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-aggregator/tests/ord_document.go
  tests/ord-aggregator/tests/registry_client.go
Labels: :wave: request review, size/L, lgtm

#2204 Call global registry in ORD aggregator tests
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-aggregator/tests/ord_document.go
  tests/ord-aggregator/tests/registry_client.go
Labels: :wave: request review, size/L, lgtm

#2193 Documentation for rate-limiting.
  docs/compass/10-01-rate-limiting.md
  docs/compass/assets/gateway-rate-limiting.svg
Labels: :wave: request review, size/M, lgtm

#2202 Final adaptations for System Fetcher mTLS
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
  components/director/internal/systemfetcher/oauth_client.go
  components/director/pkg/oauth/config.go
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
Labels: :wave: request review, size/M, lgtm

#2217 Ord aggregator test fix
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: size/S, lgtm

#2219 selfRegister cleanup fix
  chart/compass/values.yaml
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/selfreg_manager.go
Labels: :wave: request review, size/M, lgtm

#2153 Enable e2e tests on real environment - part 2
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/charts/external-services-mock/templates/basic-credentials-secret.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/charts/pairing-adapter/values.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/ord-service/role-binding.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/handler.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/cert/handler.go
  components/external-services-mock/internal/oauth/token_handler.go
  components/external-services-mock/internal/oauth/token_handler_test.go
  components/external-services-mock/internal/provider/handler.go
  components/external-services-mock/internal/provider/handler_test.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  components/operations-controller/go.sum
  installation/cmd/run.sh
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
  tests/director/tests/runtime_api_test.go
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/certs/certs.go
  tests/pkg/config/director.go
  tests/pkg/fixtures/fixtures.go
  tests/pkg/k8s/jobs.go
  tests/pkg/tenantfetcher/tenant_helper.go
  tests/pkg/token/token_utils.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :heavy_check_mark: Approved, size/XXL, lgtm

#2201 Use client certificate instead of client secret for the certificate rotation job
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/charts/external-services-mock/values.yaml
  chart/compass/values.yaml
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
Labels: :wave: request review, size/M, lgtm, to be released :rocket:

#2218 ORD Aggregator deadlock handling
  chart/compass/values.yaml
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/bundle/automock/bundle_repository.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/bundle/service.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/ordvendor/repository.go
  components/director/internal/domain/ordvendor/repository_test.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/domain/product/repository.go
  components/director/internal/domain/product/repository_test.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tombstone/repository.go
  components/director/internal/domain/tombstone/repository_test.go
  components/director/internal/domain/webhook/automock/webhook_repository.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/open_resource_discovery/automock/bundle_service.go
  components/director/internal/open_resource_discovery/automock/tenant_service.go
  components/director/internal/open_resource_discovery/automock/webhook_service.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/repo/conditions.go
  components/director/internal/repo/get.go
  components/director/internal/repo/list.go
  components/director/internal/repo/list_pageable.go
  components/director/internal/repo/list_pageable_test.go
  components/director/internal/repo/list_test.go
  components/director/internal/repo/query_builder.go
Labels: :wave: request review, size/XL, lgtm, to be released :rocket:

#2221 Add application.auths:read to integration systems scopes
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  tests/director/tests/sensitive_data_strip_test.go
  tests/pkg/token/token_utils.go
Labels: :wave: request review, size/S, lgtm, to be released :rocket:

#2213 Vulnerabilities fix
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, lgtm, to be released :rocket:

#2205 Environment changes for tenant fetcher x509 support
  chart/compass/templates/tenant-fetcher-job.yaml
  chart/compass/templates/tenant-fetcher-secret.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/client.go
  components/director/internal/tenantfetcher/client_test.go
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-gke-integration.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
Labels: :wave: request review, size/M, lgtm, to be released :rocket:

#2223 Add SupportInfo on ORD Packages
  chart/compass/values.yaml
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/package/entity.go
  components/director/internal/domain/package/fixtures_test.go
  components/director/internal/domain/package/repository.go
  components/director/internal/domain/package/repository_test.go
  components/director/internal/model/package.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/schema-migrator/migrations/director/20220224153857_add-support-info-to-packages.down.sql
  components/schema-migrator/migrations/director/20220224153857_add-support-info-to-packages.up.sql
Labels: :wave: request review, :heavy_check_mark: Approved, size/L, lgtm
