Repository kyma-incubator/compass, pull requests merged in 2022-11, with the labels that each got.

#2719 [HOTFIX] Adjust API validation rules
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2717 Introduce skip pattern in the formation mapping tests
  chart/compass/values.yaml
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/formation_mapping_api_test.go
Labels: :wave: request review, size/S, approved, lgtm

#2721 Fix formation mapping E2E tests
  chart/compass/values.yaml
  tests/director/tests/formation_mapping_api_test.go
  tests/pkg/fixtures/application_template_requests.go
Labels: :wave: request review, size/M, approved, lgtm

#2713 Support callback asynchronism for formation notification webhooks
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/graphql/webhook_validation_test.go
  components/director/pkg/webhook/types.go
  components/director/pkg/webhook_client/client.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.sum
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2716 Support multiple runtime types for Formation Templates
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/entity.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/internal/domain/label/query.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/model/formation_template.go
  components/director/pkg/graphql/formation_template_validation.go
  components/director/pkg/graphql/formation_template_validation_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20221027114250_support-multiple-runtime-types.down.sql
  components/schema-migrator/migrations/director/20221027114250_support-multiple-runtime-types.up.sql
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2718 Adjust API validation rules
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2723 Send Slack notification when the Aggregation of ORD documents fails
  chart/compass/templates/additional-prometheus-rules.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/go.mod
  components/director/internal/metrics/const.go
  components/director/internal/metrics/pusher.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, :dragon: team-dragon

#2720 Change the returned configuration value
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/converter.go
  tests/director/tests/formation_api_test.go
Labels: size/M, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#2714 Bump Dependencies of Operation Controller
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/Makefile
  components/operations-controller/config/crd/bases/operations.compass_operations.yaml
  components/operations-controller/controllers/assertions_test.go
  components/operations-controller/controllers/logger_test.go
  components/operations-controller/controllers/operation_controller_integration_test.go
  components/operations-controller/controllers/operation_controller_test.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  scripts/generic_make_go.mk
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/formation_template_fixtures.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2709 Decouple and parallelize ORD specification fetching
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/spec/service.go
  components/director/internal/domain/spec/service_test.go
  components/director/internal/open_resource_discovery/automock/fetch_request_service.go
  components/director/internal/open_resource_discovery/automock/spec_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#2729 Implement ord webhook partial processing
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2731 [HOTFIX] Implement ord webhook partial processing
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2733 Handle ord aggregator failure
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2736 Bump Go version to 1.19 of main components
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2739 Fix webhook validation
  chart/compass/values.yaml
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/formation_configuration_change.go
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, size/M, approved, lgtm

#2735 user_context header encode/decode processing
  chart/compass/values.yaml
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2711 Remove/Replace usage of deprecated go library
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
  components/director/hack/plugins/descriptionsdecorator/plugin.go
  components/director/hack/plugins/descriptionsdecorator/plugin_test.go
  components/director/hack/plugins/scopesdecorator/plugin_test.go
  components/director/internal/authenticator/jwks_fetch.go
  components/director/internal/authenticator/middleware_test.go
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/handler_test.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/onetimetoken/service_test.go
  components/director/internal/externaltenant/mapping.go
  components/director/internal/nsadapter/handler/exposed_systems_handler_test.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/packagetobundles/handler.go
  components/director/internal/securehttp/caller_test.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/systemfetcher/loader_test.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/resync/client.go
  components/director/internal/tenantfetchersvc/resync/config.go
  components/director/pkg/auth/mtls_token_provider.go
  components/director/pkg/auth/mtls_token_provider_test.go
  components/director/pkg/auth/service_account_token_provider.go
  components/director/pkg/auth/service_account_token_provider_test.go
  components/director/pkg/auth/token_provider_test.go
  components/director/pkg/config/common.go
  components/director/pkg/config/provider.go
  components/director/pkg/handler/timeout_handler_test.go
  components/director/pkg/http/error_transport.go
  components/director/pkg/http/error_transport_test.go
  components/director/pkg/http/request_test.go
  components/director/pkg/http/service_acccount_token_transport.go
  components/director/pkg/http/service_account_token_transport_test.go
  components/director/pkg/operation/update_operation_handler.go
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, :dragon: team-dragon

#2746 Do not require selfReg label of the app template on the formation notification status API
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/schema-migrator/migrations/director/20221117122326_adjust-foreign-keys.down.sql
  components/schema-migrator/migrations/director/20221117122326_adjust-foreign-keys.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2740 Bump vulnerable dependencies
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2750 Revert GQLGen library to 0.11.3 version
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2748 Enable different applicationType and appTypeValue in labels for Other…
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/selfregmanager/selfreg_manager.go
Labels: :wave: request review, size/M, approved, lgtm, to be released :rocket:

#2743 Improve ord data processing
  chart/compass/values.yaml
  components/director/internal/domain/spec/automock/spec_repository.go
  components/director/internal/domain/spec/repository.go
  components/director/internal/domain/spec/repository_test.go
  components/director/internal/domain/spec/service.go
  components/director/internal/domain/spec/service_test.go
  components/director/internal/open_resource_discovery/automock/spec_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/repo/testdb/generic_repo_list_tests.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :eagle: team-falcon

#2756 [HOTFIX] introduce indeces bundles ref
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20221105110000_introduce_bundles_refs_indeces.down.sql
  components/schema-migrator/migrations/director/20221105110000_introduce_bundles_refs_indeces.up.sql
Labels: size/S, approved, lgtm

#2754 Introduce indices for bundle references table
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20221105110000_introduce_bundles_refs_indeces.down.sql
  components/schema-migrator/migrations/director/20221105110000_introduce_bundles_refs_indeces.up.sql
Labels: size/S, approved, lgtm

#2758 Use In subquery for bundle refs
  chart/compass/values.yaml
  components/director/internal/domain/bundlereferences/repository.go
  components/director/internal/domain/bundlereferences/repository_test.go
Labels: size/M, approved, lgtm

#2761 [HOTFIX] Fix use in subquery for bundles refs
  chart/compass/values.yaml
  components/director/internal/domain/bundlereferences/repository.go
  components/director/internal/domain/bundlereferences/repository_test.go
Labels: size/M, approved, lgtm

#2727 Change the returned configuration value from "" to null
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/converter.go
  tests/director/tests/formation_api_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2765 Additional Unit test for missed branch
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/converter_test.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/subscription/fixtures_test.go
  components/director/pkg/graphql/app_template_validation_test.go
  installation/scripts/prow/compass-smoke-test.sh
Labels: :wave: request review, approved, size/L, lgtm

#2762 Remove runtime type leftovers
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/examples/create-formation-template/create-formation-template.graphql
  components/director/examples/delete-formation-template/delete-formation-template.graphql
  components/director/examples/query-formation-template/query-formation-template.graphql
  components/director/examples/query-formation-templates/query-formation-templates.graphql
  components/director/examples/update-formation-template/update-formation-template.graphql
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/model/formation_template.go
  components/director/pkg/graphql/formation_template_validation.go
  components/director/pkg/graphql/formation_template_validation_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/formation_template_fixtures.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2757 Validate Application Template name based on provider
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  tests/director/tests/application_templates_api_test.go
  tests/gateway/tests/integration_system_scope_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2763 Allow global calls (without tenant) when calling as a cert from subject mapping
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/selfregmanager/selfreg_manager.go
  components/director/internal/selfregmanager/selfreg_manager_test.go
  components/hydrator/internal/subject/cert_subject.go
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/access_level_context_provider_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/handler_test.go
  components/hydrator/pkg/oathkeeper/model.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/technical_client_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2755 Expose aggregated formation status
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/examples/query-formation/query-formation.graphql
  components/director/examples/query-formations/query-formations.graphql
  components/director/examples/query-tenants/query-tenants.graphql
  components/director/internal/dataloaders/formationStatusLoaders.go
  components/director/internal/dataloaders/formationstatusloader_gen.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_repository.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/formation.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/fomation_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#2770 Add namespace to application object
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/model/application.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/webhook_client/client_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/20221128160001_introduce-application-namespace.down.sql
  components/schema-migrator/migrations/director/20221128160001_introduce-application-namespace.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2744 Cleanup image cache in update compass script
  installation/scripts/prow/provision.sh
  installation/scripts/prow/update-compass.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2766 Check for update operation status
  chart/compass/values.yaml
  components/operations-controller/api/v1alpha1/operation_types.go
  components/operations-controller/controllers/operation_controller.go
  components/operations-controller/controllers/operation_controller_test.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
Labels: :wave: request review, size/M, lgtm, :eagle: team-falcon
