Repository kyma-incubator/compass, pull requests merged in 2022-04, with the labels that each got.

#2296 Change token issuing logic
  chart/compass/values.yaml
  components/external-services-mock/internal/oauth/token_handler.go
  components/external-services-mock/internal/oauth/token_handler_test.go
Labels: kind/bug, size/M, approved, lgtm

#2297 Update dependencies
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connectivity-adapter/Makefile
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/external-services-mock/Makefile
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/Dockerfile
  components/gateway/Makefile
  components/gateway/go.mod
  components/gateway/go.sum
  components/pairing-adapter/Dockerfile
  components/pairing-adapter/Makefile
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  components/system-broker/Makefile
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/Dockerfile
  tests/Makefile
  tests/go.mod
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2301 Increase console version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm

#2236 Add coverage to unit tests
  .gitignore
  components/director/Makefile
  scripts/generic_make_go.mk
Labels: :wave: request review, size/S, approved, lgtm

#2304 [HOTFIX] Self registration secret mount as volume
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/domain/runtime/selfreg_config.go
  components/director/internal/domain/runtime/selfreg_config_test.go
  components/director/internal/domain/runtime/selfreg_manager_test.go
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_MTLS_Missing_Cert_Key.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_MTLS_Success.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_StandardMode_Missing_ClientID_URL.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_StandardMode_Missing_ClientSecret.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_StandardMode_Success.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegisterManager_PrepareRuntimeForSelfRegistration.golden
  components/director/run.sh
Labels: :wave: request review, approved, size/L, lgtm

#2303 Self registration secret mount as volume
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/domain/runtime/selfreg_config.go
  components/director/internal/domain/runtime/selfreg_config_test.go
  components/director/internal/domain/runtime/selfreg_manager_test.go
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_MTLS_Missing_Cert_Key.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_MTLS_Success.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_StandardMode_Missing_ClientID_URL.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_StandardMode_Missing_ClientSecret.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegConfig_MapInstanceConfigs_StandardMode_Success.golden
  components/director/internal/domain/runtime/testdata/TestSelfRegisterManager_PrepareRuntimeForSelfRegistration.golden
  components/director/run.sh
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2293 E2e test on dev main
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2257 Update local component documentation
  components/connectivity-adapter/README.md
  components/connector/README.md
  components/director/README.md
  components/director/cmd/ordaggregator/README.md
  components/director/cmd/scopessynchronizer/README.md
  components/director/cmd/systemfetcher/README.md
  components/director/cmd/tenantfetcher-job/README.md
  components/director/cmd/tenantfetcher-svc/README.md
  components/director/internal/tenantfetcher/README.md
  components/external-services-mock/README.md
  components/system-broker/README.md
Labels: area/documentation, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2243 Improve documentation on security topics
  docs/compass/03-01-security.md
  docs/compass/03-02-filters.md
  docs/compass/03-04-labels.md
  docs/compass/assets/internal-auth.svg
Labels: area/documentation, :wave: request review, approved, size/L, lgtm

#2256 Update chart documentation
  chart/compass/README.md
Labels: area/documentation, size/M, approved, lgtm

#2254 Update installation document
  docs/compass/04-01-installation.md
Labels: area/documentation, approved, size/L, lgtm

#2253 Automatic Scenario Assignments documentation updates
  docs/compass/03-03-automatic-scenario-assignment.md
  docs/compass/assets/automatic-scenario-assign.svg
Labels: area/documentation, size/M, approved, lgtm

#2255 Update Components documentation
  docs/README.md
  docs/compass/02-01-components.md
  docs/compass/assets/components.svg
  docs/connector/08-01-establish-secure-connection-with-compass.md
  docs/connector/08-02-maintain-secure-connection-with-compass.md
  docs/director/03-tenancy.md
  docs/discovery-components/01-system-fetcher-component.md
  docs/discovery-components/02-application-resource-discovery-components.md
  docs/integration-system/integration-systems.md
  docs/operations-controller/01-async-operations.md
  docs/operations-controller/02-application-deletion-flow.md
  docs/operations-controller/assets/async-application-operation-loop.png
  docs/operations-controller/assets/async-application-operation.png
  docs/system-broker/flows.md
Labels: area/documentation, approved, size/L, lgtm

#2252 E2E tests documentation improvements
  .gitignore
  tests/README.md
  tests/external-services-mock/tests/README.md
  tests/gateway/tests/README.md
Labels: area/documentation, approved, size/L, lgtm, :t-rex: team-raptor

#2312 Add retry logic when deleting application in e2e tests
  chart/compass/values.yaml
  tests/pkg/fixtures/application_queries.go
Labels: :wave: request review, size/S, approved, lgtm

#2315 Fix sporadically failing system fetcher test
  chart/compass/values.yaml
  components/director/internal/systemfetcher/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2313 Remove GKE Integration tests
  installation/resources/installer-config-gke-integration.yaml.tpl
Labels: :wave: request review, approved, size/L, lgtm

#2294 Introduce Tenant on-demand API
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-internal.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/rbac.yaml
  chart/compass/templates/tenant-fetcher-secret.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/tenant_fetcher.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_test.go
  installation/resources/installer-config-local.yaml.tpl
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2319 Fix invalid cast in ns-adapter tests
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  tests/ns-adapter/tests/main_test.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon, :dragon: team-dragon

#2321 Update console version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2323 Create tenant fetcher secret only for local setup
  chart/compass/templates/tenant-fetcher-secret.yaml
  chart/compass/values.yaml
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  installation/resources/installer-config-local.yaml.tpl
Labels: size/M, approved, lgtm

#2317 allow string pointers as well as strings
  chart/compass/values.yaml
  components/director/pkg/scalar/scalar.go
Labels: :wave: request review, size/XS, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#2309 Enable Assigning a single Runtime to formation in the new Formation APIs
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/scenario_assignment_engine.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/engine.go
  components/director/internal/domain/scenarioassignment/engine_test.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#2320 Create system-fetcher e2e test for systems spanning multiple customer GA tenants
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/systemfetcher/handler.go
  tests/pkg/tenant/tenant_setup.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :eagle: team-falcon

#2307 Use tenant on demand API in Director
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/automock/tenant_fetcher.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/tenant/automock/client.go
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/provider/handler.go
  installation/resources/installer-config-local.yaml.tpl
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :dragon: team-dragon

#2327 Fix TF endpoint in chart
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
Labels: :wave: request review, approved, lgtm

#2311 Metrics for GraphQL endpoints
  chart/compass/charts/director/templates/dashboard-configmap.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/service-monitor.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/metrics/collector.go
  components/director/internal/metrics/request_interceptor.go
  components/hydrator/go.sum
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#2329 Test ns seecret
  chart/compass/templates/ns-adapter-secret.yaml
Labels: size/XS, approved, lgtm

#2331 Update formations owners
  components/director/internal/domain/formation/OWNERS
Labels: size/XS, approved, lgtm

#2326 Create test definitions conditionally
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher-job/tenant-fetcher-job-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2333 change godoc
  chart/compass/values.yaml
  components/director/internal/model/application.go
Labels: size/XS, approved, lgtm
