Repository kyma-incubator/compass, pull requests merged in 2022-05, with the labels that each got.

#2330 Stop storing subaccounts lazily
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/tenant_fetcher.go
  components/director/internal/domain/formation/automock/tenant_service.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/tenant_fetcher.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2337 Remove application:write scope from config-local.yaml file
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
Labels: size/XS, approved, lgtm

#2341 Replace ASA mutations with Formations API in e2e tests
  chart/compass/values.yaml
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/runtime_api_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/label_definitions_queries.go
  tests/pkg/fixtures/scenario_assignment_requests.go
  tests/pkg/fixtures/scenarios_queries.go
  tests/tenant-fetcher-job/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2342 Fixing pairing adapter
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/pairing-adapter/templates/adapters-configmap.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/root_resolver.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/provider/handler.go
  installation/resources/installer-config-local.yaml.tpl
  tests/go.mod
  tests/go.sum
  tests/pairing-adapter/tests/main_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/config/pairing-adapter.go
Labels: :hammer: hotfix, approved, size/L, lgtm, :eagle: team-falcon

#2346 Make some of the pairing adapter fields optional
  chart/compass/values.yaml
  tests/pkg/config/pairing-adapter.go
Labels: size/S, approved, lgtm

#2348 add pairing adapters watcher
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/templates/rbac.yaml
  chart/compass/charts/pairing-adapter/templates/adapters-configmap.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.sum
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/onetimetoken/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/adapters/adapters.go
  components/director/pkg/config/pairing_adapter.go
  components/director/pkg/kubernetes/automock/watcher.go
  components/director/pkg/kubernetes/watcher.go
  components/director/run.sh
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/config/pairing-adapter.go
Labels: approved, size/XL, lgtm, :eagle: team-falcon

#2350 Add missing client_user header
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/values.yaml
  installation/resources/installer-config-gke-benchmark.yaml.tpl
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/config/pairing-adapter.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2345 fix typos
  chart/compass/values.yaml
  tests/pairing-adapter/tests/mtls_flow_test.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#2343 Update base url for ucl systems
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/service_test.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2351 Remove group configuration from director
  chart/compass/charts/director/static-groups.yaml
  chart/compass/charts/director/templates/configmap-static-groups.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/hack/static-groups-local.yaml
  components/director/run.sh
  docs/compass/03-01-security.md
Labels: size/M, approved, lgtm

#2352 [HOTFIX] Remove group configuration from director
  chart/compass/charts/director/static-groups.yaml
  chart/compass/charts/director/templates/configmap-static-groups.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/director/values.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/hack/static-groups-local.yaml
  components/director/run.sh
  docs/compass/03-01-security.md
Labels: size/M, approved, lgtm

#2318 Merge systems api
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/merge-applications/merge-applications.graphql
  components/director/go.mod
  components/director/go.sum
  components/director/hack/config-local.yaml
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/str/strings.go
  tests/director/tests/application_api_test.go
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#2354 Remove fetching tenant when creating app template
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
Labels: size/S, approved, lgtm

#2355 Update compass console version
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#2325 Prepare for Github workflow in compass
  CODEOWNERS
Labels: :wave: request review, size/M, approved, lgtm

#2360 [HOTFIX] Update base url for ucl systems
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/service_test.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, :hammer: hotfix, size/M, approved, lgtm

#2332 Validate provider tenant on subscribtion
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/subscription_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/subscription/automock/runtime_service.go
  components/director/internal/subscription/automock/tenant_service.go
  components/director/internal/subscription/service.go
  components/director/internal/subscription/service_test.go
  components/director/internal/tenantfetchersvc/automock/director_graph_ql_client.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/subscriber.go
  components/director/internal/tenantfetchersvc/subscriber_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql_client/director_client.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/tenantfetcher/tenant_helper.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: approved, size/XL, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2363 Fix system fetcher
  chart/compass/values.yaml
  components/director/internal/systemfetcher/service.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2324 Refactor run script
  chart/compass/values.yaml
  components/director/hack/jwt_generator.sh
  components/director/pkg/kubernetes/client.go
  components/director/run.sh
  installation/scripts/prow/compass-smoke-test.sh
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2364 Guard label merge
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2367 Update merge app e2e test not to assert DEFAULT scenario
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2365 Reduce memory load in tenant-fetcher on demand API
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_test.go
  installation/scripts/prow/compass-smoke-test.sh
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2370 [hotfix-v1.33.0-rc1] Reduce memory load in tenant-fetcher on demand API
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_test.go
  installation/scripts/prow/compass-smoke-test.sh
Labels: size/L, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2369 [hotfix-v1.32.3] Reduce memory load in tenant-fetcher on demand API
  chart/compass/values.yaml
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_test.go
Labels: :hammer: hotfix, size/L, :dragon: team-dragon

#2371 Fix misleading alert
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
Labels: :wave: request review, size/XS, approved, lgtm

#2372 Enhance JWT Generator local script to include App template scopes
  components/director/hack/jwt_generator.sh
Labels: :wave: request review, size/XS, approved, lgtm

#2359 Use Tenant-on-Demand API in Tenant Mapping Handler Flow
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/automock/tenant_fetcher.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/tenantfetcher/handler.go
Labels: approved, size/L, lgtm, :dragon: team-dragon

#2373 Upgrade base image to go version 1.18
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/connector/Makefile
  components/connector/go.mod
  components/connector/go.sum
  components/director/.golangci.yml
  components/director/Dockerfile
  components/director/Makefile
  components/director/go.mod
  components/director/hack/plugins/descriptionsdecorator/plugin.go
  components/director/hack/plugins/formatter.go
  components/director/internal/repo/query_builder.go
  components/director/pkg/str/strings.go
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/hydrator/Makefile
  components/operations-controller/Dockerfile
  components/operations-controller/Makefile
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
  tests/connectivity-adapter/Makefile
  tests/connector/Makefile
  tests/director/Makefile
  tests/external-services-mock/Makefile
  tests/gateway/Makefile
  tests/istio/Makefile
  tests/ns-adapter/Makefile
  tests/ord-aggregator/Makefile
  tests/ord-service/Makefile
  tests/pairing-adapter/Makefile
  tests/system-broker/Makefile
  tests/system-fetcher/Makefile
  tests/tenant-fetcher-job/Makefile
  tests/tenant-fetcher/Makefile
Labels: :wave: request review, approved, size/XL, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2376 Lazily store subaccount when fetch on demand fails
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/formation/automock/tenant_fetcher.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/labeldef/automock/formation_service.go
  components/director/internal/domain/labeldef/automock/model_converter.go
  components/director/internal/domain/labeldef/automock/repository.go
  components/director/internal/domain/labeldef/automock/service.go
  components/director/internal/domain/runtime/automock/bundle_instance_auth_service.go
  components/director/internal/domain/runtime/automock/entity_converter.go
  components/director/internal/domain/runtime/automock/eventing_service.go
  components/director/internal/domain/runtime/automock/external_svc_caller.go
  components/director/internal/domain/runtime/automock/external_svc_caller_provider.go
  components/director/internal/domain/runtime/automock/label_repository.go
  components/director/internal/domain/runtime/automock/label_upsert_service.go
  components/director/internal/domain/runtime/automock/o_auth20_service.go
  components/director/internal/domain/runtime/automock/runtime_converter.go
  components/director/internal/domain/runtime/automock/runtime_repository.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/runtime/automock/scenario_assignment_engine.go
  components/director/internal/domain/runtime/automock/scenario_assignment_service.go
  components/director/internal/domain/runtime/automock/scenarios_service.go
  components/director/internal/domain/runtime/automock/self_register_manager.go
  components/director/internal/domain/runtime/automock/subscription_service.go
  components/director/internal/domain/runtime/automock/system_auth_converter.go
  components/director/internal/domain/runtime/automock/system_auth_service.go
  components/director/internal/domain/runtime/automock/tenant_fetcher.go
  components/director/internal/domain/runtime/automock/tenant_service.go
  components/director/internal/domain/runtime/automock/uid_service.go
  components/director/internal/domain/runtime/automock/webhook_converter.go
  components/director/internal/domain/runtime/automock/webhook_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/scenarioassignment/automock/tenant_fetcher.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/tenant/automock/tenant_fetcher.go
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/webhook/automock/runtime_service.go
  components/director/internal/domain/webhook/automock/webhook_repository.go
  components/director/internal/domain/webhook/automock/webhook_service.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/automock/tenant_fetcher.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/tenant_fetcher.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_test.go
Labels: :wave: request review, :hammer: hotfix, approved, size/XL, lgtm, to be released :rocket:, :t-rex: team-raptor, :dragon: team-dragon

#2378 [hotfix-v1.32] Lazily store subaccount when fetch on demand fails
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/formation/automock/tenant_fetcher.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/runtime/automock/tenant_fetcher.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/scenarioassignment/automock/tenant_fetcher.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
  components/director/internal/tenantfetcher/service.go
  components/director/internal/tenantfetcher/service_test.go
  components/director/internal/tenantfetchersvc/automock/tenant_fetcher.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/tenant_fetcher.go
  components/director/internal/tenantfetchersvc/tenant_fetcher_test.go
Labels: :wave: request review, :hammer: hotfix, approved, size/XL, lgtm, :t-rex: team-raptor, :dragon: team-dragon

#2366 Improve e2e tests
  chart/compass/values.yaml
  components/director/internal/domain/webhook/service.go
  components/external-services-mock/internal/auditlog/configurationchange/configuration_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/tenants_api_test.go
Labels: size/M, approved, lgtm

#2388 include the actual value in the error message
  chart/compass/values.yaml
  components/director/internal/domain/labeldef/service.go
Labels: :wave: request review, size/XS, approved, lgtm

#2383 bump alpine version
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/schema-migrator/validate.sh
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2382 clean-up test formation after test
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2379 clean-up locally created test resources in a case of failure/panic
  chart/compass/values.yaml
  tests/pairing-adapter/tests/mtls_flow_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon
