Repository kyma-incubator/compass, pull requests merged in 2022-09, with the labels that each got.

#2601 Move CRDs to charts
  chart/compass/crds/clusterMicroFrontend.yaml
  chart/compass/crds/testing_v1alpha1_clustertestsuite.yaml
  chart/compass/crds/testing_v1alpha1_testdefinition.yaml
  installation/scripts/install-compass.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2606 Remove verbose logging from compass installation
  installation/scripts/install-compass.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#2596 Region label adjustments when getting tenant in hydrator
  chart/compass/values.yaml
  components/hydrator/internal/tenantmapping/access_level_context_provider_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider_test.go
  components/hydrator/internal/tenantmapping/user_context_provider_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2603 Introduce system fetcher operational mode
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
  components/director/internal/systemfetcher/service.go
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2605 Allow for path to charts to be passed to installation script
  installation/scripts/install-compass.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2610 Destination Fetcher - rely on defaults for destination service configs
  chart/compass/charts/destination-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#2608 Add cleanup defer in the e2e test
  chart/compass/values.yaml
  tests/director/tests/runtime_api_test.go
Labels: size/XS, approved, lgtm

#2602 Enhance the System Fetcher with logic that create ORD webhook for some systems
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/webhook_repository.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#2599 Create Alert and ServiceMonitor for Portieris.
  chart/compass/templates/additional-prometheus-rules.yaml
  chart/compass/templates/portieris-service-monitor.yaml
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2614 Add Bundle CorrelationIDs to graphqlizer
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: size/M, approved, lgtm

#2612 Assert explicitly the Certificate Issuer region in E2E tests when issuer is from another region
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/main_test.go
  tests/pkg/certs/certprovider/ext_cert_provider.go
Labels: size/M, approved, lgtm

#2598 Base ORD Aggregation on Webhook entities instead of Applications
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/destinationfetchersvc/automock/bundle_repo.go
  components/director/internal/destinationfetchersvc/automock/destination_manager.go
  components/director/internal/destinationfetchersvc/automock/destination_repo.go
  components/director/internal/destinationfetchersvc/automock/destination_syncer.go
  components/director/internal/destinationfetchersvc/automock/label_repo.go
  components/director/internal/destinationfetchersvc/automock/tenant_repo.go
  components/director/internal/destinationfetchersvc/automock/uuid_service.go
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/formation/automock/application_repository.go
  components/director/internal/domain/formation/automock/application_template_repository.go
  components/director/internal/domain/formation/automock/label_repository.go
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/automock/webhook_client.go
  components/director/internal/domain/formation/automock/webhook_converter.go
  components/director/internal/domain/formation/automock/webhook_repository.go
  components/director/internal/domain/runtime/automock/runtime_service.go
  components/director/internal/domain/webhook/automock/webhook_repository.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/open_resource_discovery/automock/application_service.go
  components/director/internal/open_resource_discovery/automock/webhook_service.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/pkg/http/automock/http_round_tripper.go
  components/director/pkg/persistence/txtest/txtest.go
  tests/go.sum
  tests/ord-aggregator/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2611 Destination fetcher fix extension service defaults
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/destinationservice_test.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/service_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/model/destination.go
Labels: approved, size/L, lgtm, to be released :rocket:

#2616 Move DB data
  chart/localdb/charts/dbdump/templates/dbdump-job.yaml
  chart/localdb/charts/dbdump/templates/dbdump-pv.yaml
  installation/cmd/run.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2621 [HOTFIX] Fix endspoints of destination fetcher and destination service
  chart/compass/charts/destination-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
  installation/resources/compass-overrides-local.yaml
Labels: :hammer: hotfix, size/S, lgtm

#2618 Add destination fetcher e2e test
  chart/compass/charts/destination-fetcher/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/tenant-dependencies-secret.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/client_test.go
  components/director/internal/destinationfetchersvc/handler_test.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/config/destination_config.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/destinationfetcher/handler.go
  components/external-services-mock/internal/destinationfetcher/mockdata.go
  components/external-services-mock/internal/subscription/config.go
  tests/director/tests/application_api_test.go
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/clients/destination_client.go
  tests/pkg/fixtures/application_queries.go
Labels: approved, size/XL, lgtm, to be released :rocket:, :t-rex: team-raptor

#2622 [HOTFIX] Destination fetcher fix extension service defaults
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/destinationservice_test.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/service_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/model/destination.go
Labels: size/L, lgtm

#2623 Fix envoy filter syntax
  chart/compass/charts/gateway/templates/rate-limit-filter.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2624 ORD Service E2E tests - fix deleting destinations
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/destinationfetcher/handler.go
  tests/pkg/clients/destination_client.go
Labels: size/M, approved, lgtm

#2627 [Hotfix] ORD Service E2E tests - fix deleting destinations
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/destinationfetcher/handler.go
  tests/pkg/clients/destination_client.go
Labels: :wave: request review, :hammer: hotfix, size/M, approved, lgtm

#2629 [HOTFIX STAGE] Add explicit protocol for compass services
  chart/compass/charts/director/templates/service.yaml
  chart/compass/charts/gateway/templates/service.yaml
  chart/compass/charts/hydrator/templates/service.yaml
  chart/compass/charts/operations-controller/templates/service.yaml
  chart/compass/charts/system-broker/templates/service.yaml
Labels: :hammer: hotfix, size/XS, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2628 [HOTFIX DEV] Add explicit protocol for compass services
  chart/compass/charts/director/templates/service.yaml
  chart/compass/charts/gateway/templates/service.yaml
  chart/compass/charts/hydrator/templates/service.yaml
  chart/compass/charts/operations-controller/templates/service.yaml
  chart/compass/charts/system-broker/templates/service.yaml
Labels: :hammer: hotfix, size/XS, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2630 Update External Service Mock to reflect updates in ORD Global Registry
  chart/compass/values.yaml
  components/external-services-mock/internal/ord-aggregator/globalregistry/template.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2631 Fix prometheus port
  installation/scripts/prom-mtls-patch.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#2634 Add image pull secret to dest fetcher deployment
  chart/compass/charts/destination-fetcher/templates/deployment.yaml
Labels: size/XS, approved, lgtm

#2636 Fix Portieris ServiceMonitor
  chart/compass/templates/portieris-service-monitor.yaml
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#2625 Support webhooks for more applications types
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/ns-adapter/templates/deployment.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/application/automock/label_service.go
  components/director/internal/domain/application/automock/label_upsert_service.go
  components/director/internal/domain/application/config.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/nsadapter/adapter/configuration.go
  components/director/internal/open_resource_discovery/automock/label_repository.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/run.sh
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
  tests/director/tests/application_api_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#2639 Use configation for supported application type
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
  tests/director/tests/main_test.go
Labels: size/S, approved, lgtm

#2637 Remove default scenario from formations table
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20220919092123_default_scenario_cleanup.down.sql
  components/schema-migrator/migrations/director/20220919092123_default_scenario_cleanup.up.sql
Labels: :wave: request review, size/S, approved, lgtm

#2632 Support created at for webhooks and sort them for aggregation
  chart/compass/values.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/webhook/automock/time_service.go
  components/director/internal/domain/webhook/converter.go
  components/director/internal/domain/webhook/converter_test.go
  components/director/internal/domain/webhook/entity.go
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/domain/webhook/resolver_test.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/domain/webhook/service_test.go
  components/director/internal/model/webhook.go
  components/director/internal/repo/list.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20220920145100_add_created_at_for_webooks.down.sql
  components/schema-migrator/migrations/director/20220920145100_add_created_at_for_webooks.up.sql
  tests/director/tests/application_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, :dragon: team-dragon

#2642 Update net, crypto and prometheus/client_golang
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2641 Soften certain ORD aggregation validation rules temporarily for S/4 systems
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/schema-migrator/migrations/director/20220921130000_ord_increase_short_description_size.down.sql
  components/schema-migrator/migrations/director/20220921130000_ord_increase_short_description_size.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2640 Enrich self register labels for runtimes
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/region-instances-credentials.yaml
  chart/compass/charts/external-services-mock/templates/saas-app-names-secret.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  components/director/internal/selfregmanager/selfreg_manager.go
  components/director/internal/selfregmanager/selfreg_manager_test.go
  components/director/internal/selfregmanager/testdata/TestSelfRegisterManager_PrepareRuntimeForSelfRegistration.golden
  components/director/internal/selfregmanager/testdata/TestSelfRegisterManager_SaaSAppName.golden
  components/director/pkg/config/selfreg_config.go
  components/director/run.sh
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
  tests/director/tests/formation_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2645 Update k3d CLI in the local director script
  chart/compass/values.yaml
  components/director/run.sh
Labels: size/XS, approved, lgtm

#2647 Remove Default Scenario leftovers
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/localdb/charts/postgresql/templates/secrets.yaml
  tests/director/bench/main_test.go
  tests/pkg/tenant/tenant_setup.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2656 chore: remove license-puller requirements
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/gateway/Dockerfile
  components/pairing-adapter/Dockerfile
  scripts/README.md
  scripts/generic_make_go.mk
  tests/Dockerfile
Labels: :wave: request review, size/S, approved, lgtm, kind/cleanup, :t-rex: team-raptor, :eagle: team-falcon

#2651 Extend Webhook Output Template
  chart/compass/values.yaml
  components/director/pkg/webhook/types.go
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2635 Remove false statement regarding Integration Systems
  docs/integration-system/auto-app-management.md
Labels: size/XS, lgtm

#2657 Fix Tenants Aggregator prometheus rules
  chart/compass/charts/tenant-fetcher/templates/tnt-resync-prometheus-rules.yaml
  chart/compass/templates/additional-prometheus-rules.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/config.go
Labels: size/M, approved, lgtm, :dragon: team-dragon

#2649 Separate formation notifications
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/tenantfetchersvc/resync/builder.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2590 Fix log probing reqs
  chart/compass/values.yaml
  components/connectivity-adapter/cmd/main.go
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/director/cmd/destinationfetcher-svc/main.go
  components/director/cmd/director/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/pkg/log/request.go
  components/director/pkg/log/request_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/cmd/main.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/cmd/main.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  components/system-broker/pkg/server/server.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2664 Make ppmsProductVersionId optional template placeholder
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#2666 Update ORD service
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#2661 [Tenants Aggregator] Create Jobs PrometeusRule conditionally
  chart/compass/charts/tenant-fetcher/templates/tnt-resync-prometheus-rules.yaml
Labels: :wave: request review, size/S, approved, lgtm, :dragon: team-dragon
