Repository kyma-incubator/compass, pull requests merged in 2023-01, with the labels that each got.

#2816 Adopt K8S 1.22
  chart/compass/crds/clusterMicroFrontend.yaml
  chart/compass/crds/testing_v1alpha1_clustertestsuite.yaml
  chart/compass/crds/testing_v1alpha1_testdefinition.yaml
  installation/cmd/run.sh
  installation/scripts/install-kyma.sh
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2807 Adapt E2E tests to use new SaaS Registry subscription API
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/subscription/utils.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2819 System fetcher does not update app templates
  chart/compass/values.yaml
  components/director/internal/model/app_template.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/systemfetcher/loader_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2818 Create get formation by name endpoint
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/query-formation-by-name/query-formation-by-name.graphql
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/fomation_requests.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2820 Fix jsonpath implementation
  chart/compass/values.yaml
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/fixtures/application_template_requests.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2822 Add policyLevel 'none' to ORD policyLevel enum values
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/schema-migrator/migrations/director/20230112121009_add-ord-none-policy-level.down.sql
  components/schema-migrator/migrations/director/20230112121009_add-ord-none-policy-level.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2821 Upgrade kyma to 2.3.0
  README.md
  chart/compass/templates/agent-configuration-job.yaml
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/scripts/prom-mtls-patch.sh
Labels: size/S, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#2824 ORD Aggregator doesn't send Tenant header when fetching resource definitions for multitenant ORD application
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/fetchrequest/fixtures_test.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/pkg/http/request.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2823 Adapt db restore from dump
  chart/compass/values.yaml
  chart/localdb/charts/dbdump/templates/dbdump-job.yaml
  components/director/run.sh
  components/schema-migrator/migrations/director/201908141300_initialize_schema.up.sql
  components/schema-migrator/migrations/director/201909241337_add_system_auths.up.sql
  components/schema-migrator/migrations/director/202001311508_migrate_tenants.up.sql
  components/schema-migrator/migrations/director/202002071200_add_package_definitions.up.sql
  components/schema-migrator/migrations/director/202011031147_add_runtime_contexts.up.sql
  components/schema-migrator/migrations/director/202101291101_adopt-ord-changes.up.sql
  components/schema-migrator/migrations/director/20210302174853_add_app_template_to_webhooks.up.sql
  installation/cmd/run.sh
  installation/scripts/prow/compass-smoke-test.sh
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor

#2833 Wrap ORD service e2e test
  chart/compass/values.yaml
  tests/ord-service/tests/api_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor

#2834 Use correlation ID as client user if not provided in pairing flow
  chart/compass/values.yaml
  components/director/internal/domain/onetimetoken/service.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#2831 Ensure customer personal data is not logged
  chart/compass/values.yaml
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/authenticator/middleware.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/packagetobundles/handler.go
  components/hydrator/internal/tenantmapping/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2835 Allow application template consumers to report status for formation notifications to their applications
  CODEOWNERS
  chart/compass/values.yaml
  components/director/internal/formationmapping/OWNERS
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  installation/scripts/install-db.sh
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2830 Adjust Dockerfiles for cross-compilation
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2825 Introduce tenant hierarchy to formation notifications payload
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formation/automock/tenant_repository.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formationassignment/automock/tenant_repository.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/application_tenant_mapping.go
  components/director/pkg/webhook/formation_configuration_change.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/formation_api_test.go
  tests/director/tests/main_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2829 Application Onboarding to Support SPII Tenant Mapping Declaration
  chart/compass/charts/director/templates/configmap-tenant-mapping-config.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/apptemplate/config.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/run.sh
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#2837 Fix NPE in AppTemplate resolving logic
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/converter.go
Labels: :wave: request review, size/XS, approved, lgtm

#2838 Adjust Defers in tests to avoid object leaks
  chart/compass/values.yaml
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/bench/application_api_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/istio/tests/request_payload_limit_test.go
  tests/ns-adapter/tests/full_report_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/certs/certprovider/ext_cert_provider.go
  tests/pkg/clients/connector_client.go
  tests/pkg/clients/hydrator_client.go
  tests/pkg/clients/secured_client.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/runtime_queries.go
  tests/pkg/token/token_utils.go
  tests/system-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2843 [HOTFIX] Relax input validation of tenant mapping status API
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/external-services-mock/internal/notification/handler.go
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, approved, size/L, lgtm

#2844 Add Team Falcon to TF owners
  CODEOWNERS
Labels: size/S, approved, lgtm

#2845 Adjust validate script for arm and amd arch builds
  .gitignore
  chart/compass/values.yaml
  components/schema-migrator/Makefile
  components/schema-migrator/validate.sh
Labels: :wave: request review, size/M, approved, lgtm

#2842 Relax input validation of tenant mapping status API
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/config.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/external-services-mock/internal/notification/handler.go
  tests/director/tests/formation_api_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2847 [HOTFIX] Add version to GQLizer
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: size/XS, approved, lgtm

#2846 Add version to GQLizer
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: size/XS, approved, lgtm

#2851 Hotfix fix graphqlizer comma
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: size/XS, approved, lgtm

#2849 Fix graphqlizer comma
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: size/XS, approved, lgtm

#2853 [HOTFIX] Set quotes for version in gqlizer
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: size/XS

#2841 Introduce instances label on subscribe/unsubscribe
  chart/compass/values.yaml
  components/director/internal/domain/subscription/fixtures_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/pkg/subscription/utils.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2852 Put quotes on gqlizer
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
Labels: size/XS, approved, lgtm

#2854 Skip sending duplicate tenant mapping notifications
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_service.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor
