Repository kyma-incubator/compass, pull requests merged in 2023-11, with the labels that each got.

#3427 Add goimports linter to golangci
  chart/compass/values.yaml
  components/default-tenant-mapping-handler/golangci.yml
  components/director/.golangci.yml
  components/director/cmd/tenantloader/main.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/pkg/formationconstraint/validation.go
  components/director/pkg/graphql/formation_constraint_validation.go
  components/instance-creator/golangci.yml
  components/instance-creator/internal/handler/handler.go
  components/kyma-adapter/.golangci.yml
  components/kyma-adapter/internal/handler/handler.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#3435 Introduce retry while fetching ord well-known endpoint
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3436 [HOTFIX] Introduce retry while fetching ord well-known endpoint
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#3437 Introduce optional override parameter to UpdateAppTemplate mutation
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/automock/application_template_service.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/systemfetcher/automock/app_tmpl_service.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/systemfetcher/loader_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application/application_templates_api_test.go
  tests/pkg/fixtures/application_template_requests.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#3428 Initial content for saas subaccounts
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/Makefile
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/director/internal/tenantfetchersvc/resync/types.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/tenantfetcher/handler.go
  installation/resources/compass-overrides-local.yaml
  tests/go.mod
  tests/go.sum
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3433 Use self-signed keystore certificates for SAML destinations
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/destinationcreator/types.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_creator_service.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/destinationcreator/fixtures_test.go
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/destinationcreator/handler_test.go
  components/external-services-mock/internal/destinationcreator/mockdata.go
  components/external-services-mock/internal/destinationcreator/types.go
  components/external-services-mock/internal/httphelpers/common.go
  components/external-services-mock/pkg/destinationcreator/types.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/clients/destination_client.go
  tests/pkg/util/utils.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3434 Return null config instead of empty string
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/formationmapping/handler.go
  components/director/pkg/formationassignment/util.go
  components/director/pkg/formationconstraint/parse_template.go
  components/director/pkg/formationconstraint/validation.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/str/strings.go
  components/director/pkg/templatehelper/helper.go
  components/director/pkg/webhook/application_lifecycle.go
  components/director/pkg/webhook/application_tenant_mapping.go
  components/director/pkg/webhook/formation_configuration_change.go
  components/director/pkg/webhook/formation_lifecycle.go
  components/director/pkg/webhook/open_resource_discovery.go
  components/director/pkg/webhook/types.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
Labels: approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#3439 Fix outdated director reference in e2e tests
  chart/compass/values.yaml
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/go.mod
  tests/go.sum
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3441 [HOTFIX] Fix outdated director reference in e2e tests
  chart/compass/values.yaml
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/go.mod
  tests/go.sum
Labels: size/S, approved, lgtm, :t-rex: team-raptor

#3440 [HOTFIX] Bump images for hotfix v1.81.1 branch
  chart/compass/values.yaml
Labels: size/S, do-not-merge/hold

#3426 Support multiple tenants in authenticator context provider in hydrator component
  chart/compass/charts/external-services-mock/templates/authenticator-secrets.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/pkg/claims/const.go
  components/hydrator/internal/tenantmapping/authenticator_context_provider.go
  components/hydrator/internal/tenantmapping/authenticator_context_provider_test.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  components/hydrator/internal/tenantmapping/handler.go
  components/hydrator/internal/tenantmapping/handler_test.go
  components/hydrator/pkg/authenticator/authenticator.go
  components/hydrator/pkg/authenticator/authenticator_test.go
  components/hydrator/pkg/authenticator/types.go
  components/hydrator/pkg/authenticator/types_test.go
  components/hydrator/pkg/oathkeeper/model.go
  components/hydrator/pkg/oathkeeper/model_test.go
  installation/resources/compass-overrides-local.yaml
  tests/director/tests/config.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/authenticator/config.go
  tests/pkg/token/token_utils.go
Labels: size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#3442 Remove leftover template function
  chart/compass/values.yaml
  components/director/pkg/templatehelper/helper.go
Labels: size/S, approved, lgtm

#3444 Adapt e2e test assert
  chart/compass/values.yaml
  tests/director/tests/tenant_isolation_test.go
  tests/pkg/assertions/assertions.go
Labels: size/M, approved, lgtm

#3445 Change image dir and version for release
  chart/compass/values.yaml
Labels: size/M, approved, lgtm

#3447 Adapt user name autheticator e2e test
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/tenant/tenant_setup.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#3450 [HOTFIX] Add notification response to details
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/automock/status_service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/statusreport/notification_status_report.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_status_service.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/formationconstraint/validation.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3451 Fix test
  chart/compass/values.yaml
  tests/director/tests/tenant_isolation_test.go
  tests/pkg/assertions/assertions.go
Labels: size/S, approved, lgtm

#3449 [HOTFIX] Adapt user name autheticator e2e test
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/tenant/tenant_setup.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#3452 [HOTFIX] Add notification response to details
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/automock/status_service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/statusreport/notification_status_report.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_status_service.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/pkg/formationconstraint/join_point_details.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3453 Update image version
  chart/compass/values.yaml
Labels: size/XS

#3458 Update ORD Service version
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3456 Handle scenario label for all participants during unassign
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/unassign_formation_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3462 Fix benchmark test
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#3464 Revert "fix benchmark (#3462)"
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3443 Adapt request to TMS based on request tenant type
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/onetimetoken/service.go
  components/director/pkg/pairing/model.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/pairing-adapter/internal/adapter/model.go
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/pairing-adapter/tests/mtls_flow_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3463 Remove test intermediate state
  chart/compass/values.yaml
  tests/director/tests/notifications/runtime_notification_subscription_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor

#3465 Benchmark grep fix
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3467 [HOTFIX v1.81.2 ]Export fields of NotificationStatusReport
  chart/compass/values.yaml
  components/director/internal/domain/statusreport/notification_status_report.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/validation.go
  tests/go.sum
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3466 [HOTFIX]Export fields of NotificationStatusReport
  chart/compass/values.yaml
  components/director/internal/domain/statusreport/notification_status_report.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/validation.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3468 Guard potential race condition involving scenario label
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/unassign_formation_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3474 Use director prod image
  chart/compass/values.yaml
Labels: size/XS

#3476 Change ias-adapter image from dev to prod registry
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3471 Introduce contains scenario group formation constraint operator
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formationconstraint/operators/automock/system_auth_service.go
  components/director/internal/domain/formationconstraint/operators/config_mutator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine_test.go
  components/director/internal/domain/formationconstraint/operators/contains_scenario_groups_operator.go
  components/director/internal/domain/formationconstraint/operators/contains_scenario_groups_operator_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/do_not_generate_formation_assignment_notification_for_loops_test.go
  components/director/internal/domain/formationconstraint/operators/do_not_generate_formation_assignment_notification_test.go
  components/director/internal/domain/formationconstraint/operators/does_not_contain_resource_of_subtype_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/is_not_assigned_to_any_formation_of_type_operator_test.go
  components/director/internal/domain/formationconstraint/operators/redirect_notification_operator_test.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/validation.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/contains_scenario_groups_operator_test.go
  tests/director/tests/notifications/main_test.go
  tests/director/tests/notifications/runtime_notification_subscription_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/application_fixtures.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/application_template_queries.go
  tests/pkg/fixtures/formation_constraint_fixtures.go
  tests/pkg/fixtures/formation_constraint_queries.go
Labels: :wave: request review, approved, size/XL, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3477 Export fields of NotificationStatusReport
  chart/compass/values.yaml
  components/director/internal/domain/statusreport/notification_status_report.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/validation.go
Labels: :wave: request review, size/M, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#3478 Introduce cost-object tenant type
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/pkg/inputvalidation/validators_cert_subject_mappings.go
  components/director/pkg/tenant/entity.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/20231120135409_introduce-cost-object-tenant-type.down.sql
  components/schema-migrator/migrations/director/20231120135409_introduce-cost-object-tenant-type.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3479 Update versions
  chart/compass/values.yaml
Labels: size/M

#3469 Director pre-install job
  chart/compass/charts/director/files/certificate_rotation.sh
  chart/compass/charts/director/templates/_helpers.tpl
  chart/compass/charts/director/templates/ext-svc-certificate-pre-install-job.yaml
  chart/compass/charts/director/templates/ext-svc-certificate-rotation-job.yaml
  chart/compass/charts/director/templates/external-certificate-pre-install-job.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/values.yaml
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3480 Fix benchmark job
  installation/resources/compass-overrides-gke-benchmark.yaml
Labels: size/XS, approved, lgtm

#3482 Adopt new format in contains scenario group operator e2e test
  chart/compass/values.yaml
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/contains_scenario_groups_operator_test.go
  tests/pkg/fixtures/application_fixtures.go
  tests/pkg/notifications/operations/assign_application_error.go
  tests/pkg/notifications/operations/generate-one-time-token-for-application.go
  tests/pkg/notifications/resource-providers/application_template.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3475 Use notification report from details
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/automock/status_service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/formationconstraint/operators/config_mutator_operator.go
  components/director/internal/domain/formationconstraint/operators/config_mutator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/utils.go
  components/director/internal/domain/statusreport/notification_status_report.go
  components/director/internal/formationmapping/automock/formation_assignment_status_service.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/director/tests/notifications/runtime_notification_subscription_test.go
  tests/director/tests/notifications/tenant_hierarchy_notifications_test.go
Labels: :wave: request review, size/XXL, approved, do-not-merge/hold, lgtm, :t-rex: team-raptor

#3484 Use notification report from details
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/automock/status_service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/formationconstraint/operators/config_mutator_operator.go
  components/director/internal/domain/formationconstraint/operators/config_mutator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/utils.go
  components/director/internal/domain/statusreport/notification_status_report.go
  components/director/internal/formationmapping/automock/formation_assignment_status_service.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/director/tests/notifications/runtime_notification_subscription_test.go
  tests/director/tests/notifications/tenant_hierarchy_notifications_test.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#3483 Fix system fetcher to override status
  chart/compass/values.yaml
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  components/director/runSystemFetcher.sh
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#3486 [HOTFIX] Fix system fetcher to override status 1.83.1
  chart/compass/values.yaml
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  components/director/runSystemFetcher.sh
  tests/system-fetcher/tests/handler_test.go
Labels: size/L, :eagle: team-falcon

#3487 [HOTFIX] Fix system fetcher to override status 1.82.3
  chart/compass/values.yaml
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: size/L, :eagle: team-falcon

#3488 1.83.1 bump versions
  chart/compass/values.yaml
Labels: size/XS

#3489 1.82.3 bump versions
  chart/compass/values.yaml
Labels: size/XS

#3490 [HOTFIX] Enable App Template subscription flow in ORD Service
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20231121105202_ord-fix-views-app-tmpl-subscription-flow.down.sql
  components/schema-migrator/migrations/director/20231121105202_ord-fix-views-app-tmpl-subscription-flow.up.sql
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: size/XXL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3494 [HOTFIX] Add filtering for ORD capability entity
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3495 Fix log parameters
  components/director/internal/domain/formation/service.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3496 Fix components version
  chart/compass/values.yaml
  components/hydrator/internal/certsubjectmapping/loader.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3491 Change sidecar image tag
  chart/ory/values.yaml
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3485 Fix unstable notification e2e tests
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3502 Minor changes
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/status_service.go
  tests/director/tests/notifications/fixtures_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3503 [HOTFIX] Fix tenancy in packages and events views
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20231121125902_ord-fix-tenancy-packages-events-views.down.sql
  components/schema-migrator/migrations/director/20231121125902_ord-fix-tenancy-packages-events-views.up.sql
Labels: approved, size/L, lgtm

#3497 Adapt Capability filtering changes
  chart/compass/values.yaml
  tests/ord-aggregator/tests/handler_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3504 Fix tenancy in packages and events views
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20231121125902_ord-fix-tenancy-packages-events-views.down.sql
  components/schema-migrator/migrations/director/20231121125902_ord-fix-tenancy-packages-events-views.up.sql
Labels: approved, size/L, lgtm

#3498 Fix notification response with empty error message
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/status_service.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3506 Check for nil in template function
  chart/compass/values.yaml
  components/director/pkg/templatehelper/helper.go
Labels: size/S, approved, lgtm

#3511 Fix processing of tenant mapping notifications
  chart/compass/values.yaml
  components/ias-adapter/internal/service/automock/ias_service.go
  components/ias-adapter/internal/service/automock/tenant_mappings_storage.go
  components/ias-adapter/internal/service/tenant_mapping.go
  components/ias-adapter/internal/service/tenant_mapping_test.go
Labels: :wave: request review, approved, size/L, lgtm, cla: yes

#3514 Support oauth2ClientCredentials destinations in the Destinations Creator Operator
  chart/compass/values.yaml
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/destinationcreator/types.go
  components/director/internal/domain/destination/automock/destination_creator_service.go
  components/director/internal/domain/destination/fixtures_test.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/destination/service_test.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_service.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/pkg/destinationcreator/types.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/destinationcreator/handler_test.go
  components/external-services-mock/internal/destinationcreator/mockdata.go
  components/external-services-mock/internal/destinationcreator/types.go
  components/external-services-mock/internal/formationnotification/handler.go
  components/external-services-mock/pkg/destinationcreator/types.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/api_test.go
  tests/pkg/fixtures/formation_constraint_fixtures.go
  tests/pkg/json/utils_json.go
  tests/pkg/notifications/asserters/formation_assignments_async.go
  tests/pkg/notifications/asserters/notifications.go
  tests/pkg/notifications/operations/generate-one-time-token-for-application.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, cla: yes

#3516 Add app namespace in the formation constraint validation structures
  chart/compass/values.yaml
  components/director/pkg/templatehelper/helper.go
Labels: size/S, approved, lgtm, cla: yes

#3515 [HOTFIX] Support oauth2ClientCredentials destinations in the Destinations Creator Operator
  chart/compass/values.yaml
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/destinationcreator/types.go
  components/director/internal/domain/destination/automock/destination_creator_service.go
  components/director/internal/domain/destination/fixtures_test.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/destination/service_test.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_service.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/pkg/destinationcreator/types.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/destinationcreator/handler_test.go
  components/external-services-mock/internal/destinationcreator/mockdata.go
  components/external-services-mock/internal/destinationcreator/types.go
  components/external-services-mock/internal/formationnotification/handler.go
  components/external-services-mock/pkg/destinationcreator/types.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/formation_constraint_fixtures.go
  tests/pkg/json/utils_json.go
  tests/pkg/notifications/asserters/formation_assignments_async.go
  tests/pkg/notifications/asserters/notifications.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, cla: yes
