Repository kyma-incubator/compass, pull requests merged in 2023-04, with the labels that each got.

#2967 Resynchronize Formation Lifecycle Notifications
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/export_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder_test.go
  components/director/internal/domain/formation/notifications_generator_test.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_service.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/notification/handler.go
  components/external-services-mock/internal/notification/handler_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/tenant_queries.go
  tests/pkg/fixtures/webhook_queries.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#2969 Introduce new istio ingressgateway dashboard
  chart/compass/templates/general-dashboard-configmap.yaml
  chart/compass/values.yaml
  components/hydrator/internal/subject/cert_subject_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2994 Fix update global formation template webhook
  chart/compass/values.yaml
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_templates_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2996 Update benchmark overrides for IAS
  chart/compass/charts/external-services-mock/templates/ias-cockpit-secret.yaml
  chart/compass/values.yaml
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
Labels: size/S, approved, lgtm

#2973 [Constraint] Adding multiple systems of a given type to a formation should be forbidden
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationconstraint/automock/application_repository.go
  components/director/internal/domain/formationconstraint/automock/label_service.go
  components/director/internal/domain/formationconstraint/constraint_engine.go
  components/director/internal/domain/formationconstraint/constraint_engine_test.go
  components/director/internal/domain/formationconstraint/constraint_operators.go
  components/director/internal/domain/formationconstraint/constraint_operators_test.go
  components/director/internal/domain/formationconstraint/fixtures_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/graphql/formation_constraint_validation.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_constraint_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2981 Derive region for auto-discovered systems
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#3000 Fix flapping constraint e2e test
  chart/compass/values.yaml
  tests/director/tests/formation_constraint_api_test.go
Labels: size/M, approved, lgtm

#3001 Adapt latest ORD specification - from 1.2.0 to 1.2.2
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/bundle/converter.go
  components/director/internal/domain/bundle/entity.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/bundle/service.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/bundle.go
  components/director/internal/model/bundle_test.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/automock/application_service.go
  components/director/internal/open_resource_discovery/automock/bundle_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/global_registry.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/schema-migrator/migrations/director/20230406094000_add_version_resource_hash_and_local_tenant_id.down.sql
  components/schema-migrator/migrations/director/20230406094000_add_version_resource_hash_and_local_tenant_id.up.sql
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#3008 [HOTFIX] Fix bundle nil pointer version
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: size/S, :eagle: team-falcon

#3004 Add script for running System Fetcher on local machine
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/README.md
  components/director/cmd/systemfetcher/main.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/systemfetcher/loader_test.go
  components/director/internal/systemfetcher/service.go
  components/director/runSystemFetcher.sh
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#3006 [HOTFIX] Fix bundle nil pointer version
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3007 Honour rate limiting of 15 RPS and add retry mechanism
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/pkg/retry/retry.go
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/model/bundle.go
  components/director/internal/systemfetcher/automock/tenant_service.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
  components/director/internal/tenantfetchersvc/resync/tenant_mover.go
  components/director/pkg/retry/retry.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/gateway/internal/auditlog/client.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/health_test.go
  tests/gateway/tests/playground_suite.go
  tests/go.mod
  tests/go.sum
  tests/pkg/clients/director_client.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/testctx/testctx.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3009 Add scope to integration system
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm

#3011 Multiple hotfixes
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connectivity-adapter/pkg/retry/retry.go
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/model/bundle.go
  components/director/internal/systemfetcher/automock/tenant_service.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
  components/director/internal/tenantfetchersvc/resync/tenant_mover.go
  components/director/pkg/retry/retry.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/gateway/internal/auditlog/client.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/health_test.go
  tests/gateway/tests/playground_suite.go
  tests/go.mod
  tests/go.sum
  tests/pkg/clients/director_client.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/testctx/testctx.go
Labels: size/L, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3010 Prepend missing protocol for IAS adapter application URL
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
Labels: size/XS, approved, lgtm

#3013 Adjust istio metrics
  chart/compass/templates/general-dashboard-configmap.yaml
Labels: :wave: request review, size/M, approved, lgtm

#3018 Fix ord aggregator nil pointer dereference
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3012 Add team atlas owners
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
  components/ias-adapter/OWNERS
Labels: size/S, approved, lgtm

#3020 [HOTFIX] Fix ord aggregator nil pointer dereference (#3018)
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
Labels: size/S, :eagle: team-falcon

#3019 Escape new lines in errors in ias adapter
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/api/internal/response.go
  components/ias-adapter/internal/service/ias/service.go
Labels: size/S, approved, lgtm

#3016 Fix processing composite labels in webhook input template parsing
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notificationbuilder_test.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/webhook/datainputbuilder/builder.go
  components/director/internal/domain/webhook/datainputbuilder/builder_test.go
  components/director/internal/domain/webhook/datainputbuilder/fixtures_test.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/formation_configuration_change.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/application_fixtures.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3023 [HOTFIX] Fix processing composite labels in webhook input template parsing
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notificationbuilder_test.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/webhook/datainputbuilder/builder.go
  components/director/internal/domain/webhook/datainputbuilder/builder_test.go
  components/director/internal/domain/webhook/datainputbuilder/fixtures_test.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/formation_configuration_change.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/application_fixtures.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3003 Enrich runtime metadata with all the necessary properties for tenant mapping
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/label_service.go
  components/director/internal/domain/runtime/converter.go
  components/director/internal/domain/runtime/converter_test.go
  components/director/internal/domain/runtime/entity.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/repository.go
  components/director/internal/domain/runtime/repository_test.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/runtime.go
  components/director/pkg/graphql/runtime_validation.go
  components/director/pkg/graphql/runtime_validation_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/validation.go
  components/schema-migrator/migrations/director/20230406105155_enrich_runtime_metadata.down.sql
  components/schema-migrator/migrations/director/20230406105155_enrich_runtime_metadata.up.sql
  tests/director/tests/formation_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3025 Fix Runtime e2e test
  chart/compass/values.yaml
  tests/director/tests/runtime_api_test.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3014 Store license as labels to tenants
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/director/internal/tenantfetchersvc/resync/fixtures_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_mover_test.go
  components/director/internal/tenantfetchersvc/resync/types.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  components/external-services-mock/internal/tenantfetcher/handler.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/pkg/tenantfetcher/tenant_helper.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3021 Add customer adoption metric
  chart/compass/charts/director/templates/dashboard-configmap.yaml
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3028 (ias-adapter) normalize IAS api display name
  chart/compass/values.yaml
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
Labels: size/S, approved, lgtm, to be released :rocket:

#3024 Change ORD PR version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#3029 Revert "(ias-adapter) normalize IAS api display name"
  chart/compass/values.yaml
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
Labels: size/S, lgtm

#2961 Use app only formation template in tests
  chart/compass/values.yaml
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/formation_template_queries.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3031 ORD Aggregator mistakenly errors when validating bundle shortDescription length
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3036 Extended Customer adoption metrics
  chart/compass/charts/director/templates/dashboard-configmap.yaml
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
Labels: :wave: request review, approved, size/L, lgtm

#3037 Fix indentation in prometheus postgres exporter
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm

#3038 Add webhooks auth read
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3041 Switch between pointer values
  chart/compass/values.yaml
  components/director/pkg/auth/converter.go
Labels: size/S, approved, lgtm

#3043 Fix sandbox build for system fetcher
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#3044 [HOTFIX] Fix destination fetcher memory issue
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/client_test.go
  components/director/internal/destinationfetchersvc/export_test.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/syncjob.go
  components/director/internal/domain/tenant/repository.go
Labels: approved, size/L, lgtm

#3040 Change the image registry
  chart/compass/values.yaml
  installation/scripts/prow/update-compass.sh
Labels: size/M, approved, lgtm

#3045 [HOTFIX] Change the image registry
  chart/compass/values.yaml
  installation/scripts/prow/update-compass.sh
Labels: size/M, approved, lgtm

#3046 [HOTFIX] Change the image registry for v1.61.5
  chart/compass/values.yaml
  installation/scripts/prow/update-compass.sh
Labels: size/M, approved, lgtm
