Repository kyma-incubator/compass, pull requests merged in 2023-06, with the labels that each got.

#3096 Refactor Application Template model
  chart/compass/values.yaml
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/converter_test.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/apptemplate/automock/app_converter.go
  components/director/internal/domain/apptemplate/automock/application_converter.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/converter_test.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/subscription/automock/application_converter.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/director/pkg/graphql/app_validation.go
  components/director/pkg/graphql/app_validation_test.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  installation/scripts/prow/compass-smoke-test.sh
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/gateway/tests/integration_system_scope_test.go
  tests/go.mod
  tests/go.sum
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/application_fixtures.go
  tests/pkg/fixtures/application_requests.go
  tests/pkg/fixtures/application_template_requests.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3099 Add log on webhook delete
  chart/compass/values.yaml
  components/director/internal/domain/webhook/service.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#3100 Fix get Application template Webhook for Formation Notifications
  chart/compass/values.yaml
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/webhook_fixtures.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3091 Update applicationType label of all apps when the parent Application Template has an updated applicationType
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/apptemplate/automock/application_repository.go
  components/director/internal/domain/apptemplate/automock/label_upsert_service.go
  components/director/internal/domain/apptemplate/converter_test.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/label/automock/label_repository.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/label/service.go
  components/director/internal/domain/label/service_test.go
  components/director/internal/domain/root_resolver.go
  tests/director/tests/application_templates_api_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#3101 [HOTFIX] Fix get Application template Webhook for Formation Notifications
  chart/compass/values.yaml
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/webhook_fixtures.go
Labels: size/M, approved, lgtm

#3102 Fix flapping system fetcher unit test
  chart/compass/values.yaml
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/template_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#3097 Fix Resync API with generate FA constraint attached
  chart/compass/values.yaml
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notificationbuilder_test.go
  components/director/internal/domain/formation/notifications_generator.go
  components/director/internal/domain/formation/notifications_generator_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor

#3104 Remove sleep between event service requests
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon, :dragon: team-dragon

#3033 Do not send formation assignment error in notifications
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/pkg/webhook/application_tenant_mapping.go
  components/director/pkg/webhook/formation_configuration_change.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/notification/handler.go
  tests/director/tests/formation_api_test.go
Labels: kind/bug, :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#3090 Kyma adapter
  CODEOWNERS
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/kyma-adapter/.helmignore
  chart/compass/charts/kyma-adapter/Chart.yaml
  chart/compass/charts/kyma-adapter/OWNERS
  chart/compass/charts/kyma-adapter/templates/deployment.yaml
  chart/compass/charts/kyma-adapter/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/kyma-adapter/templates/service-account.yaml
  chart/compass/charts/kyma-adapter/templates/service.yaml
  chart/compass/charts/kyma-adapter/values.yaml
  chart/compass/values.yaml
  components/director/cmd/destinationfetcher-svc/main.go
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/authenticator/claims/nsadapterClaimsValidator.go
  components/director/internal/authenticator/claims/scopes_validator.go
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/authenticator/claims/validators_test.go
  components/director/pkg/auth-middleware/automock/claims_validator.go
  components/director/pkg/auth-middleware/middleware.go
  components/director/pkg/auth-middleware/middleware_test.go
  components/director/pkg/auth-middleware/testdata/invalid.json
  components/director/pkg/auth-middleware/testdata/jwks-private.json
  components/director/pkg/auth-middleware/testdata/jwks-private2.json
  components/director/pkg/auth-middleware/testdata/jwks-private3.json
  components/director/pkg/auth-middleware/testdata/jwks-public.json
  components/director/pkg/auth-middleware/testdata/jwks-public2.json
  components/director/pkg/auth-middleware/testdata/jwks-public3.json
  components/director/pkg/idtokenclaims/claims.go
  components/kyma-adapter/.gitignore
  components/kyma-adapter/.golangci.yml
  components/kyma-adapter/Dockerfile
  components/kyma-adapter/Makefile
  components/kyma-adapter/OWNERS
  components/kyma-adapter/cmd/main.go
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/kyma-adapter/internal/claims/validate.go
  components/kyma-adapter/internal/config/config.go
  components/kyma-adapter/internal/handler/handler.go
  components/kyma-adapter/internal/healthz/handler.go
  components/kyma-adapter/internal/healthz/handler_test.go
  components/kyma-adapter/internal/tenant/fixtures_test.go
  components/kyma-adapter/internal/tenant/tennatInfo.go
  components/kyma-adapter/internal/tenant/validator.go
  components/kyma-adapter/internal/tenant/validator_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3111 [NGPBUG-356643] Requests to SLIS fail with 414 URI Too Long
  chart/compass/values.yaml
  components/director/internal/systemfetcher/client.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3113 [HOTFIX] Requests to SLIS fail with 414 URI Too Long
  chart/compass/values.yaml
  components/director/internal/systemfetcher/client.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3114 Fix formation assignments stuck in initial state when object is without any webhooks
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3093 Expose mutations for Create/UpdateBundleInstanceAuths on behalf of a runtime
  chart/compass/charts/director/config.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/README.md
  components/director/examples/create-bundle-instance-auth/create-bundle-instance-auth.graphql
  components/director/examples/update-bundle-instance-auth/update-bundle-instance-auth.graphql
  components/director/go.mod
  components/director/go.sum
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/bundleinstanceauth/automock/converter.go
  components/director/internal/domain/bundleinstanceauth/automock/service.go
  components/director/internal/domain/bundleinstanceauth/converter.go
  components/director/internal/domain/bundleinstanceauth/converter_test.go
  components/director/internal/domain/bundleinstanceauth/fixtures_test.go
  components/director/internal/domain/bundleinstanceauth/repository.go
  components/director/internal/domain/bundleinstanceauth/repository_test.go
  components/director/internal/domain/bundleinstanceauth/resolver.go
  components/director/internal/domain/bundleinstanceauth/resolver_test.go
  components/director/internal/domain/bundleinstanceauth/service.go
  components/director/internal/domain/bundleinstanceauth/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/bundle_instance_auth.go
  components/director/pkg/graphql/bundle_validation.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/bundle_instance_auth_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/bundle_requests.go
  tests/pkg/fixtures/bundles_queries.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3115 [HOTFIX] Delete formation assignment at the start of unassign from formation + Skip nil check
  chart/compass/values.yaml
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/handler.go
Labels: approved, size/XL, lgtm, :t-rex: team-raptor

#3109 [HOTFIX] Fix matching certificate subjects
  chart/compass/values.yaml
  components/director/pkg/cert/certutils_test.go
  components/hydrator/internal/subject/cert_subject.go
  components/hydrator/internal/subject/cert_subject_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3122 Fix tenant fetcher
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/config.go
  components/director/internal/tenantfetchersvc/resync/kubernetes.go
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/synchronizer_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager_test.go
  components/director/internal/tenantfetchersvc/resync/types.go
  installation/resources/compass-overrides-local.yaml
Labels: approved, size/L, lgtm, :eagle: team-falcon, :dragon: team-dragon

#3123 Fix removing consumedAPIs from ias apps
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/service/tenant_mapping.go
Labels: approved, size/L, lgtm

#3103 Adaptations in the new join points
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/operations-manager/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/automock/status_service.go
  components/director/internal/domain/formation/export_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/status_service.go
  components/director/internal/domain/formation/status_service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_converter.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_updater.go
  components/director/internal/domain/formationassignment/automock/formation_template_repository.go
  components/director/internal/domain/formationassignment/automock/status_service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/formationassignment/updater.go
  components/director/internal/domain/formationassignment/updater_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_status_service.go
  components/director/internal/formationmapping/automock/formation_assignment_updater.go
  components/director/internal/formationmapping/automock/formation_service.go
  components/director/internal/formationmapping/automock/formation_status_service.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/graphql/formation_constraint_validation.go
  components/director/pkg/webhook_client/types.go
  tests/go.mod
  tests/go.sum
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3129 Fix system fetcher concurrency issue
  chart/compass/values.yaml
  components/director/internal/systemfetcher/client.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#3130 On AppTemplate Update also update webhooks
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/automock/webhook_repository.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/converter_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/model/app_template.go
  components/director/internal/systemfetcher/loader.go
  components/director/pkg/auth-middleware/automock/claims_validator.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application_templates_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#3131 Fix system fetcher race condition
  chart/compass/values.yaml
  components/director/internal/systemfetcher/automock/systems_api_client.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#3128 Add missing unit tests in formation assignment notifications svc
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/pkg/graphql/formation_constraint_validation.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3133 Fix formation resynchronization after unassign
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/formation_assignment_notifications_service.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3132 Add ID field to ApplicationFromTemplateInput
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/model/app_template.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application_templates_api_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, size/L, lgtm

#3137 [HOTFIX] Fix destination creator operator nil parameter
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/destination/service.go
Labels: :wave: request review, size/M, approved, do-not-merge/hold, lgtm

#3136 Fix destination creator operator nil parameter
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/destination/service.go
Labels: :wave: request review, size/S, approved, lgtm

#3139 [HOTFIX] Add template ID in input when registering application from template
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/model/app_template.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application_templates_api_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, size/L, lgtm

#3141 [HOTFIX] Fix formation resynchronization after unassign
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/formation_assignment_notifications_service.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/handler.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3134 Fix resync API sending notifications for self-referenced formation assignments
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3142 Fix correlation ID in the status API
  chart/compass/values.yaml
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3143 [HOTFIX] Fix correlation ID in the status API
  chart/compass/values.yaml
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3144 Introduce resolvers for api event
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/cmd/director/main.go
  components/director/internal/domain/api/automock/api_repository.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/application/automock/api_definition_converter.go
  components/director/internal/domain/application/automock/api_definition_service.go
  components/director/internal/domain/application/automock/event_definition_converter.go
  components/director/internal/domain/application/automock/event_definition_service.go
  components/director/internal/domain/application/automock/spec_service.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/eventdef/automock/event_api_repository.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/eventdef/service.go
  components/director/internal/domain/eventdef/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/formationmapping/automock/formation_assignment_notification_service.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/application_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3127 Add tenant to notification payload
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/operations-manager/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/label/fixtures_test.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/webhook/datainputbuilder/automock/label_input_builder.go
  components/director/internal/domain/webhook/datainputbuilder/automock/tenant_input_builder.go
  components/director/internal/domain/webhook/datainputbuilder/automock/tenant_repository.go
  components/director/internal/domain/webhook/datainputbuilder/builder.go
  components/director/internal/domain/webhook/datainputbuilder/builder_test.go
  components/director/internal/domain/webhook/datainputbuilder/fixtures_test.go
  components/director/internal/domain/webhook/datainputbuilder/label_builder.go
  components/director/internal/domain/webhook/datainputbuilder/label_builder_test.go
  components/director/internal/domain/webhook/datainputbuilder/tenant_builder.go
  components/director/internal/domain/webhook/datainputbuilder/tenant_builder_test.go
  components/director/pkg/graphql/formation_constraint_validation.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/formation_configuration_change.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/main_test.go
  tests/pkg/fixtures/application_fixtures.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3145 Alerts audit
  chart/compass/charts/gateway/templates/destinationrule-auditlog.yaml
  chart/compass/templates/additional-prometheus-rules.yaml
  chart/compass/values.yaml
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3147 [HOTFIX]Fix audience url when creating SAML destinations
  chart/compass/values.yaml
  components/director/internal/domain/destination/service.go
Labels: size/XS, approved, lgtm

#3148 Fix audience url when creating SAML destinations
  chart/compass/values.yaml
  components/director/internal/domain/destination/service.go
Labels: size/XS, approved, lgtm

#3150 General Compass Grafana Dashboard
  chart/compass/templates/general-dashboard-configmap.yaml
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3153 [HOTFIX] Fix error handling in the destination creator operator
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/utils.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_service.go
  components/director/internal/formationmapping/handler.go
Labels: :hammer: hotfix, approved, size/L, lgtm, :t-rex: team-raptor

#3152 Fix error handling in the destination creator operator
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/utils.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_service.go
  components/director/internal/formationmapping/handler.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3149 Test pods eviction fix
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3140 Dynamically replace bia
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/operations-manager/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/bundle/automock/bundle_instance_auth_service.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/bundle/resolver.go
  components/director/internal/domain/bundle/service.go
  components/director/internal/domain/bundle/service_test.go
  components/director/internal/domain/bundleinstanceauth/repository.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/consumer/consumertest/consumertest.go
  tests/director/tests/application_api_test.go
  tests/pkg/fixtures/auth_requests.go
  tests/pkg/fixtures/bundles_queries.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3155 Add cert read scope for MAP
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon
