Repository kyma-incubator/compass, pull requests merged in 2023-10, with the labels that each got.

#3346 [HOTFIX] Fix external services mock extra delay construct
  chart/compass/values.yaml
  components/external-services-mock/internal/formationnotification/handler.go
Labels: :hammer: hotfix, size/M, approved, lgtm

#3342 Add prefix to lease name of the op manager jobs
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/processor.go
  components/director/internal/operations_manager/operations_manager.go
  components/director/internal/operations_manager/operations_manager_config.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#3347 Add prefix to lease name of the op manager jobs
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/processor.go
  components/director/internal/operations_manager/operations_manager.go
  components/director/internal/operations_manager/operations_manager_config.go
Labels: size/M, :eagle: team-falcon

#3349 Revert 3322
  chart/compass/values.yaml
  components/director/internal/domain/onetimetoken/service.go
Labels: size/M

#3340 Fix reporting for FA with READY state in asynchronous case
  chart/compass/values.yaml
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_service.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/pkg/fixtures/formation_assignment_notifications_constants.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3351 Update values.yaml
  chart/compass/values.yaml
Labels: size/XS

#3354 Jobguard
  installation/scripts/kyma-scripts/jobguard/README.md
  installation/scripts/kyma-scripts/jobguard/cmd/jobguard/main.go
  installation/scripts/kyma-scripts/jobguard/go.mod
  installation/scripts/kyma-scripts/jobguard/go.sum
  installation/scripts/kyma-scripts/jobguard/pkg/jobguard/filter.go
  installation/scripts/kyma-scripts/jobguard/pkg/jobguard/httpclient.go
  installation/scripts/kyma-scripts/jobguard/pkg/jobguard/status.go
  installation/scripts/kyma-scripts/jobguard/pkg/jobguard/v2/jobguard.go
  installation/scripts/kyma-scripts/jobguard/pkg/jobguard/v2/status.go
  installation/scripts/kyma-scripts/jobguard/pkg/jobguard/waiter.go
  installation/scripts/kyma-scripts/jobguard/scripts/run.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass-smoke-test.sh
  installation/scripts/prow/jobs/provision-compass.sh
  installation/scripts/prow/jobs/validate-compass-generic.sh
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#3338 Adapt ORD from v1.5.0 to v1.5.3
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/product/converter.go
  components/director/internal/domain/product/entity.go
  components/director/internal/domain/product/fixtures_test.go
  components/director/internal/domain/product/repository.go
  components/director/internal/domain/product/repository_test.go
  components/director/internal/domain/tombstone/converter.go
  components/director/internal/domain/tombstone/entity.go
  components/director/internal/domain/tombstone/fixtures_test.go
  components/director/internal/domain/tombstone/repository.go
  components/director/internal/domain/tombstone/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/product.go
  components/director/internal/model/product_test.go
  components/director/internal/model/spec.go
  components/director/internal/model/tombstone.go
  components/director/internal/model/tombstone_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20230926130504_add_description_to_products_and_tombstones_and_remove_hierarchy_from_apis_and_events.down.sql
  components/schema-migrator/migrations/director/20230926130504_add_description_to_products_and_tombstones_and_remove_hierarchy_from_apis_and_events.up.sql
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#3345 Enhance rootTenant graphql API
  chart/compass/values.yaml
  components/director/examples/get-root-tenant/get-root-tenant.graphql
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/tenants_api_test.go
  tests/pkg/fixtures/fixtures.go
Labels: approved, size/L, lgtm

#3362 Adapt local env octopus
  installation/scripts/install-compass.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#3367 [HOTFIX] Update versions
  chart/compass/values.yaml
Labels: size/M

#3344 Kyma 2.7.3
  README.md
  docs/compass/04-01-installation.md
  installation/cmd/run.sh
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/install-kyma.sh
  installation/scripts/prom-mtls-patch.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#3339 Adapt test structure docs after splitting director test definition
  tests/README.md
Labels: size/XS, approved, lgtm

#3370 Update values.yaml
  chart/compass/values.yaml
Labels: size/M

#3368 Update Migrate version
  chart/compass/values.yaml
  components/schema-migrator/Dockerfile
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#3369 Fix aggregator log timestamps
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/pkg/log/configure.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3374 Change Ory container users
  chart/ory/charts/hydra/templates/deployment.yaml
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3365 Improve retry logic
  chart/compass/values.yaml
  components/connectivity-adapter/internal/appregistry/appdetails/middleware_test.go
  components/connectivity-adapter/internal/appregistry/director/cli_test.go
  components/connectivity-adapter/pkg/retry/retry.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/destinationfetchersvc/client_test.go
  components/director/pkg/retry/retry.go
  components/kyma-adapter/internal/gqlclient/gqlclient.go
  tests/director/tests/health_test.go
  tests/gateway/tests/playground_suite.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/testctx/testctx.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3376 [HOTFIX] Change Ory container users
  chart/ory/charts/hydra/templates/deployment.yaml
Labels: :hammer: hotfix, size/S, approved, lgtm, :t-rex: team-raptor

#3358 Fix formation assignment race condition during unassign
  chart/compass/values.yaml
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/handler.go
  components/director/pkg/persistence/txtest/txtest.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/director/tests/notifications/runtime_notification_subscription_test.go
  tests/go.mod
  tests/go.sum
Labels: size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#3377 [HOTFIX] Fix formation assignment race condition during unassign
  chart/compass/values.yaml
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/handler.go
  components/director/pkg/persistence/txtest/txtest.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/director/tests/notifications/runtime_notification_subscription_test.go
  tests/go.mod
  tests/go.sum
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#3378 [HOTFIX] Update image registry and version in hotfix branch
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3373 Add flag for generating examples in the sandbox test runs
  tests/director/Makefile
  tests/director/copy-examples.sh
  tests/director/generate_examples.sh
Labels: :wave: request review, size/S, approved, lgtm

#3390 Allow adding/modifying/deleting webhooks of app templates
  chart/compass/values.yaml
  components/director/internal/domain/label/automock/label_repository.go
  components/director/internal/domain/label/parent_verifier.go
  components/director/internal/domain/label/parent_verifier_test.go
  components/director/internal/domain/label/service.go
  components/director/internal/domain/webhook/entity.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/repo/create.go
  tests/director/tests/application/application_templates_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#3375 Support multiple cldsystemrole values
  chart/compass/values.yaml
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
  components/director/runSystemFetcher.sh
  components/schema-migrator/migrations/director/20231012115530_cld_label_support_multiple_values.down.sql
  components/schema-migrator/migrations/director/20231012115530_cld_label_support_multiple_values.up.sql
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3391 Clean up operation error when operation is marked as completed
  chart/compass/values.yaml
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
Labels: size/XS, approved, lgtm

#3372 Kyma 2.8.4
  README.md
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/install-kyma.sh
  installation/scripts/prom-mtls-patch.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3396 Introduce tombstone processor
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/automock/tombstone_processor.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/processor/automock/tombstone_service.go
  components/director/internal/open_resource_discovery/processor/common.go
  components/director/internal/open_resource_discovery/processor/tombstone.go
  components/director/internal/open_resource_discovery/processor/tombstone_test.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: size/XXL, approved, lgtm, :eagle: team-falcon

#3363 Config mutator
  CODEOWNERS
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/formationconstraint/operators/config_mutator_operator.go
  components/director/internal/domain/formationconstraint/operators/config_mutator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/formationconstraint/parse_template.go
  components/director/pkg/graphql/formation_constraint_validation.go
  tests/director/tests/formation/OWNERS
  tests/director/tests/notifications/OWNERS
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/runtime/OWNERS
  tests/go.mod
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/notifications/OWNERS
  tests/pkg/notifications/asserters/asserters.go
  tests/pkg/notifications/asserters/formation_assignments.go
  tests/pkg/notifications/asserters/formation_assignments_async.go
  tests/pkg/notifications/asserters/formation_status.go
  tests/pkg/notifications/asserters/notifications.go
  tests/pkg/notifications/asserters/notifications_count.go
  tests/pkg/notifications/asserters/notifications_unassign.go
  tests/pkg/notifications/context-keys/keys.go
  tests/pkg/notifications/expectations-builders/formation_assignment.go
  tests/pkg/notifications/operations/add-constraint.go
  tests/pkg/notifications/operations/add-webhook-to-application.go
  tests/pkg/notifications/operations/assign_application.go
  tests/pkg/notifications/operations/cleanup-notifications.go
  tests/pkg/notifications/operations/operation.go
  tests/pkg/notifications/operations/resynchronize.go
  tests/pkg/notifications/operations/unassign-application.go
  tests/pkg/notifications/operations/update-webhook.go
  tests/pkg/notifications/resource-providers/application.go
  tests/pkg/notifications/resource-providers/application_template.go
  tests/pkg/notifications/resource-providers/formation.go
  tests/pkg/notifications/resource-providers/formation_template.go
  tests/pkg/notifications/resource-providers/provider.go
  tests/pkg/notifications/resource-providers/resource.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#3399 Fix flapping ord aggregator tests
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/assertions/assertions.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#3304 Introduce default tenant mapping handler component
  chart/compass/charts/default-tenant-mapping-handler/.helmignore
  chart/compass/charts/default-tenant-mapping-handler/Chart.yaml
  chart/compass/charts/default-tenant-mapping-handler/OWNERS
  chart/compass/charts/default-tenant-mapping-handler/templates/_helpers.tpl
  chart/compass/charts/default-tenant-mapping-handler/templates/deployment.yaml
  chart/compass/charts/default-tenant-mapping-handler/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/default-tenant-mapping-handler/templates/rbac.yaml
  chart/compass/charts/default-tenant-mapping-handler/templates/service.yaml
  chart/compass/charts/default-tenant-mapping-handler/values.yaml
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/ns-adapter/templates/rbac.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/default-tenant-mapping-handler/.gitignore
  components/default-tenant-mapping-handler/Dockerfile
  components/default-tenant-mapping-handler/Makefile
  components/default-tenant-mapping-handler/OWNERS
  components/default-tenant-mapping-handler/cmd/main.go
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/default-tenant-mapping-handler/golangci.yml
  components/default-tenant-mapping-handler/internal/claims/validate.go
  components/default-tenant-mapping-handler/internal/config/config.go
  components/default-tenant-mapping-handler/internal/handler/automock/mtls_http_client.go
  components/default-tenant-mapping-handler/internal/handler/handler.go
  components/default-tenant-mapping-handler/internal/handler/utils.go
  components/default-tenant-mapping-handler/internal/healthz/handler.go
  components/default-tenant-mapping-handler/internal/healthz/handler_test.go
  components/default-tenant-mapping-handler/internal/tenant/fixtures_test.go
  components/default-tenant-mapping-handler/internal/tenant/tenantInfo.go
  components/default-tenant-mapping-handler/internal/tenant/validator.go
  components/default-tenant-mapping-handler/internal/tenant/validator_test.go
  components/director/cmd/director/main.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/config.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/run.sh
  tests/director/tests/config.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/pkg/fixtures/webhook_fixtures.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3371 Fail when deleting application if it is part of formation
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/repo/tenant_access_m2m.go
  components/director/internal/repo/upsert.go
  tests/director/tests/formation/formation_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/tenant_requests.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3404 Add create update timestamp on app template
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/apptemplate/automock/time_service.go
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/entity.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/repository_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/model/app_template.go
  components/director/pkg/graphql/applicaiton_template.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/202310191150030_add-timstamps-on-app-templates.down.sql
  components/schema-migrator/migrations/director/202310191150030_add-timstamps-on-app-templates.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/application/application_templates_api_test.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/token_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3395 Improve status codes in status API
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/pkg/apperrors/errors.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3406 Fix migrations
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20231020111424_add-timestamps-on-app-templates.down.sql
  components/schema-migrator/migrations/director/20231020111424_add-timestamps-on-app-templates.up.sql
Labels: kind/bug, size/XS, approved, lgtm

#3408 [HOTFIX] Fix MarkAsCompleted operation method
  chart/compass/values.yaml
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
Labels: :hammer: hotfix, size/XS, approved, lgtm

#3409 [HOTFIX] Bump images for hotfix v1.80.0 branch
  chart/compass/values.yaml
Labels: size/XS

#3407 Fix MarkAsCompleted operation method
  chart/compass/values.yaml
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
Labels: size/XS, approved, lgtm, to be released :rocket:

#3397 Kyma 2.9.3
  README.md
  chart/compass/charts/prometheus-postgres-exporter/README.md
  chart/compass/charts/prometheus-postgres-exporter/templates/podsecuritypolicy.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/role.yaml
  chart/compass/charts/prometheus-postgres-exporter/templates/rolebinding.yaml
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
  chart/compass/values.yaml
  chart/ory/templates/psp.yaml
  chart/ory/values.yaml
  docs/compass/04-01-installation.md
  installation/cmd/run.sh
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/install-compass.sh
  installation/scripts/install-db.sh
  installation/scripts/install-kyma.sh
  installation/scripts/install-ory.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
  tests/pkg/k8s/jobs.go
Labels: approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor

#3411 Change benchmark test Kubernetes version
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3403 Forbid self reg lbl at non cert flow
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/apptemplate/apptmpltest/selfreg_manager.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/formationassignment/status_service.go
  tests/director/tests/application/application_templates_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3415 [HOTFIX] Retry hydrator on initial load
  chart/compass/values.yaml
  components/hydrator/cmd/main.go
  components/hydrator/internal/certsubjectmapping/loader.go
  components/hydrator/internal/certsubjectmapping/loader_test.go
Labels: :wave: request review, :hammer: hotfix, approved, size/L, lgtm, :t-rex: team-raptor

#3414 Retry hydrator on initial load
  chart/compass/values.yaml
  components/hydrator/cmd/main.go
  components/hydrator/internal/certsubjectmapping/cache.go
  components/hydrator/internal/certsubjectmapping/loader.go
  components/hydrator/internal/certsubjectmapping/loader_test.go
  components/hydrator/internal/connectortokenresolver/validation_hydrator.go
  components/hydrator/internal/director/client.go
  components/hydrator/internal/runtimemapping/handler.go
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/handler.go
  components/hydrator/internal/tenantmapping/model.go
  components/hydrator/internal/tenantmapping/staticgroup.go
Labels: approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor

#3418 Adjust released components versions
  chart/compass/values.yaml
Labels: size/M

#3398 Adopt ORD specification
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/entitytype/automock/entity_type_converter.go
  components/director/internal/domain/entitytype/automock/entity_type_repository.go
  components/director/internal/domain/entitytype/automock/uid_service.go
  components/director/internal/domain/entitytype/automock/version_converter.go
  components/director/internal/domain/entitytype/converter.go
  components/director/internal/domain/entitytype/converter_test.go
  components/director/internal/domain/entitytype/entity.go
  components/director/internal/domain/entitytype/fixtures_test.go
  components/director/internal/domain/entitytype/repository.go
  components/director/internal/domain/entitytype/repository_test.go
  components/director/internal/domain/entitytype/service.go
  components/director/internal/domain/entitytype/service_test.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/model/entitytype.go
  components/director/internal/model/entitytype_test.go
  components/director/internal/open_resource_discovery/automock/entity_type_processor.go
  components/director/internal/open_resource_discovery/automock/entity_type_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/operation_processor.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/processor/automock/entity_type_service.go
  components/director/internal/open_resource_discovery/processor/common.go
  components/director/internal/open_resource_discovery/processor/entity_type.go
  components/director/internal/open_resource_discovery/processor/entity_type_test.go
  components/director/internal/open_resource_discovery/processor/fixtures_test.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/director/pkg/resource/resource.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20231020141132_add-entity-type-and-make-part-of-products-optional-for-packages.down.sql
  components/schema-migrator/migrations/director/20231020141132_add-entity-type-and-make-part-of-products-optional-for-packages.up.sql
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/registry_client.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3413 Enhance URL calculation in the destination creator operator
  chart/compass/values.yaml
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/destinationcreator/types.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/external-services-mock/internal/destinationcreator/types.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3410 Add FormationAssignmentTemplateInput to join point details
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/formationconstraint/validation.go
  components/director/pkg/graphql/formation_constraint_validation.go
  components/director/pkg/templatehelper/helper.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3416 Enrich the request with correlation id when calling tenant-fether
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/tenant_fetcher.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/runtime/automock/tenant_fetcher.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
  components/director/internal/domain/tenant/automock/fetcher.go
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3422 Fix benchmark job
  installation/resources/compass-gke-kyma-overrides.tpl.yaml
  installation/resources/compass-gke-overrides.tpl.yaml
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3423 Adapt schema migrator to support ARM builds
  chart/compass/values.yaml
  components/schema-migrator/Dockerfile
  components/schema-migrator/validate.sh
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3419 Substitute tenant caller
  chart/compass/charts/director/templates/configmap-default-tenant-labels-config.yaml
  chart/compass/charts/director/templates/tenant-loader-job-default.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantloader/main.go
  components/director/internal/domain/tenant/service.go
  components/hydrator/cmd/main.go
  components/hydrator/internal/director/automock/client.go
  components/hydrator/internal/director/client.go
  components/hydrator/internal/director/query.go
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/access_level_context_provider_test.go
  components/hydrator/internal/tenantmapping/authenticator_context_provider.go
  components/hydrator/internal/tenantmapping/authenticator_context_provider_test.go
  components/hydrator/internal/tenantmapping/automock/director_client.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider_test.go
  components/hydrator/internal/tenantmapping/handler.go
  components/hydrator/internal/tenantmapping/handler_test.go
  components/hydrator/internal/tenantmapping/model.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider_test.go
  components/hydrator/internal/tenantmapping/user_context_provider.go
  components/hydrator/internal/tenantmapping/user_context_provider_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#3425 Fix TestQueryApplicationTemplates e2e test
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_api_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#3424 Update HPA api version
  chart/compass/charts/connectivity-adapter/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/connector/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/default-tenant-mapping-handler/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/destination-fetcher/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/director/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/gateway/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/hydrator/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/ias-adapter/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/instance-creator/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/kyma-adapter/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/ord-service/templates/horizontal-pod-autoscaler.yaml
  chart/compass/charts/system-broker/templates/horizontal-pod-autoscaler.yaml
Labels: size/S, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3431 Fix applicationTemplate query to return Not Found error
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  tests/pkg/fixtures/application_template_queries.go
Labels: size/S, approved, lgtm

#3432 Fix update webhook mutation to return tenant required response
  chart/compass/values.yaml
  components/director/internal/domain/webhook/service.go
  components/director/internal/domain/webhook/service_test.go
Labels: size/S, approved, lgtm
