Repository kyma-incubator/compass, pull requests merged in 2023-03, with the labels that each got.

#2918 Allow Formation Template registration in ResourceGroup tenants
  chart/compass/values.yaml
  components/director/internal/domain/formationtemplate/automock/tenant_service.go
  components/director/internal/domain/formationtemplate/service.go
  components/director/internal/domain/formationtemplate/service_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/domain/webhook/automock/tenant_service.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/domain/webhook/service_test.go
  tests/director/tests/formation_templates_test.go
  tests/pkg/fixtures/formation_template_queries.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#2922 Improve e2e tests defers.
  chart/compass/values.yaml
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/eventing_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/oauth20_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2926 Extract the validation of instances label in separate test
  chart/compass/values.yaml
  tests/director/tests/runtime_contexts_api_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2927 Improve runtime cleanup in e2e tests.
  chart/compass/values.yaml
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connectivity-adapter/tests/connector_test.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/bench/application_api_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/eventing_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/runtime_api_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/viewer_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2925 Remove leftover ASA GraphQL model
  chart/compass/values.yaml
  tests/director/tests/automatic_scenario_assignment_test.go
  tests/director/tests/formation_api_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/label_selector_fixtures.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2920 App only formation types
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/converter_test.go
  components/director/internal/domain/formationtemplate/entity.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/formationtemplate/service_test.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/internal/domain/version/converter_test.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/model/formation_template.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/handler_test.go
  components/director/internal/repo/sql_types.go
  components/director/internal/repo/sql_types_test.go
  components/director/pkg/graphql/formation_template.go
  components/director/pkg/graphql/formation_template_validation.go
  components/director/pkg/graphql/formation_template_validation_test.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20230301155905_drop_formation_template_not_null_constraints.down.sql
  components/schema-migrator/migrations/director/20230301155905_drop_formation_template_not_null_constraints.up.sql
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/go.mod
  tests/go.sum
  tests/ns-adapter/tests/delta_report_test.go
  tests/ns-adapter/tests/full_report_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/formation_template_fixtures.go
  tests/pkg/fixtures/formation_template_queries.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2939 Add validation of provider and application type placeholders
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2940 Improve cleanup in in e2e tests.
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_constraint_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/fixtures/formation_template_queries.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2941 Enhance logs
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/formationtemplate/resolver.go
  components/director/internal/domain/integrationsystem/service.go
  components/director/internal/domain/runtime/resolver.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2928 Process asynchronous callback Formation Lifecycle Notifications
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/converter.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder_test.go
  components/director/internal/domain/formation/notifications_generator_test.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_repository.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/internal/repo/delete.go
  components/director/internal/repo/delete_test.go
  components/director/pkg/graphql/formation.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/graphql/webhook_validation_test.go
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/formation_queries.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2945 [HOTFIX] Dummy change so the compass version can change
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/service.go
Labels: size/XS

#2947 Allow BI to create formations in INITIAL state even if webhook is not present
  chart/compass/charts/director/config.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/formation/converter.go
  components/director/internal/domain/formation/converter_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/pkg/graphql/formation_validation.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2943 System should not be added to multiple different formations of a kind
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/constraint_operators.go
  components/director/internal/domain/formationconstraint/constraint_operators_test.go
  components/director/internal/domain/formationconstraint/fixtures_test.go
  components/director/internal/domain/formationconstraint/repository.go
  components/director/internal/domain/formationconstraint/repository_test.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/schema-migrator/migrations/director/20230309114302_formation_constraint_system_not_in_multiple_em_formations.down.sql
  components/schema-migrator/migrations/director/20230309114302_formation_constraint_system_not_in_multiple_em_formations.up.sql
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/constraint_reference_queries.go
  tests/pkg/fixtures/formation_template_fixtures.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2930 Add formation async status business logic implementation
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/formation/automock/formation_repository.go
  components/director/internal/domain/formation/converter_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/repository.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/integrationsystem/service.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/automock/formation_service.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/notification/fixtures_test.go
  components/external-services-mock/internal/notification/handler.go
  components/external-services-mock/internal/notification/handler_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/cert_subject_mapping_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/go.mod
  tests/go.sum
  tests/ns-adapter/tests/delta_report_test.go
  tests/ns-adapter/tests/full_report_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/pkg/fixtures/application_fixtures.go
  tests/pkg/fixtures/fixtures.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/formation_template_fixtures.go
  tests/pkg/fixtures/formation_template_queries.go
  tests/pkg/fixtures/runtime_fixtures.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2950 Fix system fetcher webhooks
  chart/compass/values.yaml
  components/director/internal/model/webhook.go
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/systemfetcher/loader_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2952 [HOTFIX] Change http method on the status API
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/external-services-mock/internal/notification/handler.go
  tests/director/tests/formation_mapping_api_test.go
  tests/pkg/fixtures/formation_queries.go
Labels: :hammer: hotfix, approved, size/L, lgtm, :t-rex: team-raptor

#2954 Fix system fetcher systems status condition
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon

#2956 [HOTFIX] Fix system fetcher systems status condition
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: size/L, :eagle: team-falcon

#2957 Use open strategy in webhooks
  chart/compass/values.yaml
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
Labels: size/M, approved, lgtm

#2958 Logs Improvements
  chart/compass/values.yaml
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notifications_generator.go
  components/director/internal/domain/formation/notifications_generator_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2953 Add mutations for tenant access create and delete
  chart/compass/charts/director/config.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/README.md
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/cmd/tenantloader/main.go
  components/director/examples/README.md
  components/director/examples/add-tenant-access/add-tenant-access.graphql
  components/director/examples/remove-tenant-access/remove-tenant-access.graphql
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_converter.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/model/tenant_access.go
  components/director/internal/repo/tenant_access_m2m.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/applicationtenancy/automock/application_service.go
  components/director/pkg/applicationtenancy/automock/business_tenant_mapping_service.go
  components/director/pkg/applicationtenancy/directive.go
  components/director/pkg/applicationtenancy/directive_test.go
  components/director/pkg/consumer/consumer.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/inputvalidation/validators_cert_subject_mappings.go
  components/director/pkg/model/system_auth.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  tests/director/tests/tenant_isolation_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/tenant_queries.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#2944 Refactor formation notification tests
  chart/compass/values.yaml
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/formation_template_queries.go
  tests/pkg/fixtures/webhook_fixtures.go
  tests/pkg/fixtures/webhook_queries.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#2964 Add formation read and write scopes to LRO
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2955 Taking the formation lifecycle notification status in the overall formation status
  chart/compass/values.yaml
  components/director/internal/dataloaders/formationStatusLoaders.go
  components/director/internal/domain/formation/automock/converter.go
  components/director/internal/domain/formation/converter.go
  components/director/internal/domain/formation/converter_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/pkg/graphql/formation.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/fomation_requests.go
  tests/pkg/fixtures/formation_queries.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#2965 Fix cert subject mappings cleanup in e2e tests
  chart/compass/values.yaml
  tests/director/tests/cert_subject_mapping_test.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/cert_subject_mapping_queries.go
Labels: size/M, approved, lgtm

#2949 Adopt ORD v1.2.0
  chart/compass/values.yaml
  chart/localdb/charts/dbdump/templates/dbdump-job.yaml
  chart/localdb/charts/postgresql/values-production.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/entity.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/bundle/converter.go
  components/director/internal/domain/bundle/entity.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/ordvendor/converter.go
  components/director/internal/domain/ordvendor/entity.go
  components/director/internal/domain/ordvendor/fixtures_test.go
  components/director/internal/domain/ordvendor/repository.go
  components/director/internal/domain/ordvendor/repository_test.go
  components/director/internal/domain/product/converter.go
  components/director/internal/domain/product/entity.go
  components/director/internal/domain/product/fixtures_test.go
  components/director/internal/domain/product/repository.go
  components/director/internal/domain/product/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/application.go
  components/director/internal/model/bundle.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/product.go
  components/director/internal/model/spec.go
  components/director/internal/model/vendor.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/schema-migrator/migrations/director/20230314160000_add_tags_labels_and_documentation_labels.down.sql
  components/schema-migrator/migrations/director/20230314160000_add_tags_labels_and_documentation_labels.up.sql
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2960 Fix system not found for deletion
  chart/compass/values.yaml
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#2959 Require app not to be empty
  chart/compass/values.yaml
  tests/director/tests/application_tenancy_synchronization_test.go
Labels: :wave: request review, size/XS, approved, lgtm

#2974 Fix IAS adapter clientId parameter
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: size/XS, approved, lgtm

#2972 Hydrador Improvements
  chart/compass/values.yaml
  components/hydrator/cmd/main.go
  components/hydrator/internal/certresolver/automock/certificate_header_parser.go
  components/hydrator/internal/certresolver/automock/revoked_certificates_cache.go
  components/hydrator/internal/certresolver/cert_header_parser.go
  components/hydrator/internal/certsubjectmapping/automock/cache.go
  components/hydrator/internal/certsubjectmapping/automock/director_client.go
  components/hydrator/internal/certsubjectmapping/loader.go
  components/hydrator/internal/certsubjectmapping/loader_test.go
  components/hydrator/internal/subject/cert_subject.go
  components/hydrator/internal/subject/cert_subject_test.go
Labels: approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor

#2975 Update IAS Adapter version
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#2970 Increase Go Runtime version
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/Dockerfile
  components/connector/go.mod
  components/connector/go.sum
  components/director/Dockerfile
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/Dockerfile
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/Dockerfile
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/Dockerfile
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/Dockerfile
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/Dockerfile
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/Dockerfile
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2980 Forbid deletion of application templates if there are existing associated applications
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20230328144000_forbid_deleting_app_template_if_it_has_associated_application.down.sql
  components/schema-migrator/migrations/director/20230328144000_forbid_deleting_app_template_if_it_has_associated_application.up.sql
  tests/director/tests/application_templates_api_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#2984 Get Webhook from app template fix
  chart/compass/values.yaml
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2989 [HOTFIX] Get Webhook from app template
  chart/compass/values.yaml
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  tests/director/tests/formation_api_test.go
Labels: :hammer: hotfix, size/M, approved, do-not-merge/hold, lgtm, :t-rex: team-raptor

#2983 Fix ias adapter validation
  chart/compass/charts/external-services-mock/templates/ias-cockpit-secret.yaml
  chart/compass/charts/ias-adapter/templates/deployment.yaml
  chart/compass/values.yaml
  components/ias-adapter/go.mod
  components/ias-adapter/go.sum
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/api/internal/paths/paths.go
  components/ias-adapter/internal/api/middlewares/auth.go
  components/ias-adapter/internal/api/middlewares/logging.go
  components/ias-adapter/internal/config/config.go
  components/ias-adapter/internal/logger/logger.go
  components/ias-adapter/internal/service/ias/client.go
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
  components/ias-adapter/internal/service/tenant_mapping.go
  components/ias-adapter/internal/storage/postgres/tenant_mapping.go
  components/ias-adapter/internal/types/application.go
  components/ias-adapter/internal/types/tenant_mapping.go
  components/ias-adapter/internal/types/tenant_mapping_test.go
  installation/resources/compass-overrides-local.yaml
Labels: approved, size/XL, lgtm

#2991 Fix webhook client and improve the logs
  chart/compass/values.yaml
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
Labels: size/M, approved, lgtm

#2993 [HOTFIX] Fix webhook client and improve the logs
  chart/compass/values.yaml
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
Labels: :hammer: hotfix, size/M, approved, lgtm
