Repository kyma-incubator/compass, pull requests merged in 2023-12, with the labels that each got.

#3520 Fix constraints validation inputs
  chart/compass/values.yaml
  components/director/pkg/formationconstraint/validation.go
Labels: size/S, approved, lgtm, cla: yes

#3524 Crm should not have leading 0
  chart/compass/values.yaml
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/pkg/tenant/tenant.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, :dragon: team-dragon, cla: yes

#3526 Update versions
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/go.mod
  tests/go.sum
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3527 Trim crm id for non-guids
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/pkg/tenant/tenant.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/director/tests/tenants_api_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon, cla: yes

#3525 Update Owners files to exclude team-dragon
  CODEOWNERS
  chart/compass/charts/tenant-fetcher/OWNERS
  components/director/cmd/tenantfetcher-svc/OWNERS
  components/director/internal/tenantfetchersvc/OWNERS
  tests/tenant-fetcher/OWNERS
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon, :dragon: team-dragon, cla: yes

#3519 Fix sf delete webhooks
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/systemfetcher/automock/webhook_service.go
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/systemfetcher/loader_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon, cla: yes

#3532 Update ext cert scopes
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, cla: yes

#3533 Partially fix compliance of ORD aggregator with the ORD specification
  chart/compass/values.yaml
  components/director/internal/domain/capability/service.go
  components/director/internal/domain/entitytype/service.go
  components/director/internal/model/api.go
  components/director/internal/model/bundle.go
  components/director/internal/model/capability.go
  components/director/internal/model/entitytype.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/integration_dependency.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/processor/entity_type.go
  components/director/internal/open_resource_discovery/processor/entity_type_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
  components/schema-migrator/migrations/director/20231206155738_remove-not-null-constaint-for-created-at-and-app-id.down.sql
  components/schema-migrator/migrations/director/20231206155738_remove-not-null-constaint-for-created-at-and-app-id.up.sql
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon, cla: yes

#3535 Improve certificate rotation jobs logs.
  chart/compass/charts/director/files/certificate_rotation.sh
Labels: size/S, approved, lgtm, cla: yes

#3538 Expose APIs and Events under System Instances in ORD Service
  chart/compass/values.yaml
  tests/ord-service/tests/api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3539 Fix notification tests with eventually
  chart/compass/values.yaml
  tests/director/tests/notifications/runtime_notification_subscription_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3541 Release v1.85.0-rc1
  chart/compass/values.yaml
Labels: size/M, approved, lgtm, cla: yes

#3530 Adjust ord clients
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3534 Fix update of resources in the ord aggregator
  chart/compass/values.yaml
  components/director/internal/domain/api/service.go
  components/director/internal/domain/api/service_test.go
  components/director/internal/domain/capability/service.go
  components/director/internal/domain/capability/service_test.go
  components/director/internal/domain/entitytype/fixtures_test.go
  components/director/internal/domain/entitytype/service.go
  components/director/internal/domain/entitytype/service_test.go
  components/director/internal/domain/eventdef/service.go
  components/director/internal/domain/eventdef/service_test.go
  components/director/internal/domain/integrationdependency/service.go
  components/director/internal/domain/integrationdependency/service_test.go
  components/director/internal/open_resource_discovery/automock/api_service.go
  components/director/internal/open_resource_discovery/automock/event_service.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/processor/api.go
  components/director/internal/open_resource_discovery/processor/api_test.go
  components/director/internal/open_resource_discovery/processor/automock/api_service.go
  components/director/internal/open_resource_discovery/processor/automock/capability_service.go
  components/director/internal/open_resource_discovery/processor/automock/entity_type_service.go
  components/director/internal/open_resource_discovery/processor/automock/event_service.go
  components/director/internal/open_resource_discovery/processor/automock/integration_dependency_service.go
  components/director/internal/open_resource_discovery/processor/capability.go
  components/director/internal/open_resource_discovery/processor/capability_test.go
  components/director/internal/open_resource_discovery/processor/entity_type.go
  components/director/internal/open_resource_discovery/processor/entity_type_test.go
  components/director/internal/open_resource_discovery/processor/event.go
  components/director/internal/open_resource_discovery/processor/event_test.go
  components/director/internal/open_resource_discovery/processor/fixtures_test.go
  components/director/internal/open_resource_discovery/processor/integration_dependency.go
  components/director/internal/open_resource_discovery/processor/integration_dependency_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon, cla: yes

#3540 Add logs in the default TM handler component
  chart/compass/values.yaml
  components/default-tenant-mapping-handler/cmd/main.go
  components/default-tenant-mapping-handler/internal/config/config.go
  components/default-tenant-mapping-handler/internal/handler/handler.go
  components/default-tenant-mapping-handler/internal/handler/utils.go
  components/default-tenant-mapping-handler/internal/types/response.go
  components/default-tenant-mapping-handler/internal/types/tenantmapping.go
  components/external-services-mock/cmd/main.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3545 Fix unstable notification lifecycle test
  chart/compass/values.yaml
  tests/director/tests/notifications/application_only_notifications_test.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3546 Change versions
  chart/compass/values.yaml
Labels: size/M, approved, lgtm, cla: yes

#3544 Fix setting of ORD ID and application namespace for integration dependency
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/common/validations.go
  components/director/internal/domain/integrationdependency/automock/package_service.go
  components/director/internal/domain/integrationdependency/converter.go
  components/director/internal/domain/integrationdependency/fixtures_test.go
  components/director/internal/domain/integrationdependency/resolver.go
  components/director/internal/domain/integrationdependency/resolver_test.go
  components/director/pkg/graphql/integration_dependency_validation.go
  components/director/pkg/graphql/integration_dependency_validation_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/integration_dependency_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3553 Replace gqlgen required dependency
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/director/go.mod
  components/director/go.sum
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3543 Fix ORD Aggregator does not persist certain ORD validation errors
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/operations_manager/automock/operation_service.go
  components/director/internal/operations_manager/interfaces.go
  components/director/internal/operations_manager/operations_manager.go
  components/director/internal/operations_manager/operations_manager_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3549 Remove Ory benchmark workaround
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3565 Upgrade ORD Service OData JPA Processor library to latest 2.0.2 version
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/values.yaml
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3567 Bump IAS Adapter dev version
  chart/compass/values.yaml
  components/ias-adapter/cmd/adapter/main.go
Labels: size/XS, lgtm, cla: yes
