Repository kyma-incubator/compass, pull requests merged in 2023-09, with the labels that each got.

#3285 Fix ORD documents validation processing errors
  chart/compass/templates/additional-prometheus-rules.yaml
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/service.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#3286 Fix labels in ORD metrics pusher
  chart/compass/values.yaml
  components/director/internal/metrics/pusher.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#3282 Destination visibillity
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/destinationcreator/config.go
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/domain/destination/automock/destination_creator_service.go
  components/director/internal/domain/destination/automock/destination_repository.go
  components/director/internal/domain/destination/automock/tenant_repository.go
  components/director/internal/domain/destination/converter.go
  components/director/internal/domain/destination/entity.go
  components/director/internal/domain/destination/fixtures_test.go
  components/director/internal/domain/destination/repository.go
  components/director/internal/domain/destination/repository_test.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/destination/service_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/model/destination.go
  components/director/run.sh
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationcreator/fixtures_test.go
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/destinationcreator/handler_test.go
  components/external-services-mock/internal/destinationcreator/types.go
  components/external-services-mock/internal/formationnotification/handler.go
  components/external-services-mock/internal/oauth/token_handler.go
  components/external-services-mock/internal/oauth/token_handler_test.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/pkg/claims/const.go
  components/schema-migrator/migrations/director/20230823153842_add-instance-id-to-destinations.down.sql
  components/schema-migrator/migrations/director/20230823153842_add-instance-id-to-destinations.up.sql
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/go.mod
  tests/go.sum
  tests/ns-adapter/tests/main_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/clients/destination_client.go
  tests/pkg/tenantfetcher/tenant_helper.go
  tests/pkg/token/token_utils.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3279 Propagate scenario group description from BTP System Landscape to TMS
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/onetimetoken/service.go
  components/director/internal/domain/onetimetoken/service_test.go
  components/director/pkg/auth-middleware/middleware.go
  components/director/pkg/auth-middleware/middleware_test.go
  components/director/pkg/pairing/model.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/pairing-adapter/internal/adapter/client.go
  components/pairing-adapter/internal/adapter/model.go
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3287 Update golang and alpine versions
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/ias-adapter/Dockerfile
  components/instance-creator/Dockerfile
  components/kyma-adapter/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3291 Fix benchmark test
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3296 Make destination subaccount validation configurable
  chart/compass/values.yaml
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/domain/destination/automock/destination_creator_service.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/destination/service_test.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_creator_service.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_service.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
Labels: approved, size/XL, lgtm, :t-rex: team-raptor

#3297 Instance creator enhancements
  chart/compass/values.yaml
  components/instance-creator/internal/client/caller.go
  components/instance-creator/internal/client/client.go
  components/instance-creator/internal/client/client_test.go
  components/instance-creator/internal/client/fixtures_test.go
  components/instance-creator/internal/client/resources/automock/resource_match_parameters.go
  components/instance-creator/internal/client/resources/automock/resources.go
  components/instance-creator/internal/client/resources/interfaces.go
  components/instance-creator/internal/client/types/service_binding.go
  components/instance-creator/internal/client/types/service_instance.go
  components/instance-creator/internal/client/types/service_offering.go
  components/instance-creator/internal/client/types/service_plan.go
  components/instance-creator/internal/handler/automock/client.go
  components/instance-creator/internal/handler/handler.go
  components/instance-creator/internal/healthz/handler.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3294 Introduce Constraint priority
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/converter.go
  components/director/internal/domain/formationconstraint/entity.go
  components/director/internal/domain/formationconstraint/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/repository.go
  components/director/internal/domain/formationconstraint/repository_test.go
  components/director/internal/domain/formationconstraint/resolver.go
  components/director/internal/domain/formationconstraint/resolver_test.go
  components/director/internal/model/formation_constraint.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20230907120953_add-priority-an-creation-timestamp-to-fc.down.sql
  components/schema-migrator/migrations/director/20230907120953_add-priority-an-creation-timestamp-to-fc.up.sql
  tests/director/tests/formation_constraint_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3298 IAS Adapter, missing IAS app: return 404 for assign, ignore for unassign
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/handlers_test.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/api/internal/response.go
  components/ias-adapter/internal/errors/errors.go
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
  components/ias-adapter/internal/service/tenant_mapping.go
Labels: approved, size/L, lgtm

#3305 Add not null consraint to created_at for Formation Constraint
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20230913161837_not-null-created-at-fc.down.sql
  components/schema-migrator/migrations/director/20230913161837_not-null-created-at-fc.up.sql
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3300 Send certificate trust details in TM notifications
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/certsubjectmapping/repository.go
  components/director/internal/domain/certsubjectmapping/repository_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/webhook/datainputbuilder/automock/cert_subject_input_builder.go
  components/director/internal/domain/webhook/datainputbuilder/automock/cert_subject_repository.go
  components/director/internal/domain/webhook/datainputbuilder/builder.go
  components/director/internal/domain/webhook/datainputbuilder/builder_test.go
  components/director/internal/domain/webhook/datainputbuilder/cert_subject_builder.go
  components/director/internal/domain/webhook/datainputbuilder/cert_subject_builder_test.go
  components/director/internal/domain/webhook/datainputbuilder/fixtures_test.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/formation_configuration_change.go
  components/director/pkg/webhook/types.go
  tests/director/tests/cert_subject_mapping_test.go
  tests/director/tests/formation_api_test.go
  tests/go.mod
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3307 [HOTFIX] Set 'json' log format only for ord aggregator
  chart/compass/charts/ord-aggregator/templates/deployment.yaml
  chart/compass/values.yaml
Labels: size/XS, lgtm, :eagle: team-falcon

#3308 Set 'json' log format only for ord aggregator
  chart/compass/charts/ord-aggregator/templates/deployment.yaml
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, :eagle: team-falcon

#3303 Fix E2E destination test's setup and configuration
  chart/compass/templates/provider-destination-oauth-secret.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/service.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/provider/handler.go
  components/external-services-mock/internal/provider/handler_test.go
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/clients/destination_client.go
  tests/pkg/config/director.go
Labels: approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3301 Kyma 2.4.3
  README.md
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/install-kyma.sh
  installation/scripts/prom-mtls-patch.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: approved, size/L, lgtm, do-not-merge/missing-docs-review, :t-rex: team-raptor

#3312 Change image registry and versions
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3310 Introduce static ord webhook type
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/model/webhook.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql/webhook_validation.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/20230918143511_add_ord_static_webhook.down.sql
  components/schema-migrator/migrations/director/20230918143511_add_ord_static_webhook.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3315 IAS Adapter: handle the case with missing IAS apps during Unassign
  chart/compass/values.yaml
  components/ias-adapter/internal/service/tenant_mapping.go
Labels: size/S, approved, lgtm

#3313 Fix formation assignment clone in formation assignment resynchronization
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/service.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3311 Kyma 2.5.2
  README.md
  docs/compass/04-01-installation.md
  installation/cmd/run.sh
  installation/resources/KYMA_VERSION
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3316 IAS adapter fixes
  chart/compass/values.yaml
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
  components/ias-adapter/internal/service/tenant_mapping.go
Labels: size/M, approved, lgtm

#3318 [HotFix] bump IAS adapter version
  chart/compass/values.yaml
Labels: size/XS

#3319 Fixes in IAS adapter
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/handlers_test.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/api/internal/response.go
  components/ias-adapter/internal/errors/errors.go
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
  components/ias-adapter/internal/service/tenant_mapping.go
Labels: approved, size/L, lgtm

#3320 [HotFix] Adjust IAS Adapter version
  chart/compass/values.yaml
Labels: size/XS

#3317 Enhance global registry template
  chart/compass/values.yaml
  components/external-services-mock/internal/ord-aggregator/globalregistry/template.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#3322 Remove backwards compatible code regarding the new scenario groups format
  chart/compass/values.yaml
  components/director/internal/domain/onetimetoken/service.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon

#3306 Adopt latest ORD specification - v1.3.0 + v1.3.2 + v1.3.3
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/domain/package/converter.go
  components/director/internal/domain/package/entity.go
  components/director/internal/domain/package/fixtures_test.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/package.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/schema-migrator/migrations/director/20230925135359_add_direction_to_apis_and_impl_standard_to_events.down.sql
  components/schema-migrator/migrations/director/20230925135359_add_direction_to_apis_and_impl_standard_to_events.up.sql
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#3325 Adjust released components versions
  chart/compass/values.yaml
Labels: :wave: request review, size/M, approved, lgtm

#3327 Minor ORD Operation Consumer improvements
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/ord-aggregator/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/open_resource_discovery/apiclient/client.go
  components/director/internal/open_resource_discovery/apiclient/client_test.go
  components/director/internal/open_resource_discovery/apiclient/config.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/handler_test.go
  components/director/internal/open_resource_discovery/operation_maintainer_test.go
  components/director/internal/open_resource_discovery/service.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#3328 Add execution time details in test logs
  installation/scripts/testing.sh
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3324 Add graphQL query to find the root parent tenant of a given tenant
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/examples/get-root-tenant/get-root-tenant.graphql
  components/director/hack/config-local.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/automock/tenant_mapping_repository.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/tenants_api_test.go
  tests/pkg/fixtures/fixtures.go
Labels: approved, size/XL, lgtm

#3332 Update all cronjob api versions
  chart/compass/charts/director/templates/ext-svc-certificate-rotation-job.yaml
  chart/compass/charts/director/templates/external-certificate-rotation-job.yaml
  chart/compass/charts/director/templates/tenant-loader-cronjob-external.yaml
  chart/compass/templates/system-fetcher-job.yaml
Labels: size/XS, approved, lgtm

#3335 Update values.yaml
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm

#3334 Adapt PodDisruptionBudget and HorizontalPodAutoscaler
  chart/ory/charts/gcloud-sqlproxy/templates/horizontalpodautoscaler.yaml
  chart/ory/charts/gcloud-sqlproxy/templates/pdb.yaml
Labels: size/XS, approved, lgtm

#3336 Kyma Adapter does not properly handle empty configuration
  chart/compass/values.yaml
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/formationnotification/handler.go
  components/external-services-mock/internal/formationnotification/handler_test.go
  components/kyma-adapter/internal/handler/handler.go
  components/kyma-adapter/internal/handler/handler_test.go
  components/kyma-adapter/internal/types/credentials/credentials.go
  components/kyma-adapter/internal/types/tenantmapping/tenant_mapping.go
  tests/director/tests/notifications/kyma_tenant_mapping_adapter_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3337 Adapt sandbox tests after splitting director test definition
  tests/director/Makefile
  tests/director/tests/application/Makefile
  tests/director/tests/formation/Makefile
  tests/director/tests/notifications/Makefile
  tests/director/tests/runtime/Makefile
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#3326 Kyma 2.6.3
  README.md
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/scripts/install-compass.sh
  installation/scripts/install-db.sh
  installation/scripts/install-kyma.sh
  installation/scripts/install-ory.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#3341 Update values.yaml
  chart/compass/values.yaml
Labels: size/S, approved, lgtm
