Repository kyma-incubator/compass, pull requests merged in 2023-02, with the labels that each got.

#2856 fix operator name
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20230120090249_introduce_formation_constraints.up.sql
Labels: size/XS, approved, lgtm

#2855 Fix cleanup in e2e tests
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/runtime_queries.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2857 Fix wrong arguments in defer func invocation
  chart/compass/values.yaml
  tests/ord-service/tests/subscription_flow_test.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#2858 [HOTFIX] Fix cleanup in e2e tests
  chart/compass/values.yaml
  tests/director/tests/application_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/runtime_queries.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor

#2866 Fix external cert secret reference
  chart/compass/values.yaml
  tests/director/tests/cert_subject_mapping_test.go
Labels: size/XS, approved, lgtm

#2867 Minor improvements
  chart/compass/values.yaml
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/service.go
  components/director/internal/domain/formationtemplate/service_test.go
  components/director/internal/repo/delete.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2863 Monitors and Alerts for Certificates Expirations
  chart/compass/templates/cert-manager-grafana-dashboard.yaml
  chart/compass/templates/cert-manager-prometheus-alerts.yaml
Labels: approved, size/L, lgtm, :eagle: team-falcon

#2871 Introduce Managed Application Provider Operator consumer type
  chart/compass/values.yaml
  components/director/pkg/consumer/consumer.go
  components/director/pkg/inputvalidation/validators_cert_subject_mappings.go
  components/director/pkg/model/system_auth.go
  components/hydrator/go.mod
  components/hydrator/go.sum
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2869 Support arbitrary parameters in spii
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/webhook/converter.go
  components/director/internal/domain/webhook/entity.go
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/model/webhook.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/json.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/20230207110700_add-parameters-column-in-webhooks.down.sql
  components/schema-migrator/migrations/director/20230207110700_add-parameters-column-in-webhooks.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/application_templates_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2872 ORD Aggregation of C4C CNS fails with local tenant id is required
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/pkg/accessstrategy/cmp_mtls_access_strategy.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2878 Remove certificate subject mapping consumet_type DB constraint
  chart/compass/values.yaml
  components/director/pkg/graphql/cert_subject_mapping_validation.go
  components/schema-migrator/migrations/director/20230209181651_remove-consumer-type-constraint.down.sql
  components/schema-migrator/migrations/director/20230209181651_remove-consumer-type-constraint.up.sql
Labels: size/S, approved, lgtm

#2880 Revert webhook parameters
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/webhook/converter.go
  components/director/internal/domain/webhook/entity.go
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/model/webhook.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/json.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/20230210120700_remove-parameters-column-in-webhooks.down.sql
  components/schema-migrator/migrations/director/20230210120700_remove-parameters-column-in-webhooks.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/formation_constraint_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/constraint_reference_queries.go
  tests/pkg/fixtures/constraint_reference_requests.go
  tests/pkg/fixtures/formation_constraint_queries.go
  tests/pkg/fixtures/formation_constraint_requests.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2879 Flip ownership for new applications
  chart/compass/values.yaml
  components/director/pkg/applicationtenancy/directive.go
  components/director/pkg/applicationtenancy/directive_test.go
Labels: size/S, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#2870 Update formation constraint
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/query-formation-constraint/query-formation-constraint.graphql
  components/director/examples/update-formation-constraint/update-formation-constraint.graphql
  components/director/hack/config-local.yaml
  components/director/internal/domain/formationconstraint/automock/automatic_scenario_assignment_service.go
  components/director/internal/domain/formationconstraint/automock/entity_converter.go
  components/director/internal/domain/formationconstraint/automock/formation_constraint_converter.go
  components/director/internal/domain/formationconstraint/automock/formation_constraint_repository.go
  components/director/internal/domain/formationconstraint/automock/formation_constraint_service.go
  components/director/internal/domain/formationconstraint/automock/formation_constraint_svc.go
  components/director/internal/domain/formationconstraint/automock/formation_repository.go
  components/director/internal/domain/formationconstraint/automock/formation_template_constraint_reference_repository.go
  components/director/internal/domain/formationconstraint/automock/label_repository.go
  components/director/internal/domain/formationconstraint/automock/tenant_service.go
  components/director/internal/domain/formationconstraint/automock/uid_service.go
  components/director/internal/domain/formationconstraint/fixtures_test.go
  components/director/internal/domain/formationconstraint/repository.go
  components/director/internal/domain/formationconstraint/repository_test.go
  components/director/internal/domain/formationconstraint/resolver.go
  components/director/internal/domain/formationconstraint/resolver_test.go
  components/director/internal/domain/formationconstraint/service.go
  components/director/internal/domain/formationconstraint/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/formation_constraint_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/formation_constraint_requests.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#2885 Fix defer in formation mapping e2e test
  chart/compass/values.yaml
  tests/director/tests/formation_mapping_api_test.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#2883 Use a path concat helper function to concatenate relative paths to base URL for API in ORD Aggregator
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/ord_document.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#2886 Introduce Formation Async Status API Skeleton
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-external-mtls.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/examples/create-formation-template/create-formation-template-with-webhooks.graphql
  components/director/examples/create-formation-template/create-formation-template.graphql
  components/director/examples/delete-formation-template/delete-formation-template.graphql
  components/director/examples/query-formation-template/query-formation-template.graphql
  components/director/examples/query-formation-templates/query-formation-templates.graphql
  components/director/examples/update-formation-template/update-formation-template.graphql
  components/director/internal/domain/formation/repository.go
  components/director/internal/domain/formation/repository_test.go
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/entity.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/automock/formation_repository.go
  components/director/internal/formationmapping/automock/formation_template_repository.go
  components/director/internal/formationmapping/config.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/internal/model/formation_template.go
  components/director/pkg/graphql/formation_template.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/webhook_client/client.go
  components/director/run.sh
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/notification/handler.go
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/schema-migrator/Dockerfile
  components/schema-migrator/migrations/director/20230216132453_add-leading-product-ids-column.down.sql
  components/schema-migrator/migrations/director/20230216132453_add-leading-product-ids-column.up.sql
  components/schema-migrator/validate.sh
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/director/tests/main_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/formation_template_fixtures.go
  tests/pkg/fixtures/formation_template_queries.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2890 Fix webhook types in async status API
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/formationmapping/handler.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2891 [HOTFIX] Fix webhook types in async status API
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, :hammer: hotfix, approved, size/L, lgtm, :t-rex: team-raptor

#2892 Add App Template Read scope to MAP operator
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#2895 fix verifiers cache usage
  chart/compass/values.yaml
  components/hydrator/internal/authnmappinghandler/handler.go
  components/hydrator/internal/authnmappinghandler/handler_test.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#2896 fix verifiers cache usage
  chart/compass/values.yaml
  components/hydrator/internal/authnmappinghandler/handler.go
  components/hydrator/internal/authnmappinghandler/handler_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor

#2898 Formation deleteion fix
  chart/compass/values.yaml
  components/director/internal/domain/labeldef/service.go
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#2897 Bump alpine to 3.17.2
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2884 Fail when deleting Application if it is part of formation
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connectivity-adapter/tests/connector_test.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/viewer_test.go
  tests/ord-service/tests/api_test.go
  tests/pkg/fixtures/application_queries.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2899 Switch helm driver to sql on local env
  docs/compass/04-01-installation.md
  installation/cmd/run.sh
  installation/scripts/install-compass.sh
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2900 Bring out *.png and *.md files from compass chart
  chart/docs/configure-managed-gcp-postgresql.md
  chart/docs/png/instance-connection-string.png
  chart/docs/png/sql-instances-list.png
Labels: size/XS, approved, lgtm

#2903 Fix install-compass.sh
  installation/scripts/install-compass.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#2902 Adopt newest ORD Version
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2904 Fix formation constraint list for formation template
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/repository.go
  tests/director/tests/formation_constraint_api_test.go
  tests/pkg/fixtures/formation_constraint_queries.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor

#2907 Support optional application template placeholders
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/converter.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/model/app_template.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: :wave: request review, size/M, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#2905 Minor improvements
  chart/compass/values.yaml
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/model/formation_template.go
  components/director/pkg/graphql/formation_template.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/notification/handler.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/authnmappinghandler/handler.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider_test.go
  components/hydrator/internal/tenantmapping/user_context_provider_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/formation_templates_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/formation_template_fixtures.go
  tests/pkg/fixtures/formation_template_queries.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#2910 Defer application unassignment in benchmark tests
  chart/compass/values.yaml
  tests/director/bench/application_api_test.go
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#2909 Fix required unused tenant in async API
  chart/compass/values.yaml
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/fixtures_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor

#2906 Do not allow systems merge if there are existing formations associated with the source system
  chart/compass/values.yaml
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  installation/scripts/kyma-scripts/testing-common.sh
  installation/scripts/prow/uninstall-compass.sh
  installation/scripts/uninstall-compass.sh
  tests/director/tests/application_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#2889 remove asa mutations
  chart/compass/charts/director/config.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/create-automatic-scenario-assignment/create-automatic-scenario-assignment.graphql
  components/director/examples/delete-automatic-scenario-assignment-for-scenario/delete-automatic-scenario-assignment-for-scenario.graphql
  components/director/examples/delete-automatic-scenario-assignments-for-selector/delete-automatic-scenario-assignments-for-selector.graphql
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/automock/asa_service.go
  components/director/internal/domain/scenarioassignment/automock/entity_converter.go
  components/director/internal/domain/scenarioassignment/automock/formation_service.go
  components/director/internal/domain/scenarioassignment/automock/gql_converter.go
  components/director/internal/domain/scenarioassignment/automock/repository.go
  components/director/internal/domain/scenarioassignment/automock/scenarios_def_service.go
  components/director/internal/domain/scenarioassignment/automock/tenant_fetcher.go
  components/director/internal/domain/scenarioassignment/automock/tenant_service.go
  components/director/internal/domain/scenarioassignment/converter.go
  components/director/internal/domain/scenarioassignment/converter_test.go
  components/director/internal/domain/scenarioassignment/fixtures_test.go
  components/director/internal/domain/scenarioassignment/resolver.go
  components/director/internal/domain/scenarioassignment/resolver_test.go
  components/director/pkg/graphql/asa_selector_validation.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  docs/compass/03-03-automatic-scenario-assignment.md
  docs/compass/assets/automatic-scenario-assign.svg
  tests/pkg/token/token_utils.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#2917 Minor improvements
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/service.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#2793 Make ORD Aggregator deployment
  CODEOWNERS
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/ord-aggregator/.helmignore
  chart/compass/charts/ord-aggregator/Chart.yaml
  chart/compass/charts/ord-aggregator/OWNERS
  chart/compass/charts/ord-aggregator/templates/deployment.yaml
  chart/compass/charts/ord-aggregator/templates/rbac.yaml
  chart/compass/charts/ord-aggregator/templates/service.yaml
  chart/compass/charts/ord-aggregator/values.yaml
  chart/compass/templates/ord-aggregator-job.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/director/Makefile
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/formation/repository.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationconstraint/repository.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/labeldef/service.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/open_resource_discovery/automock/ord_service.go
  components/director/internal/open_resource_discovery/automock/webhook_service.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/handler_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/hydrator/internal/authnmappinghandler/handler.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2919 [Hotfix] Fix method godoc
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
Labels: size/XS, approved, lgtm

#2914 Adopt new ORD Versions - 1.1.3 and 1.1.4
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/schema-migrator/migrations/director/20230224160000_add_policy_level_to_apis_and_events.down.sql
  components/schema-migrator/migrations/director/20230224160000_add_policy_level_to_apis_and_events.up.sql
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#2901 Filter ORD Service response based on formations for SaaS application consumers
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20230225090249_ord_filter_by_formations.down.sql
  components/schema-migrator/migrations/director/20230225090249_ord_filter_by_formations.up.sql
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/formation_template_queries.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#2864 Add team Falcon to TF OWNERS files
  chart/compass/charts/tenant-fetcher/OWNERS
  components/director/cmd/tenantfetcher-svc/OWNERS
  components/director/internal/tenantfetchersvc/OWNERS
  tests/tenant-fetcher/OWNERS
Labels: size/S, lgtm, :dragon: team-dragon

#2921 Improve e2e test cleanup
  chart/compass/values.yaml
  tests/director/tests/labeling_api_test.go
  tests/director/tests/runtime_api_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#2888 Formation Notification Resynchronization
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/hack/config-local.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/formation_assignment_notifications_service.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/export_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_repository.go
  components/director/internal/domain/formationassignment/converter_test.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/apperrors/consts.go
  components/director/pkg/apperrors/errors.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/notification/handler.go
  tests/director/tests/formation_api_test.go
  tests/pkg/fixtures/application_fixtures.go
  tests/pkg/fixtures/fomation_requests.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/runtime_fixtures.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon
