Repository kyma-incubator/compass, pull requests merged in 2023-08, with the labels that each got.

#3190 Release v1.69.0
  chart/compass/values.yaml
Labels: size/M, approved, lgtm

#3187 Use service layer to handle CSM on AT Deletion
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/apptemplate/automock/cert_subject_mapping_service.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/certsubjectmapping/automock/cert_mapping_repository.go
  components/director/internal/domain/certsubjectmapping/repository.go
  components/director/internal/domain/certsubjectmapping/repository_test.go
  components/director/internal/domain/certsubjectmapping/service.go
  components/director/internal/domain/certsubjectmapping/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/run.sh
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/cert_subject_mapping_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3177 Forbid creation of cert subject mappings with the same subject
  chart/compass/values.yaml
  components/director/internal/domain/certsubjectmapping/fixtures_test.go
  components/director/internal/domain/certsubjectmapping/repository.go
  components/director/internal/domain/certsubjectmapping/resolver.go
  components/director/internal/domain/certsubjectmapping/resolver_test.go
  tests/director/tests/cert_subject_mapping_test.go
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3185 Add logs to e2e test execution
  installation/scripts/testing.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#3188 Small improvement in the installation script
  installation/cmd/run.sh
  installation/scripts/install-compass.sh
  installation/scripts/install-db.sh
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#3194 Fix benchmark test
  installation/scripts/gcp.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor

#3196 Skip audit log test on dev and dev-main
  chart/compass/values.yaml
  tests/external-services-mock/tests/auditlog_integration_test.go
Labels: :wave: request review, approved, size/L, lgtm

#3183 Bump kyma adapter golang base image
  chart/compass/values.yaml
  components/kyma-adapter/Dockerfile
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#3195 Fix missing tenant region in tenant fetcher
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon, :dragon: team-dragon

#3199 [HOTFIX] Fix tnt fetcher region
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
Labels: size/S, :eagle: team-falcon, :dragon: team-dragon

#3200 [HOTFIX] Change dir and versions
  chart/compass/values.yaml
Labels: size/XS

#3202 Fix benchmark job
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: :wave: request review, size/XS, approved, lgtm

#3198 Get app by local tenant id and app template id
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/query-application/query-application-by-local-tenant-id-and-app-template-id.graphql
  components/director/hack/config-local.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application_api_test.go
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#3205 [HOTFIX] Change operation in status API
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
Labels: :hammer: hotfix, size/XS, approved, lgtm, :t-rex: team-raptor

#3207 Change operation in status API
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor

#3203 Extend Destination Creator operator
  chart/compass/values.yaml
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/destinationcreator/types.go
  components/director/internal/domain/certsubjectmapping/repository.go
  components/director/internal/domain/certsubjectmapping/resolver.go
  components/director/internal/domain/destination/automock/destination_creator_service.go
  components/director/internal/domain/destination/fixtures_test.go
  components/director/internal/domain/destination/repository_test.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/destination/service_test.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_creator_service.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_service.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/do_not_generate_formation_assignment_notification_test.go
  components/director/internal/domain/formationconstraint/operators/does_not_contain_resource_of_subtype_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/is_not_assigned_to_any_formation_of_type_operator_test.go
  components/director/pkg/destinationcreator/types.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationcreator/fixtures_test.go
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/destinationcreator/types.go
  components/external-services-mock/internal/formationnotification/handler.go
  components/external-services-mock/pkg/destinationcreator/types.go
  tests/director/tests/formation_api_test.go
  tests/external-services-mock/tests/auditlog_integration_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/formation_assignment_queries.go
Labels: size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#3211 Release 1.70.0
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3180 Production ready s4 proxy
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/service.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/internal/domain/application/config.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/webhook/converter.go
  components/director/internal/domain/webhook/converter_test.go
  components/director/internal/domain/webhook/entity.go
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/repository.go
  components/director/internal/domain/webhook/repository_test.go
  components/director/internal/domain/webhook/resolver_test.go
  components/director/internal/domain/webhook/service_test.go
  components/director/internal/model/webhook.go
  components/director/internal/open_resource_discovery/automock/client.go
  components/director/internal/open_resource_discovery/automock/fetch_request_service.go
  components/director/internal/open_resource_discovery/automock/label_service.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/global_registry.go
  components/director/internal/open_resource_discovery/global_registry_test.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/pkg/accessstrategy/access_strategy.go
  components/director/pkg/accessstrategy/automock/executor.go
  components/director/pkg/accessstrategy/cmp_mtls_access_strategy.go
  components/director/pkg/accessstrategy/open_access_strategy.go
  components/director/pkg/accessstrategy/open_access_strategy_test.go
  components/director/pkg/webhook/open_resource_discovery.go
  components/director/run.sh
  components/external-services-mock/cmd/main.go
  components/schema-migrator/migrations/director/20230807151800_add_proxy_url_to_webhooks.down.sql
  components/schema-migrator/migrations/director/20230807151800_add_proxy_url_to_webhooks.up.sql
  installation/resources/compass-overrides-local.yaml
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :eagle: team-falcon

#3212 Minor improvements around DC operator test
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/main_test.go
  tests/go.mod
  tests/go.sum
  tests/ord-aggregator/tests/registry_client.go
Labels: approved, size/L, lgtm, :eagle: team-falcon

#3213 [HOTFIX] Minor improvements around DC operator test
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/main_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, size/L, lgtm

#3217 change registry and version
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3204 Do not Override localTenantID when it is provided from placeholder
  chart/compass/values.yaml
  components/director/internal/domain/subscription/service.go
  tests/director/tests/formation_api_test.go
Labels: size/XS, approved, lgtm

#3218 [HOTFIX] Fix assert in e2e tests
  chart/compass/values.yaml
  tests/director/tests/formation_api_test.go
Labels: size/S, approved, lgtm

#3219 Fix assert in e2e tests
  chart/compass/values.yaml
  tests/director/tests/formation_api_test.go
Labels: size/S, approved, lgtm

#3220 [HOTFIX] Update image registry and version in hotfix branch
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3221 Adjust image versions for release
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3222 Remove operation manager deployment
  CODEOWNERS
  chart/compass/charts/operations-manager/.helmignore
  chart/compass/charts/operations-manager/Chart.yaml
  chart/compass/charts/operations-manager/OWNERS
  chart/compass/charts/operations-manager/templates/deployment.yaml
  chart/compass/charts/operations-manager/templates/rback.yaml
  chart/compass/charts/operations-manager/templates/service.yaml
  chart/compass/charts/operations-manager/values.yaml
  chart/compass/values.yaml
  components/director/Dockerfile
  components/director/Makefile
  components/director/cmd/operations-manager/OWNERS
  components/director/cmd/operations-manager/main.go
Labels: approved, size/XL, lgtm, :eagle: team-falcon

#3227 Rename operation finished_at column to updated_at
  chart/compass/values.yaml
  components/director/internal/domain/operation/automock/operation_repository.go
  components/director/internal/domain/operation/converter.go
  components/director/internal/domain/operation/converter_test.go
  components/director/internal/domain/operation/entity.go
  components/director/internal/domain/operation/fixtures_test.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/operation/repository_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/model/operation.go
  components/director/internal/model/operation_test.go
  components/director/internal/operations_manager/automock/operation_service.go
  components/director/internal/operations_manager/interfaces.go
  components/director/internal/operations_manager/opcreator.go
  components/director/internal/operations_manager/service.go
  components/director/internal/operations_manager/service_test.go
  components/schema-migrator/migrations/director/20230816144758_rename_finished_at_to_updated_at_in_operation_table.down.sql
  components/schema-migrator/migrations/director/20230816144758_rename_finished_at_to_updated_at_in_operation_table.up.sql
Labels: approved, size/XL, lgtm

#3231 Create db view for all scheduled operations
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20230817092855_create_view_for_all_scheduled_operations.down.sql
  components/schema-migrator/migrations/director/20230817092855_create_view_for_all_scheduled_operations.up.sql
Labels: size/S, approved, lgtm

#3234 Add missing transaction commit in aggregator
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#3236 Add missing transaction commit in aggregator
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon

#3237 adjust PR version
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3228 [HOTFIX STAGE] Destination creator operator improvement
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/M, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3242 [HOTFIX DEV] Destination creator operator improvement
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3238 Destination creator operator improvement
  chart/compass/charts/operations-controller/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/pkg/webhook_client/client.go
  components/director/pkg/webhook_client/client_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3244 [HOTFIX STAGE] Update image registry and version in hotfix branch
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3245 [HOTFIX DEV] Update image registry and version in hotfix branch
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3240 Fix error handling in the formation status API
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor

#3243 Fix concurrent write iteration
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/internal/destinationcreator/automock/destination_repository.go
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/fetchrequest/service.go
  components/director/internal/domain/fetchrequest/service_test.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/operation/repository_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/open_resource_discovery/automock/fetch_request_service.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/global_registry_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/pkg/accessstrategy/access_strategy.go
  components/director/pkg/accessstrategy/automock/executor.go
  components/director/pkg/accessstrategy/cmp_mtls_access_strategy.go
  components/director/pkg/accessstrategy/open_access_strategy.go
  components/director/pkg/accessstrategy/open_access_strategy_test.go
  components/director/pkg/webhook/open_resource_discovery.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/ord-aggregator/tests/registry_client.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3189 Adopt ORD v1.2.4
  chart/compass/values.yaml
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/api/entity.go
  components/director/internal/domain/api/fixtures_test.go
  components/director/internal/domain/api/repository.go
  components/director/internal/domain/api/repository_test.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/eventdef/entity.go
  components/director/internal/domain/eventdef/fixtures_test.go
  components/director/internal/domain/eventdef/repository.go
  components/director/internal/domain/eventdef/repository_test.go
  components/director/internal/model/api.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/version.go
  components/schema-migrator/migrations/director/20230822092554_add-correlation-ids-to-apis-and-events.down.sql
  components/schema-migrator/migrations/director/20230822092554_add-correlation-ids-to-apis-and-events.up.sql
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#3252 Update versions for v1.73.2 hotfix
  chart/compass/values.yaml
Labels: size/M

#3208 Introduce FormationTemplatesByName
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/examples/README.md
  components/director/examples/query-formation-templates-by-name/query-formation-templates-by-name.graphql
  components/director/hack/config-local.yaml
  components/director/internal/domain/formationtemplate/automock/entity_converter.go
  components/director/internal/domain/formationtemplate/automock/formation_constraint_service.go
  components/director/internal/domain/formationtemplate/automock/formation_template_converter.go
  components/director/internal/domain/formationtemplate/automock/formation_template_repository.go
  components/director/internal/domain/formationtemplate/automock/formation_template_service.go
  components/director/internal/domain/formationtemplate/automock/tenant_service.go
  components/director/internal/domain/formationtemplate/automock/webhook_converter.go
  components/director/internal/domain/formationtemplate/automock/webhook_service.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/internal/domain/formationtemplate/resolver.go
  components/director/internal/domain/formationtemplate/resolver_test.go
  components/director/internal/domain/formationtemplate/service.go
  components/director/internal/domain/formationtemplate/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/repo/testdb/generic_repo_list_tests.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/formation_templates_test.go
  tests/pkg/fixtures/formation_template_requests.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3232 Implement operations manager
  chart/compass/values.yaml
  components/director/internal/domain/operation/automock/operation_repository.go
  components/director/internal/domain/operation/converter.go
  components/director/internal/domain/operation/converter_test.go
  components/director/internal/domain/operation/entity.go
  components/director/internal/domain/operation/fixtures_test.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/operation/repository_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/model/operation.go
  components/director/internal/model/product.go
  components/director/internal/model/vendor.go
  components/director/internal/operations_manager/automock/operation_service.go
  components/director/internal/operations_manager/interfaces.go
  components/director/internal/repo/function.go
  components/director/internal/repo/function_test.go
  components/director/internal/repo/get.go
  components/director/internal/repo/list.go
  components/director/internal/repo/query_builder.go
  components/director/internal/repo/update.go
  components/director/internal/util/uuid.go
  components/director/internal/util/uuid_test.go
  components/director/pkg/apperrors/consts.go
  components/director/pkg/apperrors/errors.go
  components/director/pkg/operations_manager/operations_manager.go
  components/director/pkg/operations_manager/operations_manager_config.go
  components/director/pkg/operations_manager/operations_manager_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon

#3255 Remove Ory ns deletion
  installation/scripts/install-ory.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3257 [HOTFIX] Fix hydrator retries
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/authenticator/claims/validators_test.go
  components/hydrator/cmd/main.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/director/client.go
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/access_level_context_provider_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  components/ias-adapter/internal/api/middlewares/auth.go
  components/ias-adapter/internal/api/server.go
  components/kyma-adapter/internal/tenant/validator.go
  components/kyma-adapter/internal/tenant/validator_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/kyma_tenant_mapping_adapter_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/external-services-mock/tests/main_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-service/tests/api_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/fixtures/application_template_queries.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3258 Bump components versions for hotfix
  chart/compass/values.yaml
Labels: size/S, approved, lgtm

#3254 Remove unneeded Hydrator retries
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/values.yaml
  components/director/internal/authenticator/claims/validator.go
  components/director/internal/authenticator/claims/validators_test.go
  components/hydrator/cmd/main.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/director/client.go
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/access_level_context_provider_test.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider_test.go
  components/ias-adapter/internal/api/middlewares/auth.go
  components/ias-adapter/internal/api/server.go
  components/kyma-adapter/internal/tenant/validator.go
  components/kyma-adapter/internal/tenant/validator_test.go
  tests/director/tests/application_api_test.go
  tests/director/tests/application_templates_api_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/kyma_tenant_mapping_adapter_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-aggregator/tests/main_test.go
  tests/ord-service/tests/api_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/fixtures/application_template_queries.go
  tests/pkg/tenant/tenant_setup.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3263 Remove region value for test tenant
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3262 [HOTFIX] Remove region value for test tenant
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm

#3259 Allow BTP Applications onboarded as Application Templates to consume ORD Service APIs
  chart/compass/charts/destination-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/cmd/destinationfetcher-svc/main.go
  components/director/internal/destinationfetchersvc/automock/destination_manager.go
  components/director/internal/destinationfetchersvc/automock/tenant_repo.go
  components/director/internal/destinationfetchersvc/handler.go
  components/director/internal/destinationfetchersvc/handler_test.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/service_test.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/repo/exist.go
  components/director/internal/repo/exist_test.go
  tests/director/tests/application_templates_subscription_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon

#3256 Make destination creator operator more flexible
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/webhook/datainputbuilder/builder_test.go
  components/director/internal/healthz/ready_test.go
  components/director/internal/systemfetcher/template_test.go
  tests/director/tests/formation_api_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3264 [HOTFIX] Fa race condition fix
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor

#3268 Observe operation type when reschedule operations
  chart/compass/values.yaml
  components/director/internal/domain/operation/automock/operation_repository.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/operation/repository_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/operations_manager/automock/operation_service.go
  components/director/internal/operations_manager/interfaces.go
  components/director/pkg/operations_manager/operations_manager.go
Labels: size/M, approved, lgtm

#3239 FA not present when updating status
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor

#3269 Adapt smoke test provision script to work with prod registry also
  installation/scripts/prow/jobs/provision-compass-smoke-test.sh
Labels: size/S, approved, lgtm

#3248 Minor improvements
  chart/compass/values.yaml
  components/director/internal/domain/formationtemplate/automock/entity_converter.go
  components/director/internal/domain/formationtemplate/automock/formation_constraint_service.go
  components/director/internal/domain/formationtemplate/automock/formation_template_converter.go
  components/director/internal/domain/formationtemplate/automock/formation_template_repository.go
  components/director/internal/domain/formationtemplate/automock/formation_template_service.go
  components/director/internal/domain/formationtemplate/automock/tenant_service.go
  components/director/internal/domain/formationtemplate/automock/webhook_converter.go
  components/director/internal/domain/formationtemplate/automock/webhook_service.go
  components/director/internal/formationmapping/handler.go
  components/external-services-mock/internal/destinationcreator/fixtures_test.go
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/destinationcreator/handler_test.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/formation_api_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3270 Bump versions for v1.74.0 release
  chart/compass/values.yaml
Labels: size/M, approved, lgtm

#3272 Add logs when a test fails during e2e test execution
  installation/scripts/testing.sh
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor

#3277 [HOTFIX] Fix HTTP clients
  chart/compass/values.yaml
  components/director/cmd/director/main.go
Labels: size/XS, approved, lgtm

#3274 [HOTFIX] Change gql query used in e2e test
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/fields.go
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/application_requests.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor

#3276 Fix HTTP clients
  chart/compass/values.yaml
  components/director/cmd/director/main.go
Labels: size/XS, approved, lgtm

#3271 Add formation information in the webhooks
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/notification_builder.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notificationbuilder_test.go
  components/director/internal/domain/formation/notifications_generator.go
  components/director/internal/domain/formation/notifications_generator_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/automock/notification_builder.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/graphql/formation_constraint_validation.go
  components/director/pkg/graphql/webhook_validation.go
  components/director/pkg/webhook/application_tenant_mapping.go
  components/director/pkg/webhook/formation_configuration_change.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, size/XL, lgtm, :t-rex: team-raptor

#3280 Change gql query used in e2e test
  chart/compass/values.yaml
  components/director/pkg/graphql/graphqlizer/fields.go
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/application_requests.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor
