Repository kyma-incubator/compass, pull requests merged in 2023-07, with the labels that each got.

#3151 Add ProwJob scripts
  installation/scripts/prow/jobs/clean-vm-compass.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-vm-compass-smoke-test.sh
  installation/scripts/prow/jobs/provision-vm-compass.sh
  installation/scripts/prow/jobs/validate-compass-generic.sh
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3159 redact user data before logging
  chart/compass/values.yaml
  components/hydrator/internal/tenantmapping/access_level_context_provider.go
  components/hydrator/internal/tenantmapping/authenticator_context_provider.go
  components/hydrator/internal/tenantmapping/cert_service_context_provider.go
  components/hydrator/internal/tenantmapping/consumer_context_provider.go
  components/hydrator/internal/tenantmapping/model.go
  components/hydrator/internal/tenantmapping/system_auth_context_provider.go
  components/hydrator/internal/tenantmapping/user_context_provider.go
  components/hydrator/internal/tenantmapping/user_context_provider_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3125 Fix fetch tenant on demand to work with empty parent
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/synchronizer_test.go
  components/director/pkg/apperrors/consts.go
  components/director/pkg/apperrors/errors.go
Labels: approved, size/L, lgtm, :eagle: team-falcon, :dragon: team-dragon

#3160 Release 1.67.0
  chart/compass/values.yaml
Labels: size/M, approved, lgtm

#3164 Implement tenant on demand e2e test
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/pkg/apperrors/errors.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/internal/tenantfetcher/handler.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, :dragon: team-dragon

#3167 Add ognyan as owner
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#3165 Switch to e2e-dind-k3d
  installation/cmd/run.sh
  installation/scripts/prow/compass-smoke-test.sh
  installation/scripts/prow/execute-tests.sh
  installation/scripts/prow/jobs/clean-vm-compass.sh
  installation/scripts/prow/jobs/provision-compass-smoke-test.sh
  installation/scripts/prow/jobs/provision-compass.sh
  installation/scripts/prow/jobs/provision-vm-compass.sh
  installation/scripts/prow/provision.sh
  installation/scripts/prow/uninstall-compass.sh
  installation/scripts/prow/update-compass.sh
Labels: approved, size/XL, lgtm, :t-rex: team-raptor

#3156 Support SAP Graph tenants via Integration Suite
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/subscription_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/subscription/automock/subscription_service.go
  components/director/internal/domain/subscription/fixtures_test.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/resolver_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/internal/tenantfetchersvc/automock/director_graph_ql_client.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/subscriber.go
  components/director/internal/tenantfetchersvc/subscriber_test.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/graphql_client/director_client.go
  components/director/run
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/provider/handler.go
  components/external-services-mock/internal/provider/handler_test.go
  components/external-services-mock/internal/selfreg/handler.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  components/external-services-mock/internal/subscription/testdata/jwks-private.json
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/application_templates_subscription_test.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_mapping_api_test.go
  tests/director/tests/main_test.go
  tests/director/tests/runtime_contexts_api_test.go
  tests/go.mod
  tests/go.sum
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/fixtures/application_queries.go
  tests/pkg/subscription/config.go
  tests/pkg/subscription/utils.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3157 Kyma Tenant Mapping Adapter Implementation
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/kyma-adapter/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/operations-manager/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/bundle/service.go
  components/director/internal/domain/bundle/service_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/fixtures_test.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/features/features.go
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/handler_test.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/consumer/consumertest/consumertest.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/notification/handler.go
  components/external-services-mock/internal/notification/handler_test.go
  components/kyma-adapter/Makefile
  components/kyma-adapter/cmd/main.go
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/kyma-adapter/internal/config/config.go
  components/kyma-adapter/internal/gqlclient/gqlclient.go
  components/kyma-adapter/internal/handler/automock/client.go
  components/kyma-adapter/internal/handler/handler.go
  components/kyma-adapter/internal/handler/handler_test.go
  components/kyma-adapter/internal/handler/utils.go
  components/kyma-adapter/internal/types/credentials/credentials.go
  components/kyma-adapter/internal/types/tenantmapping/tenant_mapping.go
  components/schema-migrator/migrations/director/20230630154541_add_reset_option_to_kyma_formation_template.down.sql
  components/schema-migrator/migrations/director/20230630154541_add_reset_option_to_kyma_formation_template.up.sql
  tests/director/tests/kyma_tenant_mapping_adapter_test.go
  tests/director/tests/runtime_api_test.go
  tests/pkg/assertions/assertions.go
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3163 Split Formation assignment error and configuration
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/converter.go
  components/director/internal/domain/formationassignment/converter_test.go
  components/director/internal/domain/formationassignment/entity.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/model/formation_assignment.go
  components/director/pkg/graphql/formation_constraint_validation.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/str/strings.go
  components/director/pkg/webhook/application_tenant_mapping.go
  components/director/pkg/webhook/formation_configuration_change.go
  components/schema-migrator/migrations/director/20230706092857_add-error-column-to-formation-assignments.down.sql
  components/schema-migrator/migrations/director/20230706092857_add-error-column-to-formation-assignments.up.sql
  tests/director/tests/formation_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/formation_assignment_queries.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3169 LastSyncTimestamp should calculate the time.Now() value before sending requests to SLIS
  chart/compass/values.yaml
  components/director/internal/systemfetcher/service.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon

#3171 Fix kyma adapter e2e test
  chart/compass/values.yaml
  tests/director/tests/kyma_tenant_mapping_adapter_test.go
Labels: size/S, approved, lgtm

#3173 Release 1.68.0
  chart/compass/values.yaml
Labels: size/M, approved, lgtm

#3170 Bump base images
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/director/Dockerfile
  components/director/run
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/ias-adapter/Dockerfile
  components/kyma-adapter/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  installation/scripts/prow/compass-smoke-test.sh
  tests/Dockerfile
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3181 Improve kyma-adapter e2e test.
  chart/compass/values.yaml
  tests/director/tests/kyma_tenant_mapping_adapter_test.go
Labels: size/XS, approved, lgtm, to be released :rocket:
