Repository kyma-incubator/compass, pull requests merged in 2023-05, with the labels that each got.

#3042 Improve cleanup in e2e tests
  chart/compass/values.yaml
  tests/director/tests/formation_api_test.go
Labels: size/S, approved, lgtm

#3047 IAS Adapter add state check
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/api/internal/response.go
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: approved, size/L, lgtm

#3048 Fix token fetch in destination fetcher
  components/director/internal/destinationfetchersvc/client.go
Labels: size/XS, approved, lgtm

#3017 Allow for returning state in the response body for sync TM Notifications instead of relying on status codes only
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/model/formation_assignment.go
  components/director/pkg/webhook/types.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/notification/handler.go
  components/external-services-mock/internal/notification/handler_test.go
  tests/director/tests/formation_api_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor

#3049 Refactor dest fetcher
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
Labels: size/XS, approved, lgtm

#3051 Change the log level to info on update/delete app template mutations
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
Labels: :wave: request review, size/XS, approved, lgtm

#3050 [HOTFIX] Fix token fetch in destination fetcher
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
Labels: size/XS, approved, lgtm

#3053 [HOTFIX] Fix runtime update
  chart/compass/values.yaml
  components/director/internal/domain/runtime/service.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
Labels: :hammer: hotfix, size/M, approved, lgtm, :t-rex: team-raptor

#3054 Fix runtime update
  chart/compass/values.yaml
  components/director/internal/domain/runtime/service.go
  components/director/internal/model/runtime.go
  components/director/internal/model/runtime_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor

#3055 Fix token header in destination fetcher
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
Labels: size/XS, approved, lgtm

#3056 [HOTFIX] Fix token header in destination fetcher
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
Labels: size/XS, approved, lgtm

#3052 Decrease requests to SLIS by leveraging lastChangeDateTime filter
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/cmd/systemfetcher/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/systemssync/automock/entity_converter.go
  components/director/internal/domain/systemssync/automock/systems_sync_repository.go
  components/director/internal/domain/systemssync/converter.go
  components/director/internal/domain/systemssync/converter_test.go
  components/director/internal/domain/systemssync/entity.go
  components/director/internal/domain/systemssync/fixtures_test.go
  components/director/internal/domain/systemssync/repository.go
  components/director/internal/domain/systemssync/repository_test.go
  components/director/internal/domain/systemssync/service.go
  components/director/internal/domain/systemssync/service_test.go
  components/director/internal/model/systems_sync.go
  components/director/internal/systemfetcher/automock/systems_sync_service.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/filter_builder.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/pkg/resource/resource.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/20230503101000_add_system_sync_timestamps.down.sql
  components/schema-migrator/migrations/director/20230503101000_add_system_sync_timestamps.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon

#3062 UCL managed app templates have invalid jsonPaths
  chart/compass/values.yaml
  components/director/internal/systemfetcher/loader.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon

#3061 [Formation constraint operator] Do not send notifications to formation participants of a given type
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formation/automock/notification_builder.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notificationbuilder_test.go
  components/director/internal/domain/formation/notifications_generator.go
  components/director/internal/domain/formation/notifications_generator_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/automock/notification_builder.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/notifications_test.go
  components/director/internal/domain/formationconstraint/automock/formation_template_repo.go
  components/director/internal/domain/formationconstraint/automock/runtime_context_repo.go
  components/director/internal/domain/formationconstraint/constraint_engine.go
  components/director/internal/domain/formationconstraint/constraint_engine_test.go
  components/director/internal/domain/formationconstraint/constraint_operators.go
  components/director/internal/domain/formationconstraint/constraint_operators_test.go
  components/director/internal/domain/formationconstraint/fixtures_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/graphql/formation_constraint_validation.go
  tests/director/tests/formation_api_test.go
  tests/director/tests/formation_constraint_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/constraint_reference_queries.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3065 Dummy PR to change commit with stuck signature
  components/director/internal/domain/formation/service.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor

#3066 Change tenant type in systems sync timestamps db table
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20230515172300_change_tenant_type_systems_sync_timestamps.down.sql
  components/schema-migrator/migrations/director/20230515172300_change_tenant_type_systems_sync_timestamps.up.sql
Labels: size/M, approved, lgtm

#3067 Update main.go
  components/external-services-mock/cmd/main.go
Labels: size/XS, approved, lgtm

#3072 TestQueryApplicationTemplates is not stable
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
Labels: :wave: request review, size/XS, approved, lgtm

#3076 Change Kyma formation type name to be title case
  chart/compass/values.yaml
  components/director/internal/model/formation.go
  components/schema-migrator/migrations/director/20230517134244_rename_kyma_formation_type.down.sql
  components/schema-migrator/migrations/director/20230517134244_rename_kyma_formation_type.up.sql
  tests/director/tests/formation_templates_test.go
Labels: size/S, approved, lgtm

#3079 Add owner to falcon
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#3075 Adjust test settings
  chart/compass/values.yaml
  tests/director/tests/application_templates_api_test.go
Labels: :wave: request review, size/XS, approved, lgtm

#3074 Decline test execution if another CTS object is present in the cluster
  installation/scripts/testing.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#3077 System Fetcher overrides original app template appInput values when merging with templateOverrideApplicationInput
  chart/compass/values.yaml
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  tests/system-fetcher/tests/handler_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon

#3080 Use atomic option for helm upgrades
  installation/scripts/install-compass.sh
  installation/scripts/install-db.sh
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor

#3071 Allow CLD-based application providers to override UCL defaults for individual properties when mapping SLIS systems
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/README.md
  components/director/cmd/systemfetcher/main.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/internal/systemfetcher/template.go
  components/director/internal/systemfetcher/template_test.go
  components/director/runSystemFetcher.sh
  installation/resources/compass-overrides-gke-benchmark.yaml
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon

#3064 Create tm webhooks during ord aggregation
  chart/compass/charts/operations-manager/templates/deployment.yaml
  chart/compass/charts/ord-aggregator/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/operations-manager/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/domain/apptemplate/automock/webhook_service.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/systemssync/service_test.go
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/service.go
  components/director/internal/domain/webhook/service_test.go
  components/director/internal/open_resource_discovery/automock/webhook_converter.go
  components/director/internal/open_resource_discovery/automock/webhook_service.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/global_registry.go
  components/director/internal/open_resource_discovery/global_registry_test.go
  components/director/internal/open_resource_discovery/interfaces.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/systemfetcher/loader.go
  components/director/internal/tenantfetchersvc/resync/builder.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3083 High number of Tenant Fetcher alerts incoming
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon, :dragon: team-dragon

#3057 Introduce new join points
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/operations-manager/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/automock/webhook_converter.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notificationbuilder.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/automock/constraint_engine.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_converter.go
  components/director/internal/domain/formationassignment/automock/formation_template_repository.go
  components/director/internal/domain/formationassignment/automock/label_service.go
  components/director/internal/domain/formationassignment/automock/notification_service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/notifications.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationconstraint/constraint_operators.go
  components/director/internal/domain/formationconstraint/fixtures_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/label_upsert_service.go
  components/director/internal/domain/webhook/converter.go
  components/director/internal/domain/webhook/converter_test.go
  components/director/internal/domain/webhook/fixtures_test.go
  components/director/internal/domain/webhook/resolver_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_converter.go
  components/director/internal/formationmapping/automock/formation_assignment_service.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/internal/model/formation_constraint.go
  components/director/internal/tenantfetchersvc/resync/builder.go
  components/director/pkg/formationconstraint/join_point_details.go
  components/director/pkg/formationconstraint/join_point_location.go
  components/director/pkg/graphql/formation_constraint_validation.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/webhook_client/types.go
  components/schema-migrator/migrations/director/20230518165828_add_two_new_target_operation_types.down.sql
  components/schema-migrator/migrations/director/20230518165828_add_two_new_target_operation_types.up.sql
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3086 Extract formation assignment updater
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/operations-manager/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_updater.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/updater.go
  components/director/internal/domain/formationassignment/updater_test.go
  components/director/internal/domain/operation/converter_test.go
  components/director/internal/domain/operation/fixtures_test.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/operation/repository_test.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/automock/formation_assignment_service.go
  components/director/internal/formationmapping/automock/formation_assignment_updater.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/internal/operations_manager/opcreator.go
  components/director/internal/operations_manager/opcreator_test.go
  components/director/internal/operations_manager/opdata.go
  components/director/internal/operations_manager/opdata_test.go
  components/director/internal/operations_manager/service.go
  components/director/internal/operations_manager/service_test.go
  components/director/internal/systemfetcher/template.go
  components/director/internal/tenantfetchersvc/resync/builder.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, :dragon: team-dragon

#3094 Fix reverse assignment state handling
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: size/S, approved, lgtm
