Repository kyma-incubator/compass, pull requests merged in 2024-06, with the labels that each got.

#3902 Allow async flow control operator to be attached to synchronous participants
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator.go
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/utils.go
  components/director/pkg/formationconstraint/formation_constraint_input.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/instance-creator/tests/config.go
  tests/instance-creator/tests/instance_creator_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, cla: yes

#3898 Improve system fetcher e2e tests
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3900 Disallow empty labels creation
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  components/director/internal/domain/label/converter.go
  components/director/internal/domain/label/converter_test.go
  components/director/internal/domain/label/entity.go
  components/director/internal/model/label.go
  tests/director/tests/application/application_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3905 Add tracing IDs in the status API
  components/director/cmd/director/main.go
Labels: size/XS, approved, lgtm, cla: yes

#3907 Suspend NS Adapter component
  components/director/Makefile
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3904 Make "Unassign Operation" creation more robust
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/pkg/apperrors/errors.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/application_only_notifications_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3903 Improve cleanup of resources in the e2e tests
  tests/connector/tests/apitests_test.go
  tests/connector/tests/hydrator_api_test.go
  tests/director/tests/application/application_api_test.go
  tests/director/tests/application/application_templates_api_test.go
  tests/director/tests/bundle_instance_auth_test.go
  tests/director/tests/certificates_access_test.go
  tests/director/tests/formation/formation_api_test.go
  tests/director/tests/integration_system_api_test.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/formation_mapping_api_test.go
  tests/director/tests/notifications/kyma_tenant_mapping_adapter_test.go
  tests/director/tests/notifications/runtime_notification_subscription_test.go
  tests/director/tests/notifications/tenant_hierarchy_notifications_test.go
  tests/director/tests/oauth20_test.go
  tests/director/tests/runtime/runtime_api_test.go
  tests/director/tests/runtime/runtime_contexts_api_test.go
  tests/director/tests/scopes_test.go
  tests/director/tests/sensitive_data_strip_test.go
  tests/director/tests/token_api_test.go
  tests/director/tests/validation_test.go
  tests/external-services-mock/tests/async_api_delete_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/compass_auth_test.go
  tests/gateway/tests/integration_system_scope_test.go
  tests/gateway/tests/tenants_test.go
  tests/gateway/tests/viewer_test.go
  tests/instance-creator/tests/instance_creator_test.go
  tests/istio/tests/request_payload_limit_test.go
  tests/ord-aggregator/tests/handler_test.go
  tests/ord-service/bench/system_bundles_test.go
  tests/ord-service/tests/api_test.go
  tests/pairing-adapter/tests/mtls_flow_test.go
  tests/pkg/fixtures/integration_system_queries.go
  tests/pkg/fixtures/runtime_queries.go
  tests/pkg/testctx/testctx.go
  tests/system-broker/tests/auth_test.go
  tests/system-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3909 Fix for failing Operation Controller tests
  components/operations-controller/Makefile
Labels: size/XS, approved, lgtm, :eagle: team-falcon, cla: yes

#3911 Remove unused code
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/formationassignment/resolver.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/scenarioassignment/service.go
  components/director/internal/domain/scenarioassignment/service_test.go
  components/director/internal/tenantfetchersvc/resync/builder.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3908 Support initial configuration during assign
  components/director/go.mod
  components/director/internal/domain/application/automock/formation_service.go
  components/director/internal/domain/application/automock/scenarios_filter_sanitizer.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/formation_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/domain/runtime_context/automock/formation_service.go
  components/director/internal/domain/runtime_context/automock/label_repository.go
  components/director/internal/domain/runtime_context/automock/label_upsert_service.go
  components/director/internal/domain/runtime_context/automock/runtime_context_repository.go
  components/director/internal/domain/runtime_context/automock/runtime_repository.go
  components/director/internal/domain/runtime_context/automock/tenant_service.go
  components/director/internal/domain/runtime_context/automock/uid_service.go
  components/director/internal/domain/runtime_context/service.go
  components/director/internal/domain/runtime_context/service_test.go
  components/director/internal/model/formation_assignment.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/graphqlizer/graphqlizer_test.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/fomation_requests.go
  tests/pkg/fixtures/formation_assignment_notifications_constants.go
  tests/pkg/fixtures/formation_queries.go
  tests/pkg/fixtures/operations_requests.go
  tests/pkg/notifications/asserters/formation_assignments.go
  tests/pkg/notifications/operations/assign_application.go
  tests/pkg/notifications/operations/cleanup_notifications.go
  tests/pkg/notifications/operations/unassign_application.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, cla: yes

#3919 [HOTFIX] Adjust deployment identifier for systems
  tests/system-fetcher/tests/handler_test.go
Labels: size/M, do-not-merge/hold, :eagle: team-falcon, cla: yes

#3918 Adjust deployment identifier for systems
  tests/system-fetcher/tests/handler_test.go
Labels: size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3921 Add migrations for breakdown of EntityType in ORD Service
  components/schema-migrator/migrations/director/20240518141635_ord_api_events_entity_types.down.sql
  components/schema-migrator/migrations/director/20240518141635_ord_api_events_entity_types.up.sql
Labels: approved, size/L, lgtm, cla: yes

#3922 [HOTFIX] Label filtering to respect source and target of FA
  components/director/internal/domain/formation/repository.go
  components/director/internal/domain/formation/repository_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3924 Hotfix remove legacy application name uniquness
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/subscription/service.go
  tests/director/tests/application/application_api_test.go
Labels: do-not-merge/hold, size/L, cla: yes
