Repository kyma-incubator/compass, pull requests merged in 2024-04, with the labels that each got.

#3763 Add formation_id in ORD Service views
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20240329112233_ord_svc_multiple_formations_dedupe.down.sql
  components/schema-migrator/migrations/director/20240329112233_ord_svc_multiple_formations_dedupe.up.sql
Labels: :wave: request review, approved, size/L, lgtm, cla: yes

#3783 [Hotfix] Adjust IAS adapter version
  chart/compass/values.yaml
Labels: size/XS, cla: yes

#3777 Add operations resolver
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/operation_converter.go
  components/director/internal/domain/application/automock/operation_service.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/operation/converter.go
  components/director/internal/domain/operation/converter_test.go
  components/director/internal/domain/operation/fixtures_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/open_resource_discovery/data/ord_operation_data.go
  components/director/internal/open_resource_discovery/data/ord_operation_data_test.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/handler_test.go
  components/director/internal/open_resource_discovery/operation_maintainer.go
  components/director/internal/open_resource_discovery/operation_processor.go
  components/director/pkg/graphql/application.go
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application/application_api_test.go
  tests/director/tests/application/application_templates_api_test.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon, cla: yes

#3782 Support for initial config for assignment when formation is in DRAFT state
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/gateway/templates/virtualservice-statusapi-token.yaml
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/values.yaml
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/auth_middleware_test.go
  components/director/internal/formationmapping/fixtures_test.go
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  installation/cmd/run.sh
  tests/director/tests/config.go
  tests/director/tests/formation/formation_api_test.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/director/tests/notifications/formation_mapping_api_test.go
  tests/director/tests/notifications/status_api_external_call_test.go
  tests/instance-creator/tests/instance_creator_test.go
  tests/pkg/fixtures/application_template_queries.go
  tests/pkg/notifications/operations/assign_application.go
  tests/pkg/notifications/resource-providers/application.go
  tests/pkg/notifications/resource-providers/application_from_template.go
  tests/pkg/notifications/resource-providers/formation.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, cla: yes

#3788 Fix status API external token authenticator
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/values.yaml
  installation/resources/compass-overrides-local.yaml
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3786 Revert changes
  chart/compass/values.yaml
  components/director/cmd/director/main.go
Labels: size/S, approved, lgtm, cla: yes

#3789 Fix TestFormationNotificationsForDraftFormationWithInitialConfig e2e test tenancy
  chart/compass/values.yaml
  components/director/internal/formationmapping/auth_middleware.go
  tests/director/tests/notifications/status_api_external_call_test.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3790 Scenarios labels log improvement
  chart/compass/values.yaml
  components/director/internal/domain/labeldef/service.go
Labels: :wave: request review, size/XS, approved, lgtm, cla: yes

#3792 Fix instance creator log parameters
  chart/compass/values.yaml
  components/instance-creator/internal/handler/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3791 Fix formationTemplate gql query not found error
  chart/compass/values.yaml
  components/director/internal/domain/formationtemplate/resolver.go
  components/director/internal/domain/formationtemplate/resolver_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3794 Ensure that configuration is provided to status reset API
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3795 Adjust release versions
  chart/compass/values.yaml
Labels: size/M, cla: yes

#3797 Fix IAS Adapter body unmarshal
  chart/compass/values.yaml
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: :wave: request review, size/XS, approved, lgtm, cla: yes, :globe_with_meridians: team-atlas

#3798 Remove leftover sync status report from IAS Adapter
  components/ias-adapter/internal/api/internal/handlers/automock/async_processor.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/service/processor/processor.go
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: :wave: request review, size/M, approved, lgtm, cla: yes, :globe_with_meridians: team-atlas

#3799 Minor log improvement
  chart/compass/values.yaml
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/service.go
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3802 Fix resynchronization when there is a participant without webhook but with error
  chart/compass/values.yaml
  components/director/internal/domain/formation/finalize_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3800 Update IAS adapter version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, cla: yes, :globe_with_meridians: team-atlas

#3807 Fix strict IAS adapter validation
  chart/compass/values.yaml
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: :wave: request review, size/XS, approved, lgtm, cla: yes, :globe_with_meridians: team-atlas

#3804 Fix assign formation not found errors
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/service.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3808 Handle race condition in async flow control operator
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator.go
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3805 Add env var for ORD Service
  chart/compass/charts/ord-service/templates/deployment.yaml
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3811 Add IAS adapter status report logs
  chart/compass/values.yaml
  components/ias-adapter/internal/service/processor/processor.go
Labels: :wave: request review, size/S, approved, lgtm, cla: yes, :globe_with_meridians: team-atlas

#3801 Do not delete constraint if it is attached
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/automock/formation_constraint_repository.go
  components/director/internal/domain/formationconstraint/automock/formation_template_constraint_reference_repository.go
  components/director/internal/domain/formationconstraint/automock/uid_service.go
  components/director/internal/domain/formationconstraint/fixtures_test.go
  components/director/internal/domain/formationconstraint/service.go
  components/director/internal/domain/formationconstraint/service_test.go
  components/director/internal/domain/formationtemplateconstraintreferences/automock/formation_template_constraint_reference_repository.go
  components/director/internal/domain/formationtemplateconstraintreferences/repository.go
  components/director/internal/domain/formationtemplateconstraintreferences/repository_test.go
  components/schema-migrator/migrations/director/20240410172316_remove_constrain_cascade_deletion.down.sql
  components/schema-migrator/migrations/director/20240410172316_remove_constrain_cascade_deletion.up.sql
  tests/director/tests/formation/formation_constraint_api_test.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/director/tests/notifications/runtime_notification_subscription_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3809 Adapt ORD Service change
  chart/compass/values.yaml
  installation/scripts/prow/compass-smoke-test.sh
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3816 Update values.yaml
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3785 Expose the region of a System Instance in UCL Discovery Service
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20240415112919_add_region_of_application_in_ord.down.sql
  components/schema-migrator/migrations/director/20240415112919_add_region_of_application_in_ord.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3815 Fix IAS adapter async response
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
Labels: :wave: request review, size/S, approved, lgtm, cla: yes, :globe_with_meridians: team-atlas

#3793 Fix UpdateApplicationTemplate mutation when app template has product label
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/apptmpltest/selfreg_manager.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/selfregmanager/selfreg_manager.go
  components/director/internal/selfregmanager/selfreg_manager_test.go
  tests/director/tests/application/application_templates_api_test.go
  tests/pkg/fixtures/application_fixtures.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3814 Fix request body validation when assignment status is reported
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3817 Remove compass-console
  chart/compass/charts/cockpit/.helmignore
  chart/compass/charts/cockpit/Chart.yaml
  chart/compass/charts/cockpit/templates/configmap.yaml
  chart/compass/charts/cockpit/templates/deployment.yaml
  chart/compass/charts/cockpit/templates/mf-virtualservice.yaml
  chart/compass/charts/cockpit/templates/secret.yaml
  chart/compass/charts/cockpit/templates/service.yaml
  chart/compass/charts/cockpit/templates/virtualservice.yaml
  chart/compass/charts/cockpit/values.yaml
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/values.yaml
  docs/compass/04-01-installation.md
  installation/cmd/run.sh
  installation/scripts/install-ory.sh
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3778 Support Data Center aggregation by default when auto-discovering system tenants
  chart/compass/values.yaml
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3821 Change expired images to prod
  chart/compass/values.yaml
Labels: size/M, approved, lgtm, cla: yes

#3681 Associate destinations with bundle id made from destination creator
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/connector/go.mod
  components/connector/go.sum
  components/director/cmd/destinationfetcher-svc/main.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationfetchersvc/automock/bundle_repo.go
  components/director/internal/destinationfetchersvc/automock/destination_repo.go
  components/director/internal/destinationfetchersvc/automock/formation_assignment_repository.go
  components/director/internal/destinationfetchersvc/destinationservice_test.go
  components/director/internal/destinationfetchersvc/service.go
  components/director/internal/destinationfetchersvc/service_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/model/destination.go
  components/director/internal/repo/conditions.go
  components/director/pkg/destinationcreator/types.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationfetcher/handler.go
  components/external-services-mock/internal/destinationfetcher/mockdata.go
  components/external-services-mock/internal/destinationsvc/fixtures_test.go
  components/external-services-mock/internal/destinationsvc/handler.go
  components/external-services-mock/internal/destinationsvc/handler_test.go
  components/external-services-mock/internal/destinationsvc/mockdata.go
  components/external-services-mock/internal/destinationsvc/types.go
  components/external-services-mock/pkg/destinationcreator/types.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/director/tests/config.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/clients/destination_client.go
Labels: :wave: request review, size/XXL, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3824 [dev-main fix] Fix cert based tests
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_subscription_test.go
  tests/director/tests/formation/formation_api_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3845 Update test with correct cn
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_subscription_test.go
Labels: :wave: request review, size/XS, approved, lgtm, cla: yes

#3846 Fix test to use same OU subaccount as in the certSecuredGraphQLClient
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/director/tests/application/application_api_test.go
  tests/director/tests/application/application_templates_subscription_test.go
  tests/ord-service/tests/api_test.go
  tests/ord-service/tests/main_test.go
Labels: :wave: request review, size/M, lgtm, :t-rex: team-raptor, cla: yes

#3848 Fix job name
  chart/compass/values.yaml
  tests/director/tests/application/application_api_test.go
  tests/ord-service/tests/api_test.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3843 Fix region consumption of a system instance in the ORD Service calls
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20240422143028_ord-fix-region-value-of-systems.down.sql
  components/schema-migrator/migrations/director/20240422143028_ord-fix-region-value-of-systems.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3812 Introduce Global Applications API
  chart/compass/charts/director/config.yaml
  chart/compass/charts/hydrator/static-groups.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/automock/application_with_tenants_converter.go
  components/director/internal/domain/application/automock/tenant_converter.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/application/fixtures_test.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/repository.go
  components/director/internal/model/application.go
  components/director/internal/repo/list.go
  components/director/internal/repo/testdb/generic_repo_create_tests.go
  components/director/internal/repo/testdb/generic_repo_list_pageable_tests.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/director/pkg/tenant/entity.go
  tests/director/tests/application/application_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/application_requests.go
Labels: size/XXL, approved, lgtm, to be released :rocket:, cla: yes

#3850 Fix failing e2e tests
  chart/compass/values.yaml
  tests/director/tests/application/application_api_test.go
  tests/ord-service/tests/api_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3851 Add global app read scope to tenant_discovery_operator
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3841 Enrich logger with additional tracing information
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/default-tenant-mapping-handler/internal/handler/handler.go
  components/director/cmd/scopessynchronizer/main.go
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/finalize_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/formationmapping/auth_middleware.go
  components/director/internal/formationmapping/handler.go
  components/director/pkg/correlation/middleware.go
  components/director/pkg/correlation/middleware_test.go
  components/director/pkg/log/configure.go
  components/director/pkg/log/request.go
  components/director/pkg/log/request_test.go
  components/director/pkg/webhook_client/client.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/formationnotification/handler.go
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/instance-creator/internal/handler/handler.go
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/go.mod
  tests/go.sum
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3842 Enrich the tenant mapping request body logs in the instance creator c…
  chart/compass/values.yaml
  components/instance-creator/internal/client/types/tenantmapping/tenant_mapping.go
  components/instance-creator/internal/client/types/tenantmapping/tenant_mapping_test.go
  components/instance-creator/internal/handler/handler.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3853 Fix labels fetching in the global applications API
  chart/compass/values.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/automock/label_repository.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/label/repository.go
  components/director/internal/domain/label/repository_test.go
  components/director/pkg/graphql/application.go
  tests/director/tests/application/application_api_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, size/XL, lgtm, cla: yes

#3852 E2E dest fetcher fixes
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  components/director/internal/destinationfetchersvc/client.go
  components/director/internal/model/destination.go
  components/external-services-mock/internal/destinationsvc/handler.go
  components/external-services-mock/internal/destinationsvc/handler_test.go
  components/external-services-mock/internal/destinationsvc/types.go
  tests/director/tests/config.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/clients/destination_client.go
  tests/pkg/request/make_request.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, cla: yes

#3857 Make global ORD entities visible in systems
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20240430084814_ord-expose-global-entities.down.sql
  components/schema-migrator/migrations/director/20240430084814_ord-expose-global-entities.up.sql
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes
