Repository kyma-incubator/compass, pull requests merged in 2024-02, with the labels that each got.

#3627 Change K8s GKE version for benchmark
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
Labels: size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3592 Postgres15 preparations
  chart/compass/values.yaml
  chart/localdb/charts/dbdump/templates/dbdump-job.yaml
  chart/localdb/charts/postgresql/values-production.yaml
  chart/localdb/charts/postgresql/values.yaml
  components/director/cmd/director/main.go
  components/director/hack/jwt_generator.sh
  components/director/run.sh
  components/schema-migrator/validate.sh
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3624 Cost object on subscriptions
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/handler.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/external-services-mock/internal/subscription/config.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  tests/director/tests/application/application_templates_subscription_test.go
  tests/director/tests/application/application_tenancy_synchronization_test.go
  tests/director/tests/config.go
  tests/director/tests/notifications/kyma_tenant_mapping_adapter_test.go
  tests/director/tests/tenant_isolation_test.go
  tests/director/tests/tenants_api_test.go
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3628 Upgrade kyma from 2.9.3 to 2.11.4
  README.md
  chart/compass/charts/connector/templates/certs-setup-job.yaml
  chart/compass/charts/testing/charts/octopus/templates/manager.yaml
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3615 Add timestamps to the graphql schema
  chart/compass/values.yaml
  components/director/internal/model/formation_assignment.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, approved, size/L, lgtm, cla: yes

#3630 Subscription cost object e2e test
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_subscription_test.go
  tests/pkg/tenantfetcher/tenant_helper.go
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3587 Support regional cld based app providers
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/cmd/director/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/apptemplate/automock/label_service.go
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/repository.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/label/query.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/systemfetcher/automock/template_renderer.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/operation_processor.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/template.go
  components/director/pkg/credloader/automock/keys_cache.go
  components/director/pkg/credloader/loader.go
  components/director/pkg/credloader/loader_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/director/tests/application/application_templates_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/application_template_requests.go
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3631 Create cost object from ga
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/director/internal/tenantfetchersvc/resync/event_page_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager_test.go
  components/director/internal/tenantfetchersvc/resync/types.go
  installation/resources/compass-overrides-local.yaml
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3635 Fix flapping TestMoveSubaccountsFailIfSubaccountHasFormationInTheSourceGA
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: size/S, approved, lgtm, :eagle: team-falcon, cla: yes

#3634 Fix deployment
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
Labels: size/XS, approved, lgtm, :eagle: team-falcon, cla: yes

#3637 [HOTFIX] Upgrade kyma from 2.9.3 to 2.11.4
  README.md
  chart/compass/charts/connector/templates/certs-setup-job.yaml
  chart/compass/charts/testing/charts/octopus/templates/manager.yaml
  chart/compass/templates/bench/director/director-bench.yaml
  chart/compass/templates/bench/ord-service/ord-service-bench.yaml
  chart/compass/templates/tests/connectivity-adapter/connectivity-adapter-test.yaml
  chart/compass/templates/tests/connector/connector-test.yaml
  chart/compass/templates/tests/director/director-test.yaml
  chart/compass/templates/tests/external-services-mock/external-services-mock-test.yaml
  chart/compass/templates/tests/gateway/gateway-test.yaml
  chart/compass/templates/tests/istio/istio-test.yaml
  chart/compass/templates/tests/ns-adapter/ns-adapter-test.yaml
  chart/compass/templates/tests/ord-aggregator/ord-aggregator-test.yaml
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/templates/tests/pairing-adapter/pairing-adapter-test.yaml
  chart/compass/templates/tests/system-broker/system-broker-test.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: size/M, approved, lgtm, do-not-merge/missing-docs-review, :t-rex: team-raptor, cla: yes

#3614 Create system fetcher operations when new GA or CRM ID is created in UCL
  chart/compass/charts/director/templates/deployment.yaml
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/systemfetcher/apiclient/client.go
  components/director/internal/systemfetcher/apiclient/client_test.go
  components/director/internal/systemfetcher/apiclient/config.go
  components/director/internal/systemfetcher/automock/business_tenant_mapping_service.go
  components/director/internal/systemfetcher/handler.go
  components/director/internal/systemfetcher/handler_test.go
  components/director/internal/systemfetcher/operation_maintainer.go
  components/director/run.sh
  components/external-services-mock/cmd/main.go
  tests/pkg/tenant/tenant_setup.go
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon, cla: yes

#3639 Fix e2e test for CLD
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_api_test.go
Labels: size/XS, approved, lgtm, cla: yes

#3633 Use custom SQL query for listing tenants by paretn ID and tenant Type
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenantparentmapping/repository.go
Labels: :wave: request review, approved, size/L, lgtm, cla: yes

#3640 Fix e2e test for devmain
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_api_test.go
Labels: size/XS, approved, lgtm, cla: yes

#3644 Optimise introduce-tenant-parents-table up migration
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20240116180042_introduce-tenant-parents-table.up.sql
Labels: approved, size/L, lgtm, cla: yes

#3645 [HOTFIX] Optimise introduce-tenant-parents-table up migration
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20240116180042_introduce-tenant-parents-table.up.sql
Labels: approved, size/L, lgtm, cla: yes

#3646 Use image from prod registry
  chart/compass/values.yaml
Labels: size/XS, cla: yes

#3647 Use custom SQL query for listing tenants by paretn ID and tenant Type
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenantparentmapping/repository.go
Labels: approved, size/L, lgtm, cla: yes

#3632 Upgrade Kyma from 2.11.4 to 2.13.1
  README.md
  docs/compass/04-01-installation.md
  installation/resources/KYMA_VERSION
  installation/resources/kyma/kyma-overrides-minimal.yaml
  installation/scripts/install-kyma.sh
  installation/scripts/prow/jobs/compass-gke-benchmark.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: size/S, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, cla: yes

#3642 Handle design time destinations as raw json
  chart/compass/values.yaml
  components/director/internal/destinationcreator/fixtures_test.go
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/service_test.go
  components/director/internal/domain/destination/automock/destination_creator_service.go
  components/director/internal/domain/destination/automock/destination_repository.go
  components/director/internal/domain/destination/automock/tenant_repository.go
  components/director/internal/domain/destination/automock/uid_service.go
  components/director/internal/domain/destination/fixtures_test.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/destination/service_test.go
  components/director/internal/domain/formationconstraint/operators/automock/application_repository.go
  components/director/internal/domain/formationconstraint/operators/automock/automatic_scenario_assignment_service.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_creator_service.go
  components/director/internal/domain/formationconstraint/operators/automock/destination_service.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_assignment_notification_service.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_assignment_repository.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_assignment_service.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_constraint_svc.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_repository.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_template_repo.go
  components/director/internal/domain/formationconstraint/operators/automock/label_repository.go
  components/director/internal/domain/formationconstraint/operators/automock/label_service.go
  components/director/internal/domain/formationconstraint/operators/automock/runtime_context_repo.go
  components/director/internal/domain/formationconstraint/operators/automock/system_auth_service.go
  components/director/internal/domain/formationconstraint/operators/automock/tenant_service.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/utils.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
Labels: approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, cla: yes

#3643 Improve error handling during unassign/delete operations
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formation/status_service.go
  components/director/internal/domain/formation/status_service_test.go
  components/director/internal/domain/formationassignment/repository_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3648 Fix ias-adapter image
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3650 Change image registry and versions
  chart/compass/values.yaml
Labels: size/M, approved, lgtm, cla: yes

#3654 Introduce tenant_discovery_operator consumer type
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3655 Introduce tenant_discovery_operator consumer type in backend
  chart/compass/values.yaml
  components/director/pkg/consumer/consumer.go
  components/director/pkg/inputvalidation/validators_cert_subject_mappings.go
  components/director/pkg/model/system_auth.go
  components/hydrator/go.mod
  components/hydrator/go.sum
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3638 Cost object from sa
  chart/compass/charts/tenant-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/model/businesstenantmapping.go
  components/director/internal/tenantfetchersvc/resync/automock/tenant_creator.go
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/director/internal/tenantfetchersvc/resync/fixtures_test.go
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/synchronizer_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_mover_test.go
  components/director/internal/tenantfetchersvc/resync/types.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  installation/resources/compass-overrides-local.yaml
  tests/go.mod
  tests/go.sum
  tests/tenant-fetcher/tests/handler_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3657 Change ORD Service image to prod registry
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3658 SpringBoot Update for ORD Service
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3660 [HOTFIX] Fix old design time destination authentication key deletion
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3659 Fix old design time destination authentication key deletion
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator_test.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3667 Handle empty config in instance creator asynchronous flow control operator
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator.go
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/utils.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3669 [HOTFIX] Handle empty config in instance creator asynchronous flow control operator
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator.go
  components/director/internal/domain/formationconstraint/operators/asynchronous_flow_control_operator_test.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/utils.go
Labels: :wave: request review, :hammer: hotfix, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3670 [HOTFIX] Instance Creator - Fix logging, add role for its certificate and fix handler bug
  chart/compass/charts/instance-creator/templates/rbac.yaml
  chart/compass/values.yaml
  components/instance-creator/internal/client/types/tenantmapping/tenant_mapping.go
  components/instance-creator/internal/client/types/tenantmapping/tenant_mapping_test.go
  components/instance-creator/internal/handler/handler.go
  components/instance-creator/internal/handler/handler_test.go
  components/instance-creator/internal/handler/utils.go
Labels: :hammer: hotfix, size/L, :t-rex: team-raptor, cla: yes

#3671 [HOTFIX] Bump images for hotfix v1.89.1 branch
  chart/compass/values.yaml
Labels: :hammer: hotfix, size/XS, :t-rex: team-raptor, cla: yes

#3672 Extend error checks
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/status_service.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3674 Fix system fetcher flapping unit test
  chart/compass/values.yaml
  components/director/cmd/systemfetcher/main.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3676 Optimise union lister querying
  chart/compass/values.yaml
  components/director/internal/domain/aspect/repository_test.go
  components/director/internal/domain/aspecteventresource/repository_test.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/bundlereferences/repository_test.go
  components/director/internal/domain/document/repository_test.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/integrationdependency/repository_test.go
  components/director/internal/domain/runtime_context/repository_test.go
  components/director/internal/domain/spec/repository_test.go
  components/director/internal/repo/list_union.go
  components/director/internal/repo/list_union_test.go
  components/director/internal/repo/query_builder.go
Labels: :wave: request review, size/M, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, cla: yes

#3678 Adapt expected token path in e2e test
  chart/compass/values.yaml
  tests/director/tests/notifications/application_subscription_notifications_test.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3682 Change system broker image to prod version
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3675 [HOTFIX] Fix WriteTenants mutation
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  components/schema-migrator/migrations/director/20240215155511_add-tenant-access-to-new-crms.down.sql
  components/schema-migrator/migrations/director/20240215155511_add-tenant-access-to-new-crms.up.sql
  tests/director/tests/notifications/tenant_hierarchy_notifications_test.go
  tests/director/tests/tenants_api_test.go
  tests/pkg/subscription/utils.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3677 Load hydrator verifiers on startup
  chart/compass/charts/hydrator/templates/deployment.yaml
  chart/compass/values.yaml
  components/hydrator/cmd/main.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/authnmappinghandler/handler.go
  components/hydrator/internal/authnmappinghandler/handler_test.go
  components/hydrator/internal/config/authenticator_subdomain_mapping.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3652 Fix WriteTenants mutation
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/tenantfetchersvc/resync/event_page.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/subscription/handler.go
  components/external-services-mock/internal/subscription/handler_test.go
  components/schema-migrator/migrations/director/20240223100938_add-tenant-access-to-new-crms.down.sql
  components/schema-migrator/migrations/director/20240223100938_add-tenant-access-to-new-crms.up.sql
  tests/director/tests/notifications/tenant_hierarchy_notifications_test.go
  tests/director/tests/tenants_api_test.go
  tests/pkg/subscription/utils.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3685 Instance Creator - Remove destinations from the returned config
  chart/compass/values.yaml
  components/instance-creator/internal/handler/handler.go
  components/instance-creator/internal/handler/handler_test.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3686 Adapt oauth2mTLS destination test on real env
  chart/compass/values.yaml
  components/director/internal/destinationcreator/service.go
  components/director/internal/destinationcreator/types.go
  components/director/internal/domain/destination/automock/destination_creator_service.go
  components/director/internal/domain/destination/automock/destination_repository.go
  components/director/internal/domain/destination/automock/tenant_repository.go
  components/director/internal/domain/destination/automock/uid_service.go
  components/director/internal/domain/destination/service.go
  components/director/internal/domain/formationconstraint/operators/destination_creator_operator.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/external-services-mock/internal/destinationcreator/handler.go
  components/external-services-mock/internal/destinationcreator/mockdata.go
  components/external-services-mock/internal/destinationcreator/types.go
  components/external-services-mock/internal/formationnotification/handler.go
  components/external-services-mock/internal/formationnotification/handler_test.go
  components/external-services-mock/pkg/destinationcreator/types.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/go.mod
  tests/go.sum
Labels: approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3687 Trigger systems sync only for customers and accounts
  chart/compass/values.yaml
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
Labels: size/M, approved, lgtm, cla: yes

#3684 Optimisation for subscription flow
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/automock/director_graph_ql_client.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/director/pkg/graphql_client/director_client.go
  components/director/pkg/graphql_client/director_client_test.go
Labels: kind/bug, :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3688 Disable rescheduling of system fetching operations for existing tenants
  chart/compass/values.yaml
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/systemfetcher/apiclient/client.go
  components/director/internal/systemfetcher/apiclient/client_test.go
  components/director/internal/systemfetcher/handler.go
  components/director/internal/systemfetcher/handler_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3689 Use right secret for initializing system field discovery config
  chart/compass/charts/external-services-mock/templates/region-instances-credentials.yaml
  chart/compass/charts/external-services-mock/templates/saas-app-names-secret.yaml
  chart/compass/values.yaml
  components/director/pkg/config/system_field_discovery_engine_config.go
  components/director/run.sh
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon, cla: yes

#3691 Add deprecation notice
  README.md
Labels: size/XS, lgtm, cla: yes

#3692 Extend ORD Service e2e test
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_subscription_test.go
  tests/director/tests/notifications/application_subscription_notifications_test.go
  tests/director/tests/notifications/tenant_hierarchy_notifications_test.go
  tests/ord-service/tests/api_test.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3693 Fix for wrong GQL query
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/director/pkg/graphql_client/director_client.go
  components/director/pkg/graphql_client/director_client_test.go
Labels: kind/bug, :wave: request review, size/M, approved, lgtm, release blocker, to be released :rocket:, :eagle: team-falcon, cla: yes
