Repository kyma-incubator/compass, pull requests merged in 2024-01, with the labels that each got.

#3566 Add discovery consumers allowlist to formation templates
  chart/compass/values.yaml
  components/director/internal/domain/formationtemplate/converter.go
  components/director/internal/domain/formationtemplate/entity.go
  components/director/internal/domain/formationtemplate/fixtures_test.go
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/internal/model/formation_template.go
  components/director/pkg/graphql/formation_template.go
  components/director/pkg/graphql/formation_template_validation.go
  components/director/pkg/graphql/formation_template_validation_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/graphqlizer/graphqlizer.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20231228152252_add-discovery-consumers-allowlist.down.sql
  components/schema-migrator/migrations/director/20231228152252_add-discovery-consumers-allowlist.up.sql
  tests/go.mod
  tests/go.sum
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, approved, size/L, lgtm, to be released :rocket:, :t-rex: team-raptor, cla: yes

#3568 Fix unstable notification lifecycle test
  chart/compass/values.yaml
  tests/director/tests/notifications/application_only_notifications_test.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3570 Use prod images
  chart/compass/values.yaml
Labels: size/M, cla: yes

#3548 Fix nil pointer dereference in hydrator component
  chart/compass/values.yaml
  components/hydrator/internal/certsubjectmapping/loader.go
  components/hydrator/internal/certsubjectmapping/loader_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3542 Use the new e2e tests format in the redirect e2e test
  chart/compass/values.yaml
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/integration_dependency_test.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/application_only_notifications_test.go
  tests/pkg/notifications/asserters/formation_assignments.go
  tests/pkg/notifications/asserters/formation_status.go
  tests/pkg/notifications/asserters/notifications_count.go
  tests/pkg/notifications/asserters/notifications_unassign.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3562 Allow hydra healthpoint access
  chart/compass/templates/internal-communication-policies.yaml
Labels: :wave: request review, size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3571 Change System Fetcher cron job to be a deployment
  CODEOWNERS
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/system-fetcher/.helmignore
  chart/compass/charts/system-fetcher/Chart.yaml
  chart/compass/charts/system-fetcher/OWNERS
  chart/compass/charts/system-fetcher/templates/deployment.yaml
  chart/compass/charts/system-fetcher/templates/rbac.yaml
  chart/compass/charts/system-fetcher/templates/service.yaml
  chart/compass/charts/system-fetcher/values.yaml
  chart/compass/templates/system-fetcher-job.yaml
  chart/compass/templates/tests/system-fetcher/system-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/Makefile
  components/director/cmd/systemfetcher/main.go
  components/director/internal/systemfetcher/model.go
  components/director/runSystemFetcher.sh
  tests/system-fetcher/tests/handler_test.go
  tests/system-fetcher/tests/main_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3572 Differentiate ready assignment states in status API
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
  components/director/internal/formationmapping/handler_test.go
  components/director/internal/model/formation_assignment.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/director/tests/notifications/fixtures_test.go
  tests/pkg/notifications/asserters/formation_assignments_async.go
  tests/pkg/notifications/operations/execute-status-report.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3575 Fix formation assignment state in notification payload
  chart/compass/values.yaml
  components/director/pkg/webhook/application_tenant_mapping.go
  components/director/pkg/webhook/formation_configuration_change.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/notifications/asserters/formation_assignments_async.go
  tests/pkg/notifications/asserters/notifications.go
  tests/pkg/notifications/asserters/notifications_unassign.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3577 Update golang and alpine versions
  chart/compass/values.yaml
  components/connectivity-adapter/Dockerfile
  components/connector/Dockerfile
  components/default-tenant-mapping-handler/Dockerfile
  components/director/Dockerfile
  components/external-services-mock/Dockerfile
  components/gateway/Dockerfile
  components/hydrator/Dockerfile
  components/ias-adapter/Dockerfile
  components/instance-creator/Dockerfile
  components/kyma-adapter/Dockerfile
  components/operations-controller/Dockerfile
  components/pairing-adapter/Dockerfile
  components/schema-migrator/Dockerfile
  components/system-broker/Dockerfile
  tests/Dockerfile
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3579 Update ord-service
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3580 Add tenant_access:write scope to business_integration consumer type
  chart/compass/values.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3576 Maintain lastUpdate property of ORD resources
  chart/compass/values.yaml
  components/director/internal/domain/bundle/converter.go
  components/director/internal/domain/bundle/entity.go
  components/director/internal/domain/bundle/fixtures_test.go
  components/director/internal/domain/bundle/repository.go
  components/director/internal/domain/bundle/repository_test.go
  components/director/internal/domain/integrationdependency/resolver.go
  components/director/internal/model/api.go
  components/director/internal/model/bundle.go
  components/director/internal/model/data_product.go
  components/director/internal/model/entitytype.go
  components/director/internal/model/eventapi.go
  components/director/internal/model/integration_dependency.go
  components/director/internal/open_resource_discovery/processor/api.go
  components/director/internal/open_resource_discovery/processor/api_test.go
  components/director/internal/open_resource_discovery/processor/capability.go
  components/director/internal/open_resource_discovery/processor/capability_test.go
  components/director/internal/open_resource_discovery/processor/common.go
  components/director/internal/open_resource_discovery/processor/data_product.go
  components/director/internal/open_resource_discovery/processor/data_product_test.go
  components/director/internal/open_resource_discovery/processor/entity_type.go
  components/director/internal/open_resource_discovery/processor/entity_type_test.go
  components/director/internal/open_resource_discovery/processor/event.go
  components/director/internal/open_resource_discovery/processor/event_test.go
  components/director/internal/open_resource_discovery/processor/fixtures_test.go
  components/director/internal/open_resource_discovery/processor/integration_dependency.go
  components/director/internal/open_resource_discovery/processor/integration_dependency_test.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/schema-migrator/migrations/director/20240110153859_add-lastUpdate-to-bundle.down.sql
  components/schema-migrator/migrations/director/20240110153859_add-lastUpdate-to-bundle.up.sql
Labels: :wave: request review, approved, size/XL, lgtm, to be released :rocket:, :eagle: team-falcon, cla: yes

#3584 Release v1.87.0 update prod images
  chart/compass/values.yaml
Labels: size/M, cla: yes

#3581 Allow assign only for applications that are ready
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3583 Fix status report for self-referenced formation assignment
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3588 [HOTFIX] Fix status report for self-referenced formation assignment
  chart/compass/values.yaml
  components/director/internal/formationmapping/handler.go
Labels: :wave: request review, size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3590 [HOTFIX] Bump images for hotfix v1.87.0 branch
  chart/compass/values.yaml
Labels: size/XS, cla: yes

#3573 Implement SetTenantLabel mutation
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/hack/config-local.yaml
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/tenant/automock/business_tenant_mapping_service.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/domain/tenant/service.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/tenants_api_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/fixtures.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3595 Make formation participant not required in the GraphQL schema
  chart/compass/values.yaml
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
Labels: :wave: request review, size/M, approved, lgtm, cla: yes

#3593 Add timestamps to formations and formation assignments
  chart/compass/values.yaml
  components/director/cmd/director/main.go
  components/director/cmd/ns-adapter/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/api/converter.go
  components/director/internal/domain/application/converter.go
  components/director/internal/domain/aspect/converter.go
  components/director/internal/domain/aspecteventresource/converter.go
  components/director/internal/domain/bundle/converter.go
  components/director/internal/domain/document/converter.go
  components/director/internal/domain/eventdef/converter.go
  components/director/internal/domain/formation/automock/formation_assignment_repository.go
  components/director/internal/domain/formation/converter.go
  components/director/internal/domain/formation/converter_test.go
  components/director/internal/domain/formation/entity.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/repository.go
  components/director/internal/domain/formation/repository_test.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationassignment/converter.go
  components/director/internal/domain/formationassignment/converter_test.go
  components/director/internal/domain/formationassignment/entity.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service_test.go
  components/director/internal/domain/integrationdependency/converter.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/webhook/converter.go
  components/director/internal/model/formation.go
  components/director/internal/model/formation_assignment.go
  components/director/pkg/graphql/formation.go
  components/director/pkg/graphql/formation_assignment.go
  components/director/pkg/graphql/timestamp.go
  components/schema-migrator/migrations/director/20240119172919_add-formation-assignments-timestamps.down.sql
  components/schema-migrator/migrations/director/20240119172919_add-formation-assignments-timestamps.up.sql
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3585 Add instance creator certificate rotation job
  chart/compass/charts/director/templates/instance-creator-certificate-pre-install-job.yaml
  chart/compass/charts/director/templates/instance-creator-certificate-rotation-job.yaml
  chart/compass/charts/external-services-mock/templates/oauth-credentials-secret.yaml
  chart/compass/values.yaml
  installation/resources/compass-overrides-gke-benchmark.yaml
  installation/resources/compass-overrides-local.yaml
Labels: approved, size/L, lgtm, cla: yes

#3589 System Fetcher with Operations
  chart/compass/charts/system-fetcher/templates/deployment.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/domain/systemssync/automock/systems_sync_repository.go
  components/director/internal/domain/systemssync/repository.go
  components/director/internal/domain/systemssync/repository_test.go
  components/director/internal/domain/systemssync/service.go
  components/director/internal/domain/systemssync/service_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/model/operation.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/operation_maintainer.go
  components/director/internal/systemfetcher/automock/business_tenant_mapping_service.go
  components/director/internal/systemfetcher/automock/operation_maintainer.go
  components/director/internal/systemfetcher/automock/operation_service.go
  components/director/internal/systemfetcher/automock/operations_manager.go
  components/director/internal/systemfetcher/automock/system_fetcher_service.go
  components/director/internal/systemfetcher/automock/systems_api_client.go
  components/director/internal/systemfetcher/automock/systems_sync_service.go
  components/director/internal/systemfetcher/automock/tenant_service.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/fixtures_test.go
  components/director/internal/systemfetcher/handler.go
  components/director/internal/systemfetcher/handler_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/operation_maintainer.go
  components/director/internal/systemfetcher/operation_maintainer_test.go
  components/director/internal/systemfetcher/operation_processor.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/internal/systemfetcher/systemfetcher_operation_data.go
  components/director/internal/systemfetcher/systemfetcher_operation_data_test.go
  components/director/internal/systemfetcher/template.go
  components/director/runSystemFetcher.sh
  components/schema-migrator/migrations/director/20240123091602_extend-supported-operration-types.down.sql
  components/schema-migrator/migrations/director/20240123091602_extend-supported-operration-types.up.sql
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon, cla: yes

#3612 Soften multiple validation errors in ORD aggregation
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/external-services-mock/internal/ord-aggregator/template.go
Labels: size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3613 Insecure ClusterRoleBinding overrides
  chart/compass/templates/jwks_cluster_binding.yaml
  chart/compass/values.yaml
  installation/resources/compass-overrides-local.yaml
Labels: size/S, approved, lgtm, cla: yes

#3616 Use dedicated gql files for smoke test
  installation/scripts/prow/compass-smoke-test.sh
  tests/smoke-test/create-formation.graphql
  tests/smoke-test/query-applications.graphql
  tests/smoke-test/register-application-with-bundles.graphql
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, cla: yes

#3619 Fix sanitize method for ORD documents
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/ord_document.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon, cla: yes

#3620 Fix merge labels in sanitize method for ORD documents
  chart/compass/values.yaml
  components/director/internal/open_resource_discovery/ord_document.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon, cla: yes

#3618 Tenant access deletion
  chart/compass/values.yaml
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/repository_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/repo/tenant_access_m2m.go
  tests/director/tests/tenant_isolation_test.go
Labels: :wave: request review, approved, size/XL, lgtm, :t-rex: team-raptor, cla: yes

#3621 Add new products to global registry template in external services mock
  chart/compass/values.yaml
  components/external-services-mock/internal/ord-aggregator/globalregistry/template.go
Labels: size/S, approved, lgtm, cla: yes

#3622 Check if there are root tenants
  chart/compass/values.yaml
  components/director/internal/domain/tenant/fixtures_test.go
  components/director/internal/domain/tenant/service.go
  components/director/internal/domain/tenant/service_test.go
  components/director/internal/repo/tenant_access_m2m.go
  components/director/pkg/applicationtenancy/directive.go
Labels: approved, size/L, lgtm, cla: yes

#3623 Adapt postgres exporter queries to use tenant parents table
  chart/compass/charts/prometheus-postgres-exporter/values.yaml
Labels: :wave: request review, approved, lgtm, :t-rex: team-raptor, cla: yes

#3625 Change image registry and versions
  chart/compass/values.yaml
Labels: :wave: request review, size/M, approved, lgtm, cla: yes

#3617 Constraint inconsistencies fix
  chart/compass/values.yaml
  components/director/internal/domain/formationconstraint/service.go
  components/director/internal/domain/formationconstraint/service_test.go
  components/schema-migrator/migrations/director/20240127192653_constraint-validation.down.sql
  components/schema-migrator/migrations/director/20240127192653_constraint-validation.up.sql
  tests/director/tests/formation/formation_constraint_api_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes
