Repository kyma-incubator/compass, pull requests merged in 2024-05, with the labels that each got.

#3862 Fix "Consumer provider with user context header" e2e test
  chart/compass/templates/tests/ord-service/ord-service-test.yaml
  chart/compass/values.yaml
  tests/ord-service/tests/main_test.go
  tests/ord-service/tests/subscription_flow_test.go
  tests/pkg/config/director.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3863 Remove deprecated linters
  chart/compass/values.yaml
  components/default-tenant-mapping-handler/cmd/main.go
  components/default-tenant-mapping-handler/golangci.yml
  components/director/.golangci.yml
  components/director/cmd/director/main.go
  components/instance-creator/cmd/main.go
  components/instance-creator/golangci.yml
  components/kyma-adapter/.golangci.yml
  components/kyma-adapter/cmd/main.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3787 Support fine-grained SLIS filtering during onboarding
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/connector/pkg/oathkeeper/contract.go
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/director/cmd/systemfetcher/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/apptemplate/fixtures_test.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/systemfetcher/client.go
  components/director/internal/systemfetcher/client_test.go
  components/director/internal/systemfetcher/model.go
  components/director/internal/systemfetcher/service.go
  components/director/internal/systemfetcher/service_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/labels_validation_test.go
  components/director/pkg/str/strings.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/certresolver/validation_hydrator.go
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/director/tests/application/application_templates_api_test.go
  tests/go.mod
  tests/go.sum
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, to be released :rocket:, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3849 Encode consumer id in error message
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  tests/director/tests/application/application_templates_api_test.go
Labels: kind/bug, :wave: request review, size/S, approved, lgtm, to be released :rocket:, cla: yes

#3855 Remove some operations-controller alerts
  chart/compass/templates/additional-prometheus-rules.yaml
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon, cla: yes

#3867 Bump versions
  chart/compass/values.yaml
Labels: size/M, approved, lgtm, cla: yes

#3865 Add dedicated method for formation/formation assignments timestamps update
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/asa_engine.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_repository.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_service.go
  components/director/internal/domain/formation/automock/constraint_engine.go
  components/director/internal/domain/formation/automock/formation_assignment_notifications_service.go
  components/director/internal/domain/formation/automock/formation_assignment_repository.go
  components/director/internal/domain/formation/automock/formation_repository.go
  components/director/internal/domain/formation/automock/formation_template_repository.go
  components/director/internal/domain/formation/automock/label_def_repository.go
  components/director/internal/domain/formation/automock/label_def_service.go
  components/director/internal/domain/formation/automock/label_repository.go
  components/director/internal/domain/formation/automock/label_service.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/automock/process_func.go
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/automock/status_service.go
  components/director/internal/domain/formation/automock/tenant_service.go
  components/director/internal/domain/formation/automock/tenant_svc.go
  components/director/internal/domain/formation/automock/uuid_service.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/repository.go
  components/director/internal/domain/formation/repository_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/automock/application_converter.go
  components/director/internal/domain/formationassignment/automock/application_repo.go
  components/director/internal/domain/formationassignment/automock/application_repository.go
  components/director/internal/domain/formationassignment/automock/constraint_engine.go
  components/director/internal/domain/formationassignment/automock/entity_converter.go
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_repository.go
  components/director/internal/domain/formationassignment/automock/formation_repository.go
  components/director/internal/domain/formationassignment/automock/label_service.go
  components/director/internal/domain/formationassignment/automock/notification_builder.go
  components/director/internal/domain/formationassignment/automock/notification_service.go
  components/director/internal/domain/formationassignment/automock/runtime_context_converter.go
  components/director/internal/domain/formationassignment/automock/runtime_context_repo.go
  components/director/internal/domain/formationassignment/automock/runtime_context_repository.go
  components/director/internal/domain/formationassignment/automock/runtime_converter.go
  components/director/internal/domain/formationassignment/automock/runtime_repo.go
  components/director/internal/domain/formationassignment/automock/runtime_repository.go
  components/director/internal/domain/formationassignment/automock/status_service.go
  components/director/internal/domain/formationassignment/automock/template_input.go
  components/director/internal/domain/formationassignment/automock/tenant_repository.go
  components/director/internal/domain/formationassignment/automock/uid_service.go
  components/director/internal/domain/formationassignment/automock/webhook_converter.go
  components/director/internal/domain/formationassignment/automock/webhook_repository.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/model/formation.go
  components/director/internal/model/formation_assignment.go
Labels: approved, size/XL, lgtm, :t-rex: team-raptor, cla: yes

#3859 Add created and updated timestamps to certificate subject mappings
  chart/compass/values.yaml
  components/director/internal/domain/certsubjectmapping/converter.go
  components/director/internal/domain/certsubjectmapping/converter_test.go
  components/director/internal/domain/certsubjectmapping/entity.go
  components/director/internal/domain/certsubjectmapping/fixtures_test.go
  components/director/internal/domain/certsubjectmapping/repository.go
  components/director/internal/domain/certsubjectmapping/repository_test.go
  components/director/internal/model/cert_subject_mapping.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/schema-migrator/migrations/director/20240502143640_add-csm-timestamps.down.sql
  components/schema-migrator/migrations/director/20240502143640_add-csm-timestamps.up.sql
Labels: approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3868 Make the hydrator component bootstrap more resilient
  chart/compass/values.yaml
  components/default-tenant-mapping-handler/cmd/main.go
  components/director/cmd/destinationfetcher-svc/main.go
  components/director/cmd/director/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/pkg/inputvalidation/validators_cert_subject_mappings.go
  components/hydrator/cmd/main.go
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/hydrator/internal/subject/cert_subject.go
  components/hydrator/internal/subject/cert_subject_test.go
  components/instance-creator/cmd/main.go
  components/kyma-adapter/cmd/main.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3870 [HOTFIX] Add dedicated method for formation/formation assignments tim…
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/asa_engine.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_repository.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_service.go
  components/director/internal/domain/formation/automock/constraint_engine.go
  components/director/internal/domain/formation/automock/formation_assignment_notifications_service.go
  components/director/internal/domain/formation/automock/formation_assignment_repository.go
  components/director/internal/domain/formation/automock/formation_repository.go
  components/director/internal/domain/formation/automock/formation_template_repository.go
  components/director/internal/domain/formation/automock/label_def_repository.go
  components/director/internal/domain/formation/automock/label_def_service.go
  components/director/internal/domain/formation/automock/label_repository.go
  components/director/internal/domain/formation/automock/label_service.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/automock/process_func.go
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/automock/status_service.go
  components/director/internal/domain/formation/automock/tenant_service.go
  components/director/internal/domain/formation/automock/tenant_svc.go
  components/director/internal/domain/formation/automock/uuid_service.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/repository.go
  components/director/internal/domain/formation/repository_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formationassignment/automock/application_converter.go
  components/director/internal/domain/formationassignment/automock/application_repo.go
  components/director/internal/domain/formationassignment/automock/application_repository.go
  components/director/internal/domain/formationassignment/automock/constraint_engine.go
  components/director/internal/domain/formationassignment/automock/entity_converter.go
  components/director/internal/domain/formationassignment/automock/fa_notification_service.go
  components/director/internal/domain/formationassignment/automock/formation_assignment_repository.go
  components/director/internal/domain/formationassignment/automock/formation_repository.go
  components/director/internal/domain/formationassignment/automock/label_service.go
  components/director/internal/domain/formationassignment/automock/notification_builder.go
  components/director/internal/domain/formationassignment/automock/notification_service.go
  components/director/internal/domain/formationassignment/automock/runtime_context_converter.go
  components/director/internal/domain/formationassignment/automock/runtime_context_repo.go
  components/director/internal/domain/formationassignment/automock/runtime_context_repository.go
  components/director/internal/domain/formationassignment/automock/runtime_converter.go
  components/director/internal/domain/formationassignment/automock/runtime_repo.go
  components/director/internal/domain/formationassignment/automock/runtime_repository.go
  components/director/internal/domain/formationassignment/automock/status_service.go
  components/director/internal/domain/formationassignment/automock/template_input.go
  components/director/internal/domain/formationassignment/automock/tenant_repository.go
  components/director/internal/domain/formationassignment/automock/uid_service.go
  components/director/internal/domain/formationassignment/automock/webhook_converter.go
  components/director/internal/domain/formationassignment/automock/webhook_repository.go
  components/director/internal/domain/formationassignment/repository.go
  components/director/internal/domain/formationassignment/repository_test.go
  components/director/internal/model/formation.go
  components/director/internal/model/formation_assignment.go
Labels: approved, size/XL, lgtm, :t-rex: team-raptor, cla: yes

#3874 Add OWNERS hold label
  OWNERS
Labels: size/XS, lgtm, cla: yes

#3876 Fix processing of jsonpath for SLIS select criteria
  components/director/cmd/systemfetcher/main.go
Labels: size/S, approved, lgtm, :eagle: team-falcon, cla: yes

#3871 Ignore tenants with slashes
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3860 Kyma 2.16.1
  components/director/run.sh
  components/schema-migrator/Dockerfile
Labels: size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3881 Restrict scenario label changes from the outside
  components/director/examples/create-formation-template/create-formation-template-with-webhooks.graphql
  components/director/examples/delete-formation-template-label/delete-formation-template-label.graphql
  components/director/examples/list-formations-for-object-global/list-formations-for-object-global.graphql
  components/director/examples/register-application/register-application-with-bundles.graphql
  components/director/examples/register-application/register-application-with-status.graphql
  components/director/examples/register-application/register-application-with-webhooks.graphql
  components/director/examples/register-application/register-application.graphql
  components/director/examples/set-formation-template-label/set-formation-template-label.graphql
  components/director/examples/unassign-formation-global/unassign-application-from-formation-global.graphql
  components/director/internal/domain/application/automock/formation_service.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_assignment_service.go
  components/director/internal/domain/formationconstraint/operators/automock/formation_repository.go
  components/director/internal/domain/formationconstraint/operators/constraint_engine.go
  components/director/internal/domain/formationconstraint/operators/fixtures_test.go
  components/director/internal/domain/formationconstraint/operators/is_not_assigned_to_any_formation_of_type_operator.go
  components/director/internal/domain/formationconstraint/operators/is_not_assigned_to_any_formation_of_type_operator_test.go
  components/director/internal/domain/runtime/automock/formation_service.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/service.go
  components/director/internal/domain/runtime/service_test.go
  components/director/internal/domain/runtime_context/automock/formation_service.go
  components/director/internal/domain/runtime_context/service.go
  components/director/internal/domain/runtime_context/service_test.go
  tests/connectivity-adapter/tests/app_registry_test.go
  tests/connectivity-adapter/tests/connector_test.go
  tests/connector/tests/apps_for_runtime_test.go
  tests/director/bench/application_api_test.go
  tests/director/tests/application/application_api_test.go
  tests/director/tests/labeling_api_test.go
  tests/director/tests/runtime/runtime_api_test.go
  tests/gateway/tests/automatic_status_update_test.go
  tests/gateway/tests/viewer_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/application_queries.go
  tests/pkg/fixtures/application_requests.go
  tests/pkg/fixtures/runtime_queries.go
  tests/smoke-test/assign-application-to-formation.graphql
  tests/smoke-test/register-application-with-bundles.graphql
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3858 System Field Discovery via Operations Manager
  components/director/cmd/director/main.go
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/cmd/tenantfetcher-svc/main.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/apptemplate/automock/system_field_discovery_engine.go
  components/director/internal/domain/apptemplate/resolver.go
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/internal/domain/operation/automock/operation_repository.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/operation/repository_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/subscription/automock/application_service.go
  components/director/internal/domain/subscription/automock/subscription_service.go
  components/director/internal/domain/subscription/automock/system_field_discovery_engine.go
  components/director/internal/domain/subscription/resolver.go
  components/director/internal/domain/subscription/resolver_test.go
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/internal/model/operation.go
  components/director/internal/operations_manager/automock/operation_service.go
  components/director/internal/operations_manager/interfaces.go
  components/director/internal/operations_manager/operations_manager.go
  components/director/internal/operations_manager/operations_manager_config.go
  components/director/internal/operations_manager/operations_manager_test.go
  components/director/internal/system-field-discovery-engine/apiclient/client.go
  components/director/internal/system-field-discovery-engine/apiclient/client_test.go
  components/director/internal/system-field-discovery-engine/apiclient/config.go
  components/director/internal/system-field-discovery-engine/automock/application_service.go
  components/director/internal/system-field-discovery-engine/automock/application_template_service.go
  components/director/internal/system-field-discovery-engine/automock/client.go
  components/director/internal/system-field-discovery-engine/automock/operations_manager.go
  components/director/internal/system-field-discovery-engine/automock/system_field_discovery_engine_config.go
  components/director/internal/system-field-discovery-engine/automock/system_field_discovery_service.go
  components/director/internal/system-field-discovery-engine/automock/tenant_service.go
  components/director/internal/system-field-discovery-engine/config/saas_reg_config.go
  components/director/internal/system-field-discovery-engine/config/system_field_discovery_engine_config.go
  components/director/internal/system-field-discovery-engine/data/system_field_discovery_operation_data.go
  components/director/internal/system-field-discovery-engine/data/system_field_discovery_operation_data_test.go
  components/director/internal/system-field-discovery-engine/handler.go
  components/director/internal/system-field-discovery-engine/handler_test.go
  components/director/internal/system-field-discovery-engine/operation_processor.go
  components/director/internal/system-field-discovery-engine/operation_processor_test.go
  components/director/internal/system-field-discovery-engine/service.go
  components/director/internal/system-field-discovery-engine/service_test.go
  components/director/internal/system-field-discovery-engine/system_field_discovery_engine.go
  components/director/internal/system-field-discovery-engine/system_field_discovery_engine_test.go
  components/director/internal/system-field-discovery-engine/testdata/TestSystemFieldDiscoveryEngine_data.golden
  components/director/pkg/config/system_field_discovery_engine_config.go
  components/director/pkg/webhookprocessor/webhook_processor.go
  components/director/pkg/webhookprocessor/webhook_processor_test.go
  components/director/run.sh
  components/schema-migrator/migrations/director/20240515124631_extend-supported-operation-types.down.sql
  components/schema-migrator/migrations/director/20240515124631_extend-supported-operation-types.up.sql
  tests/director/tests/application/application_templates_subscription_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :eagle: team-falcon, cla: yes

#3891 [HOTFIX] v1.94.1 IAS adapter auth changes
  chart/compass/charts/gateway/templates/oathkeeper-rules.yaml
  chart/compass/charts/ias-adapter/templates/virtual-service-internal.yaml
  chart/compass/values.yaml
  components/ias-adapter/internal/api/middlewares/auth.go
  components/ias-adapter/internal/api/middlewares/id_token.go
  components/ias-adapter/internal/api/server.go
Labels: size/L, :t-rex: team-raptor, cla: yes, :globe_with_meridians: team-atlas

#3887 Aggregate deployment identifier for all systems 2
  tests/system-fetcher/tests/handler_test.go
Labels: size/XS, approved, lgtm, :eagle: team-falcon, cla: yes

#3890 Avoid parent OWNERS
  components/connectivity-adapter/OWNERS
  components/connector/OWNERS
  components/default-tenant-mapping-handler/OWNERS
  components/director/cmd/destinationfetcher-svc/OWNERS
  components/director/cmd/ns-adapter/OWNERS
  components/director/cmd/ordaggregator/OWNERS
  components/director/cmd/scopessynchronizer/OWNERS
  components/director/cmd/systemfetcher/OWNERS
  components/director/cmd/tenantfetcher-svc/OWNERS
  components/director/internal/domain/certsubjectmapping/OWNERS
  components/director/internal/domain/formation/OWNERS
  components/director/internal/domain/formationassignment/OWNERS
  components/director/internal/domain/formationconstraint/OWNERS
  components/director/internal/domain/formationtemplate/OWNERS
  components/director/internal/domain/formationtemplateconstraintreferences/OWNERS
  components/director/internal/formationmapping/OWNERS
  components/director/internal/info/OWNERS
  components/director/internal/nsadapter/OWNERS
  components/director/internal/open_resource_discovery/OWNERS
  components/director/internal/scopes_sync/OWNERS
  components/director/internal/systemfetcher/OWNERS
  components/director/internal/tenantfetchersvc/OWNERS
  components/director/pkg/accessstrategy/OWNERS
  components/director/pkg/operation/OWNERS
  components/director/pkg/scenario/OWNERS
  components/gateway/OWNERS
  components/hydrator/OWNERS
  components/ias-adapter/OWNERS
  components/instance-creator/OWNERS
  components/kyma-adapter/OWNERS
  components/operations-controller/OWNERS
  components/pairing-adapter/OWNERS
  installation/scripts/OWNERS
  installation/scripts/prow/OWNERS
  tests/connectivity-adapter/OWNERS
  tests/connector/OWNERS
  tests/director/tests/formation/OWNERS
  tests/director/tests/notifications/OWNERS
  tests/director/tests/runtime/OWNERS
  tests/gateway/OWNERS
  tests/instance-creator/OWNERS
  tests/istio/OWNERS
  tests/ns-adapter/OWNERS
  tests/ord-aggregator/OWNERS
  tests/ord-service/OWNERS
  tests/pairing-adapter/OWNERS
  tests/pkg/notifications/OWNERS
  tests/system-fetcher/OWNERS
  tests/tenant-fetcher/OWNERS
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3895 [HOTFIX] Director is failing due to DB indicator errors
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
Labels: :wave: request review, size/XS, approved, do-not-merge/hold, lgtm, :eagle: team-falcon, cla: yes

#3893 Director is failing due to DB indicator errors
  components/director/internal/domain/tenant/fetcher_on_demand.go
  components/director/internal/domain/tenant/fetcher_on_demand_test.go
Labels: :wave: request review, size/XS, approved, lgtm, :eagle: team-falcon, cla: yes

#3896 Support graphql operations queries
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/examples/README.md
  components/director/examples/get-operation-by-id/get-operation-by-id.graphql
  components/director/examples/schedule-operation/schedule-operation.graphql
  components/director/hack/config-local.yaml
  components/director/hack/jwt_generator.sh
  components/director/internal/domain/operation/automock/operation_converter.go
  components/director/internal/domain/operation/automock/operation_service.go
  components/director/internal/domain/operation/resolver.go
  components/director/internal/domain/operation/resolver_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/director/tests/config.go
  tests/director/tests/operations_test.go
  tests/go.mod
  tests/go.sum
  tests/pkg/fixtures/operations_requests.go
Labels: size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3872 Extend operation entity with error severity
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/cmd/ordaggregator/main.go
  components/director/go.mod
  components/director/go.sum
  components/director/internal/domain/operation/converter.go
  components/director/internal/domain/operation/converter_test.go
  components/director/internal/domain/operation/entity.go
  components/director/internal/domain/operation/fixtures_test.go
  components/director/internal/domain/operation/repository.go
  components/director/internal/domain/operation/repository_test.go
  components/director/internal/domain/operation/resolver_test.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/model/operation.go
  components/director/internal/model/operation_test.go
  components/director/internal/open_resource_discovery/custom_errors.go
  components/director/internal/open_resource_discovery/handler.go
  components/director/internal/open_resource_discovery/operation_maintainer.go
  components/director/internal/operations_manager/automock/operation_service.go
  components/director/internal/operations_manager/interfaces.go
  components/director/internal/operations_manager/operations_manager.go
  components/director/internal/operations_manager/operations_manager_test.go
  components/director/internal/system-field-discovery-engine/handler.go
  components/director/internal/systemfetcher/handler.go
  components/director/internal/systemfetcher/operation_maintainer.go
  components/director/internal/systemfetcher/operation_maintainer_test.go
  components/director/pkg/graphql/graphqlizer/fields.go
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/schema-migrator/migrations/director/20240516105526_add-error-severity-on-operations.down.sql
  components/schema-migrator/migrations/director/20240516105526_add-error-severity-on-operations.up.sql
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/ord-aggregator/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3897 Return all operation entities for each application in operations subresolver
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3882 Improve API error responses
  components/director/internal/domain/formationtemplate/repository.go
  components/director/internal/domain/formationtemplate/repository_test.go
  components/director/pkg/apperrors/errors.go
  components/hydrator/internal/tenantmapping/handler.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, cla: yes
