Repository kyma-incubator/compass, pull requests merged in 2024-03, with the labels that each got.

#3696 Use correct tenant for calling subscription API in System Field Discovery Engine flow
  chart/compass/values.yaml
  components/director/internal/domain/subscription/service.go
  components/director/internal/domain/subscription/service_test.go
  components/director/internal/system-field-discovery-engine/system_field_discovery_engine.go
Labels: :wave: request review, size/S, approved, lgtm, :eagle: team-falcon, cla: yes

#3699 Generate images for component that do not have prod versions for release
  chart/compass/values.yaml
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/instance-creator/internal/client/automock/external_svc_caller.go
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/pairing-adapter/internal/adapter/automock/HTTPDoer.go
Labels: size/M, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3698 Release v1.90.0
  chart/compass/values.yaml
Labels: :wave: request review, size/M, approved, cla: yes

#3694 Optimize long running db query
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3697 Validate application template placeholders
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/resolver_test.go
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  tests/director/tests/application/application_templates_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3703 Add resources to git.ignore
  .gitignore
Labels: size/XS, approved, lgtm, cla: yes

#3701 Introduce Formation Viewer Consumer Type
  chart/compass/values.yaml
  components/director/pkg/consumer/consumer.go
  components/director/pkg/inputvalidation/validators_cert_subject_mappings.go
  components/director/pkg/model/system_auth.go
  components/hydrator/go.mod
  components/hydrator/go.sum
Labels: size/S, lgtm, :t-rex: team-raptor, cla: yes

#3705 Fix tenant regions
  chart/compass/charts/external-services-mock/templates/deployment.yaml
  chart/compass/templates/tests/tenant-fetcher/tenant-fetcher-test.yaml
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/resync/synchronizer.go
  components/director/internal/tenantfetchersvc/resync/synchronizer_test.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager.go
  components/director/internal/tenantfetchersvc/resync/tenant_manager_test.go
  components/director/internal/tenantfetchersvc/resync/types.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/tenantfetcher/handler.go
  installation/resources/compass-overrides-local.yaml
  tests/tenant-fetcher/tests/handler_test.go
  tests/tenant-fetcher/tests/main_test.go
Labels: kind/bug, :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3707 update version
  chart/compass/values.yaml
Labels: size/S, cla: yes

#3664 Adopt API Metadata Validator
  chart/compass/charts/ord-aggregator/templates/deployment.yaml
  chart/compass/templates/additional-prometheus-rules.yaml
  chart/compass/values.yaml
  components/director/cmd/ordaggregator/main.go
  components/director/cmd/systemfetcher/main.go
  components/director/internal/common/validations.go
  components/director/internal/domain/api/service.go
  components/director/internal/domain/operation/service.go
  components/director/internal/domain/operation/service_test.go
  components/director/internal/model/api.go
  components/director/internal/model/aspect.go
  components/director/internal/model/aspect_event_resource.go
  components/director/internal/model/capability.go
  components/director/internal/model/eventapi.go
  components/director/internal/open_resource_discovery/automock/client.go
  components/director/internal/open_resource_discovery/automock/validator.go
  components/director/internal/open_resource_discovery/automock/validator_client.go
  components/director/internal/open_resource_discovery/client.go
  components/director/internal/open_resource_discovery/client_test.go
  components/director/internal/open_resource_discovery/custom_errors.go
  components/director/internal/open_resource_discovery/fixtures_test.go
  components/director/internal/open_resource_discovery/global_registry.go
  components/director/internal/open_resource_discovery/global_registry_test.go
  components/director/internal/open_resource_discovery/ord_document.go
  components/director/internal/open_resource_discovery/sanitizer.go
  components/director/internal/open_resource_discovery/service.go
  components/director/internal/open_resource_discovery/service_test.go
  components/director/internal/open_resource_discovery/validation.go
  components/director/internal/open_resource_discovery/validation_client.go
  components/director/internal/open_resource_discovery/validation_client_test.go
  components/director/internal/open_resource_discovery/validation_test.go
  components/director/internal/open_resource_discovery/validator.go
  components/director/internal/open_resource_discovery/validator_test.go
  components/director/internal/operations_manager/automock/operation_service.go
  components/director/internal/operations_manager/interfaces.go
  components/director/internal/operations_manager/operations_manager.go
  components/director/internal/operations_manager/operations_manager_test.go
  components/director/pkg/graphql/integration_dependency_validation.go
  components/director/pkg/graphql/version_validation.go
  components/external-services-mock/internal/ord-aggregator/globalregistry/template.go
  components/external-services-mock/internal/ord-aggregator/template.go
  installation/cmd/run.sh
  tests/ord-aggregator/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3722 Remove ownership of some files
  CODEOWNERS
Labels: :wave: request review, size/M, approved, lgtm, cla: yes

#3725 Update CODEOWNERS
  CODEOWNERS
Labels: size/M, approved, lgtm, cla: yes

#3727 Update Dockerfile
  components/hydrator/Dockerfile
Labels: size/XS, lgtm, :t-rex: team-raptor, cla: yes

#3728 Revert "Update Dockerfile"
  components/hydrator/Dockerfile
Labels: size/XS, lgtm, cla: yes

#3729 Adjust System Field Discovery Engine e2e test to work and for real env
  chart/compass/values.yaml
  tests/director/tests/application/application_templates_subscription_test.go
Labels: kind/bug, :wave: request review, size/S, approved, lgtm, :eagle: team-falcon, cla: yes

#3732 Add API Metadata Validator flag setting to the installation docs
  docs/compass/04-01-installation.md
Labels: size/XS, lgtm, cla: yes

#3733 Release v1.91.0
  chart/compass/values.yaml
Labels: size/M, approved, lgtm, cla: yes

#3730 Upgrade gqlgen library
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/connector/hack/gqlgen.go
  components/connector/pkg/graphql/externalschema/config.yaml
  components/connector/pkg/graphql/externalschema/models_gen.go
  components/connector/pkg/graphql/externalschema/schema_gen.go
  components/default-tenant-mapping-handler/go.mod
  components/default-tenant-mapping-handler/go.sum
  components/director/go.mod
  components/director/go.sum
  components/director/pkg/graphql/config.yaml
  components/director/pkg/graphql/models_gen.go
  components/director/pkg/graphql/schema_gen.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/ias-adapter/go.mod
  components/ias-adapter/go.sum
  components/instance-creator/go.mod
  components/instance-creator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  components/system-broker/go.mod
  components/system-broker/go.sum
  tests/go.mod
  tests/go.sum
  tests/system-fetcher/tests/handler_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3734 Fix placeholder resolving
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/go.mod
  tests/go.sum
Labels: :wave: request review, size/M, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3735 [HOTFIX] Fix placeholder resolving
  chart/compass/values.yaml
  components/connectivity-adapter/go.mod
  components/connectivity-adapter/go.sum
  components/connector/go.mod
  components/connector/go.sum
  components/director/pkg/graphql/app_template_validation.go
  components/director/pkg/graphql/app_template_validation_test.go
  components/external-services-mock/go.mod
  components/external-services-mock/go.sum
  components/gateway/go.mod
  components/gateway/go.sum
  components/hydrator/go.mod
  components/hydrator/go.sum
  components/kyma-adapter/go.mod
  components/kyma-adapter/go.sum
  components/operations-controller/go.mod
  components/operations-controller/go.sum
  components/pairing-adapter/go.mod
  components/pairing-adapter/go.sum
  tests/go.mod
  tests/go.sum
Labels: size/L, lgtm, :t-rex: team-raptor, :eagle: team-falcon, cla: yes

#3736 v1.91.0-version-bump
  chart/compass/values.yaml
Labels: size/M, cla: yes

#3754 Fix cost-object id trimming
  chart/compass/values.yaml
  components/director/internal/domain/tenant/automock/business_tenant_mapping_converter.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  tests/director/tests/tenants_api_test.go
Labels: kind/bug, :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon, cla: yes

#3756 [HOTFIX] Fix cost-object id trimming
  chart/compass/values.yaml
  components/director/internal/domain/tenant/automock/business_tenant_mapping_converter.go
  components/director/internal/domain/tenant/converter.go
  components/director/internal/domain/tenant/converter_test.go
  components/director/internal/domain/tenant/resolver.go
  components/director/internal/domain/tenant/resolver_test.go
  components/director/internal/tenantfetchersvc/provisioner.go
  tests/director/tests/tenants_api_test.go
Labels: approved, size/XL, lgtm, :eagle: team-falcon, cla: yes

#3737 Update k8s api version
  installation/cmd/run.sh
  installation/scripts/prow/jobs/provision-compass.sh
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3651 Unify naming style in docs
  README.md
  docs/README.md
  docs/compass/02-02-basic-architecture.md
  docs/compass/02-03-app-runtime-flow.md
  docs/compass/03-01-security.md
  docs/compass/03-03-automatic-scenario-assignment.md
  docs/compass/03-04-labels.md
  docs/compass/03-bundles-api.md
  docs/compass/03-bundles-credential-requests.md
  docs/compass/03-formation-templates.md
  docs/compass/03-tenant-loading.md
  docs/compass/04-01-installation.md
  docs/compass/08-01-basic-flow-tutorial.md
  docs/compass/09-01-e2e-test-design.md
  docs/compass/10-01-rate-limiting.md
  docs/connector/08-01-establish-secure-connection-with-compass.md
  docs/connector/08-02-maintain-secure-connection-with-compass.md
  docs/connector/08-03-revoke-client-certificate.md
  docs/connector/oathkeeper-connector-authentication.md
  docs/director/03-default-eventing-for-application.md
  docs/director/03-error-handling.md
  docs/director/03-statuses.md
  docs/director/03-tenancy.md
  docs/director/10-01-troubleshooting.md
  docs/integration-system/auto-app-management.md
  docs/internal/investigations/README.md
  docs/internal/investigations/api-documentation/generate-api-documentation.md
  docs/internal/investigations/gateway-architecture/gateway-architecture.md
  docs/internal/investigations/graphql-complex-updates/graphql-complex-updates.md
  docs/internal/investigations/graphql-file-upload/file-upload-with-graphql.md
  docs/internal/investigations/rest-adapters/rest-adapter-for-graphql.md
  docs/internal/investigations/secure-resolvers/secure-resolvers-v2.md
  docs/internal/investigations/secure-resolvers/secure-resolvers.md
  docs/internal/investigations/simplify-api-usage/simplify-api-usage.md
  docs/internal/investigations/storage/managed-db/managed-dbs.md
  docs/internal/investigations/storage/s3/README.md
  docs/internal/proposals/README.md
  docs/internal/proposals/compass-split/compass-split.md
  docs/internal/proposals/error-handling/error-handling.md
  docs/internal/proposals/pairing-adapters/pairing-application-instance-with-compass.md
  docs/internal/proposals/pairing-adapters/pairing-with-use-integration-system.md
  docs/internal/proposals/pairing-adapters/pairing-without-using-integration-system.md
  docs/internal/proposals/separate-compass/separate-compass.md
  docs/internal/supported-apis.md
  docs/operations-controller/01-async-operations.md
  docs/runtime-agent/runtime-agent-contract.md
  docs/tenants-aggregator/01-overview.md
  installation/README.md
  installation/resources/readme.md
  scripts/README.md
Labels: size/L, lgtm, cla: yes

#3757 Add env var for instance creator region in e2e test
  chart/compass/templates/tests/instance-creator/instance-creator-test.yaml
  chart/compass/values.yaml
  tests/instance-creator/tests/config.go
  tests/instance-creator/tests/instance_creator_test.go
Labels: size/XS, approved, lgtm, :t-rex: team-raptor, cla: yes

#3758 Delete formations that are in draft state
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3760 Fix Instance Creator e2e test flapping on real env
  chart/compass/values.yaml
  components/instance-creator/internal/handler/handler.go
  tests/instance-creator/tests/instance_creator_test.go
  tests/pkg/notifications/asserters/formation_assigments_async_custom_config_matcher.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3761 Set ORDAggregationValidationErrors severity to warning
  chart/compass/templates/additional-prometheus-rules.yaml
Labels: size/XS, approved, lgtm, cla: yes

#3709 Change ORD service version
  chart/compass/values.yaml
Labels: :wave: request review, size/XS, approved, lgtm, cla: yes

#3759 Do not delete systems used by other tenants on deleteTenants
  chart/compass/values.yaml
  components/director/internal/domain/tenant/repository.go
  components/director/internal/domain/tenant/repository_test.go
  tests/director/tests/tenants_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3731 Fix formation assignment bulk notification matching
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/automock/asa_engine.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_repository.go
  components/director/internal/domain/formation/automock/automatic_formation_assignment_service.go
  components/director/internal/domain/formation/automock/constraint_engine.go
  components/director/internal/domain/formation/automock/converter.go
  components/director/internal/domain/formation/automock/formation_assignment_converter.go
  components/director/internal/domain/formation/automock/formation_assignment_notifications_service.go
  components/director/internal/domain/formation/automock/formation_assignment_service.go
  components/director/internal/domain/formation/automock/formation_repository.go
  components/director/internal/domain/formation/automock/formation_template_repository.go
  components/director/internal/domain/formation/automock/label_def_repository.go
  components/director/internal/domain/formation/automock/label_def_service.go
  components/director/internal/domain/formation/automock/label_repository.go
  components/director/internal/domain/formation/automock/label_service.go
  components/director/internal/domain/formation/automock/notifications_generator.go
  components/director/internal/domain/formation/automock/notifications_service.go
  components/director/internal/domain/formation/automock/process_func.go
  components/director/internal/domain/formation/automock/runtime_context_repository.go
  components/director/internal/domain/formation/automock/runtime_repository.go
  components/director/internal/domain/formation/automock/service.go
  components/director/internal/domain/formation/automock/status_service.go
  components/director/internal/domain/formation/automock/tenant_fetcher.go
  components/director/internal/domain/formation/automock/tenant_service.go
  components/director/internal/domain/formation/automock/uuid_service.go
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/notifications.go
  components/director/internal/domain/formation/notifications_generator.go
  components/director/internal/domain/formation/notifications_generator_test.go
  components/director/internal/domain/formation/notifications_test.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/unassign_formation_test.go
  components/director/internal/domain/formationassignment/fixtures_test.go
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/pkg/webhook_client/types.go
  tests/director/tests/notifications/application_only_notifications_test.go
Labels: :wave: request review, size/XXL, approved, lgtm, :t-rex: team-raptor, cla: yes

#3765 [HOTFIX] Add formation state write scope to integration system
  chart/compass/values.yaml
Labels: :hammer: hotfix, size/XS, approved, lgtm, cla: yes

#3769 Fix instance creator delete state status reports
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/domain/formationassignment/status_service.go
  components/director/internal/domain/formationassignment/status_service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3770 Fix deletion of formation that does not have webhooks
  chart/compass/values.yaml
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3767 Allow horizontally scaling SaaS Application Providers to onboard to UCL
  chart/compass/values.yaml
  components/director/internal/domain/apptemplate/service.go
  components/director/internal/domain/apptemplate/service_test.go
  tests/director/tests/application/application_templates_api_test.go
Labels: :wave: request review, approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3772 [Improvement] Improve formation assignment asserters logs
  chart/compass/values.yaml
  tests/director/tests/notifications/fixtures_test.go
  tests/pkg/notifications/asserters/formation_assignments_async.go
Labels: size/S, approved, lgtm, :t-rex: team-raptor, cla: yes

#3762 Fix failing of lazy tenants creation
  chart/compass/values.yaml
  components/director/internal/domain/formation/automock/tenant_svc.go
  components/director/internal/domain/formation/resolver.go
  components/director/internal/domain/formation/resolver_test.go
  components/director/internal/domain/root_resolver.go
  components/director/internal/domain/runtime/automock/tenant_svc.go
  components/director/internal/domain/runtime/resolver.go
  components/director/internal/domain/runtime/resolver_test.go
Labels: approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3774 Fix assign formation when an error occurs during processing of formation assignments
  chart/compass/values.yaml
  components/director/internal/domain/formation/assign_formation_test.go
  components/director/internal/domain/formation/service.go
  components/director/pkg/persistence/txtest/txtest.go
Labels: :wave: request review, size/M, approved, lgtm, :t-rex: team-raptor, cla: yes

#3775 Update versions for release
  chart/compass/values.yaml
Labels: size/M, approved, lgtm, cla: yes

#3695 Optimisation for subscription flow
  chart/compass/values.yaml
  components/director/internal/tenantfetchersvc/automock/tenant_provisioner.go
  components/director/internal/tenantfetchersvc/provisioner.go
  components/director/internal/tenantfetchersvc/provisioner_test.go
  components/director/internal/tenantfetchersvc/subscriber.go
  components/director/internal/tenantfetchersvc/subscriber_test.go
Labels: approved, size/L, lgtm, :eagle: team-falcon, cla: yes

#3771 Allow states that were introduced in Status API to work in synchronous cases
  chart/compass/values.yaml
  components/director/internal/domain/formationassignment/service.go
  components/director/internal/domain/formationassignment/service_test.go
  components/director/internal/model/formation_assignment.go
  components/external-services-mock/cmd/main.go
  components/external-services-mock/internal/formationnotification/handler.go
  tests/director/tests/notifications/application_only_notifications_new_format_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3773 Delete formation only if there are no left assignments
  chart/compass/values.yaml
  components/director/internal/domain/formation/fixtures_test.go
  components/director/internal/domain/formation/service.go
  components/director/internal/domain/formation/service_test.go
  tests/director/tests/formation/formation_api_test.go
  tests/ord-service/tests/subscription_flow_test.go
Labels: :wave: request review, approved, size/L, lgtm, :t-rex: team-raptor, cla: yes

#3768 IAS Adapter - Handle S/4 participants
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/automock/health_service.go
  components/ias-adapter/internal/api/internal/handlers/automock/tenant_mappings_service.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/api/internal/response.go
  components/ias-adapter/internal/errors/errors.go
  components/ias-adapter/internal/service/automock/ias_service.go
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
  components/ias-adapter/internal/service/tenant_mapping.go
  components/ias-adapter/internal/service/tenant_mapping_test.go
  components/ias-adapter/internal/types/application.go
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: approved, size/L, lgtm, cla: yes, :globe_with_meridians: team-atlas

#3779 Introduce lifecycle tmestamps for tenants
  chart/compass/values.yaml
  components/schema-migrator/migrations/director/20240328144434_update-at-and-created-at-on-tenants.down.sql
  components/schema-migrator/migrations/director/20240328144434_update-at-and-created-at-on-tenants.up.sql
Labels: :wave: request review, size/M, approved, lgtm, :eagle: team-falcon, cla: yes

#3702 Introduce List Applications by Local Tenant Id and Filter API
  chart/compass/charts/director/config.yaml
  chart/compass/values.yaml
  components/director/hack/config-local.yaml
  components/director/internal/domain/application/automock/application_repository.go
  components/director/internal/domain/application/automock/application_service.go
  components/director/internal/domain/application/repository.go
  components/director/internal/domain/application/repository_test.go
  components/director/internal/domain/application/resolver.go
  components/director/internal/domain/application/resolver_test.go
  components/director/internal/domain/application/service.go
  components/director/internal/domain/application/service_test.go
  components/director/internal/domain/root_resolver.go
  components/director/pkg/graphql/schema.graphql
  components/director/pkg/graphql/schema_gen.go
  tests/director/tests/application/application_api_test.go
  tests/pkg/fixtures/application_requests.go
Labels: :wave: request review, approved, size/XL, lgtm, :eagle: team-falcon, cla: yes

#3780 IAS Adapter - Handle S/4 participants (#3768)
  chart/compass/values.yaml
  components/ias-adapter/internal/api/internal/handlers/automock/health_service.go
  components/ias-adapter/internal/api/internal/handlers/automock/tenant_mappings_service.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping.go
  components/ias-adapter/internal/api/internal/handlers/tenant_mapping_test.go
  components/ias-adapter/internal/api/internal/response.go
  components/ias-adapter/internal/errors/errors.go
  components/ias-adapter/internal/service/automock/ias_service.go
  components/ias-adapter/internal/service/ias/service.go
  components/ias-adapter/internal/service/ias/service_test.go
  components/ias-adapter/internal/service/tenant_mapping.go
  components/ias-adapter/internal/service/tenant_mapping_test.go
  components/ias-adapter/internal/types/application.go
  components/ias-adapter/internal/types/tenant_mapping.go
Labels: approved, size/L, lgtm, cla: yes
